### ISSUE TITLE
Latest Update Crusher still crashing on NEI Recipe display/ Minetweaker recipe reseting

### ISSUE THREAD

**Issue by SneakyDevil** [BluSunrize/ImmersiveEngineering#1002]
As it says on the tin. 

I've disabled a recipe(In this case TFC Graphite), which as a default recipe makes 2 powder. The new recipe I added makes 6. I reload the script, it outputs x6 for a short period of time. Then suddenly it will go back to the old recipe and only output x2..

not sure what to upload so here's the logs for mineteaker and the script
script:http://puu.sh/nA9yS/b980903eec.zs
log:http://puu.sh/nA9zw/d8fdd7216a.log

**Comment by malte0811** [comment]
What do you consider "a short period of time" and what did  you do in said period? I just tried to reproduce this by removing the recipe for iron grit and replacing it with one that produces 4 grit instead, waiting a quarter of a hour and checking whether it still used the new recipe, which it did.
Are you testing this on a dedicated server (and are there other people on there) or in a singleplayer world?
Only cause I can think of right now would be TFC doing some weird stuff to prevent their recipes from being changed.
And if you are experiencing some crash (as it says in the title), could you post a crashlog?

**Comment by SneakyDevil** [comment]
Short period of time is roughly a few seconds to a minute. I'll throw a stack in, it will output the x6 sometimes and the x2 sometimes. Once it outputs the x2, it stays on the x2.

Here's the crashlog:http://puu.sh/nAArN/dab5415380.txt

**Comment by malte0811** [comment]
That crash is caused by some recipe with an invalid input, maybe an invalid oredict name. This is most likely something in your MT script.
I am unable to reproduce the bug at all. It works perfectly fine for me (waited about 10 minutes). Could you try whether this bug happens with only IE and MT installed? And I assume that this happens every time for you (just checking that this isn't caused by the computer being in a "bad mood" with regards to hash values/concurrency/...)?

**Comment by SneakyDevil** [comment]
Did you use the script I linked? and Yeah I can try.

**Comment by malte0811** [comment]
No, I used [this](https://gist.github.com/malte0811/c15c44573766877a9b3e) script, the first 2 recipes are from past tests, the last line was to test my way of preventing the crash you had. I don't have TFC in my dev instance, so I used a recipe that was present in my instance.

**Comment by SneakyDevil** [comment]
You were right, it appears the crash was a three fold thing. The invalid ore dict entries caused the NEI crash while the valid ore dict entries confused the Crusher to what recipe it needed to use.

**Comment by Bunsan** [comment]
I can shed some light on this issue. It appears to be a bug in base IE with regards to inserting itemStacks into inventories. I'll use the example that works with just IE and NEI. The recipe used is the blaze rod producing 4 blaze powder and a chance at sulphur. Build the crusher and have it input directly into a vanilla chest. The recipe will appear to be working fine. However before crushing the rods, place 61 blaze powder in the output chest, so that then first craft completes the one stack and creates a new one blaze powder. From that point forward it will just produce one blaze powder. If you place 63 in chest and insert blaze rods it will complete the stack and create a new stack of 3 powder and continue producing just 3 powder per craft. When the switch occurs NEI updates to a new recipe.  Now this does not occur if you use something to remove items from crusher, such as conveyor as it never forms over a stack of items. The change in recipe also occurs when just IE is in the instance. I have not tested other IE machines for this same issue.
Tested with:
forge-1.7.10-10.13.4.1566-1.7.10-universal
ImmersiveEngineering-0.7.3
NotEnoughItems-1.7.10-1.0.5.111-universal
CodeChickenCore-1.7.10-1.0.7.47-universal
Waila-1.5.10_1.7.10

**Comment by malte0811** [comment]
Thank you a giant lot for this information, I think I know what is going on now. And that also explains why it wasn't happening for me: I made it output 4 iron dust and `64 mod 4=0`.

**Comment by BluSunrize** [comment]
Sounds like we're just missing a ".copy()" somewhere in the outputting, no?

**Comment by malte0811** [comment]
Yes, in `Utils.addToOccupiedSlot` I think. I'll fix it later today.
