### ISSUE TITLE
Immersive Engineering slowing down tps alot

### ISSUE THREAD

**Issue by Berserker66** [BluSunrize/ImmersiveEngineering#1021]
On my server the Galacticraft Mars dimension slowed to a crawl. After some investigation with Opis, this is the most suspicious data:

https://i.imgur.com/3fg9dag.png

Only a restart of the server seems to remedy the issue and the tps recover, but it slows down again within hours.

We're still on 0.7.3, but I didn't see anything related in your changelog.

Edit: tps overview: https://i.imgur.com/mmjrmjz.png

In this dimension, the only IE stuff is some wiring, floodlights and a diesel generator.

**Comment by BluSunrize** [comment]
Which brings up the interesting question:
What the fuck is trying to spawn in that dimension? xD
Obviously this is easily fixed by disabling the spawn-prevention stuff of floodlights in the config, but I'd love to know what is trying to spawn all over Mars.
...
Come to thing of it, this sounds like the pitch to a bad Sci-Fi horror flick, doesn't it?

**Comment by Berserker66** [comment]
Well, galacticraft adds mobs, like "Evolved Skeleton", "Evolved Creeper" etc., but they don't spawn that much.

**Comment by Joshwoo69** [comment]
Might be due to block to block updates...

**Comment by Berserker66** [comment]
The floodlights aren't moving, so I doubt it's block updates.

**Comment by malte0811** [comment]
What are those 90 calls? Average per tick, average per second, maximum per tick? Average over what period of time? The amount of calls usually spikes (100-300 calls/tick, tested in the overworld) for a few ticks when MC tries to find a place where it can spawn something, but goes back to 0 afterwards.
Are you preventing mob spawning in some other way as well (i.e. magnum torches)? I am not sure, but I think that if MC does not find a place to spawn the mobs in, it will try again in the next tick, which could cause this if there is pretty much no place in a chunk close (within mob spawning range) to a player.
Block updates wouldn't make sense as a cause for this since that method is only called when MC checks whether an entity can spawn somewhere.

**Comment by Berserker66** [comment]
It's calls during one opis run, which is about 10 seconds. But those are consistently there, the number fluctuates a bit, but those calls happen continously. No other mob spawn prevention, at least that I know of.

**Comment by malte0811** [comment]
The time spend in the spawn check handler is about 150 ms during the whole Opis run (which could possibly be improved), but the mars dimension is taking up ~450 ms per tick, so about three times more per tick than the handler in the whole opis run of 10 seconds, so somewhere between 200 (ideal tickrate) and 20 (500 ms per tick) ticks. That sounds like there is something else going on that is taking up a lot of time. Can you try disabling the spawn prevention in the config and see how much that improves the tickrate? And no matter what the result is it would be very nice if you could install Sampler (http://forum.industrial-craft.net/index.php?page=Thread&threadID=10820, extra tweaks section), generate an .nps file of at least 10 seconds of runtime (`/sampler start`, wait, `/sampler stop`, `/sampler export IE.nps`) and upload it to something like dropbox.

**Comment by Berserker66** [comment]
Sorry for not answering. I went to bed and the users on the server kept tinkering. They eventually fixed it but don't know what it actually was. Only IE difference I see is that they replaced the wiring; it's now BC kinesis pipes and then the floodlights are connected directly to it individually. (Kinesis -> LV Conn -> Lv Wire -> Floodlight)
