### ISSUE TITLE
API ERROR: didn't implement demandsEnergy() properly

### ISSUE THREAD

**Issue by Tsyklop** [BluSunrize/ImmersiveEngineering#1037]
It appears in the console when connecting "Wire Connector", from ImmersiveEngineering, to any IC2 machines.
industrialcraft-2-2.2.816-experimental ImmersiveEngineering-0.7.4
![default](https://cloud.githubusercontent.com/assets/6783568/14084276/a2badd70-f522-11e5-806b-e44e0edba1cd.png)

**Comment by BluSunrize** [comment]
*shrug*
If they had a decent API tutorial...

**Comment by Tsyklop** [comment]
https://bitbucket.org/Aroma1997/uncomplication/issues/16/uncomplication-api-error-didnt-implement

**Comment by malte0811** [comment]
I was about to say that this only happens with Uncomplication.
@Aroma1997 there is no method called `demandsEnergy()`. Do you mean `acceptsEnergyFrom(TileEntity, ForgeDirection)`?

**Comment by Aroma1997** [comment]
Umm.
From what I can see, (I might be wrong there, because that part of Uncomplication is not made by me) this happens, when injectEnergy() accepts less energy than getDemandedEnergy() returned.
But maybe @Speiger can say more about this.

**Comment by BluSunrize** [comment]
Oooh, This is about Uncomplication? I don't give a fuck then :D

I support default IC2, not any addons that change the energy transfer system. Sorry, but that's not worth the trouble.
In the end, IE (in 1.7.10) is a RF mod afterall.

**Comment by Speiger** [comment]
@BlueSunrize first Ic2 has a Tutorial like discription in the API.
Second: The IC2 Classic Energynet has simply no Stupidity Security. So if you do not give a fuck about that then remove the IC2 Feature since you using it wrong. And if you are to lazy for that then accept that you get called stupid... I told you/others already a couple times that you use the API wrong. And you are still telling: IC2 has no tutorial after i told you where to get it and als partly what you should do...

This bug by the way means you returning(giving back) more then you are requesting You are causing a EnergyLoop. Thats why the energynet is throwing that out. Simply you have to return what did not get injected...
And finally read the api description

**Comment by Speiger** [comment]
After reading the commit which you did for trying to solve that problem i nodest one thing.
What is rule number one if you convert a Double To a Int with a convertion? Right you use a second buffer. A Double buffer... Simply to prevent upwards casting what double to int does... That is your problem.
I will provide you as soon as i get up with the Flux&Electric Flux generator converter code from IC2 Classic which will allow you a easy convertion proper math... without more power comming out then in.. And also supporting 0,2EU input.

**Comment by malte0811** [comment]
First of all: I think you should change the message to actually tell the developer which method you are talking about, not some method that we don't even implement because it doesn't seem to exist in vanilla IC2.
Second: the connectors only ever demand an amount of EU that corresponds to an integer amount of RF (except rounding errors...). If the net sends less than that, the connectors will accept less than one RF/tick less than they have been offered, which, if it was just voided, usually would not even be noticed since the wires lose some energy as well. If the IC2 net sends more or less energy than requested, it will have to.deal with the fact that the connectors don't consume all the energy.
Third: If you think that the new version of the code causes any bugs with IC2 experimental that will be noticed by the player/that aren't energy net equivalents of slightly misballanced hash functions, give us pictiures of a setup and a clear explanation of what is happening.

**Comment by Speiger** [comment]
> I think you should change the message to actually tell the developer which method you are talking about, not some method that we don't even implement because it doesn't seem to exist in vanilla IC2.

https://github.com/malte0811/ImmersiveEngineering/commit/37bf43f681ec4e198c632a8ccbdadd89493932b7

> Second: the connectors only ever demand an amount of EU that corresponds to an integer amount of RF (except rounding errors...). If the net sends less than that, the connectors will accept less than one RF/tick less than they have been offered, which, if it was just voided, usually would not even be noticed since the wires lose some energy as well. If the IC2 net sends more or less energy than requested, it will have to.deal with the fact that the connectors don't consume all the energy.

(Example code)
`double adding = Math.min(providing, energySink2.getDemandedEnergy());`
`double energyReturned = energySink2.injectEnergy(energyPath2.targetDirection.toForgeDirection(), adding, source);`
`else if(energyReturned >= energyProvided - energyLoss) throw error`

Note:
-Variable Providing = energyProvided - energyLoss (Also double)

> Third: If you think that the new version of the code causes any bugs with IC2 experimental that will be noticed by the player/that aren't energy net equivalents of slightly misballanced hash functions, give us pictiures of a setup and a clear explanation of what is happening.

Well IC2 Exp has just more Savety codes which allow game not to throw errors if you did something wrong...

And how you do a Converter?
https://github.com/TinyModularThings/TinyModularThings/blob/master/src/speiger/src/api/common/energy/EUConverter.java
This is the Converter from EU To MJ but can be used from EU To RF just with a Differend Convertion. That should sholve your problem....

**Comment by malte0811** [comment]
What has my commit to do with your message talking about methods that don't exist? I had to guess which method you were talking about, and if your message does anything it leads to more confusion since it says something about a method returning true when it shouldn't, not something about a methods return value being greater than 0 when it shouldn't.
If `throw error` actually throws an exception/error that isn't caught somewhere, it isn't called with normal IC2 exp. The setup that was spamming the log works perfectly fine with IC2 exp without uncomplication. The return value of `insertEnergy` can't be greater than the inserted amount if you don't try to insert a negative amount.
Then show me a situation where the new code misbehaves with IC2 classic. Only exception is voiding less than 1 RF=0.25EU per tick.
I would be able to write a converter to deal with less than 0.25 EU per tick, but any wire with a decent length will lose more than that anyway, so I don't feel like it is necessary.

**Comment by Speiger** [comment]
> What has my commit to do with your message talking about methods that don't exist? I had to guess which method you were talking about, and if your message does anything it leads to more confusion since it says something about a method returning true when it shouldn't, not something about a methods return value being greater than 0 when it shouldn't.

oh well
>  If throw error actually throws an exception/error that isn't caught somewhere, it isn't called with normal IC2 exp. The setup that was spamming the log works perfectly fine with IC2 exp without uncomplication. The return value of insertEnergy can't be greater than the inserted amount if you don't try to insert a negative amount.

Throw error is the message you have up there which is spamming. Also that it runs fine with IC2 Exp is because IC2 Exp has more Stupid usage catches simply that less bugs on not right coded addons show up... And IC2 Classic says: Hey you did something wrong there fix it.
Also IC2 classic /Uncomplication skip tileEntities that have a 0 or smaller energy request...

Also just a question are you stupid or something like that? i mean i showed you Example code and you think this is the full handling code...
The problem happens only because IE does not support the API properly and also do not know how to do math properly so shut up if you do not know how to solve a problem like that.

**Comment by Aroma1997** [comment]
I agree, that the log message should be clearer using the correct function name.
However, the fact, it doesn't spam that message using only IC2Exp, doesn't mean, the problem isn't there in IC2Exp. IC2 just ignores that problem, setting the returned value to a somewhat decent value and just continuing while IC2Classisic/Uncomplication actually TELL YOU, that they did that, and that there is a problem.

**Comment by malte0811** [comment]
@Aroma1997 I understand that the old code may have been a bit "confusing" for the energy net, but I don't understand what is wrong about the new implementation. It does not consume more than it is given/than it demanded and it does not produce energy. The return value of `insertEnergy` is not always zero, but if it was required to be 0, there wouldn't be any need for a return value to exist (I know that it says that 0 is the preferred value in the documentation, but that should not mean that returning something else is really bad). And the new code does not trigger the message any more, so your code seems to be happy with it.

**Comment by BluSunrize** [comment]
Speiger, if you keep insulting my contributors, you can fuck off.

I don't feel like bothering with this issue, since I have ceased active development on 1.7.10.
If you feel like duking this out, be my guest, but keep it respectful.

**Comment by Speiger** [comment]
@BluSunrize do it yourself. You are pushing this "IC2" Problem to all others but yours do not expect me to be friendly to you and the people who say something differendly...

**Comment by BluSunrize** [comment]
I'm not pushing this on anyone.
I literally don't give a damn about IC2 compat. If it breaks? So be it. I don't feel like fixing and I don't expect anyone too. If anyone volunteers though, I won't stop them.

**Comment by Speiger** [comment]
First Problem: IC2 Machines did constantly use Power From IE Connectors.. You tell thats a IC2 Problem. After that thing is fixed same thing happens to RF Type of Energies and you are telling no longer its a problem of another mod...
Well you know IE wires are only prefered because they can autoconvert SO FIX THAT Feature of Remove it.

**Comment by BluSunrize** [comment]
Please do show me where I claimed that to be an IC2 issue? Because I can't remember.

**Comment by Speiger** [comment]
xD Find it yourself. Its recorded on a stream. A forgecrafter

**Comment by BluSunrize** [comment]
Pft, fuck off. You can't make unfounded accusations and ask me to deliver your proof. You've got nothing on me, you can shut up and sit down.

**Comment by Speiger** [comment]
Fix your stuff or remove that that is broken... Then i am quiet

**Comment by BluSunrize** [comment]
Dude. Honestly. Stop making requests like I owe you something.
If it pains you SO much, PR it. I'm not doing any further work on IE for 1.7.10. That Minecraft version is done to me.

**Comment by Speiger** [comment]
You know i do not care about your mod... What i care about is that mods deliver not a broken thing.. IC2 Classic is the best example... And even if i am not friendly to persons i am at least throwing out Stable stuff...

**Comment by Speiger** [comment]
At least in +1.8 you can not support this broken feature anymore...

**Comment by BluSunrize** [comment]
Yep! 1.8 is the new beauty. Better inventory management, no longer dependant on RedstoneFlux and CoFH drama, better rendering and IE as one of the few big tech mods =3
