### ISSUE TITLE
[Suggestion] Add more blocks for Thermoelectric Generators

### ISSUE THREAD

**Issue by Ayrrow** [BluSunrize/ImmersiveEngineering#104]
As it currently stands, only water, lava and ice seem to be able to be used for the Thermoelectric generators. I know you can use Uranium, but my pack doesn't have that. 

It would be nice to see a few more blocks (both hot and cold) added to improve the generator.

**Comment by BluSunrize** [comment]
It works for every fluid, as well as multiple solid blocks.
When dealing with fluids it bases it on the temperature assigned to the fluid by the mod author (if you have Thermal Foundation, Pyrotheum and Cryotheum work really well).
The few solid blocks it does are for balance and realism reasons. Uranium and Plutonium are used in actual Radioisotope Thermoelectric Generators (RTG), and ice...well, it's cold.
Fire would not produce enough heat, and also netherrack would make that way too easy, and that's really about it in terms of temperature "significant" blocks.
Which would you suggest otherwise?

**Comment by JAWSAWN** [comment]
Packed Ice from the vanilla should be even colder than Ice. Also you missed the snow block.
Also Netherrack and Nether Bricks should be considered hot blocks since they are from the hottest dimension(Nether)? Also torch and fire sounds odd but could be considered small amounts of heat?
These are the blocks from vanilla that made sense for me.

**Comment by BluSunrize** [comment]
Netherrack+Brick, fire and torches are way too low in their thermal output, snow is too easy again
Packed ice shoudl work, but apparently it's broken, I'll go check it out.

**Comment by JAWSAWN** [comment]
Also does all of the molten TiC metals have the same heat value? They work. Also Liquid death works too??? Was that intentional? Also does non-source blocks work like flowing lava and water? If yes are they same as sources or not?

**Comment by BluSunrize** [comment]
Read.
"It works for every fluid, as well as multiple solid blocks."
That means every fluid block will be considered based on the temperature given to it by the author.
And it needs sourceblocks.
