### ISSUE TITLE
Arc Furnace not producing slag

### ISSUE THREAD

**Issue by Vingyy** [BluSunrize/ImmersiveEngineering#1043]
My Arc Furnace is smelting stuff, but it isn't producing slag. I have a conveyor connected to the back, but nothing is output. This isn't a big problem, but I kind of wanted to make an assembly line for concrete.

**Comment by Vingyy** [comment]
Does the furnace not produce slag if it is smelting dust?

**Comment by malte0811** [comment]
It only produces slag when smelting ores (which automatically doubles them) or making steel from iron and coke. That makes sense since slag is, from what I remember, the molten rock that was mixed with the ore and any other impurities.
To automatically produce slag I would recommend using the arc furnace to produce steel which should have slag as a byproduct.

**Comment by BluSunrize** [comment]
It also shows you in NEI what recipes produce slag.
Closed.
