### ISSUE TITLE
Galacticraft Ores. java.lang.IndexOutOfBoundsException.

### ISSUE THREAD

**Issue by Tsyklop** [BluSunrize/ImmersiveEngineering#1051]
Crash: http://pastebin.com/xT7fS6TJ

~~I try look recipe - Aluminum ingot~~

EDIT#1: this happens if i remove Aluminum ores, from mod Galacticraft, from OreDict:

https://github.com/Tsyklop/Cloud-Atlas/blob/master/scripts/OreDictionary.zs#L196

~~what wrong?~~

if comment this -  all OK.
`oreAluminium.remove(<GalacticraftCore:tile.gcBlockCore:7>);
oreAluminium.remove(<GalacticraftMars:tile.asteroidsBlock:3>);`

**Comment by malte0811** [comment]
It is the silly thing with aluminum and aluminium again. Try removing the arc furnace recipe that has `oreAluminium` (with an i) as the input. It is (or should be) automatically generated since both `oreAluminium` and `ingotAluminium` exist in the oredict when the auto-generation runs. Alternatively you can try adding IE's alumin(i)um ore to `oreAluminium` and the ingot to `ingotAluminium`, by default it is registered as just `ore/ingotAluminum`.
