### ISSUE TITLE
conveyor could cause weird mob spawn?

### ISSUE THREAD

**Issue by ZZaphodd** [BluSunrize/ImmersiveEngineering#1057]
Strange mob spawn near a metal press and conveyors.
I spammed a lot of torch and slabs around, but mobs are keep spawning

I see the yellow mob night spawn cross mark under the conveyor even there's a torch next to it.
And I placed slab blocks underneath the conveyor but mobs are still spawning

modpack : ftb skyblock 1.04

![image](https://cloud.githubusercontent.com/assets/8099421/14559238/367a6d00-0342-11e6-9ec1-d979b417cd68.png)

red : mob spawning suspect location, and minecraft says mob will spawn at night here(F7)
green  : a torch
![image](https://cloud.githubusercontent.com/assets/8099421/14559249/3e335c96-0342-11e6-900e-d41173b8aa37.png)

**Comment by syntax-error** [comment]
I can confirm a host of lighting issues on IE version 0.7.5; I also had two creepers spawn in one of these rooms, when the room was otherwise fully lit.

![2016-04-15_22 10 59](https://cloud.githubusercontent.com/assets/1825714/14561247/4fbe7c78-0358-11e6-8f76-b69b71de4f54.png)
![2016-04-15_22 11 06](https://cloud.githubusercontent.com/assets/1825714/14561246/4fbc6ca8-0358-11e6-8dfd-35d23cae1241.png)
![2016-04-15_22 11 16](https://cloud.githubusercontent.com/assets/1825714/14561248/4fc5b8ee-0358-11e6-96d7-2d6c5f65136a.png)
![2016-04-15_22 11 34](https://cloud.githubusercontent.com/assets/1825714/14561249/4fcaefbc-0358-11e6-8cd2-9d89782f1141.png)

**Comment by ZZaphodd** [comment]
I found a workthrough, it might be? just place conveyor non-sloped, still there could be lighting problem but does not spawn mobs anymore.

It look like less nice then before and it could be problem if there's 'Entity picker' like hopperhock from botania nearby(didn't test), I'm so happy because creepers does not destroy my base anymore.

**Comment by p75369** [comment]
For a temporary work around, try powered lanterns (or chandeliers/magnum torches) as they prevent mob spawns in a radius, rather than just emitting light.
