### ISSUE TITLE
Multiblock Lighting Issues in 0.7.4 and .5

### ISSUE THREAD

**Issue by Anesos** [BluSunrize/ImmersiveEngineering#1058]
I'm seeing problems with multiblock lighting in 0.7.4 and .5. This happens without fastcraft, optifine, or cofhtweaks installed and without solid blocks above the IE multiblock so this is different from the past reports that I was able to find. 

I'm playing the TechNodeFirmacraft pack and was not seeing this problem in the 2.15 version which included IE 0.7.2. The problem is consistent in TNFC 2.16, which includes 0.7.4. Every night, the IE multiblocks turn completely dark. I can walk around them and look at them in different directions for a bit and then they will light back up properly, but it will happen again later on. See attached images for a) after entering the world and b) after walking around a bit to get them to light.

![2016-04-15_14 02 47](https://cloud.githubusercontent.com/assets/17343257/14575693/5d5c37c0-0318-11e6-9994-5d538acf3395.png)

![2016-04-15_14 03 09](https://cloud.githubusercontent.com/assets/17343257/14575711/71ed476a-0318-11e6-940a-7bbb9b85c87c.png)

I also confirmed this after updating to 0.7.5 and with removing both dynamic lighting and hardcore darkness. The unlit machines are extremely dark because of hardcore darkness I believe, but it still happens without hardcore darkness installed.

I've been doing a video series with the pack, so I can point to it on video as well if that's helpful.

**Comment by Dijkstra1** [comment]
I am having lighting glitches to playing FTB infinity evolved (it uses fastcraft), blocks shuch as the improved blast, have dark areas around then where the rest of block would be if it was still a fall block, also if am climbing and wooden post my skin will go darker to.

**Comment by malte0811** [comment]
@Anesos This does not happen in my dev instance, which means that it is probably caused by some other mod. I assume that you removed the usual suspects (Optifine and Fastcraft), hardcore darkness and dynamic lighting before taking the screenshots?
@Dijkstra1 FTB Infinity contains Fastcraft. There are some known lighting issues with Fastcraft, if the lighting fixes itself after removing Fastcraft, we can't really do anything about it.

**Comment by Anesos** [comment]
The screenshots above were with hardcore darkness and dynamic lighting installed, but no fastcraft or optifine on my install. I also confirmed that I was seeing the problem without hardcore darkness or dynamic lighting installed on the client.

But with more testing today, I've found a somewhat complex interaction that was tainting my results.It appears that once the lighting calculation is bugged, it stays that way in the map file itself until you move close enough to make it re-calculate as I mentioned / showed in the screenshots above.

I mostly play this map on a server with a few other people, but for testing I used a backup copy of the world in single player so I could add / remove / update mods easily without changing the server. Looking through it all again, I found that fastcraft was still on the server. And when I copied the map over for single player, where I did not have fastcraft installed, the lighting problems seemed to have come over with the map files.

I've since removed fastcraft from the server and after you walk up to a dark machine and make it recalc the light, I haven't seen it go back to dark again. So in the end, it appears this was indeed a compatibility issue with fastcraft. Of course, if I leave it off the server now, we have chunk loading and performance issues so I'm stuck between which is the lesser evil.

In summary:
- Fastcraft was still on the server and that was causing the IE multiblock lighting issues to happen in the map.
- Once the lighting is messed up, it stays that way in the map even if you remove fastcraft or copy the map over to a single player save.
- Walking up to a machine and looking around at different angles causes the lighting to recalculate and fix the problem.
- If fastcraft is still installed, go back to the top of the list and the problem happens again. If fastcraft is not installed, the problem doesn't happen again.

So in the end, yes it's the fastcraft compatibility problem again further compounded by hardcore darkness making light level 0 look pitch black. 

Better compatibility with fastcraft is highly desired both on my end and for all of those new FTB skyblock players. These IE multiblocks are gorgeous, but now I have to choose between broken lighting and better performance.

**Comment by mindforger** [comment]
one thing, to support this, I really have to mention is world generation! It's messy with this many mods and makes a game quiet annoying when you always have to wait for the terrain to generate, even when only sprinting, and fastcraft therefor is somewhat a "must have"

**Comment by malte0811** [comment]
@sfPlayer1 This has started happening recently (a few weeks or so) and someone said that it started after updating FTB Infinity to [2.5.0](http://www.feed-the-beast.com/projects/ftb-infinity-evolved/files/2292902).
The relevant methods are `Block.getMixedBrightnessForBlock(World, int, int, int)`, `Block.getAmbientOcclusionLightValue()` and `Block.getCanBlockGrass()`. Did you change anything in these methods in Fastcraft version 1.22 or 1.23 that could cause this? If you did, can we work around it in some way?

**Comment by Dijkstra1** [comment]
So fastcraft does seem to be the be the issue, I know you do not have to do any thing but could you, if it help when I have night vision the problem is fixed, but when it runs out it back again.

**Comment by malte0811** [comment]
Fixed, will push the commit and PR later today.
@sfPlayer1 forget what I said, it is my fault, but in a very weird way:
In Superflat and RFTools worlds, `Block.getLightOpacity` is called before the chunk the block is in exists (I think you made a bug report about that with forge). This caused #999. My fix for that (6cd75891ad98f3f24fa12af9d107a01090f33df4) includes making blocks opaque if the `IBlockAccess` is not a `World` since I can't check for loaded chunks in an arbitrary (I will change that to be the default opacity value). Fastcraft checks for light opacity using a non-`World` `IBlockAccess`, causing the block to believe that it is opaque. This causes no light to get through to the rendering block. Result: The multiblock is rendered black.

**Comment by mindforger** [comment]
@malte0811 will this probably be cherrypicked back into 1.7.10 in a fix for the fix for the fix for the fix ?

**Comment by sfPlayer1** [comment]
Getting the world from IBlockAccess is reasonably annoying, I wish the interface had a method for it -_-

IC2 is using http://pastebin.com/gCwJra51 to find the World (best effort). ReflectionUtil.getFieldRecursive() finds a field with a specific type by scanning Class.getDeclaredFields() recursively (super classes up to java.lang.Object).

**Comment by malte0811** [comment]
@mindforger I have to fix this in 1.7.10 if I want to fix it at all since I don't have access to the 1.8 code.
@sfPlayer1 thanks for the code, but for now I will just make it return the "default" value for `IBlockAccess`'s that aren't worlds (Default value: return value of the `getLightOpacity`-method without parameters). That seems to work pretty well, just tried it with Fastcraft

**Comment by NoOneNo** [comment]
https://github.com/sp614x/simpledeobf

As an example, here is a guide on getting OptiFine into your dev environment with simpledeobf. This is the prime use-case of simpledeobf, and the reason for its existence.

The following is the actual command I use for the deobfuscation itself, so you'll need to change the directory names. It's a single command, but I broke it up into lines for readability.

java -jar simpledeobf-0.5.jar
--input h:\Minecraft\mods\obf\OptiFine_1.8.8_HD_U_H2.jar
--output h:\Minecraft\mods\mcp\OptiFine_1.8.8_HD_U_H2-dev.jar
--mapFile h:\Minecraft\.gradle\caches\minecraft\de\oceanlabs\mcp\mcp_stable\20\srgs\notch-mcp.srg
--ref h:\Minecraft\.gradle\caches\minecraft\net\minecraft\minecraft_merged\1.8.8\minecraft_merged-1.8.8.jar
--map="CL: bet$1 net/minecraft/client/entity/AbstractClientPlayer$1"
--map="CL: b$8 net/minecraft/crash/CrashReport$8"
--defaultPkg optifineroot
--forcePublic
This will give you a jar with the stable_20 mappings. The 2 map options are needed because OptiFine declares some extra inner classes that are not present in vanilla and have no mappings. If you want to do this for a different Minecraft version, you'll have to change these. Just start without manual mappings, and check if there are still obfuscated classes in the result. Check in the MCP files what the outer class is, and add a mapping. Rinse and repeat.

Open the resulting jar file, and delete the net/minecraftforge directory. There are dummy classes inside that are normally not loaded, but will cause problems in a dev environment. They need to go.

Now you have to create a tweaker and class transformer, because the default OptiFine ones will not work properly in a dev environment. Here is mine that I use in Better Foliage, you need something similar. The point is to change dots to slashes in the class names, so the OptiFine transformer can find the deobfuscated class files.

Edit the META-INF/MANIFEST.MF file. Change the TweakClass option to the tweaker you just made.

The jar is now ready. If you also want source attachment, which is highly recommended, just decompile it with your favourite tool (I prefer JD-GUI), and save a source jar. Make sure that "Realign line numbers" or the equivalent option is turned on.

Drop the jar in the mods folder of your workspace, manually add it to the project dependencies after all the Gradle stuff, set its source attachment, and you're ready. You can start your project with OptiFine thrown in the mix, debug, set breakpoints, and everything.

Note: Debugging into one of the vanilla classes that OptiFine overwrites may or may not give you some headache under Eclipse. I can only confirm it works fine under IDEA, which allows you to switch between sources on the fly if multiple jar files declare a class. A popup comes up saying "Alternative source available for the class blah blah blah", and you can switch to the OptiFine jar, which contains the class actually executing.
