### ISSUE TITLE
[1.8.9] Ic2 Uranium 238 bypass using Uranium block with Ore Dictionary Converter

### ISSUE THREAD

**Issue by Insufficient-Charge** [BluSunrize/ImmersiveEngineering#1108]
This is a clash with three mods, but I believe it's IE's fault. Since the uranium block from IE is made from 9 uranium ingots, I can then use the Ore Dictionary Converter (from that mod) to turn it into a block of uranium from Ic2. Said uranium block can then be turned into 9 Uranium 238 from the Ic2 mod. This bypasses many machines needed in order to get said uranium 238, because the IE Uranium block is ore dictionaried with the Ic2 uranium block. This, however, might not be IE's fault, and please tell me if I should contact other mod authors. :)
![2016-05-07_16 50 45](https://cloud.githubusercontent.com/assets/13188566/15094737/e4760184-1473-11e6-8a65-4241d5ccc116.png)
![2016-05-07_16 50 58](https://cloud.githubusercontent.com/assets/13188566/15094739/e71be5ac-1473-11e6-913b-298156d3a2c2.png)

**Comment by theunkn0wn1** [comment]
This is an exploit enabled insofar as IE uranium block is  oredict to IC2/e uranium block. This can be mitigated by using MineTweaker to disable IE's uranium block recipe.

I do agree this exploit breaks game balance however IE has no reason to fix other mods issues, IE is not the root cause here as IC2/e made the error(IMHO) of using oredict for its uranium storage block even though it's component items, u238 are not oredict to ingotUranium...

**Comment by BluSunrize** [comment]
Okay, let me get this straight.

IE adds Uranium ingots. They oredict to "ingotUranium". It adds a storage block, oredicted as "blockUranium". That is the same procedure as done for Iron and Godl and for basically every metal added by a mod.
IC2 adds a block registered to "blockUranium", which breaks down into Uranium 235, which isn't an "ingotUranium" and is supposed to be the end of a more complex production chain.
Where is MY error here? IC2 should maybe label the block as blockUranium235, rather than chucking it into a pool with other Uranium blocks that use the "normal" system of blocks and ingots?
I don't see myself in the duty to do anything about this, because as far as I'm concerned, I did nothing wrong. I'd say to poke the IC2 devs about it, or use Minetweaker (I think it's called Crafttweaker now?) to take the IC2 block out of the uranium table, because, this is where the oredict is important, if my Block of Uranium isn't registered as "blockUranium", it won't work with IE's Thermoelectric Gen.

**Comment by Insufficient-Charge** [comment]
I didn't know any natural order of ore dictionary mattered...sorry about this... I will contact then author s of ic2

**Comment by BluSunrize** [comment]
Not a natural order per say. But an unspoken consensus. Along with the naming scheme of [type][material] ("ingotIron", "gemDiamond", "nuggetCopper") comes the general idea that everything that is called "Iron" is the same material, and therefore associated under the commonly found situations of Minecraft.
E.g: 1 block is 9 ingots. As such, I'd expect something called "blockUranium" to consist of 9x "ingotUranium". That's the general thoughtprocess I went for in IE. If other mods followed some other process, they're free to voice that.
