### ISSUE TITLE
[1.8.9][bug] Barrels not accepting fluids from metal pipes.

### ISSUE THREAD

**Issue by elkillo** [BluSunrize/ImmersiveEngineering#1141]
i have a fermentor and squeezer filling a refinery for biodesial. i noticed that even though the refinery and squeezer are full i cannot get any fluids into the top of a barrel with metal pipes. it should also be noted that adding buckets or bottles to the UI also does not get any sort or reaction either. so getting the speed upgrade for the drill isn't possible as it need bottles of seed oil. testing in SSP mod list can be listed on request.

**Comment by malte0811** [comment]
Buckets/bottles not getting filled in the squeezer and the fermenter is a known bug that should be fixed in the next version. Pipes are currently misbehaving a bit, that should also be fixed in the next version. Try placing a pipe anywhere on the ground, then break it and check whether fluid is being transferred to the barrel.

**Comment by elkillo** [comment]
i can confirm this is a temp fix but it does work.
