### ISSUE TITLE
[1.8.9] Preheaters take 0RF/t and don't work?

### ISSUE THREAD

**Issue by chrisbecke** [BluSunrize/ImmersiveEngineering#1159]
I have constructed an advanced blast furnace and hooked up two preheaters that I have connected to power. They are not operating. Perhaps I am supplying insufficient power as I have, only, a triple water wheel at the moment. But when I examine the Engineers manual's page on preheaters it claims they take 0RF/t.
Also - saw the same issue on forgecraft on direwolfs latest forgecraft for 1.8.9 when he built them.

**Comment by BluSunrize** [comment]
First of all: Dire's vids are literally nothing to go by. He paid little to no attention to IE on the last season and effectively dropped it for EIO. I fixed a LOT of stuff since then.The manual page showing 0 Flux/t is a known bug (albeit one that noone seems to be bothred to report. I literally heard of it in discord yesterday).
Now the question is: Do they actually work? Do they speed up your Blastfurnace? Have you tried that? Because that's the important piece.

**Comment by chrisbecke** [comment]
Are the fans on the pre-heaters meant to animate while they operate?

**Comment by BluSunrize** [comment]
Not really, no. Couldn't be bothered, with Forge's current clunky model system. Might bring back the animation when we have OGEX in 1.9.
