### ISSUE TITLE
[Suggestion] Interior Wiring Aesthetic

### ISSUE THREAD

**Issue by p75369** [BluSunrize/ImmersiveEngineering#1165]
I know you don't want to introduce block based RF transmission, this is not that.

However, I do think it would be nice if we had a more OSHA compliant indoor wiring option than bare wires.

So, here is my suggestion:

Conduits. Functionally identical to wires, but cosmetically different.

- Thicker, clearly insulated, texture/model.
- Relays become junction boxes.
- Connectors become plugs/sockets.
- Conduits don't sag.
- Conduits connnect to the base of the junction/plug.
 - Those combined should create the effect of it being pressed against a surface when, say, two junctions are mounted on a wall.
 - If you're feeling like a challenge, maybe a pathfind on placement so that it can hug a wall and wrap around corners.

**Comment by James-T-Oudvoure** [comment]
I support this. Wires look ugly as hell inside a building, but block/rf "pipes" look even worse. This could allow the internal wiring of something to look beautiful.

**Comment by BluSunrize** [comment]
No.
I have said time and time again that IE will not be introducing a secondary power system. I stand by that decision.
IE's current wires are implemented and working. A second system would further user confusion as well as dramatically increase the require upkeep work on the codebase. It's bad enough to debug the current energy transfer system since it was written so long ago. I'm not opening another can of that.

**Comment by James-T-Oudvoure** [comment]
At least you've given an actual reason for refusing, instead of just saying "Nope!".

**Comment by p75369** [comment]
Aww, guess I underestimated what goes into a cosmetic tweak. Ah well, live and learn.
