### ISSUE TITLE
[Error] I am running a Server and Players Loading IE Machines causes Crash

### ISSUE THREAD

**Issue by Ryansemch** [BluSunrize/ImmersiveEngineering#1177]
When ever A player loads a Chunk with an IE Multi-Block machine in it(The area in question has 2 crushers and Excavators), The Server Closes down and Generates with Error File. I would appreciate some Help.
http://pastebin.com/sTf2wsm8
Thank you

**Comment by mindforger** [comment]
it looks like a side check issue with stabilizermod ... it tries to play a sound om the server and hooks into IE stuff to do this .. you may try to post the issue to stabilizermod too

**Comment by malte0811** [comment]
Maybe similar to #354? I'll look for references to IESound.

**Comment by malte0811** [comment]
Probably caused by [this line](https://github.com/BluSunrize/ImmersiveEngineering/blob/1.7.10/src/main/java/blusunrize/immersiveengineering/common/blocks/metal/TileEntityCrusher.java#L78). IESound does not exist on the server because the superclass is client-only. That variable should have an `@Overrride`-annotation.

**Comment by Ryansemch** [comment]
So I can just remove The Crusher for now and not build another, Is there anyway for me to fix this?

**Comment by malte0811** [comment]
The world should load just fine in singleplayer. I suggest you copy the world into singleplayer, break the crusher and put it back on the server. More permanent fixes would require replacing the server version of IE with a custom one, but that isn't recommended and I am not even sure whether it is entirely legal.
