### ISSUE TITLE
Is there a Supersized improved blast furnace?

### ISSUE THREAD

**Issue by LemADEC** [BluSunrize/ImmersiveEngineering#1190]
As seen on FTB Inventions 1.0.1 which includes ImmersiveEngineering-0.7.7, the mod tries to create an oversized blast furnace:
![2016-06-12_11 50 42](https://cloud.githubusercontent.com/assets/4776032/15990495/0dd97736-3094-11e6-8fdc-84976ad25753.png)
![2016-06-12_11 50 44](https://cloud.githubusercontent.com/assets/4776032/15990496/0ec9e356-3094-11e6-9943-1235463969ad.png)

I had the issue initially by creating an Improved blast furnace (3x3x3), right next to my existing Cruse blast furnace.

**Comment by BluSunrize** [comment]
Using optifine?

**Comment by LemADEC** [comment]
No optifine involved

**Comment by LemADEC** [comment]
I can't reproduce in single player, so it might be network or plugin related.

**Comment by malte0811** [comment]
Plugin related? So you have some sort of forge-bukkit(or whatever it is called now)-mix on the server?

**Comment by LemADEC** [comment]
Yes, we do have a Cauldron style server.

**Comment by malte0811** [comment]
Then it is probably caused by Cauldron. Something similar used to happen with Optifine because they called a method with the wrong metadata value, but I haven't ever seen this happen without Optifine before this bug report. Cauldron is not supported by IE, as it says in the [CONTRIBUTING:md](https://github.com/BluSunrize/ImmersiveEngineering/blob/1.7.10/CONTRIBUTING.md#other-mods) file.
I know, it also says that Optifine is not supported, but the public versions of IE were pretty stable and I had nothing else to do when I debugged this bug with Optifine.

**Comment by LemADEC** [comment]
I don't see how a server plugin would cause such client side rendering bug, that seems fairly stretched

**Comment by bookerthegeek** [comment]
Just because you don't see how does not mess it doesn't. 

And it might not be a "plugin". It literally could be just bukkit messing up.

**Comment by LemADEC** [comment]
I'm not saying it's impossible, I'm just surprised it could be causing that impact with no other visible effects on any other mods in our 10 different servers. We'll see when we can test it with pure Forge.

**Comment by mindforger** [comment]
just because you claim you'd hit all right hand thrown baseballs doesn't mean that there might be a left handed thrower that makes you miss terribly ... other people claim they can hit most aof left and right hand thrown baseballs but they do not claim to never miss ... 

you can either program in a defensive way to prevent certain issues or you can go all fancy and risk someone throwing you off by doing things in other ways than expected, something that cauldron does! (not a blame just as it is)

try to switch to sponge, it is based on forge ... a mod that implements a bukkit like API

**Comment by LemADEC** [comment]
Issue is intermittent. When it's not happening, I can see a visual glitch for a split second. I wonder if it's network latency related.

**Comment by mindforger** [comment]
all blocks you see are the same block with different rendering data, they start in this weird state and then render the right away after they got updated ... maybe cauldron/bukkit transmits the blocks without data and updates them a split second later !?
also could be a plugin blocking the blockupdate for one update cycle

**Comment by LemADEC** [comment]
Issue is reproduced with Forge server:
![image](https://cloud.githubusercontent.com/assets/4776032/17276871/3b798150-5735-11e6-807a-26e662190296.png)
As said earlier, it's intermittent, client side only, probably related to network latency.
ImmersiveEngineering-0.7.7
forge-1.7.10-10.13.4.1614-1.7.10
No optifine
No shaders

**Comment by LemADEC** [comment]
Issue is reproduced from any side, without an attached blast furnace.
