### ISSUE TITLE
[1.8]Excavator wheel renders the wrong way

### ISSUE THREAD

**Issue by xbony2** [BluSunrize/ImmersiveEngineering#1191]
[Looks a little silly.](https://i.imgur.com/JA6c1d4.png)

**Comment by elkillo** [comment]
Its the new super ergonomic mining wheel! Its a new feature bit a bug! :D (jk ofc). Have you tried relogging and is optifine or bukket/couldron installed?

**Comment by xbony2** [comment]
There's no Optifine or Bukkit. Relogging hasn't helped.

**Comment by RocketPhoenix** [comment]
Can we change this to a suggestion instead of an issue?
It's better when you see this feature [in action](http://imgur.com/a/bTE2F)
This is in the All the Mods modpack version 1.19 for MC 1.10.2
Immersive Engineering version 0.10-38, in case you're interested in removing this for some reason
(inside an RFTools dimension, with the power input facing East)

**Comment by BluSunrize** [comment]
@RocketPhoenix try updating to the latest IE. Would save you from necroposting on old issues ;)

**Comment by xbony2** [comment]
No offense, but I think that's a dumb idea :P maybe you could make a silly addon or something.

**Comment by RocketPhoenix** [comment]
My, bad.
I was under the impression that this was fixed for a version previous to what I'm using :p 
Could you please re-implement this feature into future versions?

**Comment by BluSunrize** [comment]
...no?
