### ISSUE TITLE
[1.8.9]CPU-Spikes/Lagg-Spikes after installing IE

### ISSUE THREAD

**Issue by cad435** [BluSunrize/ImmersiveEngineering#1193]
Hello,

After playing a while with IE stuff, my game got laggs periodically and I noticed a strange CPU behaviour, I'll attach a Pic of the CPU-Load (http://fs5.directupload.net/images/160613/uniivzr3.png)

I'm not 100% sure if it's IE but it's quite likely cause it happens only after playing with IE items/blocks and it haven't happened before installing IE.

Removing or installing Optifine don't make any difference.

Here are the other mods I installed: http://prntscr.com/bfvkty

("thaumcraftServerHelper" is something from myself, It's not causing it, I already checked it!)

It happens on a Server as well as in SP

cad435

**Comment by malte0811** [comment]
Please generate an NPS file for this. CPU load doesn't not really help except in showing that there is lag. You can generate the NPS file by 2 different methods:
1. (I would recommend this method since it is easier and gives samples of the spikes only) Install Sampler (You can download it [here](http://forum.industrial-craft.net/index.php?page=Thread&threadID=10820), "Extra tweaks/tips" section) and run the command `/sampler trigger ticktime 100`. Wait for a few lagspikes to happen, you should see messages in the server log saying that samples have been exported to specific files (If those messages don't appear, try replacing the 100 by 50. That will capture less "spiky" spikes). There should be files called `spike-xxx-xxxxxx.nps` in the main server directory (where stuff like the eula confirm file is).
2. The second method is described [on the AE-website](http://ae-mod.info/profiling/) (but please don't send the file to the AE people since they have nothing to do with it)
Once you have the NPS-file/files, upload it to something like Dropbox and post the links here.

**Comment by cad435** [comment]
öhm, Isn't Sampler just for server-threads, wich will exclude all ClientSideOnly/GL-operation threads? 0.o
Please correct me If I'm wrong...
anyway, I wasn't able to complete a Biodiesel an a brand new creative map untill the first Spikes occure - here are the NPS Files.
[Immersive_Engineering_Issue_1193_Lagg_Spikes.zip](https://github.com/BluSunrize/ImmersiveEngineering/files/312518/Immersive_Engineering_Issue_1193_Lagg_Spikes.zip)


Thanks for take time

**Comment by malte0811** [comment]
Ok, those files don't show anything interesting. I thought you were talking about server performance, not client. If you have FPS lag, use `/sampler trigger frametime 100`. The command I gave you before triggered at server ticks over 100 ms, this one will trigger at frames lasting over 100 ms.
By the way, sampler will pick up anything (server+client thread, robot managing thread, thaumcraft aura processing, etc) happening in the Java process during the lag spike. The problem is, if it triggers at the wrong time it won't be able to record anything interesting.

**Comment by cad435** [comment]
yes, I know the tool, but I used it only for servers, never for Clients...
Anyway, there are another 5 NPS files: [Immersive_Engineering_Issue_1193_Lagg_Spikes_2.zip](https://github.com/BluSunrize/ImmersiveEngineering/files/312546/Immersive_Engineering_Issue_1193_Lagg_Spikes_2.zip)

**Comment by cad435** [comment]
While playing around I noticed something else:
every lag seems to be a run from the Garbage-collector...

maybe this helps...

**Comment by XFactHD** [comment]
This would mean that you either haven't allocated enough ram or you have allocated to much ram. I once tried to play MC with 14GB of ram allocated to it and because the jvm can't handle that much ram in one application efficiently, the game lagged every time the garbage collector ran.

**Comment by malte0811** [comment]
I'll take a look at a heap dump of my instance later today, but MC 1.8 generally generates more unused objects/garbage than previous versions because all methods like `getBlock(int, int, int)` have been changed to take a `BlockPos` object as a parameter.

**Comment by mindforger** [comment]
i found that resizing the generation-space-ratios to the demands of forge and the used mods can halp a lot 

but it needs several cycles of evaluation with dumping tenuring stages and space fragmentation ... i can share some configs later @cad435 i'll post an issue on my heavily outdated IE fork when i get home in about 8h for you so we can discuss this without disturbing Blu and Malte :) https://github.com/mindforger/ImmersiveEngineering/issues

**Comment by cad435** [comment]
I have 3GB of Ram allocated.
It seems to be fine, Garbage Collector is working properly, up to a point were it suddenly starts lagging each time the GC takes a run. And it seems to happen when playing around with the IE-Mod.

@mindforger: TBH i'm not sure what you talking about, if you talk about the maxPermGen space, I run on Java8 were MaxPermGen isn't supported anymore, but I'll appreciate any help!

cad35

**Comment by DosMike** [comment]
Taking a quick look at [IESmartObjModel.java](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/client/models/IESmartObjModel.java) and some other jars. **I don't know how relevant this is**, but I can imagine making your caches static might help. as of right now e.g. IESmartObjModel is holding IESmartObjModels in the cachedBakedItemModels, which (because cachedBakedItemModels is not static) hosts another cachedBakedItemModels-list of their own. A bit like this:

```
IESmartObjModel
+ cachedBakedItemModels
 + IESmartObjModel (entry 1)
  - cachedBakedItemModels (should be empty, but it's a GC-able object)
 + IESmartObjModel (entry 2)
  - cachedBakedItemModels (should be empty, but it's a GC-able object)
 ...
```

I'd make those caches *static* fields or if each IESmartObjModel requires it's own cache (seems to be not the case) think of a different class structure.

**Comment by malte0811** [comment]
They really should be static, I just never noticed that they weren't. I also found a way to drastically reduce the amount of memory the crusher uses on the server side (up to about x64 in the most extreme case), I will push a commit to fix that tomorrow.

**Comment by cad435** [comment]
Ddrdd,,


Outlook for Android herunterladen






On Tue, Jun 14, 2016 at 9:09 PM +0200, "malte0811" <notifications@github.com> wrote:












They really should be static, I just never noticed that they weren't. I also found a way to drastically reduce the amount of memory the crusher uses on the server side (up to about x64 in the most extreme case), I will push a commit to fix that tomorrow.

**Comment by BluSunrize** [comment]
And THAT is why email reply on github is terrible. GG on the formatting buddy >_>
