### ISSUE TITLE
[1.7.10] IE crashes on startup

### ISSUE THREAD

**Issue by naamtune** [BluSunrize/ImmersiveEngineering#1210]
I used IE sometime early of last year with no problem on top of all the other mods. I recently decided to wipe clean my mods folder and put in IE version 0.7.7 along with SEUS and Optifine mods but when attempting to start up the game, I get the crash below:
http://pastebin.com/EvxSAEr8

Then I left IE as only mod installed and it continues to crash at startup. Not sure what other issue it could be.

**Comment by mindforger** [comment]
did you wipe your config also?
on top of that your java version is outdated, i noticed you are probably running on the JRE delivered with the launcher!
change that in your settings, aside from that i have no idea what could cause that :)

and one thing ahead, whenever you report issues about IE, always try without optifine first, it causes a lot of issues you won't think of

**Comment by BluSunrize** [comment]
Yeah, I think a config wipe should do the trick here.

**Comment by TeeJayPlayz** [comment]
Im having the same problem. I wanted to use this mod in a modpack adventure but it keeps crashing my modpack for my testers. I have these mods: Optifine, Buildcraft, Industrial Craft, IE, and Custom NPCS. Now i tried putting it alone and testing it but it keeps crashing me every time and here is what i get: http://pastebin.com/1xbtz2Lj

Please help D: i need to get this modpack up within the next week otherwise ill miss my deadline!

**Comment by AEnterprise** [comment]
if you have the same problem, did you try the same fix?

**Comment by naamtune** [comment]
@BluSunrize  @mindforger 

Outdated Java RE isn't part of the issue since I was able to run all other mods (all up to date) with no issue. As of currently I'm running all mods w/ an outdated JRE.

However, deleting the config folder did the trick. I forgot to do that after I had wiped the mods folder. I'm able to play the game with all the mods installed, including shadersmod and Optifine. Thank you guys for the help.

**Comment by mindforger** [comment]
@naamtune i was hinting you to use a newer version of java because of firstly security concerns and secondly of **KNOWN ISSUES**!
Next time you will come along with rendering issues and say "but i run sevceral other mods with optifine just fine" but optifine is well known to cause rendering issues under certain circumstances ... it was an attempt you help you not to blame you

**Comment by naamtune** [comment]
@mindforger My apologies if my previous post about the JRE came off rude. It wasn't meant to imply that your suggestion was not useless, as it would definitely have patched security flaws and known issues. I appreciate your assistance though.
