### ISSUE TITLE
[1.8.9] ArcFurnace crashes when melting armor

### ISSUE THREAD

**Issue by KIN0025** [BluSunrize/ImmersiveEngineering#1215]
The arc ~~reactor~~ furnace crashes when melting iron Armour. 
I haven't tested any other types yet. This happens on 0.8 - 28. 

This kills the save until the config option is disabled.

Logs:
[fml-server-latest.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/334614/fml-server-latest.txt)
[crash-2016-06-27_05.02.19-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/334612/crash-2016-06-27_05.02.19-server.txt)

**Comment by BluSunrize** [comment]
First off: An Arc Furnace is NOT, under NO condition and Arc Reactor. This is not an Iron Man mod. Totally unrelated!

Back to the topic at hand: Are you sure this was caused by vanilla iron armor? If so, are there any mods in your pack that modify the crafting recipe for that armor or add other recipes for it?

**Comment by malte0811** [comment]
I can confirm this crash, vanilla iron armor. The inputs are deleted from the inventory before the output is calculated. This isn't a problem for any other recipes (non-arc-recycling) since they don't try to access the input stack in `getOutputs`.
A possible fix is moving [this](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/blocks/metal/TileEntityMultiblockMetal.java#L618) call to the start of the method, but that could cause dupes if there is a crash in between the outputting and the input deleting. An alternative might be to copy the input to a variable before deleting it from the inventory and calling the outputting method afterwards, but that might get messy.

**Comment by KIN0025** [comment]
Can confirm that it occurs with only JEI and Immersive Engineering installed.
