### ISSUE TITLE
[1.8.9] Crash while tesselating block in world

### ISSUE THREAD

**Issue by belathus** [BluSunrize/ImmersiveEngineering#1230]
http://pastebin.com/Qa3sjsqj

It isn't common; in fact, this crash is pretty rare. At the time of the crash, I was just placing concrete.

**Comment by malte0811** [comment]
*Might* have been fixed by f17c8f3545b28b66c04beb703ce9e25ec75ce524, which I will PR now.
Does this crash happen frequently for you? If it happens frequently, please try the next version of IE once it is released. Otherwise I would suggest to close this issue since it isn't really possible to check whether it has been fixed or not.

**Comment by belathus** [comment]
This crash is pretty rare, really. I'll go ahead and close it, and let you know if I see something else in the next release. Thanks!
