### ISSUE TITLE
[Suggestion] Weapon ideas

### ISSUE THREAD

**Issue by Azormik** [BluSunrize/ImmersiveEngineering#1254]
I've been thinking of some weapon ideas to expand the arsenal.
1. "Arc gun"[short-med range] . It shoots out bolts of electricity and can hit multiple targets. To make it look retro sci-fi there will be testla coils sticking out the front and you can upgrade the damage by adding more coils to the front. It starts out with one coil and you can add 2 extra ones at the front. You can also increase the battery capacity.
2. "Slag cannon" [short range] . Inspired by the Flack Cannon from Unreal Tournament. It uses slag as ammunition it's powered by steam and basically acts just like the Flack cannon. Minus the secondary fire. To make it look retro sci-fi there will be a pressure gauge on the side with some steam pipes connected to the tank with valves. To increase its power and range you have to upgrade the steam tank.
3. "Gatling Gun" [short-medium range] . It's powered by steam and gears . You increase the fire duration by increasing the tank capacity that holds the steam and you add gears to increase the rotation/firing speed (3 gears max) . I haven't really thought of the ammunition a whole lot. Maybe It can use nuggets or you have to use the press to make small bullets with ingots. To make this look retro sci-fi there will be some gears connected to the barrels and some steam pipes connected to the tank with valves.

**Comment by elkillo** [comment]
i believe Blu has already said that this mod is not going the Steam route. so the second and third ideas are unlikely however a portable Tesla coil as a heavier weapons sounds like it is more inline with the mod. Probably would need the fairway suit on to not have the electricity back and kill you =P. besides i think something like a bolt action rifle fits the whole industrial era theme of the mod also maybe, but balancing would have to take place so that people will still use the revolver. But those are my 2 cents ultimately its up to the devs on what they want.

**Comment by PrincessRTFM** [comment]
> fairway suit
Did you mean _faraday_ suit? Cause fairway doesn't make much sense to me, but I might have missed something...

**Comment by elkillo** [comment]
no i ment faraday, but i was posting on my phone and it auto corrected it =P
