### ISSUE TITLE
[Feature Request] Dyeable Conveyor Belts

### ISSUE THREAD

**Issue by Voxel-Friend** [BluSunrize/ImmersiveEngineering#1257]
Title says it all, just a thing that feels like it should be but isn't, I understand if you don't want to (I realize how much of a  PITA it would be to add 15-16 states to  a handful of Tiles)

**Comment by ShadowDrakken** [comment]
I second this. Just as with redstone wiring, it's very handy to have colored tracks to prevent accidental crossover of systems.

My idea for this however would be rather than dying the belt, to add colored labels stuck onto the rails of the conveyor, just as you might see IRL :)

**Comment by Voxel-Friend** [comment]
Even If they still fuction similarly (red conveyor sending items onto a blue, for example) it would open up some options aesthetically, plus it would help keep track of what goes where.

Very Amateur mockups
Version 1 (Shadowdrakkens version)
![conveyorv2](https://cloud.githubusercontent.com/assets/12395262/17952968/9e97af20-6a34-11e6-89b5-ed6092d6a580.png)
Version 2 (My version)
![conveyorv1](https://cloud.githubusercontent.com/assets/12395262/17952967/9e957e62-6a34-11e6-834c-032120fbeb48.png)

This suggestion was born from browsing TacoRedneck's amazing nuclear facility, and specifically seeing [this](http://i.imgur.com/dd77fHF.png)  (he  probably had a texture pack.)

**Comment by BluSunrize** [comment]
With the old modeling system this was basically impossible, hence why I didn't comment sooner.
Now, with the new dynamic model system, I can make this possible!
I will probably add some coloured stripes on top of the belt, but not colour hte entire thing (that'd look weird)
This won't actually bring any sorting features (because belts are not smart enough for that), but it will allow players to easier track which belt goes where.

Sound good? Definitely on my ToDo list now!

**Comment by Voxel-Friend** [comment]
Sounds great! Saw the teaser on twitter, looks good!

**Comment by Voxel-Friend** [comment]
since this is implemented, will close.
