### ISSUE TITLE
[1.8.9] Assembler not working in version 0.8-32

### ISSUE THREAD

**Issue by Shandoo94** [BluSunrize/ImmersiveEngineering#1270]
I updated Immersive Engineering from version 0.8-28 to 0.8-32. In version 0.8-32 the assembler isn't crafting anymore. I tryed to rebuild the multiblock, but it didn't help. Am I the only one with this issue?

**Comment by malte0811** [comment]
I can confirm this issue from looking at the source code, I only added a check for `computerOn[i]` and forgot about checking `controllingComputers>0`. If you have OpenComputers or ComputerCraft, you should be able to fix this by connecting some sort of computer to the assembler (as described in the "Computer support" section of the manual).

**Comment by Shandoo94** [comment]
I connected a computer from ConputerCrfat as descibed in the manual. The computer is running, but the assembler still isn't doing anything. I'm using ComputerCraft 1.7. Is it possible to temporary fix this by diabeling the ComputerCraft support in the Config-File?

**Comment by malte0811** [comment]
Disabling CC support won't help, I can tell you that much without my computer.
I am not sure under which conditions the method that needs to be called is called, you could try connecting a wired modem+1 block of wire and connecting the modem to the "network" by right-clicking it. Another sollution might be to make a startup script on the CC computer calling `peripheral.wrap` for the side the assembler is on. The problem is that I can't test these fixes right now because I don't have a computer with MC 1.8, especially not with the latest version of IE, with me.
