### ISSUE TITLE
[Suggestion] Fluid Pipe Valves

### ISSUE THREAD

**Issue by Dijkstra1** [BluSunrize/ImmersiveEngineering#1328]
I would like an fluid valve, something like below but metal handle, and rusty vanity might be nice, and it must spin, right clicking it would toggle fluid being able to pass though.

![image](http://previews.123rf.com/images/lucadp/lucadp1207/lucadp120700007/14508699-one-pipe-with-a-red-valve-and-a-white-label-for-custom-text-3d-render--Stock-Photo.jpg)

P.S. I do not care if cut of liquids from pass through, i Just want it to look nice.

**Comment by Bitterholz** [comment]
Is that actually Implementable? Because as far as i know, Pipes in IE are just dummies for the network of pipeage...AKA Fuild can go in and out on any Connection. So essentially it teleports the Fluid.
Not sure how a Valve could be implemented in that

But indeed it would be a nice addition

**Comment by MrEvilCookie** [comment]
fluid vales are cool)

**Comment by BluSunrize** [comment]
@MrEvilCookie, that was possibly one of the least productive comments you could make.

@Bitterholz has already grasped one of the key issues. To make this actually work, I would reduce the efficiency of hte pipe-net by a LOT, because every time the valve is opened or closed, I'd probably wipe the connection cache, forcing the pipes to search for all available outputs again.

Lastly, this suggestion exists already, see #1124, so please search before you open a new issue.

**Comment by berinhardt** [comment]
What @Bitterholz says could easily be bypassed by making the valves have a small internal storage and work like retextured barrels that outputs into another network. I asked for this feature in the past because It's kind of weird turning on and off the "valves" (actual barrels) with a hammer

**Comment by MalkContent** [comment]
can't you keep it separate connection caches and merge them on demand when the valve is open? not sure how that would do performance wise

**Comment by theunkn0wn1** [comment]
@MalkContent The problem arises when multiple valves are placed in the network, greatly increasing memory and computational requirements when every possible path has to be calculated potentially growing exponentially. Fundamentally it would be cheaper for larger networks to recalculate on the spot, which is still expensive.
@berinhardt , we might as well add a rs toggle to the barrel then, no need for a new block. I don't recall if this function already exists. But otherwise the idea of using a storage block as a configurable buffer seems to be the most efficient method to achieve the desired end IMHO.

**Comment by MalkContent** [comment]
i don't see how that would be (much) more memory/computation intensive than one big network that isn't divided by valves
you have the network an input point puts into, [x] get all output points from the network, get the networks of all open valves in the network, goto [x]; prevent going in circles by creating network ids and see that you don't check the same network twice

don't even have to actually merge tables, just check all chained up networks.
all valves open should have you end up with the same amount of table gets like the same network w/o the valves. dunno how much the extra stuff of checking valves open/closed would cost
i guess you could just remember which networks are merged and only evaluate the valves when a valve changes/is added/removed

disclaimer: i know nothing of how IE pipes actually work, just took a guess and probably am talking out of my ass

**Comment by Dijkstra1** [comment]
How does this sound make item that works like a lever and looks like then handle of value, have the barrel toggle output on redstone, and stick handle on the barrel.

**Comment by berinhardt** [comment]
I like the "RS to the barrel" idea, even the common levers go with the factory theme
