### ISSUE TITLE
[1.10.2] Wooden Posts not extending arms when engineers hammer used on the sides.

### ISSUE THREAD

**Issue by devilunaworkshop** [BluSunrize/ImmersiveEngineering#1346]
![2016-08-28_20 54 54](https://cloud.githubusercontent.com/assets/21285218/18036004/9f9efb96-6d61-11e6-88c1-7fe52fc5fc69.png)

When right-clicking sides of the top-most block, the arms of the post do not extend.

**Comment by Bitterholz** [comment]
Do the bounding boxes show up tho? or just notting happening at all?

**Comment by theunkn0wn1** [comment]
I can confirm the side arms have never worked since the 1.10 migration occurred, it does not seem the function ever got implemented

**Comment by Bitterholz** [comment]
Wouldnt say "not implemented". I think it comes down to problems with rendering and extended blockstates. Ive rattled with those too, not a fun experience i tell ya

**Comment by BluSunrize** [comment]
love how accusing "never got implemented" sounds, yet this is the first time I have ever had it reported, lol.

**Comment by theunkn0wn1** [comment]
I'm sorry Blu, seems my choice of wording was a little poor as I never intended to cast any accusations. I haven't reported this in the past because when I encountered this issue many of IE's  features had yet to be implemented for 1.10 so I just foolishly brushed it off.

Either way the core issue remains: the post extensions cannot be added to wooden posts as the feature had existed in previous versions of IE

**Comment by BluSunrize** [comment]
Fixed, see commit above
