### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Chupp4-Jo3** [BluSunrize/ImmersiveEngineering#1368]
http://pastebin.com/equ1drEu

I broke it....

Afraid I don't know anything other that it crashes on startup after I got lazy and updated a load of mods at the same time :/

Hope this makes sense to you

**Comment by BluSunrize** [comment]
Reproduce that without optifine.

**Comment by mindforger** [comment]
```Java
	public float getCharWidthFloat(char character)
	{
		if(character==32)
			return customSpaceWidth;
		return super.getCharWidth(character)+spacingModifier;
	}
	@Override
	public int getCharWidth(char character)
	{
		return (int)this.getCharWidthFloat(character);
	}
```

did the super call backfire?! i just have no idea how that can actually happen

**Comment by BluSunrize** [comment]
It's an optifine issue, I'm fairly sure. I've seen this one before.

**Comment by BluSunrize** [comment]
because I call super.getCharWidth, not this.getCharWidth. I'm not looping it.

**Comment by Chupp4-Jo3** [comment]
Of course it was bloody Optifine -_-

ty for the help guys, you reckon it's worth sending the crash report to the Optifine devs or is it just Optifine doing its crazy shenanigans?

**Comment by BluSunrize** [comment]
I don't think they'd care.

**Comment by mindforger** [comment]
is there a chance that optifine hooks into the base class using the exact same method-signature causing your code to implicitely override the hooked version!? i see what you mean but i was looking at another construct where the super.m1 is calling another methode "m2" that has been overrriden calling the "this.m1" .. you are not overriding the getWidthFloat, but what if it is implicitely overridden because optifine changed the base class? Maybe it would help if you make the signature more unique? getCharWidthFloat_ImmersiveStyle()? XD
