### ISSUE TITLE
[1.10.2] Coke Oven stops working when creosote reachs 10000 instead of 12000

### ISSUE THREAD

**Issue by calloatti** [BluSunrize/ImmersiveEngineering#1377]
IE Version: Compiled from source 1.10.2 2016/09/03

Full Minecraft Log: http://pastebin.com/BLuKDgWR

Pic: http://i.imgur.com/vgoyxkQ.png

**Comment by cabralRodrigo** [comment]
@calloatti This is maybe caused by the fact that the recipe that uses Block of Coal gives 500 ml buckets of creosote oil, so there is not enough space in the internal tank, making the coke oven stop.

Reference: [IEContent.java](https://github.com/BluSunrize/ImmersiveEngineering/blob/01707f989313d2eb606669ba1f06f4c1def586f6/src/main/java/blusunrize/immersiveengineering/common/IEContent.java#L612)

**Comment by BluSunrize** [comment]
Yup. That exactly. The oven refuses to waste creosote.
