### ISSUE TITLE
Crash on server launch [10.2]

### ISSUE THREAD

**Issue by MysticAura** [BluSunrize/ImmersiveEngineering#1384]
MC Version: 10.2
Forge Version: 2076
Mod Version: 0.10-38

Steps to Reproduce: Launch server.. kaboom :P 
[Crash Log](http://pastebin.com/14gbEP9V)

**Comment by Bitterholz** [comment]
Heyo Mystic!

You seem to be experiencing an issue with Cross-Mod-Compat

Hinted at by these lines:
net/minecraft/client/resources/I18n
at com.polipo.foundry.ItemStackKey.toString(ItemStackKey.java:139)

Im pretty much guesing right here, but it seems that Foundry mod tries to access an invalid Asset. Because i can defenitly confirm IE running fine.

Try running without Foundry installed and if it is causing the problem also report it on their Side ;)

**Comment by BluSunrize** [comment]
It's not Foundry's fault. Don't send people to other mods' trackers unless we actually know that. This is my error. Just because another mod is mentioend in the log doesn't mean it's their fault >_>

I know what caused this, I can fix it. Don't worry about it.

**Comment by BluSunrize** [comment]
There we go. Fixed for future releases.
