### ISSUE TITLE
[1.10.2] [Bugs] Drill

### ISSUE THREAD

**Issue by Dijkstra1** [BluSunrize/ImmersiveEngineering#1385]
So made a drill and:

- It works even without biodiesel (Just one block)
- Books says fill in the refinery, No it does have to stick an EnderIO tank on the output and fill it that (This may be a bug if the refinery as i could not fill the jerrycan as well in the refinery)  
- When the drill focused on stone and there is ore in 3 x 3 the ore will be left

**Comment by MalkContent** [comment]
The latter is intentional (i think). As far as i understand it, it will dig everything with equal or lower hardness than the block you are aiming at. Pretty neat if you want to harvest stuff like diamond/redstone with a fortune or silktouch enchantment.

The first seems intentional, too. Block break is slower than when fueled by diesel power. I suppose bashing that big ass drill against the rock by hand should be somewhat effective :)

**Comment by BluSunrize** [comment]
Doubly correct. And the second bug was another issue that has been fixed already! :D

**Comment by Dijkstra1** [comment]
I still think something needs to be done about the last one I want to do mass mining not have to stop to mine blocks that are blocking my way because they are harder than stone, maybe upgrade that lets tear through block with higher hardness (drill takes as long as if it was hitting the hardest block in the 3x3
