### ISSUE TITLE
[1.10.2][Forge 2075][0.10 - 40] Stack Overflow At Client Start

### ISSUE THREAD

**Issue by Hastling** [BluSunrize/ImmersiveEngineering#1390]
http://pastebin.com/2k0GwAJg

If any more information is needed to help please let me know.

**Comment by mindforger** [comment]
duplicate https://github.com/BluSunrize/ImmersiveEngineering/issues/1368
remove optifine .. also optifine is outdated

**Comment by Hastling** [comment]
Well that's sad to hear, consensus among my server members is that Optifine is more useful than IE right now so I guess we'll be giving it a pass for now. Thanks for the info.

**Comment by mindforger** [comment]
optifine has an issue tracker also, and hence it seems to be something they are doing on their side causing this, try complaining there

**Comment by Hastling** [comment]
> try complaining there

Didn't realize me trying to receive help for an issue was complaining.

**Comment by mindforger** [comment]
isn't "complaining" the right word for having an issue and asking someone to fix it?
.. maybe thats why people tell me I would have a rude language .. i just don't know the right words sometimes, sorry

**Comment by VT-14** [comment]
Most mods don't support Optifine.  Optifine is only really safe for Vanilla Minecraft.  If you have any other crashes (especially if its a render crash), then step 1 is to remove Optifine to see if it's having any effect.


@mindforger "complaining" is often taken as a synonym for "whining" or "crying." I would have gone with "try reporting there."

**Comment by BluSunrize** [comment]
Yes. This is an optifine issue.
Yes it has been reported before. We would have preferred if you check that, because it saves us unnecessary issues.
No, we don't mind people reporting bugs. I'd rather hear it twice than not at all.

But please do report this to optifine instead, because I am quite convinced that their coremodding caused this.

**Comment by Hastling** [comment]
Normally I do, and did this time, look through the first page of open and closed issues to see if it's been reported before so as to avoid a duplicate, but unlike myself the author of #1368 chose to not post in the title that it was a stack overflow which was the keyword I was hunting for. And just like that issue when I received the answer that it was Optifine I accepted that and closed the issue. I will report this issue to the Optifine Devs, but all these same responses to my already closed issue is getting a little "Duplicate"-y.

**Comment by BluSunrize** [comment]
Regarding the "same responses" comment: I'm the mod dev. The others do not speak for me. While I very much appreciate their input and contribution and I mostly agree with them in their diagnosing of issues, I do have the final word in these matters, since I also have to close a lot of these issues =P

**Comment by Hastling** [comment]
I really hope that sp614x is able to fix the issue as I really enjoy the effort put into not just the high clarity blender models, but also the functionality that IE affords myself and others. But I also enjoy getting above 30 FPS.
