### ISSUE TITLE
You cannot attach this wire here

### ISSUE THREAD

**Issue by JamesArhy** [BluSunrize/ImmersiveEngineering#145]
Following an upgrade from 0.1.9 to 0.3.2 and also from 0.3.2 to 0.3.3 I am having to destroy and rebuild all of my MV connectors and Electrum wiring due to this issue.  If a connector has been connected to electrum wire for any amount of time (other than right after placing it), I cannot add more wiring connections.  An example would be where I shift+right-clicked a hardened energy cell that had two MV connectors on it.  Once I replaced the cell and put the MV connectors back on the energy cell, it would tell me "You cannot attach this wire hire" when I would try to right click my electrum wire on the mv connector that WASN'T affected by the energy cell removal but it would link to the newly placed mv connector.

At one point I rewired my entire base and then a good 30 minutes later I needed to make one change which required me to redo about 30 MV connectors due to this glitch.

**Comment by BluSunrize** [comment]
It should be fixed in 0.3.3 though. Or is the issue still there after saving and reloading?
because I'm fairly sure I took care of this.

**Comment by Pihrra** [comment]
When I upgraded from 0.3.2 to 0.3.3 all my wiring disappeared too.
I was able to simply put new MV wires in without having to break and replace anything. However this wasn't the case for the few HV wires I had that also broke and I had to break and replace all my HV relays and connectors because I also got the "You cannot attach this wire hire" message.
Once I did this everything was back to normal so I'm not sure it's the same issue. (I didn't have any LV wiring in this world.)

**Comment by BluSunrize** [comment]
Okay, so...fixed then? :D

**Comment by Synticonic** [comment]
I have got this problem. I had to cheat to emit  some resources because they had not created in the world. And this problem with wires is still existed in 1.12.2

**Comment by BluSunrize** [comment]
This issue is 3 years old and unlikely to be related to yours. Open a new one with a detailed description of your problem please.
