### ISSUE TITLE
[0.10-40] Redstone breaker

### ISSUE THREAD

**Issue by GeneWeaver** [BluSunrize/ImmersiveEngineering#1457]
inverting the redstone breaker does not do anything, still acts as if not inverted.

**Comment by Joshwoo70** [comment]
it works. Did you power it with redstone? we need a pic of your setup.

**Comment by Doragoon01** [comment]
I have this same problem on my server.
Power flows through it.  Power stops when the breaker receives a redstone signal.  But when you hit it with a hammer and it says the behavior is inverted, but the power will still flow through it unless it receives a redstone signal.
I'm not sure how a picture would help since it's just the breaker on a block with a lever on it.
