### ISSUE TITLE
java.lang.IllegalArgumentException: Empty string not allowed

### ISSUE THREAD

**Issue by Rongmario** [BluSunrize/ImmersiveEngineering#1487]
http://hastebin.com/silukeyovi.sql

**Comment by BluSunrize** [comment]
I could have sworn I replied to this. Weird.

Anyway, I do believe this is caused by crossmod interaction, since IE's own Creosote Oil should not be null at that point. I would like to ask you to figure out which mod is interferring here. The easiest way would be to remove half the mods, see if it works; if it doesn't, the erroring mod is in the half you have left, otherwise in the other half. So split that again in half, and so on and so forth. That should narrow it down a lot quicker than trying to disable one mod after the other.
