### ISSUE TITLE
[1.10.2] Checking if pipe cover is climbable

### ISSUE THREAD

**Issue by XFactHD** [BluSunrize/ImmersiveEngineering#1499]
I just took another look at the commit that readded the pipe covers and your answer on twitter concerning their climbability and got an idea: Wouldn't it be possible to make the function return a `Pair<Boolean, Boolean>` (one Boolean for the usability as cover and one for the climbability) instead of only one Boolean or would that possibly create an overhead?

**Comment by BluSunrize** [comment]
It'd be a bit of a mess, really. If anything I could probably have the function return two fuctions.
So the initial one is called to get the two others, that are then stored in lists. I'll look into it.

**Comment by XFactHD** [comment]
Thanks for considering it. :)

**Comment by BluSunrize** [comment]
It's a thing now!
https://github.com/BluSunrize/ImmersiveEngineering/commit/df9ad4eb7f53940fc0440994ae97d48512a599a2

IMCs with "fluidpipeCover" add a Function<ItemStack,Boolean> to determine if a block is a valid cover,
IMCs with "fluidpipeCoverClimb" add a Function<ItemStack,Boolean> to determine if a on a pipe is climbable. Not the nicest option, but since it's a function based system, each mod should only ever have to send 2 messages.

**Comment by XFactHD** [comment]
Awesome, but it seems that you overlooked something: The lines that validate the climbability against the list is commented out.
