### ISSUE TITLE
[Suggestion] Make "Stored Energy" overlay easier to read

### ISSUE THREAD

**Issue by ToadsworthLP** [BluSunrize/ImmersiveEngineering#1506]
It's sometimes hard to read the "Stored Energy" values when looking at a cable, capacitor,... with a voltmeter in hand. I know, you can also check them by right-clicking, which will print the values into the chat, but it would be better, in my opinion, if the overlay was easier to read. So here comes my suggestion: Remove the batteries that are displayed around each letter and put one big battery (or, by config, nothing) in the background for better contrast, and also reduce the space between the letters. This should be a config, because the design with the small batteries is nice too. It's just hard to read.

Also, two small questions which have nothing to do with the suggestion itself:
1. When will reactors get implemented? The uranium is even implemented, when will it get a use?
2. May we get a coal generator for early game, active power generation?

**Comment by BluSunrize** [comment]
Those are not batteries, they are nixie tubes =P
The config option to disable them is called "NixietubeFont"

As for the questions:
1) Whenever Damien actually works on IE again. He's currently working on his own portfolio and has a lot going on in his personal life. All of that takes definite priority. This is a wonderful hobby, but life must come first.
2) Nope, sorry. I (or we, even) specifically decided against coal gen because it's boring and everyone does it! :D Part of IE's charm comes from straying off the beaten path after all =P
