### ISSUE TITLE
[0.10 - 42] Full barrels can stack.

### ISSUE THREAD

**Issue by laserlemons** [BluSunrize/ImmersiveEngineering#1542]
I don't know whether or not this is intentional but it means that 20,736 buckets can be stored in a single chest or 497,664 buckets in one silo, which doesn't seem right to me.

**Comment by BluSunrize** [comment]
Yeah that's vanilla. Vanilla's stacking mechanic dictates that any matching items can stack as long as their NBT tag is the same as well.
I'll take a look at it.

**Comment by mindforger** [comment]
@BluSunrize can Barrels be filled like buckets? Because this behaviour lead to havy duping in the past! Barrels should never stack or should be checked if they behave like buckets then!

the dupe was to insert 1 stack of (i forgot what container item it was) into an RailCraft tank and it took the amount for ONE filling and filled the whole stack with it (partially an issue of RC at that time to not unstack the items but happens way too often to go untested imho)

**Comment by BluSunrize** [comment]
Barrels only get filled as blocks, never as items.

**Comment by mindforger** [comment]
@laserlemons look at tinkers construct, their seared tank/glass can also be stacked when having the exact same amount of fluid in them, you could also complain to them as it feels wrong for me like for you
