### ISSUE TITLE
[Suggestion] Do what you really want

### ISSUE THREAD

**Issue by ToadsworthLP** [BluSunrize/ImmersiveEngineering#1553]
Fans like steam, you (at least according to [this](https://twitter.com/BluSunrize/status/784770190148067329) tweet) like steam, so why not implement steam? 
A lot of people (here some examples: [1](https://minecraft.curseforge.com/projects/immersive-engineering?page=2#c1136), [2](https://github.com/BluSunrize/ImmersiveEngineering/issues/1255), [3](https://github.com/BluSunrize/ImmersiveEngineering/issues/159)) want steam, and it would be nice to have it as early- to midgame active power generation. Earlier, you were really opposed to the idea of [coal](http://riteboiler.com/images/outdoor-high-pressure-steam-atmospheric-boiler.jpg), lava, maybe even [sun](https://i.ytimg.com/vi/k9gFr5lRZEs/maxresdefault.jpg)-powered steam generation and steam turbines to power a kinetic generator, but maybe, you changed your mind? Come on please, Damien already made a [model and textures](https://twitter.com/Damien_hazard/status/726122986059796480), give the fans what they want :D

**Comment by BluSunrize** [comment]
I like how this issue is named "do what you really want" and finishes with "give the fans what they want"
Are you for-seriousing me?

Also, if you followed all the relevant tweets accordingly, you would ahve seen that I very specifically said that a full steam tier is not being retconned in. If I ever make an IE2? Sure. It can have a steam tier.
Force one in now with a fully existing electrical tier available, and force a full change on progression, recipes and gamebalance? Nooope.
And this hole topic on twitter wasn't about using stream for electrical power. I am very much aware of Damien's turbine (you honestly think I don't get to see that stuff first?)
This was about steam itself as the power system. Which, once again, is too late to put in now.

**Comment by ToadsworthLP** [comment]
Well, looks like I heavily misinterpreted that, and I only put all the links there as a reminder. Sorry. But yeah, just like the title says, "Do what you want". I don't say, IE is bad, I'm only showing possibilities for making it better. Was the last sentence a bad joke? Yeah, it was. But maybe some people make the connection AND think it's funny. Which is unlikely. I guess I'll wait for IE2 then...

**Comment by bookerthegeek** [comment]
Got to say that steam turbine is pretty epic looking.
