### ISSUE TITLE
(Minor) Core Sample Drill must be replaced for it to work again

### ISSUE THREAD

**Issue by jzburda** [BluSunrize/ImmersiveEngineering#1566]
I don't know if it's intended or not, but the Core Sample Drill cannot start working again until it's broken and replaced. If it is intended, then I don't understand why half of the computer support (getVeinIntegrity, for example) is available.

**Comment by mindforger** [comment]
because you can always right click it to get an actual info of the vein integrity as long as it stays placed after it found a vein, so the CC interface has the same abilities like you have

**Comment by jzburda** [comment]
So basically, it reads the core sample it's received, and doesn't allow you to read the core sample constantly changing?

**Comment by mindforger** [comment]
it should totally change! @BluSunrize ?

**Comment by BluSunrize** [comment]
Yeah, actually the computer driver for the sample drill is totally pointless atm.
Samples were redesigned to be actual items that can be picked up.
One way to handle that for computers would be to have a "Mineral Analyzer" block that can analyze samples and feed the info to a computer.
No, I am absolutely not adding a block for computer compat.
So since that's out of the question, anyone got a smart idea? Best thing would probably just be to remove the driver entirely and skip on computer compat for the sample drill...

**Comment by mindforger** [comment]
Wasn't aware of that, i am yet not at that point :D 

still relying on some 1.7.10 info here sorry

>anyone got a smart idea?

relay this post to openmods :D

**Comment by codewarrior0** [comment]
Kind of off-topic:

I like having a crate full of core samples since it's a public record of vein locations that I can share with other players. I just wish there were a way to use the sample to navigate back to the vein without having to use F3 (or e.g. the coord display under a minimap).

**Comment by mindforger** [comment]
ore compass XD shift right cklick in air to open GUI, stuff a sample in it and follow the needle
