### ISSUE TITLE
0.47 Pipes are causing extreme performance loss

### ISSUE THREAD

**Issue by StarvingPoet** [BluSunrize/ImmersiveEngineering#1621]
Only mod IE 0.47
superflat test world
6x30 section of pipes.

(Behavior does not persist in 0.44)

When a large number of pipes are loaded, they cause substantial drop in fps when placing or removing blocks with block lag that increases with the number of pipes in immediate area (150 fps -> 20).   

Might be related to this commit: https://github.com/BluSunrize/ImmersiveEngineering/commit/41fe8090fc9da4d617ee16653f9a1a1d006ad8e9

If using optifine / shaders, it can cause client to CTD with the following error - usually only occurs if trying to log into server in an area with pipes.
```
 -- Block being tesselated --
[B#347] 2016/10/20 21:33:07 [INFO]  Details:
[B#347] 2016/10/20 21:33:07 [INFO]  	Block type: ID #404 (tile.immersiveengineering.metalDevice1 // blusunrize.immersiveengineering.common.blocks.metal.BlockMetalDevice1)
[B#347] 2016/10/20 21:33:07 [INFO]  	Block data value: 6 / 0x6 / 0b0110
[B#347] 2016/10/20 21:33:07 [INFO]  	Block location: World: (-446,27,278), Chunk: (at 2,1,6 in -28,17; contains blocks -448,0,272 to -433,255,287), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
[B#347] 2016/10/20 21:33:07 [INFO]  Stacktrace:
[B#347] 2016/10/20 21:33:07 [INFO]  	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:81)
[B#347] 2016/10/20 21:33:07 [INFO]  	at mods.betterfoliage.client.Hooks.renderWorldBlock(Hooks.kt:97)
```

**Comment by malte0811** [comment]
I can confirm this issue and have an idea on how to fix it (by caching the cache key of the pipe models :smile:), but I have no idea why it wasn't happening before. I ran VisualVM on a laggy instance, the relevant code was not changed since the 15th September according to git.

**Comment by BluSunrize** [comment]
Wait wut? I do cache pipes, I'm pretty sure?

**Comment by malte0811** [comment]
You cache pipes, but calculating the cache *key* for a pipe requires 6 getTileEntity calls! According to VisualVM getCacheKey is taking up most of the time.

**Comment by malte0811** [comment]
Ok, I take back everything I said, I had VisualVM configured to only profile IE classes. It is my fault, but I messed up in 80d5d88e69c9785b0720a803f50090cfb707ec12, not 41fe8090fc9da4d617ee16653f9a1a1d006ad8e9. This commit caused the value of the IOBJModelCallback property to be compared, and since that is the TE the values didn't match even when the hash values matched. This caused a lot of new models to be generated, which obviously caused lag. This was amplified by the time-expensive cache key calculation for the pipes, but they are not the root cause of this.
