### ISSUE TITLE
[1.10] Support for Forge Energy Capabilities or Tesla

### ISSUE THREAD

**Issue by shartte** [BluSunrize/ImmersiveEngineering#1622]
Do you have plans to support one of the two capability based energy APIs in IE?

We're currently porting AE2 and would love to avoid the interface based CofH RF API. Instead, we're supporting Tesla and the Forge stuff as RF on our end.

If you're not opposed to supporting either, I might send a Pull Request your way to add support for Tesla or the Forge system (whichever you prefer).

Best Regards

**Comment by BluSunrize** [comment]
I refuse to accept Tesla, and I'm pretty adamant on that.
Forge Energy is worth the consideration, but I am not fully decided yet.

**Comment by shartte** [comment]
Fair enough. 
Have you considered providing a capability-based way of interfacing with your API?
That would be another approach we could take to accept power from IE.

**Comment by malte0811** [comment]
@BluSunrize have you decided whether you want Forge Energy yet? I would probably have the time to implement it. I personally think that since we are already supporting one "kitchen-sink" power type (RF), we might as well support the official "kitchen-sink" power type as well. I agree on not supporting Tesla (for basically the same reasons you gave except for disliking capabilities).

**Comment by BluSunrize** [comment]
I have plans to deal with Forge Energy, yes. But I plan to write that myself and it won't be in build 49.
