### ISSUE TITLE
[Question] 3D Models in a Manual Book

### ISSUE THREAD

**Issue by chaos234** [BluSunrize/ImmersiveEngineering#1623]
Hey @BluSunrize,

I want to aks you if you can provide me with the code to implement the 3D Block-Models, like in your Engineer's Manuel you are doing it.

I want to use it in my mod which is for 1.7.10 and for 1.10.2 so I ask you if I can get/use the code for that in my mod

I hope that you can help me with this.

**Comment by BluSunrize** [comment]
You'll have to ask @boni, the current code for rendering multiblocks is from him =P

**Comment by BluSunrize** [comment]
You'll have to ask @bonii-xx, the current multiblock render code was written by him ^^

**Comment by bonii-xx** [comment]
It's the same as your code but reusing the world renderer, blu :P
Anyway the trick is to (transform the render view where you want it, and then render the structure block for block)[https://github.com/SlimeKnights/Mantle/blob/master/src/main/java/slimeknights/mantle/client/gui/book/element/ElementStructure.java#L188-L247].

The rendering itself is the same as rendering blocks in the world, using a ("simulated world")[https://github.com/SlimeKnights/Mantle/blob/master/src/main/java/slimeknights/mantle/client/book/StructureBlockAccess.java]. The principle is pretty simple, the implementation is messy because book stuff/gui stuff is.
