### ISSUE TITLE
Crash with pipes and thermoelectric generator

### ISSUE THREAD

**Issue by Plurp13** [BluSunrize/ImmersiveEngineering#1644]
I was trying to figure out how to get the pump to work and ended up trying to place a fluid pipe on the side of a thermoelectric generator. Unfortunately the game froze up and then crashed, now I can't get back into the world. It just immediately crashes as soon as it loads up. Anyway here's the crash report.

http://pastebin.com/Qvx70ubZ

**Comment by Plurp13** [comment]
Erm, I hate to be a bother, but it's been a week, I just wanna make sure it's been seen...

**Comment by BluSunrize** [comment]
Actually completely missed this. My bad!
This issue seems to stem from the fact that some TileEntity returns true for having a FluidHandler and then returns null for some reason.
As a temporary fix, I'd recommend going into Forge's config and turning on the option to remove erroring tiles.
Load the world, that should remove the fluid pipe. Check if the error is reproducable.
Then do me a favour and see what other blocks are currently connected to a pipe in that vicinity. Screenshots would be great.

**Comment by Plurp13** [comment]
Ok so I tried turning on that config option and it still crashed...
http://pastebin.com/2srtQZ8d bang
But I can get you a screen shot of a recreation without the fluid pipe. I think I remember what I was doing when it happened. Would that help?

**Comment by Plurp13** [comment]
Ok so I couldn't recreate the crash, the only thing I didn't try was doing it actually in the nether, if you think that has something to do with it I'll try that. Anyway here's a picture of what it should have looked like if it hadn't crashed, just pretend it's a nether lava ocean. (It's a different world cuz I still can't get into the first one or I might have better luck)

![2016-11-06_12 18 03](https://cloud.githubusercontent.com/assets/8428847/20039917/31d408ea-a41b-11e6-9f2a-ff4003716e7e.png)

**Comment by Plurp13** [comment]
No?

**Comment by BluSunrize** [comment]
I can't reply because I actually don't know what's happening. My generators do not return true for that capability. And I refuse to put null checks there since conventions says I shouldn't have to and this is more efficient....

**Comment by Plurp13** [comment]
Ah. Well that stinks. I just wanted to be sure it had been seen in case it was fixable.
