### ISSUE TITLE
Crash loading a new or existing SSP world

### ISSUE THREAD

**Issue by iamomicron** [BluSunrize/ImmersiveEngineering#1652]
Loading an existing world, or even creating a new one in SSP creates the following crash. I have tried 4 times and each time the issue has been reproduced. The issues appears to stem from `onWorldLoad`

http://pastebin.com/zMUd21T1

IE Version: `0.10-48`
Forge Version: `12.18.2.2116`

However, strangely, the client never actually closes once the crash occurs. The screen just sits at this permanently. 

![image](https://cloud.githubusercontent.com/assets/4225347/19864115/bdbdee8e-9f8e-11e6-907b-b4028be8d385.png)

**Comment by BluSunrize** [comment]
You have a mod that is registering null for an EntityRender.
That's bad thing.

I would ask you to figure out which mod it is. The easiest way to do is is removing half the mods and see if the issue is still there. If it is, it's in the half you have left, otherwise it's in the other half. Obviously you don't remove IE.
So then you take the half with the broken mod and halve that again. You repeat that until you know which mod causes the issue, and then we can tell the relevant dev to fix their stuff ^^

**Comment by iamomicron** [comment]
Alright, cheers. I'll look into it soon and report back when I find what's causing it. Any way to check through the forge log for this?

**Comment by BluSunrize** [comment]
Not to my knowledge, no. I wish there was :/

**Comment by Akai1** [comment]
The problem is the new CCL version. Maybe related to the [latest changes](https://github.com/TheCBProject/CodeChickenLib/commits/master).

**Comment by iamomicron** [comment]
Can confirm the above. Will make an issue over on the CCL repo.
