### ISSUE TITLE
TextureDump

### ISSUE THREAD

**Issue by Xiaminou** [BluSunrize/ImmersiveEngineering#1662]
https://www.reddit.com/r/feedthebeast/comments/5b6bwg/exploring_the_texture_map/

You are ranked N°2, Congratulations.
(I don't know if it causes any issues or anything, but at least it might start a discussion, if I'm wrong and this turns out to be useless feel free to close the issue)
![textures_mipmap_0](https://cloud.githubusercontent.com/assets/8670392/20026294/df6f7c4c-a2f8-11e6-9d40-02ae14061ef3.png)

**Comment by BluSunrize** [comment]
No need to be a douche about it >_>
I mean seriously. Basically all you did was come in there and say "Your mod is terrible."
Which is roughly what I expected that TextureDump mod to result in.

Now to clear a few things up:
1) I'm not, by any means #2 for the worst texturemapping. There are /multiple/ mods worse than me, Mekanism and Endertanks only being some of them.
2) Most of my maps are just about the size they need to be. Revolvers /need/ to have a map like that. And multiblock UVs are packed as tightly as I possibly could.
3) There is one specific case in this mod which does feature a waste of space, and if you had read the contribution guidelines and used the search function, you would have found this:
https://github.com/BluSunrize/ImmersiveEngineering/issues/1634
An issue @mezz himself opened, and that we discussed on IRC, and where I already stated that I was working on fixing the "sponsor" textures. In fact, I /have/ fixed them, the new code is done, just not published yet. I've been working on it over the past three days.
4) Don't start a witchhunt if you don't know what you are dealing with. And if you do, at least phrase it nicer. You actually said in your post "I don't know if it causes any issues or anything", so maybe ask on IRC first? Alternatively, at least say something like "Would it be possible to reduce some of the texture sizes, or is there no way to optimize it further?"
Something like that. Just...nicer. Makes us mod devs way more likely to want to discuss it. We're humans too, after all.

RIGHT.
Rant over.
Issue stays open for now, since I am actually working on optimization and this topic is open for discussion.

**Comment by Xiaminou** [comment]
"I mean seriously. Basically all you did was come in there and say "Your mod is terrible.""

But... it's not... and it's one of my favorite mods, I didn't mean it like that.

**Comment by BluSunrize** [comment]
Shader Commit has happened, see
https://github.com/BluSunrize/ImmersiveEngineering/commit/da596e593c3ea28ae35c50ff2dad6baf1fd10471
https://github.com/BluSunrize/ImmersiveEngineering/commit/e449629ffd52329b55ee681a1c07f29c68aabb56
https://github.com/BluSunrize/ImmersiveEngineering/commit/267cf97eb74843702490162401dd4f84c0787353
https://github.com/BluSunrize/ImmersiveEngineering/commit/a5d513fefee97aeaa102461e1bdfbcf46eae77ae
https://github.com/BluSunrize/ImmersiveEngineering/commit/6249cb9077ff4a8cd3904b594cf36762091dc8c4

Issue resolved.
