### ISSUE TITLE
Visual Multiblock glitch

### ISSUE THREAD

**Issue by Crossfire50** [BluSunrize/ImmersiveEngineering#1671]
![2016-11-09_11 27 54](https://cloud.githubusercontent.com/assets/23365637/20151822/85ce0458-a670-11e6-9da8-23acb0185c82.png)

I don't know the reason but every time i log into my server my fermenter, squeezer, and improved blast furnace are glitched and i have to break the multi block and replace it to fix the issue.

let me know if i can provide any further information to solve this problem

**Comment by prenetic** [comment]
Same issue on my server, this just cropped up after we updated to FTB Infinity Lite pack version 1.1.0 from 1.0.1. I am seeing this occur with regularity against the generator multiblock structure. 

ImmersiveEngineering-0.10-48
FTBserver-1.10.2-12.18.2.2124-universal

**Comment by mindforger** [comment]
>let me know if i can provide any further information to solve this problem

you yould probably read the contibution guidelines, they thell you which informations are required :)

**Comment by Crossfire50** [comment]
yes i have optifine installed and i tried with and without.
forge version 1.10.2-12.18.2.2114
mod list is as following : 
applied energistics
backpack
baubles
biomes o plenty
blood magic
botania
cooking for blockheads
enchanting plus
ender io
ender storage
expandable backpacks
forestry
gravestone mod
hopperducts
immersive engineering
industrial craft 2 experimental 
JEI
journeymap
lumberjack
malisis doors
Minecraft comes alive
NEI
pams harvestcraft
railcraft
redstone paste
rf tools
rf tools dimensions
Tinkers construct
waila

**Comment by mindforger** [comment]
a shot from the hip from my side would be malisis doors, as it prodeuced issues with blockstates for several mods **in the past** ... but use a copy of the world as you will loose all doors when removing malisis :)

other than that i have no idea :(

**Comment by BluSunrize** [comment]
First of all, break and replace those blocks. Should that not work, remove Malisis Doors as mindforger suggested.

Please report back with any info.

**Comment by Crossfire50** [comment]
So i broke and replaced the blocks and removed malisis doors and both didn't help. The weird thing is that i have the metal press in the same room and its not glitching. I used F3 and found out its in a different chunk then all the other machines are so i took the pre-heater for the blast furnace and brought it to another chunk. logged out and in and it wasn't glitched. After moving the pre-heater in and out of the chunk many times in different spots. I have come to the conclusion that something is wrong with that chunk. I don't know how to fix it but looks like ill have to move the entire contents of that room somewhere else in my house. Thanks for the help guys i don't know what initially caused the issue in the first place but at least i have a fix now.

**Comment by Echmaidzin** [comment]
I can concur with @Crossfire50. I have been having the same issue _and_ also noticed that it didn't affect everything. I made the assumption that, since it didn't affect the windmills, the fluid tank a couple chunks away, or some posts on the other side of the "compound" as it were while still affecting the nearby post, that it might have had something to do with either multiple structures bunched together, and/or having them run while the server's empty.

However in light of their revelation, I made the same observation; all affected structures are in the same chunk. It even affected the transformer, though that might be in part due to it stacking the post it was connected to and making it weird-out.

For the record, this visual glitch was found to be happening on the stock Direwolf20 1.10 modpack without any other mods added, removed, or disabled, so it doesn't have Malisis Doors; everything in the pack listing is what's active.

Hopefully his screen as well as the minimap within it demonstrates the same conclusion that @Crossfire50 came to, that this is also all happening only to structures within this chunk, or at least so far this is the only chunk I've found them to bug out in.

![2016-11-16_16 07 09](https://cloud.githubusercontent.com/assets/23512282/20371548/6ab54df2-ac1a-11e6-818c-ccfb6d87c8a5.png)

**Comment by BluSunrize** [comment]
Well, it seems to basically happen to all the blocks that use the multblockslave flag, which means they use dummybocks to add boundingboxes, but these dummies don't actually render anything.
That means every multiblock, all posts, transformers, preheaters, waterwheels.
Windmills are unaffected since they only have a single block.

Seing that it's only in one chunk there's bound to be /something/ in that chunk that causes it, but figuring out what is pretty tricky.

**Comment by YOYOK9** [comment]
Any news on this issue? I have noticed the same on my server:
https://puu.sh/vjzNl/b6b0503bc2.jpg
https://puu.sh/vjzNG/8609801db9.jpg (shows ghost blocks)

Extra: 2 things
1) the pics i have attached are between 2 chunks.
2) not sure if it is meant to do this but I noticed sometimes when I build the oven I see "ghost" blocks appear all around the oven then disappear, however sometimes some don't completely vanish. Could this be the issue? tested in new chunk as well. got the same "ghosting".

ImmersiveEngineering-0.10-57
forge-1.10.2-12.18.3.2281-universal

**Comment by PrincessRTFM** [comment]
Then please open a new issue instead of necroposting on one three years old. And since I'm already replying to say that, I'll add:

- Remove Optifine
- Remove Foamfix
- Test again
- If it persists, open that new issue with a crashlog, forcing it if needed (in-world, hold `F3` and `C` for ten seconds)
