### ISSUE TITLE
Pump not increasing speed when powered on still water

### ISSUE THREAD

**Issue by VallenFrostweaver** [BluSunrize/ImmersiveEngineering#1684]
Water is used for all examples below.

Comparing the powered pump piped from an IE tank and one that is not powered and you can see there is a difference. When powering a pump and piping from still water it is pumping 1 bucket at a time but much slower than the powered tank pumping out.  In conclusion, there is no speed increase when pumping fluids with a powered pump unless from another water storage device. This may be as intended but it is not apparent from the manual in my experience. If as intended and no changes are expected please just close the issue.

**Comment by BluSunrize** [comment]
Sorry I found it a bit tricky to read that report, so let me try to sort my brain here:

You have 3 pumps. One is pumping water from water blocks in the world. One is unpowered and receiving water from a tank, and the last one is powered and receiving water from a tank?

The unpowered one is the slowest. That makes sense, because it doesn't actually do anything. Pipes have a flowlimit of 50 mB/tick when there is no powered pump.
The powered one is faster. It should be doing 144 mb/tick since that is what a tank will output.
The pump grabbing water from the world is doing one bucket at a time, but on a per second basis.

Is that the scenario? What exactly is wrong about it? Picking up fluids in the world is a different process from taking fluid from a tank, so they do have different speeds, yes.
Am I missing something?

**Comment by VallenFrostweaver** [comment]
No worries. I wrote it terribly though not with the intention of being poorly written.

You are correct and I regret actually posting this issue. I was misunderstanding the manual when it refers to the speed being up to 5 times faster. I was not thinking that may refer to the example of an unpowered pump taking from a tank vs. a powered one. I had thought the powered pump on water blocks was going to be the slowest but I don't even know why I thought that at this point. Sorry to have wasted your time on this. >.<
