### ISSUE TITLE
[Suggestion] Taller posts

### ISSUE THREAD

**Issue by xenoflot** [BluSunrize/ImmersiveEngineering#1690]
Hi,

I'm currently running an HV line across my paddock and I'm finding the posts are just way too short when 32 blocks apart. The catenary of the wire makes it drop down to about waist height in the middle. The people from Occupational Health & Safety paid me a visit and it wasn't pleasant. They said something about lethal electric fences and made me re-post on ugly stone pillars.

If I might make a suggestion, there's currently no difference(?) between the three types of posts except for the colouration. Perhaps they could differ by their height and girth, with the aluminium and then steel posts looking more suitable for higher tension wires?

Cheers!

**Comment by XFactHD** [comment]
In 1.7.10 I always built those kinds of posts myself with those ramp like blocks (forgot how they ware called) but I don't know if they have already been reimplemented. One feature I always wanted to have is that they also connect vertically and not only in a horizontal line.

**Comment by laz2727** [comment]
Would love some transmission towers as well.

**Comment by Tajmoti** [comment]
I really support this. Either make post extensions like in the mod Immersive integration but i think it would be preferable to make the normal posts at least 2 blocks higher as xenoflot said because it feels really weird when the wires hang so low you can almost touch them with your head. Real poles are like 3-4 times higher than a person. Please make it happen :) Thank you
