### ISSUE TITLE
bad registered Constantan blocks and items

### ISSUE THREAD

**Issue by Hypsellis** [BluSunrize/ImmersiveEngineering#1691]
I'm sorry to come back with that, but there is still some issues of compatibility between Cupronickel and Constantan.
It's impossible to switch between Constantan and Cupronichel block for the recipes, same for nuggets, slabs, and plates. It's not possible to switch between them in the ore dictionnary converter too. I suppose they are bad registered in ore dictionnary.
There are some strange behaviour with Tinker's Construct and Foundry interaction. When you cast molten Cupronickel, you can get Constantan block, and reverse.

**Comment by BluSunrize** [comment]
Could you detail this?
Are you trying to use another mods Cupronickel for IE recipes? Or are you trying to use IE's Constantan in another mods recipes?

**Comment by Hypsellis** [comment]
Both of them. ;)

**Comment by BluSunrize** [comment]
Could at least provide an example?
Tell me what you are trying to craft? What items from what mods?
 Screenshots would help.

**Comment by Hypsellis** [comment]
The most notable issue is that it's impossible to switch between Cupronickel and Constantan block, slab, nugget and plates with the ore dictionnary converter while it's possible with ingot and dust. https://minecraft.curseforge.com/projects/oredictionaryconverter?gameCategorySlug=mc-mods&projectID=227564
You surely register only the Constant ingot and dust in the ore dictionnary. It unduces to some strange behaviour and incompabilities between Cupronickel and Constantan, notably with Foundry and Tinker's Construct Interaction.
Use Tinker's Construct cast will always give Constantan, even if you cast molten cupronickel, and reverse if you use Foundry cast, you get cupronickel when you cast molten cupronickel.

![capture](https://cloud.githubusercontent.com/assets/17103411/20462965/87664700-af29-11e6-981f-bc55e9038d10.PNG)
![capture2](https://cloud.githubusercontent.com/assets/17103411/20462966/876f4184-af29-11e6-8997-9c8246b9f64a.PNG)
![capture3](https://cloud.githubusercontent.com/assets/17103411/20462967/87784b4e-af29-11e6-8f1b-f1fc77b0d2a7.PNG)
![capture4](https://cloud.githubusercontent.com/assets/17103411/20462968/878500e6-af29-11e6-9c84-95f7ea9c5b94.PNG)
![capture5](https://cloud.githubusercontent.com/assets/17103411/20462969/878a0d84-af29-11e6-8e27-e385a39fa362.PNG)
![capture6](https://cloud.githubusercontent.com/assets/17103411/20462970/8797cf82-af29-11e6-86b2-0fbce634e211.PNG)
![capture7](https://cloud.githubusercontent.com/assets/17103411/20462971/879bbcd2-af29-11e6-9384-f9e9cee2d8c9.PNG)

**Comment by BluSunrize** [comment]
Right then.
I register all my stuff as Constantan. My dusts, ingots, nuggets, blocks, plates, slabs and sheetmetal are /all/ registered as "[prefix]Constantan".
I register alloying for TConstruct which then automatically results in casting being registered as well.
Now Foundry makes the metals equal. Which is fair enough, since Constantan is technically just a very specific mix of copper and nickel.
Foundry adds its own smelting and its own fluid cupronickel and foundry registers it with TConstruct.
But, and this is where I am guessing, because I register with TCon first, my Constantan pieces are the determined output for TCon when casting. Foundry, in its casting recipes, obviously puts priority on their own metals.

The result of that is what you see above.
The thing is though, that Substratum/Foundry's Cupronickel is registered as Constantan as well and can be used interchangeably in IE recipes.
What it won't work for is another mod looking specifically for Cupronickel, like the mod Base Metals.

So once again I ask you to give me a DIRECT EXAMPLE of what you are trying to craft, because you still haven't done so!
What are you trying to make, what item, from which mod, and which ingredients are not working as intended?

**Comment by Hypsellis** [comment]
I never talked about crafting recipe if you had readded well my posts, I talk you about the fact that 
> it's impossible to switch between Cupronickel and Constantan block, slab, nugget and plates with the ore dictionnary converter while it's possible with ingot and dust. 
If you don't what I talk about, I talk about this mod. https://minecraft.curseforge.com/projects/oredictionaryconverter?gameCategorySlug=mc-mods&projectID=227564

**Comment by WanionCane** [comment]
@Hypsellis since your problem is with Ore Dictionary Converter,maybe registering all constantan things from Immersive Engineering as Cupronickel would help?

**Comment by Hypsellis** [comment]
It's not to me you should tell it but to BluSunrize Wanion, I can't register his block for him. ^^'

**Comment by BluSunrize** [comment]
1) Yes you can, that'S what Mientweaker/Craftweaker is for.
2) I don't see the point in registering my stuff because, you /still/ haven't given me a concrete example of a recipe you need it for. OreDictionary Converter is pretty pointless if you still can't tell me what you actually need the items for ;)

**Comment by AEnterprise** [comment]
his problem seems to be switching between the slabs, nuggets and plates. nuggets are not realy a problem as you can just recraft those in an ingot and swap that

for the plates: how are all the different plates made? if one is just made in a regular crafting grid and the other in a specific machine they should probably remain not exchangable

**Comment by Hypsellis** [comment]
I told you, but you ignore it. It's impossible to switch between Constantan and Cupronichel block, nuggets, slabs, and plates in ore dictionnary converter, while it's possible for ingot and dust. It means that you register as Cupronickel only ingot and dust, which is an error. 
And MineTweaker can only add recipes, it doesn't register any blocks or items in ore dictionnary. It's kinda annoying to see how modders get rid off problem by invocating MineTweaker, it's not supposed to be a mode used for correcting mod issues.

**Comment by AEnterprise** [comment]
ok i'm not an IE dev but i am a modder so gona respond to this as such cause i have a problem with that statement @Hypsellis 

first off: your report isn't being ignored, you're not responding to the questions, the question is what you can't make, not what you can't switch between

the oredictionary isn't suposed to be EE3 where you can just swap one thing for another, it's for allow compat between mods that add exactly the same item/block

there are tons of things in mods in general NOT in the oredict under the same name because they are NOT the same, some mods make iron plates in a crafting grid, others need alot of complex machines, so those plates are not suposed to be equivalent so are not in the oredict under the same tag, not everything HAS to be in the oredict

the primary use of the oredict is to allow crafting, not swap between cosmetic blocks (like slabs and blocks)

and unless things changed in recent versions minetweaker and such CAN add/remove things in the oredict, it indeed isn't for correct mod issues but this isn't a mod issue

the only thing that MIGHT be an 'error' is the nuggets not being in the oredict and maybe causing an nugget item not being craftable, but that's all

@BluSunrize sorry for the rant on your issuetracker

**Comment by Hypsellis** [comment]
I understand your point of view. But I still stay on my position. MineTweaker is often uses as an excuse for not correcting bugs in mod. And modders tends to belittle reporters by insinuating that in fact it's them who do the things wrong and understand absolutely nothing. Like if we reported issue only for the fun to annoy modders. I don't what you guys imagine you, but I'm definitely not in this logic. I don't target BluSunrize particularly but modders behaviour in general.
I know that sometimes some items and blocks are not registered in ore dict because they are not supposed to be the same, but it's not the case here. Constantan is registered as Cupronickel too, this is why it's possible to use both Cupronickel and Constantan in recipes that use them. But it works only with Constantan ingot and dust. So like I told before, it means that only ingot and dust are registered as Cupronickel. And the ore dictionnary converter is a really good way to realize it, it's possible to switch between constantan and cupronickel dust and ingot, but not with block, slab, plate and nugget. 
![capture](https://cloud.githubusercontent.com/assets/17103411/20579305/4924ba26-b1cc-11e6-9802-cd3c1fb3f578.PNG)
![capture2](https://cloud.githubusercontent.com/assets/17103411/20579306/492b4d28-b1cc-11e6-9c2e-93c763c3776f.PNG)
And god it's not to me to do everything, if you guys don't trust me or understand me, just try it by yourself. I think I have been enough clear about the problem.

**Comment by BluSunrize** [comment]
Okay once again:
I do not register any part of my Constantan stuff as Cupronickel. Neither the ingot or dust in IE are registered as Cupronickel from side.

And I repeat: The OreDictionary converter, is NOT a recipe. I want you to give me an actual example of what item or block you want to craft. Simple conversion is no reason for me to add it.

**Comment by Hypsellis** [comment]
So why is it possible to switch between Cupronickel and Constantan ingot and dust in all recipes if you don't register them as Cupronickel ?

**Comment by mindforger** [comment]
install crafttweaker/minetweaker, now repeat the following steps with all the items you think that have to be the same and post the results please (not images, only the text please :P)

(0. be able to use commands)
1. take the item in the hand
2. type "/mt hand" 
3. note down the result
4. repeat 1 to 3 with the corresponding item
5. repeat the whole process with the next pair of items

this way we can have a quick look into your ore dictionary, because i guess that the other mod is combining those two dusts and ingots together while it has no "oredict" for blocks, slabs and especially plates!
i may can provide you with a tiny zen-script to get it working if my guess is right

**Comment by Hypsellis** [comment]
Thanks for this command, I didn't know it. Anyway now I understand, in fact it's not IE which register bad its blocks and items but Substratum. Substratum registers Cupronickel as both Constantan and Cupronickel. It's surely Substratum which registers bad its block sand items. It explains why it's possible to switch between some and not others.

**Comment by EXTER7** [comment]
Reposting from the Substratum issue:



Blocks now register with alternate Ore Dictionary names in Substratum 1.8.2.1. Note that by default Ore Dictionary Converter will only convert certain items such as ores, ingots, dusts, and blocks. To enable conversion for more items you need to edit the ODC config file (fodc.conf) to add entries to the whitelist.
To be able to convert to convert IE constantan to Substratum cupronickel, the entry "*.Cupronickel" needs to be added to the ODC black-list, this is needed because ODC requires all ore dictionary names for an item to be the same, but IE constantan is registered as "*Constantan" while Substratum cupronickel is registered as both "*Cupronickel" and "*Constantan".

The fodc.conf should look similar to the following:

general {

    B:log_names=false

    S:blacklist=.*Cupronickel

    S:whitelist=^ore.*,^ingot.*,^dust.*,^block.*,^plate.*,^gear.*,^rod.*,^nugget.*,^slab.*
}

**Comment by Hypsellis** [comment]
Thanks I will look into it. ;)

**Comment by Hypsellis** [comment]
Thanks it works now, I close this issue now. ;)
