### ISSUE TITLE
Can't trade with villagers

### ISSUE THREAD

**Issue by DigitalSketch** [BluSunrize/ImmersiveEngineering#1719]
When I right-click on any Immersive Engineering villager, I get interaction.  Is this a configuration option that needs to be set?

We're running version 0.10-48

**Comment by BluSunrize** [comment]
Have you tried different items? Are IE villagers the only ones with these problems, or are vanilla or other mods also affected? 
Can you reproduce this in an instance with just Forge and IE?

**Comment by DigitalSketch** [comment]
We're running the hermit pack on a server and I tried this in a single player world and it just worked.  The only difference is we're running sponge on the server.  Is there a known issue with sponge that prevents them from trading?

**Comment by BluSunrize** [comment]
Wouldn't surprise me, honestly. Does Sponge have a permissions system?

**Comment by DigitalSketch** [comment]
Unsure, I posted in their github as well.  Wondering if there is a setting somewhere that needs to change.

**Comment by DigitalSketch** [comment]
Talking with the owner of the server, is there a permission we might need to set somewhere?

**Comment by BluSunrize** [comment]
No idea, never used Sponge before.
I know that IE in itself doesn't do anything special with its villagers so I don't see what would be causing this on my side...

**Comment by mindforger** [comment]
i have no idea how close the IE villager relates to a vanilla one, but maybe sponge does not recognize it as normal villager and suspects your interaction as invalid or drops the action because it can not handle the entity

can you ask the server owner to test this with sponge but without plugins and re-add plugins until it breaks to see if it is a permission problem or some plugin canceling the interaction because of permissions or config issues
