### ISSUE TITLE
[1.10.2  0.10-50] Liquid containers not working as intended in Squeezer/Fermenter

### ISSUE THREAD

**Issue by VallenFrostweaver** [BluSunrize/ImmersiveEngineering#1746]
**Issue A:** In both the Squeezer and Fermenter buckets/chemical thrower/jerrycan (if inserted via an input) will go into the area for processing materials instead of the area to be filled with the fluid. These items need to be manually placed inside the machines.  If this is intended, then why is there an item output on Fermenters?

**Issue B:** Automating the outputs of the Squeezer/Fermenter (with conveyors, etc.) will not pull these same items out. NOTE: The Squeezer WILL pull out any HOP Graphite Dust from the item output but not buckets/chemical thrower/jerrycan.

**Comment by mindforger** [comment]
you can add recipes utilizing the slots if you want, and for filling things there is another machine for that purpose!

**Comment by BluSunrize** [comment]
^ that basically. Same answer as with #1747
The item output exists for any potential recipe with an item output.

Just becaues none exist in vanilla IE doesn't mean some other mod cannot add them for compat reasons.
Fluid slots are not really automateable because I don't think that they need to be.
Fluid can be retrieved with pipes and stored in tanks.
For automated filling, the bottling machine will be re-implemented at some point in the future.
