### ISSUE TITLE
External Heater lags out the client

### ISSUE THREAD

**Issue by bmario** [BluSunrize/ImmersiveEngineering#1749]
When your energy grid doesn't provide enough energy for all machines, there is a possible lag. As soon as the external heater reachers 0 IF in the internal buffer, it starts to lag the client.
The furnace next to the heater has something to cook, so the heater should be active. As it has not enough energy available, it turns on and off very quickly. 

Maybe an sideeffect of #1702.

I noticed that behavior on build 48 and 50.

![2016-11-28_23 25 10](https://cloud.githubusercontent.com/assets/130405/20688698/3d276dd2-b5c2-11e6-9dd6-c82f470b4773.png)
![2016-11-28_23 24 50](https://cloud.githubusercontent.com/assets/130405/20688700/3fe53752-b5c2-11e6-811d-9cf752950006.png)

**Comment by BluSunrize** [comment]
I've been looking into this, a bit, and I have yet to find a satisfactory solution.

I do have a special form of my Energy Storage that will track average in and output rates.
So I tried to check averageInput>averageOutput. Sadly, that doesn't work too well when the last averaged output is 32 (8 for heating, 24 for speedup) and the input is 7. Means the thing never turns on again.

If I allow the average output to degrade again (which it does at /2 per tick) it goes back to flickering, because the decay happens over the course of a few ticks.
Even with an adjustable rate on how fast these average values decay ('average = average*factor + extracted*(1-factor)') it's still flickery due to a few ticks of decay immediately allowing the machine to turn on again.

I'd like to hear more people's input and ideas of it, because I currently can't find a good solution myself

**Comment by mindforger** [comment]
how about a bit of hysteresis? make a minimum amount of energy to activate
when active it can run dry but need to fill above the minimum level before activating again

this would elimnate flickering but it still will turn on and off whenever reaching the hystersis level and falling to 0

**Comment by BluSunrize** [comment]
Got a fix for it in the pipeline

**Comment by mindforger** [comment]
@BluSunrize I am programming industrial sensors XD you just triggered some knowledge on my end

**Comment by BluSunrize** [comment]
Damn, I'm actually getting some "immersive" information then xD
Oh right, losing this for now btw. Commit above should have dealt with this, Release 51 contains it.

**Comment by bmario** [comment]
The new build fixed it for me. Thanks.
