### ISSUE TITLE
[Crash]: java.lang.ClassCastException: java.lang.String cannot be cast to com.google.common.base.Optional

### ISSUE THREAD

**Issue by Lanse505** [BluSunrize/ImmersiveEngineering#1759]
**IE Version + Forge Version:**
IE: immersiveengineering-0.10-48
Forge: 1.10.2-12.18.2.2151

**Crashlog:**
https://gist.github.com/Lanse505/644155d2bf1a8d20230886c12cfc8247

**What Happened? / Can it be reproduced?:**
Basically I just charged up a Railgun while "floating" using a Simply Jetpacks Jetpack.
It loaded to 99 and went "boom" as usual then everything froze and crashed.

**Reproducability:**
Unreliably...
Can't reproduce it with a high-chance.
Might be something to look into but since due to the reproducability being low I'd say it's very low priority.

**Comment by BluSunrize** [comment]
Yeah, the lack of reproducability makes this nigh impossible to debug.
Plus, I have no friggin clue what actually causes it.

The code segment in question grabs the ammunition data contained in the railgun proejectile entity.
That data is an ItemStack, and the key/serializer is created in the exact same manner as the one on an ItemFrame. So the code is proven in vanilla to work.

The only difference is that the vanilla stuff has more type arguments in places where they are optional. This /shouldn't/ make a difference, because these typearguments are lost in bytecode anyway.

So yeah, no idea what causes this :/

**Comment by mindforger** [comment]
sounds like a racing condition to me, whenever you grab the data the dart maxybe already gone or something?

**Comment by cubesky** [comment]
I got the same issue.
Crash-Report here: http://paste.ee/p/XDqKI
We played in a server with forge and sponge version 1.10.2. 
A man fire a Railgun. And I crashed immediately. And when I reconnected, my client soon crashed.

**Comment by BluSunrize** [comment]
As I have learned recently, Draconic Evolution is one of the mods that can indirectly cause this.
Please make sure you're on the latest version of DE.

**Comment by cubesky** [comment]
@BluSunrize I haven't install Draconic Evolution mod. All mods I have installed is shown in crash-report in http://paste.ee/p/XDqKI

**Comment by cubesky** [comment]
Mainly mods I have installed is Mekanism , ImmersiveEngineering , Botania , Roots , Quark ,
