### ISSUE TITLE
Request: additional armors.

### ISSUE THREAD

**Issue by Kaisoul** [BluSunrize/ImmersiveEngineering#1767]
So far i am loving Immersive Engineering but...
i would like for the mod to have at least 1 or 2 more armors
the Faraday  suit is great as immersion and light armor but any chance we can get improved versions with a
medium level protection and heavy level protection.

Exsample

Light armor: current Faraday suit = to leather armor in combat protection
Medium armor: Reinforced Faraday suit = to possible chain mail level or iron level protection
Heavy armor:  Nuclear Powered Faraday suit = to diamond level protection /w possible upgrade slots for things like night vision or oxygen tank.   

i just want to be able to play your mod with out needing to go hunt down mods that give me armor to enjoy mods like rougher mobs & lycanite mobs  i already have 2 common magic mods for armor but a tech armor option would be perfect fit into my 1.10.2 Lan world.

**Comment by BluSunrize** [comment]
Well the Faraday Suit is really only used when doing stuff with Tesla Coils. It's a very special case set of armor, similar to IC2s Hazmat suit.
So I personally don't see the point in having reinforced versions, simply because you're not really supposed to actually fight stuff while wearing it.
If the armors had the same protection as existing vanilla armor, I see little use in using it over vanilla armor, with the exception that IE stuff looks way nicer.

Not to mention that powering an armor on nuclear energy is probably really bad for your reproductive abilities.

**Comment by Kaisoul** [comment]
understandable it's just nice to have armors with special functions even if
there not "combat functions"  being able to customize stuff like IE
(immersive engineering) can would be pretty fun way to explore the world.

**Comment by VallenFrostweaver** [comment]
Ok. I think we've waited long enough for you to unveil the "Big Daddy" armor that we can attach the drill to and a rivet gun attachment or the like. This mod screams a little throw to the retro futurism of Bioshock to me.

To make it more "Immersive" friendly perhaps at least a deep diving suit that works great under water allowing normal freedom of movement (perhaps even step assist or 2 block jumps), digging/melee weapon and infinite or extremely extended air but when out of water it gives a slowing effect on the user, no step assist/2 block jump.  This would mean people would only make this to do underwater work or exploring the water temples but then it would prevent duplication in your typical armors seen in other minecraft modding (in my experience). You could even limit it further by having it require fuel or energy.

**Comment by VallenFrostweaver** [comment]
Another thought might be like the Rocketeer style where you have no chest armor but can use a jetpack that runs on a fuel of choice. Maybe a matching helmet might work too but keeping it lightly armored or no armor would help it to balance plus the need for fuel and steel perhaps. It would be excellent to have it be difficult to control too (like you are always on ice like effect when trying to land/manouver) since it is a freakin' jetpack after all.  Just more thoughts.

**Comment by mindforger** [comment]
@BluSunrize 
how about THIS addition to the mod to extend the use of your suit?

https://www.youtube.com/watch?v=_fTC_Ud_k3U
or
https://www.youtube.com/watch?v=qX1W3pRY54o

**Comment by VallenFrostweaver** [comment]
Last idea for the moment - a Steamboy monocycle. Sounds like it would be difficult to model but in execution it's just a horse that may be changed a bit.

**Comment by BluSunrize** [comment]
Regarding the last comment: IE isn't steampunk

Regarding the big daddy-esque powersuit. Far ahead of you. Has been planned basically since the first week of developing this mod. Currently however, IE's main artist is out of comission, so that project will have to wait.

Also, that's completely off topic. The original suggestion of this issue was the inclusion of more Faraday suits, and I stand by my sentiment of: There is absolutely no point to that.
