### ISSUE TITLE
[Feature Request] Dirt -> Clay

### ISSUE THREAD

**Issue by rjhall90** [BluSunrize/ImmersiveEngineering#1782]
Clay is just very fine soil, so it would make sense that clay - a relatively uncommon resource in Minecraft, with less overall blocks per map than even diamond, should have a recipe.

I propose that one (or more) dirt blocks in a crusher should have a clay equivalent. 1:1, 2:1, or even 4:1 would be an acceptable ratio, I believe. It's a feature that would take minutes to implement but have a fantastic impact on otherwise painful recipes, especially concrete.

**Comment by mindforger** [comment]
Clay is pretty common, you have to search at waterlevel in rivers and on coasts

dirt is just tooooo common to give it any ration higher than 1:1 because it would throw very very very much mods off  balance!

it also would take you just minutes to write up a little zen-script for the crusher if you think your modpack need adjustment and reuires for a dirt to clay recipe

http://minetweaker3.powerofbytes.com/wiki/Mods:Immersive_Engineering_Support

just write a simple textfile with the script, call it DirtToClay.zs and drop it into the "scripts" folder of your minecraft (you just need to install crafttweaker and modtweaker eventually)

**Comment by BluSunrize** [comment]
Yeah Clay recipes never sit very right with me. Botania's Clayconia does it decently, I'd say, but I find it hard to come up with a "techy" way of producing it.
Also @mindforger just for the record, Modtweaker is not required for IE's compat to work

**Comment by mindforger** [comment]
ah, nice to know :)

**Comment by MalkContent** [comment]
Can't clay be an "ore vein" for the excavator? I don't know if that would make sense.
I'm having a hard time thinking of mods that get thrown off balance because of a clay overdose.
The couple of pieces you need every here and there you find easy.
The clay you need to build a big machine hall or something takes forever to grind

**Comment by mindforger** [comment]
you can also define custom ore veins if you want, you will only have to add clay to the ore dictionary to make it available to the excavator script

**Comment by MalkContent** [comment]
sure, but I was just wondering if using an excavator to dig up clay would even make sense

**Comment by mindforger** [comment]
sounds total legit to me
normally clay is "made" by crushing up minerals to compose the right mix for the right usage 
but it also is harvested by bench-mining according to wikipedia and an excavator makes much sense there to me

**Comment by rjhall90** [comment]
I'd be okay with either one of these. When I said ratio, I meant dirt to clay ratio. Even if you had to sift 8 dirt to make a clay ball, that's fine.

If no recipes for clay, please stop concrete from taking it. I'd like to build large buildings out of concrete, but it murders clay. Real concrete doesn't even have clay.

**Comment by rjhall90** [comment]
So I've been poking around with MineTweaker and it doesn't actually support 1.10.2, which is the MC version I'm using for IE. Any suggestions to work around this?

**Comment by mindforger** [comment]
https://mods.curse.com/mc-mods/minecraft/239197-crafttweaker

^ continuation of minetweaker 100% compatible

**Comment by DrakoAlcarus** [comment]
Try this mod if you don't like tearing up terrain, or can't find enough  clay at water level.

https://minecraft.curseforge.com/projects/clay-worldgen

It's such a simple mod to have, and I use in in every mod pack, and adjust depending on how much clay is needed.

**Comment by mindforger** [comment]
dunno if foreign mod advertation is a good aproach in an issue tracker

**Comment by DrakoAlcarus** [comment]
I don't see the problem with it. It's not a bug or missing feature. It's not my mod, and other mod devs have suggested other mods that do what I request, especially when what I want usually goes against the plans for the mod developer

**Comment by BluSunrize** [comment]
yeah I don't mind it given that it's not your mod, however I feel it unfitting for the issue at hand. The request was for a crafting recipe for clay, not a world generation mod :V

**Comment by DrakoAlcarus** [comment]
True. I only suggested it because the OP said: "Clay is just very fine soil, so it would make sense that clay - a relatively uncommon resource in Minecraft, with less overall blocks per map than even diamond, should have a recipe."

Other than that, I don't really know what else can be done except crushing dirt into fine soil, then running it through the mixer into mud, then drying the liquid out into a dirt/clay block and breaking it. Or increase the clay yield from mining.
