### ISSUE TITLE
(0.10-52)  Splitter Conveyors missing one split under certain circumstances

### ISSUE THREAD

**Issue by ConKuk** [BluSunrize/ImmersiveEngineering#1789]
*** EDIT: See video at bottom

Issue: Under certain circumstances the items will only move in one direction on a splitter conveyor.

Noticed this first when using Direwolf20's 1.10.2 pack ( version 1.1.3 ), which contains 0.10-52 version of IE. forge 12.18.2.2171), but has a bunch of other mods.

Later tested this with fresh minecraft 1.10.2:
* Forge 12.18.3.2185
* IE 0.10-52
* SuperCircuitMaker 1.0.4  ( Just for the timer, not that good with vanilla to make timer :P )

=== The same result!

The following description concerns a branching pattern as follow:
![2016-12-11_00 01 07_overlay](https://cloud.githubusercontent.com/assets/4126743/21076579/d4939dfc-bf37-11e6-9080-cc2bc422cab5.png)

The timer is timed so nothing will stack on the belts. even bumped to 30 ticks for these tests!
When 'precisely inserting' ( this is an important detail) items into a conveyor belt ( For example if using a hopper ), on the second split counting from the point of insertion one of the split conveyors always routes the item one way.
( Marked on the picture above )

See result of item splitting:
![2016-12-11_00 01 26](https://cloud.githubusercontent.com/assets/4126743/21076565/70a956b0-bf37-11e6-9c94-77a1089631a6.png)

On the right side it goes as expected: 32, 16, 8, 4, 2...
but on the left it skips one and goes 0, 32, 16, 8.

I tried NS, SN, EW and WE directions, the only thing different is that in two occasions its the right branch and on the other 2 its the left,
![2016-12-11_00 24 15](https://cloud.githubusercontent.com/assets/4126743/21076610/816d4618-bf38-11e6-8289-0f214965c194.png)

Pic includes the Axis widget from F3 screen. (Unfortunately there is no ortho view in minecraft so its perspective).

Every split of the 4 looks like this, just in different direction:
![split](https://cloud.githubusercontent.com/assets/4126743/21076634/228dc414-bf39-11e6-9e3f-8f2854730cfe.png)

There seems to be some correlation to direction of movement after FIRST split, since its always happens when the item first split to +x or +z and than had to split in opposite  ( -x, -z ) direction.

Interestingly, if dropping item from vanilla dropper ( the one that spits in random directions , i.e not precise  [Made a chute with glass to make sure it doesn't miss the conveyor]), than all branches work BUT it breaks the routing left/right consistency, see picture:
![2016-12-11_00 51 01](https://cloud.githubusercontent.com/assets/4126743/21076750/2e6f3c4c-bf3c-11e6-8abb-e0aef2d37783.png)
Its no longer binary.

Hope I didn't miss anything...

I wanted to make an autocrafting system where I order some plates and that number drops on input and splits to 4 presses, noticed that only 3 are getting ingots.....

VIDEO:
https://www.youtube.com/watch?v=9Qt4KkltfNQ

**Comment by BluSunrize** [comment]
If items stack, the splitting breaks. I can't do anything about it. Transport needs to be a bit slower, otherwise the autostacking will fudge it up.

**Comment by ConKuk** [comment]
As I stated:::::

> The timer is timed so nothing will stack on the belts. even bumped to 30 ticks for these tests!

**Comment by BluSunrize** [comment]
Right, sorry, I must have missed that then. I'll look into it.

**Comment by ConKuk** [comment]
Items not splitting correctly was the SECOND ( and secondary ) issue I mentioned, and it is not such a big one.
The problem is the FIRST issue, when NOTHING gets sent to one of the forks.

**Comment by ConKuk** [comment]
> Right, sorry, I must have missed that then. I'll look into it.

I understand your frustration, and the reason for your first reply.
As Developer myself, I know you have to deal with people that just rush to post something that they think you HAVE to fix, without thinking first.

I only ask that you read the whole post and share your thoughts if possible, I'm also interested in to why this bug might happen. ( From code logic point of view )

**Comment by ConKuk** [comment]
Added a video to the OP

**Comment by BluSunrize** [comment]
Right so what I figured out in testing, the NBT data used to store an entities direction isn't cleared properly on certain occasions. This clearance is based on the distance of the entity from the next block it's moving into, but I find myself unable to find a distance that works, because either one conveyor has it offset a tiny bit more on its last tick, which makes it not delete the data, or it has anther tick after clearing which makes it reapply the data with a flipped side.
The results are that either, for case one, the faulty conveyor then determines the output direction of all other conveyors to follow, or for case 2, it flips at the last possible moment and shoots it out the other side.

Since neither of these options are satisfactory, I've come up with a solution that not only writes the direction to NBT but also appends the block's position (hashcode of the BlockPos, written in hexadecimal) to the key of the NBT data. That means that every conveyor adds a unique entry to the entities NBT, so it extends the size of hteir NBT data slightly, but it also remedies the issue.
Plus, it seems to be 1 or 2 in 10 conveyors that have this issue, so at maximum, it adds two extra NBT tags.
Also, note that these are added to the entity and are wiped as the Entity is removed, so when you pick it up or store it in a chest. This is not the NBT of the ItemStack, so it will not persist on the actual item itself.

Commit to fix this is coming later today along with a release.

**Comment by ConKuk** [comment]
Thank you for sharing your debug and solution process.
