### ISSUE TITLE
[0.10-53] Splitting conveyors are still not routing correctly

### ISSUE THREAD

**Issue by ConKuk** [BluSunrize/ImmersiveEngineering#1813]
* Minecraft 1.10.2
* Forge-12.18.3.2185
* IE-0.10-53
![2016-12-21_23 12 10](https://cloud.githubusercontent.com/assets/4126743/21406439/565f3ca2-c7d4-11e6-84c6-e2d26b854e52.png)

Clean install, no other mods. ( Not even SuperCircuitMaker )

I'm sorry to be the bearer of bad news but while I see far less bouncing around ( Items 'deciding' to go 
a different direction at the last moment on the splitter), the problem of the splitters not sending anything to one direction is still there.

![2016-12-21_23 11 48](https://cloud.githubusercontent.com/assets/4126743/21406567/faaf7bb4-c7d4-11e6-9d91-e279fc18a55c.png)

![2016-12-21_23 12 00](https://cloud.githubusercontent.com/assets/4126743/21406572/01945e86-c7d5-11e6-916f-33f57a9d1cbd.png)

Video:
[https://www.youtube.com/watch?v=q9CJ24IbqCE](https://www.youtube.com/watch?v=q9CJ24IbqCE)

**Comment by mindforger** [comment]
can chunkborders have an effect on the routing?

**Comment by malte0811** [comment]
I have been able to reproduce this, I will try to fix it now.

**Comment by malte0811** [comment]
I didn't manage to fix it yet, even though I have an unfinished potential fix. I will be away until monday, if anyone else wants to work on this before then I will tell them what I know so far.

**Comment by BluSunrize** [comment]
share the knowledge, please, I'd like to look into it.

**Comment by malte0811** [comment]
1. I use the setup shown in the screenshots. I build it such that the first splitting belt touches a chunk border, but I don't think this is relevant. The input is a hopper, I make the items loop back to it for continuous testing.
2. The item entities automatically stack to 2 items. This might be relevat as it might change the entity size (haven't actually checked).
3. The item is first considered to be about to leave the belt (the direction tag is removed), but still touches it in the tick. This only happens in one direction and some unknown additional circumstances.
4. A solution might be changing the splitting conveyor to store the splitting direction in some internal map instead of the item NBT (the entities would need to be removed from the map a couple of ticks after the item last touched the belt).

**Comment by BluSunrize** [comment]
Oh, that's all? No worries then, I'll just extend the collision timers more or smth. I'll look into this. Thanks malte ^^Am 24.12.2016 9:17 vorm. schrieb malte0811 <notifications@github.com>:I use the setup shown in the screenshots. I build it such that the first splitting belt touches a chunk border, but I don't think this is relevant. The input is a hopper, I make the items loop back to it for continuous testing.The item entities automatically stack to 2 items. This might be relevat as it might change the entity size (haven't actually checked).The item is first considered to be about to leave the belt (the direction tag is removed), but still touches it in the tick. This only happens in one direction and some unknown additional circumstances.A solution might be changing the splitting conveyor to store the splitting direction in some internal map instead of the item NBT (the entities would need to be removed from the map a couple of ticks after the item last touched the belt).

**Comment by BluSunrize** [comment]
^ This commit has the timing extended
I'd encourage you to try it with a Jenkins build, but I'm afraid the Jenkins is dead right now. xD

**Comment by BluSunrize** [comment]
This version on Jenkins
http://ci.blamejared.com/job/ImmersiveEngineering-1.10.2/33/
Should have this fixed.

@ConKuk, could I bother you to experiment with that build to see if you can still reproduce the issue? ^_^

Also, obviously, Jenkins builds are not official releases so please treat this with a grain of salt and don't distribute a modpack with it or smth. =P

**Comment by ConKuk** [comment]
@BluSunrize Done:
* Tested with both equal distribution and exponential.
* Tested WITH and WITHOUT hoppers ( so basically tested free-fall and insertion to conveyors)

Results:
* 4 on each output for the equal distribution one.

* And got the following series on the exponential one:
- 1,1,2,4,8,16,16,8,4,2,1,1

So now everything seems to be working great now.
Screenshots:
![2016-12-25_18 58 22](https://cloud.githubusercontent.com/assets/4126743/21472169/0e48c0d8-cad5-11e6-8374-4a404c53e253.png)
![2016-12-25_18 58 25](https://cloud.githubusercontent.com/assets/4126743/21472170/1196c23a-cad5-11e6-927a-95433d74b6b4.png)

**Comment by BluSunrize** [comment]
Thank you for testing =3

I'll close this then, as its fixed for future releases.
