### ISSUE TITLE
crash while reading immersive engineering manual

### ISSUE THREAD

**Issue by DaemosDaen** [BluSunrize/ImmersiveEngineering#1823]
While looking at how to build things in the manual, the game crashes severely. This only happens while looking at the IE manual. I am running the DW20 1.0.4 mudpack which seems to use  0.10-52. If this has been fixed, then I apologize I'm on a sever and have little control on when we update.

Relevant files:
https://1drv.ms/u/s!AlpZQdyrEQxIhJA_oo7JBkZiSvG-Mg
https://1drv.ms/u/s!AlpZQdyrEQxIhJBA5mbSKEPZsr1gkg
https://1drv.ms/t/s!AlpZQdyrEQxIhJBBXkFQ7kkOK4AvyQ

**Comment by DaemosDaen** [comment]
note: this only crashes the client, the server does not seems to care.

**Comment by malte0811** [comment]
Try using an up to date Java version. You are running java 8 *Update 25* which was published in late 2014 if I recall correctly. The current version is Update 111. We haven't had any reports of this problem with up to date Java and since this is a crash in some internal bits of the JVM, we probably can't fix it.
Yes, I know that this is the Java version shipped by Mojang and Curse and I have heard stories about newer Java versions breaking on integrated graphics cards (or something like that), but even figuring out what is causing this would require a lot of work, fixing it might prove to be impossible.
@BluSunrize We should really add using a fairly recent Java version (something like "either latest or published within the last 2 month") to the bug report requirements in the contributing guidelines...

**Comment by DaemosDaen** [comment]
This happened after I updated to update 111.

**Comment by malte0811** [comment]
I assume you mean that the crash files you uploaded come from an update 111 JVM:
> # JRE version: Java(TM) SE Runtime Environment (8.0_25-b18) (build 1.8.0_25-b18)

From the first file. I might take a look at this later if I don't have anything else to do, but I can't promise it.

**Comment by DaemosDaen** [comment]
I actually had update 110 installed she the first set was created, but performed an update and still received the error. I I'll see about the odd version showing up, that may be the end all be all answer.

**Comment by XFactHD** [comment]
You need to change the java version in the launcher profile.

**Comment by DaemosDaen** [comment]
Ok, Mohan/MS need to use what ever version of Java installed, not the cruddy version MC comes with, thanks for the help.
