### ISSUE TITLE
ImmEng crashes on load with IC2C

### ISSUE THREAD

**Issue by Baughn** [BluSunrize/ImmersiveEngineering#1828]
This is on the latest version, 0.10-54.

You're accessing ic2/core/recipe/AdvRecipe without first checking whether or not it exists. Which it doesn't; presumably it's an IC2Exp class, or from an earlier version. In any case it's not part of the API.

@Speiger says you should use https://github.com/TinyModularThings/IC2Classic/blob/master/src/main/java/ic2/api/classic/recipe/crafting/IAdvRecipe.java instead.

Full crash report: http://sprunge.us/FSaa
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Do not report to Forge! Remove FoamFix (or replace with FoamFix-Lawful) and try again. (foamfix-0.4.2-anarchy.jar)
  ForgelinPlugin (Forgelin-1.2.0.jar)
  LoadingPlugin (ResourceLoader-MC1.9.4-1.5.1.jar)
  AppleCore (AppleCore-mc1.10.2-2.1.0.jar)
  NWRTweak (redstonepaste-mc1.9.4-1.7.4.jar)
  LoadingPlugin (LoadingProfiler-MC1.9.4-1.3.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.338.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.7.jar)
  LoadingPlugin (Quark-r1.1-68.jar)
  llibrary (llibrary-1.7.2-1.10.2.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.61-beta.jar)
  Default Options (DefaultOptions_1.10.2-6.1.5.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.6.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.0.178-universal.jar)
  IvToolkit (IvToolkit-1.2.9.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.1.6.jar)
  literalascension (literalascension-1.10.2-1.0.0.3.jar)
Contact their authors BEFORE contacting forge

// Quite honestly, I wouldn't worry myself about that.

Time: 12/29/16 7:27 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Immersive Engineering (immersiveengineering)
Caused by: java.lang.NoClassDefFoundError: ic2/core/recipe/AdvRecipe
	at blusunrize.immersiveengineering.common.util.compat.IC2Helper.init(IC2Helper.java:24)
	at blusunrize.immersiveengineering.common.util.compat.IECompatModule.doModulesInit(IECompatModule.java:83)
	at blusunrize.immersiveengineering.ImmersiveEngineering.init(ImmersiveEngineering.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
(...)
```

**Comment by Speiger** [comment]
Just to point out. The API Baughn is only fitting for IC2Classic. It will not work for IC2Exp.
What you need to check for when wanting to prevent a crash is for ic2cs modID "IC2-Classic-Spmod"
and then shut down the feature.
If you want to keep the feature for classic do use the class Baughn told you.
Also a note that IC2Classic has Stacksize recipes (aka using more then 1 item at 1 slot) so stacksize of 1 is not always required. There are recipes which need like 8 or 16 items.

If you need more help here you find me.

**Comment by BluSunrize** [comment]
I'm afraid that my compatability is directed at IC2, the official one.
How classic even manages to interfere with it is a mystery to me, since my compat class shouldn't load unless there is a mod with the id "IC2"
Upon looking at thecrashlog, turns out there is, which is absolutely terrible. No two different mods should have the same modid, that just causes chaos. You really should look into changing this for 1.11.

I'll look at a safeguard, but for future reference: I don't cater to inofficial distributions, generally.

**Comment by Speiger** [comment]
Well ic2classic uses the modID IC2 for compact reasons. The only difference is that I have some class differences. And the official IC2 is aware of these things. And IC2C is officialy supported by IC2Exp (not codewise but Perm wise) 
About 1.11 you do not need to worry I will skip for about 4-6 months mc versions since the constant updateing would cause the IC2C becomes like "XYCraft" in the public. 
But its a shame that you are forced to use CoreClasses to read recipe data in Exp...

anyway thanks that you work on that

**Comment by Speiger** [comment]
ty
