### ISSUE TITLE
IE Wires Disappearing after server restart/crash.

### ISSUE THREAD

**Issue by wiloxe** [BluSunrize/ImmersiveEngineering#1839]
So the title of this issue says the general issue i'm having.
Whenever we restart the server or it crashes so we have to restart it the wires disappear but only some not all. And this is very confusing for everyone who plays on the server and me who have to go around and replace thier lost wires...

IE Version: 0.10.58
Forge: 12.18.3.2202
If any more information is required please feel free to ask.

**Comment by BluSunrize** [comment]
Check if the chunks it happens in contain chunkloaders or are being loaded by FTBUtils.

**Comment by wiloxe** [comment]
There was something loading chunks at one place however none at others. And still the wires just vanish into who knows where. It's quite odd...
Tho i want to point out that we did change some config values on wires such as length, Transfer rates and connector transfer rates just to make make them handle more RF so the wires dosen't keep burning up in our setup...

**Comment by PONYRYDE** [comment]
Same problem here and as well in the same chunk its opposite, I can't make `<a href="http://imgur.com/a/QOEHt">this</a>` wire disappear. I have removed all IE blocks in the chunk, unloaded it, disabled all chunk loading, filled the area with dirt but as soon as I put any relays or connectors in the same locations the MV wire magically reappears. 

Note that in the pic it has connected itself to a HV connector. Magic.

**Comment by PONYRYDE** [comment]
validateConnections = true got rid of the magic wires (I found more) but wires are still disappearing.

**Comment by mindforger** [comment]
@BluSunrize can a corrupted chunk be cause of this?

i have read in EnderIO about the mod SimpleLabels beeing a suspect to chunk corruption leading to rendering issues and vanishing storages (mostly because there seems a major NBT corruption)

**Comment by malte0811** [comment]
First of all: @wiloxe @PONYRYDE Are you using a "normal" forge server or some sort of special server software like Cauldron, KCauldron, Thermos?

For reference: [This](https://github.com/SleepyTrousers/EnderIO/issues/4010#issuecomment-274870107) is (probably) the comment @mindforger ist talking about.

(No real result, just random stuff I found)

I personally don't think this is caused by chunk corruption etc since the connections are stored in a centralized map (per dimension) in the [ImmersiveNetHandler](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/api/energy/wires/ImmersiveNetHandler.java) and written to the disk in [IESaveData](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/IESaveData.java) (`TileEntityImmersiveConnecatble::loadConnsFromNBT` is only used to send the connections to the client if I didn't miss anything).

The save data is marked dirty every time there is a change to the NetHandler (except for one wire removal method, I fixed that in my local instance). Additionally there is a weird `markDirty` call [here](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/EventHandler.java#L119). This call looks like it is intended to force writing the save data, but it seems to run AFTER `isDirty` is checked. The call a few lines further down looks weird/useless as well as all changes should cause a `markDirty` call anyways.

I think that a debug build is probably going to be the easiest way of debugging this (@BluSunrize?). I have added a few debug printouts to my local instance, if anyone else has suggestions for printouts I can add them. @BluSunrize If you want to make the build yourself, I can push the debug code to github.

**Comment by BluSunrize** [comment]
Nah, by all means, give them yours, Malte. That's easier than having to do a load of branch managing again.

**Comment by malte0811** [comment]
@wiloxe @PONYRYDE Please try using this build: https://www.dropbox.com/s/d1n6q35qw2n0vnf/ImmersiveEngineering-0.10-55-debug1.jar?dl=0. It may or may not fix the problem, please upload logs in either case (some of the things I did shouldn't be done except for debugging, but make testing easier, so if it works, I will need to do more changes) and don't use this build for anything else. Built of commit 740badd78069873eb8147d1d1f285acdd5b381a4.

**Comment by PONYRYDE** [comment]
Didn't fix it for me.

In my case while the problem is confined to a chunk it may only be because the build is confined within chunk boundaries to economize on chunk loading.

I have neither Ender IO or Simple Labels installed.
Opening baubles had no effect

<a href="http://paste.ee/p/XMKm1">LOG</a>

Mod list:

  antiqueatlas-1.9.4-4.3.0
  AppleSkin-mc1.10.2-1.0.4
  AutoRegLib-1.0-2
  Baubles-1.10.2-1.3.6
  bdlib-1.12.2.17-mc1.10.2
  BetterAchievements-1.10.2-0.3.2.35
  BetterAgriculture-[1.10.2]-1.0.1
  Bloodmoon-MC1.10.2-1.5
  Bookshelf-1.10.2-1.4.2.334
  Botania r1.9-340
  Chameleon-1.10-2.2.0
  Chisel-MC1.10.2-0.0.7.7
  chiselsandbits-12.11
  ChiselsBytes-1.9.4-0.32
  compatlayer-1.10-0.1.7
  CookingForBlockheads_1.10.2-4.2.26
  coroutil-1.10.2-1.1.11
  covers-0.4.1.14-mc1.10.2
  cyberware-1.9.4-1.10.2-beta-0.2.6
  CyclopsCore-1.9.4-0.9.1
  EnchantingPlus-1.10.2-4.1.0.115
  EvilCraft-1.10.2-0.10.18
  expandableBackpacks1.1.10-1.10.2
  extrablocks-1.0.2
  extrautils2-1.10.2-1.1.2
  FastLeaveDecay-MC1.10.2-1.2.3
  flatcoloredblocks-mc1.10-v4.4
  forestry_1.10.2-5.2.17.360
  Forgelin-1.2.0
  FTBLib-1.10.2-3.2.3
  FTBUtilities-1.10.2-3.2.4
  gendustry-1.6.5.27-mc1.10.2
  generators-0.9.20.19-mc1.10.2
  GrimoireOfGaia3-1.10.2-ALPHA-1.4.6
  hopperducts-mc1.9.4-1.4.8
  ImmersiveEngineering-0.10-55-debug1
  InventoryTweaks-1.61-58
  ironchest-1.10.2-7.0.11.797
  itemscroller-1.10.2-0.7.1
  jei_1.10.2-3.14.2.401
  jeibees-0.9.0.4-mc1.10.2
  JustEnoughResources-1.10.2-0.5.8.98
  literalascension-1.10.2-1.0.0.4
  llibrary-1.7.2-1.10.2
  malisiscore-1.10.2-4.2.8
  malisisdoors-1.10.2-5.1.5
  Mantle-1.10.2-1.1.4
  mcjtylib-1.1x-2.3.4
  modnametooltip_1.10.2-1.6.0
  morebees-1.10.2-1.3.1
  moreoverlays-1.9-mc1.10.2
  mp3spi-1.9.5-1
  NaturalPledge-r1.6
  Neat 1.3-12
  NoMoreRecipeConflict-0.6(1.10.2)
  OpenComputers-MC1.10.2-1.6.1.6
  OpenFM-1.9.4-0.1.0.18
  Pam's HarvestCraft 1.9.4-1.10.2h
  platforms-1.10.0-1.2.6
  pressure-1.3.1.18-mc1.10.2
  Quark-r1.1-70
  Railcraft_1.10.2-10.0.1
  RandomThings-MC1.10.2-3.7.7
  redstonepaste-mc1.9.4-1.7.4
  refinedstorage-1.2.18
  Reliquary-1.10.2-1.3.3.620
  rftools-1.1x-5.82
  RTG-1.10.2-4.1.1.7
  shetiphiancore-1.10.0-3.3.4
  SimplyConveyors-1.4.2
  SoundFilters-0.9_for_1.9.4
  StorageDrawers-1.10.2-3.5.17
  TConstruct-1.10.2-2.6.2
  theoneprobe-1.10-1.3.3
  TinkerToolLeveling-1.10.2-1.0.1
  TombManyGraves-1.10.2-2.1.12
  vorbisspi-1.0.3-1
  zombieawareness-1.10.2-1.11.1


I feel I've been a bit lazy with the bug hunting, wasn't in the mood for tedium, but am commencing test instance now.

**Comment by malte0811** [comment]
Very few people actively hunt down the bugs they report, no reason to feel like you have been lazy. From a first glance over the log it doesn't look like my debug code produced anything useful. Are those mods available as a pack on curseforge or somewhere?

**Comment by PONYRYDE** [comment]
I feel reporting a bug demands a certain amount of due diligence and I get some satisfaction from finding the cause. Wow I'm such a nerd.

It's just my own collection of mods. The bare essentials with minimal duplication of function to maximize performance late game. This time around I am trying to do without too much mystical item transport, Random Things Super Lubricant Ice and conveyors appealed, but I am tempted to add Ender IO because conduits and a block having only six sides.

So far no luck on reproducing the problem with just IE installed but I can confirm it's not limited to one chunk now, either it has spread or I got lucky with the bit of wiring I did elsewhere after it started.

The problem doesn't occur in a new world, at least with minimal testing.

**Comment by PONYRYDE** [comment]
Found a backup from just before the problem started and played spot the difference. That difference being Expandable Backpacks Sending Compartment.

To reproduce:
1. Install IE and Expandable Backpacks
2. Link a Backpack with an installed Sending Compartment to a chest (Storage Crate won't link for some reason)
3. Lay wires and restart.

Uninstalling Expandable Backpacks resolves the issue, removing or deleting the Sending Compartment does not.

It may be of interest that once the problem has started and with Railcraft installed, every time an IE item is picked up this is logged

[Client thread/WARN]: Couldn't find resource table railcraft:chests/village_workshop

I kept seeing that spam but never put two and two together.
Sated.

**Comment by malte0811** [comment]
I was able to replicate this bug as you described it, for some reason the `WorldSaveData` IE uses isn't being checked any more. I am looking through the decompiled source code right now, which isn't made easier by the fact that there is no deobf version (So all calls to MC have names like `func_145893_b`).
There is one thing I can explain already: why storage crates don't work with the backpacks. As you may know, inventory handling changed in 1.8 (I think?), from `I(Sided)Inventory` to capabilities. Expandable backpacks is using a method in the hopper TE class to detect inventories (which is just weird), this method uses the deprecated inventory type. IE updated to use capabilities for inventories when it was updated to 1.8, so the backpacks don't see IE's inventories.

**Comment by malte0811** [comment]
I have found the cause of this and reported it to the author of Expandable Backpacks, see [here](https://minecraft.curseforge.com/projects/expandable-backpacks/issues/21). This issue should probably be closed since it is not IE's fault.

**Comment by PONYRYDE** [comment]
Your quick. I was just about say I'd report it there but got distracted trying to link a backpack to a donkey (you gave me false hope). Good job.

**Comment by malte0811** [comment]
I don't know whether you can insert into donkeys using hoppers, you might be able to make a chest minecart work though. Link the backpack to a chest, break the chest and place a track+chest minecart in the same space. I haven't tried that, but it might work from what I have seen in the code :smile:

**Comment by PONYRYDE** [comment]
That actually works but I think you new mod that lets us load and unload donkeys with hoppers and endow them with ender chests will be more practical.

**Comment by wiloxe** [comment]
Okay well now we know the issue and i hope it will be fixed on expandable backpacks side soon. Thanks guys!
