### ISSUE TITLE
Recipes to respect ore dictionary?

### ISSUE THREAD

**Issue by xSparky911x** [BluSunrize/ImmersiveEngineering#1847]
Even if I delete items from the ore dictionary using mine tweaker, the machines from IE still show those items as if the machines are completely ignoreing the ore dictionary. If I look at crafting recipes after I deleted items from the ore dictionary, those items are no longer listed. This is not the case with IE. It as is the item recipes are hard coded into the machines. Or is there a way to remove some IE machine recipes with MT?

**Comment by xSparky911x** [comment]
nevermind found this...

http://minetweaker3.powerofbytes.com/wiki/Mods:Immersive_Engineering_Support

**Comment by mindforger** [comment]
isn't there a current issue that MT does not correctly reflect it's changes in JEI?

**Comment by xSparky911x** [comment]
Not that I was aware but I never looked. I did manage to get the items to not show in recipes for crafting tables for example by modifying the ore dictionary with mine tweaker. Im going to test with this crusher example here right away.

**Comment by xSparky911x** [comment]
Well by deleting the ore dictionary entry (for bauxite for example) the crusher no longer accepts those items but still shows the recipe in JEI. Minetweaker is supposed to have mod integration for IE but I'm pretty sure the port/fork of MT (Craft Tweaker) does not support this because this method mods.immersiveengineering.Crusher.removeRecipe(<immersiveengineering:metal:10>); does not work. It still shows the recipe.

Regardless, back to my original complaint, removing the ore dictionary entry for Bauxite, shoul remove the ore from even showing up in the recipe if the recipe was using oreAluminum. It would only show the aluminum from the other mods I have installed. Works for almost every other mod and their machines that I am using thus far.

**Comment by mindforger** [comment]
i think https://github.com/BluSunrize/ImmersiveEngineering/issues/1837 could shed a bit light on your issue

**Comment by xSparky911x** [comment]
Although I am trying to remove a recipe not add one, it should basically be the same? Also I see this was fixed (possibly) recently? Hopefully there is a push soon

**Comment by XFactHD** [comment]
The fix was already pushed but there is no new version yet.

**Comment by BluSunrize** [comment]
Right, let's address a few things :D
As people have already mentioned, there is a fix for the recipes not updating in JEI, recent Jenkins build should even have it already, since I pushed last night.
However. One thing I have to point out: Modifying the OreDictionary with Minetweaker is not always a good idea. The OreDict is decided to be used by mods internally, and only added to on load. Removing things from it, especially using MT on world load could result in some critical issues, and I'll say now: I'm absolutely not liable for any of those. Heck, there shouldn't ever be an option to remove an item from the OreDict, tbh. It's just that that registry has blown up to be far more than it was supposed to be. It was orignally designed to just allow every mod to say "This is copper. Other mods may use my copper".
But noone ever planned for mod devs or packmakers to decide that suddenly, this ore /isn't/ aluminium anymore. So with that in mind, feel free to try the latest build off of Jenkins, but beware that the Minetweaking you're doing might not work as intended.

**Comment by XFactHD** [comment]
I agree on that and to be honest I don't have any idea how they are removing OreDict entries in a sane way as there is no remove method as far as I know.

**Comment by mindforger** [comment]
@BluSunrize i am amazed how you always are able to teach an old dog like me new tricks :D

**Comment by xSparky911x** [comment]
I do agree with most of what you said. I am trying to be a pack maker my self. But I am definately not trying to make changes like this isn't aluminum anymore lol. I am simply trying to get rid of the fact ever mod NEEDS to have their own version of an ore. Like do I really need 4 different versions of copper?! lol. Maybe I am going about it the wrong way but I start off with if the particular mod has a disable this ore from generating option in their config, I do that but that doesn't remove the use of that ore or its children like ingots, dust, nuggets and so on from recipes. When counting up to over 100 mods thats a lot of recipes to edit. Finding the method of removing ore dictionary entries in Mine Tweaker was a blessing in a way because after removing the ore generation (if I could) all that was left was ignoring it all together from every recipe that called for that particular ore (or child) in it. With IE I had no real way of doing that because of the JEI changes mentioned in relation to this bug. Maybe I'm being too picky when wanting only one kind of the same item showing up in the world as well as recipes but little things like that I believe help make the pack nicer and cleaner? I don't know why you would think you would be held liable for anything outside of your code, after all its only a game, how can anyone claim you damaged their life lol. Being a mod developer maybe you can steer me in a better direction as to how to properly remove all these "duplicates: and the recipes that relate to them easily with some other method

**Comment by XFactHD** [comment]
The reason that every mod needs its own version of an ore is that this way every mod can stand on its own feet. If we started to all depend on mods that only add materials we would have the same problem again because one mode would depend on Substratum and the other one on Base Metals.

**Comment by BluSunrize** [comment]
You don't unregister for that. You disable the oregen for all but one. 
Because in the end, even an "undesired" ingot can still be used in a recipe. 
That's the whole point of the Ore dictionary, that you /don't/ have to remove all other ingots. 
Sure it's a bit weird when that new machine you built suddenly outputs other ingots, but users are used to that. That's why StorageDrawers can auto convert. My suggestion is: Take it as it is, don't try to unregister metals. 
I can totally understand doing it to not allow blood to be used as slime balls (TCon) since that is an odd balance to some, but metals are specifically meant to be interchangeable.

**Comment by xSparky911x** [comment]
Alright cool. I really appreciate the explanations and the help. I also appreciate your patience in helping me
