### ISSUE TITLE
[Imcompatibility MOD] Extra utilities mod X Immersive Engineering v0.7.7

### ISSUE THREAD

**Issue by DinhoGameShow** [BluSunrize/ImmersiveEngineering#1862]
I and a group of friends, we are playing Minecraft in version 1.7.10, and making use of the mod Immersive Engineering v0.7.7.
However, it presents an incompatibility of RF transistors due to the existence of the Extra Utilities Mod, making them both inoperative.

I wonder if there's anything I can do to make it work again?

Note: I do not speak much English so I made use of the translator. Also I did not get an answer from the forum regarding this specific problem, so if it already exists I apologize.

Thanks

**Comment by mindforger** [comment]
minecraft 1.7.10 is not officially suported anymore!
if you have a crash, please paste it on pastebin.com and link it here

**Comment by chaos234** [comment]
As @mindforger has written, pls provide any crash report but from what I have read this seem a non-crash related problem.

If you can, make a short video (must not contain any audio, demonstrating is quite enough) so that it can be reproduced. In addition to this you should provide the full modlist which can be made simply by making a screenshot of your mods directory and uploading it here directly.

Without the mentioned things above, nothing can be checked @DinhoGameShow but if you can provide it, I can try to reproduce it and **eventually** fix it by sending a PR to this repro so please be pacient.
