### ISSUE TITLE
[Bug] Ticking Block Entity with Embers mod

### ISSUE THREAD

**Issue by Voxel-Friend** [BluSunrize/ImmersiveEngineering#1864]
Cross posting this with Ember's Github.

Crashlog: https://gist.github.com/Voxel-Friend/e4ca8c774175b54602830acf9bb6c7aa

How to recreate:
1: Build Embers' Reservoir Multiblock, complete with Machine Accessors, Caminite Rings and Mechanical core
2: Fill Multiblock with creosote from IE using any method.
3: Connect Ember's mechanical pump to Ember's Reservoir.
4: Connect to pump Ember's fluid pipe.
5: Connect to pipe IE's Fluid pipe.
6: build IE's Assembler Multiblock to where fluid port faces IE Fluid Pipe.
7: Apply redstone signal to mechanical pipe from step 3
8: ???
9: LOSS

Embers Issue https://github.com/RootsTeam/Embers/issues/93

**Comment by mindforger** [comment]
did this happen while standing beside it or when leaving the area? is everything chunkloaded?

from a first guess without knowing if the pump fails somehow i would say this is an pipe from an unloaded chunk

**Comment by Voxel-Friend** [comment]
Sorry for not replying. No chunk loaders were used and it happened while standing beside it, looking away (if that matters.)

**Comment by Voxel-Friend** [comment]
*Timid bump*

**Comment by BluSunrize** [comment]
My apologies for not looking into this earlier. It kinda went under.

**Comment by Voxel-Friend** [comment]
:D

**Comment by Flabort** [comment]
On one hand, the block entity being ticked that seems to have caused the crash does seem to be the Embers Mechanical Pump. On the other hand, all the other mentions of either mod in the crashlog do seem to point at Immersive Engineering before pointing at Embers, and the IE team have gotten right on the task of investigating.

My uninformed guess (as neither a mod developer or someone involved in the maintenance of either mod) based on the fact that you have an Embers fluid pipe inbetween the pump and the IE pipe, and "TileEntityFluidPipe$PipeFluidHandler.fill" from the IE side of things, is that the IE pipe is seeing the entire Embers Fluid-Handling Multiblock (pipe, pump, etc) as a valid place for fluids in it's pipe to go - because the pipe can hold fluid - and it's trying to put the fluid into the muliblock controller (the pump), only the pump can't hold fluid because it doesn't have a tank.

EITHER THAT, or the fluid pump is seeing the IE pipe as a valid place to put liquids, but once liquids reach that pipe, there's no-where else for them to go and the program gets confused.

It really depends on whether either style of pipe can store a buffer of fluid between ticks, being pumped in one direction or the other.
