### ISSUE TITLE
[Suggestion] Flip powered lanterns upside down with Engineer's Hammer

### ISSUE THREAD

**Issue by omega025** [BluSunrize/ImmersiveEngineering#1870]
Title says it all. I would love to have the ability to flip the powered lanterns so that the copper wire contact points are on the top rather than the bottom for when using lanterns on ceilings.  Since the Engineer's Hammer doesn't currently do anything to the lanterns (as far as I've been able to determine), this method seems to be available and would be logical given the tool's other rotation functions.

**Comment by mindforger** [comment]
wall mounted would also be an valid option in this case ... but using the hammer is not the perfect choice, it should depend onto which face you place the lamp

**Comment by omega025** [comment]
Or perhaps both?  A lamp's orientation could be determined by the surface it is placed on, and the Engineer's Hammer could allow a player to flip it if they change their mind, instead of needing to break it, or if the required placement angle would be difficult to get to.

**Comment by mindforger** [comment]
i somehow can sense how blue is chewing on the table while reading this, because he would have to adapt all orientations for the mounting points of the cables XD 

what do you think should happen to the cable attached to the lamp when hitting it with the hammer ... break replace would be much more friendly coding wise in this case

**Comment by XFactHD** [comment]
I like the idea of this but in my opinion the rotating with the hammer doesn't make much sense because if a lamp is hanging from the wall and you turn it around, the holding bracket (or whatever you want to call it) would point away from the wall and the lamp would float. I also have to agree with @mindforger, the coding would most likely be really complicated.

**Comment by omega025** [comment]
Would the coding be as complex if the rotation was restricted to up/down flipping?  I feel like the current lantern model might look odd sideways, and the current wood and metal wall mount blocks provide a plausible wall mounting solution already.

**Comment by BluSunrize** [comment]
@mindforger pls. Blu without the e. x3

I can look into this. There is probably a really good reason I never did this before, but I can't remember. I'll investigate the matter and see if I can either remember why I never did it in the first place, or I'll actually add the feature. =P

**Comment by mindforger** [comment]
... stupid brain autocompetion ...
