### ISSUE TITLE
LV Wire Coil wont craft in enderio crafter

### ISSUE THREAD

**Issue by jrwizzard** [BluSunrize/ImmersiveEngineering#1873]
duplicated on enderio issues list

The 'LV Wire Coil'(immersive engineering) will not craft in the EnderIO Crafter.

**Comment by jrwizzard** [comment]
playing skyfactory 3 1/27/2017

**Comment by BluSunrize** [comment]
Could you please provide pictures? And Version numbers? And overall read the contribution guidelines?

**Comment by jrwizzard** [comment]
umm no? free bug reporting isnt enough? go fuck yourself, I'm not going to
do your job for you. The date and game played gives the version numbers.

**Comment by KnightMiner** [comment]
No, it does not. There are multiple versions of the SkyFactory 3 pack, including the latest Beta, the latest Release, and the one that is neither. Free bug reporting is worthless if you fail to provide details to help us discover if your issue exists, as many reported issues are either from old versions or are a misunderstanding of the user.

And before you resort to name calling again, don't forget BluSunrize is providing you free entertainment.

**Comment by BluSunrize** [comment]
I'm sorry that my inquiry about the issue has left you offended.
I was merely hoping to acquire more information on the matter, as well as to encourage you to make use of our very helpful contribution guidelines. A lot of devs have those these days, and they do make our job a lot easier.
Due to the lack of a provided version number this issue is quite difficult to investigate, hence why I asked for your assistance on the matter. Screenshots are exceedingly helpful in these situations.

I once again apologize about my lack of capability to "do my job", and I shall now promptly proceed to "go fuck myself".
Have a good day sir.

**Comment by Jezza** [comment]
Free bug reporting?
Wow... what a service to provide...
It would be almost like having an entire mod for free....

The world we would live in...

**Comment by K-4U** [comment]
![apply](http://www.k-4u.eu/burn.jpeg)

**Comment by mindforger** [comment]
i would have answered "haven't had my paycheck from you yet, won't fix" XD

**Comment by BluSunrize** [comment]
Can you twats not for once appreciate my sarcasm and not ruin a perfectly civil end to an issue report?

None of those were necessary, for crying out loud. You're just making it worse by being rude again.

**Comment by jrwizzard** [comment]
lol

Definitely no lack of entitlement in this click. While I do appreciate the
results of the creator(s) efforts in this mod, it is still just a mod, more
or less a resume to bigger and greater things. Perhaps I replied a little
too over zealous, but github.com does make money off all of this. The game
and date was to refer to the release as of that date. Good luck on your mod
and your resume(or not).
