### ISSUE TITLE
[1.10.2] Pump turns non-infinite liquid source blocks into cobblestone

### ISSUE THREAD

**Issue by omega025** [BluSunrize/ImmersiveEngineering#1874]
With my current project I'm using ImEng with the Hatchery mod, and have a setup that converts chicken manure drops into liquid fertilizer to be stored in a tank.  An assembler combines manure blocks with pumped-in water to create buckets of liquid fertilizer, which a dispenser then places underneath a pump, and the pump transfers the liquid fertilizer into a tank.

It works, but only once - when the dispenser places the liquid fertilizer the pump successfully transfers it into the tank, but instead of being replaced with air, the liquid fertilizer block underneath the pump is replaced with cobblestone, blocking the dispenser and pump.

**Comment by malte0811** [comment]
That is intentional, it prevents lag when e.g. pumping lots of lava from the Nether. You can disable the cobble placing by shift-rightclicking the upper block of the pump with a hammer, you should get a warning about potential lag due to fluid updates which should not be a problem for the setup you described.

This is stated in the manual as well, but it claims that a wirecutter needs to be used, this is incorrect and should be corrected.

**Comment by omega025** [comment]
Good catch, thank you @malte0811. Leaving this post so the manual's outdated reference to using wire cutters can be corrected.
