### ISSUE TITLE
Crash after clicking blueprint in automated workbench

### ISSUE THREAD

**Issue by sethlesser** [BluSunrize/ImmersiveEngineering#1875]
I accidentally clicked the graphite electrode blueprint in an automated workbench and it crashed my game and continues to crash my game every time I load into the world. I would love to fix this as I was getting quite attached to the world. 
Crashlog: http://pastebin.com/bwHJ5DNa
If anymore info is needed I will try to provide it.

**Comment by BrisingrAerowing** [comment]
What Java Runtime are you using? If you are using OpenJDK, then that is the issue here, as that [does not have JavaFX](https://gist.github.com/androidfred/bc64da9e6a355b984d37439ed63ae16b).

OpenJDK users can install OpenJFX to get these classes, although OpenJDK 8 is needed.

I would still recommend installing Oracle JRE instead, as Minecraft does not officially support OpenJDK.

If you ARE using Oracle JRE, then I don't know what should be done.

**Comment by sethlesser** [comment]
*Java **Version 8 Update 121, It loads just a tiny bit of the world, just
enough for images to start showing then it crashes with the crash log*

On Sat, Jan 28, 2017 at 3:42 PM, Brisingr Aerowing <notifications@github.com

**Comment by sethlesser** [comment]
Never mind, was running 1 version outdated and this problem was fixed in the newest version. Thank you for the assistance.
