### ISSUE TITLE
Fatal Error reloading CraftTweaker recipes

### ISSUE THREAD

**Issue by Eufranio** [BluSunrize/ImmersiveEngineering#1882]
When I use `/mt reload`, reloading the minetweaker (CraftTweaker version) scripts, it kicks me from the server with a Fatal Error:
Log: https://hastebin.com/rarudofomu.rb

Not sure if it should be reported here. If it's in CraftTweaker's end, please let me know.

**Comment by BluSunrize** [comment]
Could you please provide a paste/hastebin of your MT script as well? That could help figure out if a certain recipe change causes this

**Comment by Eufranio** [comment]
Yes. That's ALL in the script:
```
<ore:dustUranium>.remove(<immersiveengineering:metal:14>);
<ore:ingotUranium>.remove(<immersiveengineering:metal:5>);
recipes.remove(<immersiveengineering:metal:5>);
recipes.remove(<immersiveengineering:metal:14>);
```

**Comment by BluSunrize** [comment]
*grmph*

I assume that they manual pages generate while Minetweaker still accesses recipes or something.
Honestly, I'd rather you take this up with @jaredlll08 because I hate dealing with concurrent modifications.
Plus, I feel like my code really shouldn't /need/ synchronized access there. But maybe I'm wrong.

Thoughts, anyone? @malte0811?

**Comment by jaredlll08** [comment]
My thoughts are that if you use `/mt reload` you lose all rights to support (at least for Crafttweaker)

**Comment by BluSunrize** [comment]
Uuh? Explain?

**Comment by jaredlll08** [comment]
Simple, if a user cannot reproduce a bug without running `/mt reload` then I can't help them, since it has to do with other mods not expecting their stuff to be changed during runtime, however at the same time I cannot remove the command because I was nearly burnt at the stake the last time I even suggested it.

At the end of the day, a user(player in this case) should NEVER have to run `/mt reload` when their game is running.

**Comment by Gunner76th** [comment]
I am having the same issue here https://github.com/BluSunrize/ImmersiveEngineering/issues/1929
