### ISSUE TITLE
Extreme Lag from Wooden Posts

### ISSUE THREAD

**Issue by SuperSaiyanSolar** [BluSunrize/ImmersiveEngineering#1903]
This is a bit of an odd issue, but a few people on a private server I play on have been having a serious, game-breaking issue from Wooden Posts.

While I do not have this problem personally, multiple people on this server have said that, whenever a Wooden Post is placed, their FPS drops to an absolute 0, and they have to force-close the game if the block is not removed.
What makes this issue strange is that I have not experienced it myself, but multiple others have. The only difference between our clients is the amount of RAM allocated (Myself having 6GB, the others having 4 or 5GB).

The thing is, we've never had any issue running things on as little as 4GB, so I have no idea what's happening here other than a possible memory leak or something of the like. We love this mod dearly, and any kind of fix or help would be greatly appreciated.

(Please note that this is not the only mod we're using, but as I said- 4GB is usually more than enough for the game to run without issue.)

**Comment by malte0811** [comment]
I have an idea for a potential cause of this, I'll take a look in a couple of hours.

**Comment by malte0811** [comment]
My idea was wrong, only thing I found was that `ClientProxy.removeStateFromConnectionModelCache` was completely broken (fixed in 577afbc03731abf8bc0827fbc8cc19967d817fee). @SuperSaiyanSolar I have a couple of questions:
1. What pack are you using? Is it on Curse or somewhere?
2. You say that you don't get the lag. Do you mean that you can place a post in your base and be fine or do you mean that you can get close to a post that causes lag for others without problems?
3. Is there anything in common about the players experiencing the problem that differentiates them from you except for the RAM limit? Both in-game (e.g. all are using a certain item or have unlocked something in some mod) and "computer-wise" (e.g. all are using Linux, OpenJDK or something).
4. Do you get the lag as well if you lower your RAM limit to 4 GB?

**Comment by SuperSaiyanSolar** [comment]
1. It's a completely custom modpack for myself and a group of friends, but I can post the full list if you need it.

2. I can place a post myself or go near a post someone else placed and have no issues. No matter what, the posts do not generate lag on my end.

3. There is no difference whatsoever. Even when there are no enhancements from other mods, the lag persists. The only difference is the amount of RAM allocated.

4. After a quick test, I can confirm that RAM is the issue. I don't believe the person who was claiming to have 5Gb allocated actually did, because it seems just fine when I use 5. 4GB, however, is almost an immediate game-breaking lag spike. Any other structure renders just fine and causes no lag, though. So it's odd that something as simple as the Wooden Post causes such a massive RAM issue. The modpack usually runs just fine on 4.

Is this a bug, or are we really that close to the border of RAM? If it was any other machine I would understand the lag, but... a Wooden Post..? It seems like it could be an issue to me.

**Comment by beeschurger** [comment]
Im getting the same issue with extremem lag from any kind of post (wooden, aluminium, ore steel) and I would very much like to see this issue solved

**Comment by mindforger** [comment]
Then make a new issue and follow the guidelines please, necro posting a “same here“ without any details helps nobody ;)
