### ISSUE TITLE
Make the mining drill worth using please

### ISSUE THREAD

**Issue by Waisse** [BluSunrize/ImmersiveEngineering#1905]
It uses bio-diesel and take durability damage that can only be repaired in an anvil with increasing xp cost. It doesn't take enchants. The only good feature is the single block mining with shift and underwater mining. I can't be bothered to use it as my multi-tool in my base or my hand mining solution because it take too much hassle to maintain it.

I suggest to make the drill head take enchants, or add an easier way to maintain the drill : maybe add an actual lubrication tank that prevent durability loses as long as it's not empty. Or add an easier way to repair the drill head.

**Comment by BluSunrize** [comment]
Easier way to repair? Gladly. I'm open to any suggestion that isn't crafting or an automated anvil.

Enchantments? No. This mod distances itself from magic for the most part (exceptions being Botania and Bloodmagic compat)

I realize it's not as glorious as a Tinker Tool, but that's really not its appeal either. It's hard to find a balance and yet make something appealing.

**Comment by Waisse** [comment]
What about lubrication to prevent/greatly reduce durability damage ?
Terrasteel/manasteel drill head that uses mana to repair ?
Demon will drill head ?

**Comment by VT-14** [comment]
How about a sharpening kit or machine?  Something that uses RF or a cheap disposable item to 'repair' a tool.  I assume the durability is to say "the drill head is dull."  Possibly limit the number of times you can sharpen a drill head without adding extra material (vanilla repair), and allow use on vanilla (or all) tools if you want to go that far.

**Comment by the-realest-stu** [comment]
What if instead of breaking, the drill heads would become "broken" and useless. Broken drill heads could be recycled in an arc furnace for 80% or so of the metal used to craft it.

**Comment by LiEyWe** [comment]
I like the way you have to repair your drill now. But in my opinion, the steel drill head should last longer than the fuel in the upgraded tank size. I think you have about a third of fuel left when the drill head breaks.

**Comment by enricotagliavini** [comment]
Actually I like the Mining Drill even more than the tinker tools for excavation. No offense meant to tinker tools, they are great. However the mining drill last longer and steel is cheaper than cobalt / ardite. The mining drill is also very fast. To mine the ores I still use tinker tools because of the fortune enchant, but that's it. Maybe adding an upgrade with the same effect of luck (and stack-able to get the three possible levels) would be an idea to improve the mining drill. Maybe a pneumatic blasting percussion or a sonic rig.

The durability of the steel head is not too bad (yeah a bit short maybe also considering the XP cost to repair it, but not useless). Maybe a way to replace the head on the field (without an engineering workbench) would help, you can make a few heads and change them on the go. A sharpening kit can also do, I prefer the idea of replacing the head because it feel a bit more realistic, but I would not freak out for a sharpening kit.

**Comment by bookerthegeek** [comment]
I think a general increase in the durability of the drill head would be enough. Maybe enough to last two full inventories of mining ore before it becomes broken. Then the current system to repair it.

**Comment by malte0811** [comment]
Just as a note: the drill was taking more damage than intended, see #1934 (3 instead of 1 per "extra block").

**Comment by bookerthegeek** [comment]
True. And thinking about it, actually I feel a different measurement would work. Leave everything else alone. The non enchantability is fine, even the repair mechanic is fine. Having to return to base is fine.
* `Durability = X * 3`
* `X = Expanded fuel tanks worth of mining`

That right there would make it worth it.

**Comment by BluSunrize** [comment]
Malte fixed the drill as described above, so I'll close this. New reports after the release of Build 58 are welcome.
