### ISSUE TITLE
 Exception in thread "Immersive Engineering Registry Iteratoration Thread" 

### ISSUE THREAD

**Issue by Vashidu** [BluSunrize/ImmersiveEngineering#1921]
Everytime I stop my client or server, im getting this after the server shuts down, unsure if really a bug. [https://gist.github.com/Vashidu/c1eb20128417d9cdc7ee2578603e18e8](https://gist.github.com/Vashidu/c1eb20128417d9cdc7ee2578603e18e8)

**Comment by malte0811** [comment]
This most likely means that some mod in your pack is creating an insane amount of recipes. IE looks at all of those recipes to determine what item should smelt into what in an arc furnace when recycling items (e.g. an iron pickaxe into 3 iron). Since the thread isn't finishing its work in this case, the recycling recipes won't be added either, so you should just disable arc furnace recycling in the config. Doing so won't hurt in your case, it might even improve performance since the thread doesn't have to run.

**Comment by mindforger** [comment]
@malte0811 maybe add an shutdown hook to kill it properly with an log message why it did not finish/where it infini-loops

**Comment by BluSunrize** [comment]
well I assume it dies within the thread. It's already pretty safeguarded against infinite loops, but I assume it's just chewing through memory due to recipe amounts. Unfortunately, I have *no idea* what a healthy number of recipes is and what isn't, so it's really hard to find a condition for that :/
