### ISSUE TITLE
Question about the Potion Fluid

### ISSUE THREAD

**Issue by BrisingrAerowing** [BluSunrize/ImmersiveEngineering#1931]
How exactly is one supposed to get a potion fluid? I cannot find anything in the manual about it, and clicking potions on tanks doesn't work either. I play in creative, so commands are an option.

**Comment by BluSunrize** [comment]
Actually, there is something in the manual about it. Squeezer, page 2:

> The most common uses for this machine are [...] the creation of potions from water and their various ingredients.

Water + Netherwart to Akward potion, proceed from there.
Clicking bottles on tanks won't be possible, I'm afraid, without very explicit special casing, so I'd rather not do that.

**Comment by mindforger** [comment]
so it is possible to make potion fluid and bottle it but not the other way around? How about an recycling machine? Same principle like the recycling recipes from the arc furnace. 

It accepts items and tries to reduce them into their crafting ingredients (as long as it has only has fixed/non-replaceable items in the recipe or is a potion which can be converted to liquid and dropping the empty flask ... or consume it ... but we want to be eco-friendly aren't we ? XD )

**Comment by BluSunrize** [comment]
Well it doesn't work like that Mind. Bottling is only possible in the bottling machine and only because I wrote a specific recipe for it, that assigns the potion type to the item.
To do this by rightclicking a barrel I would have to specialcase my barrels+tanks to check on interaction for the Bottle and check if the fluid is a potion fluid. Sure, that would work but that would then *only* work on IE tanks, and on no other mods.

Similarly goes emptying. Special case the barrels and tanks or it'd need an unbottling machine to reverse the process .-.

**Comment by mindforger** [comment]
oh okay i thought you actually implemented potion as fluids, sorry then this is really special case then :)

**Comment by BluSunrize** [comment]
Well I did implement them as fluids. But there is no vanilla "hook" for that. It's a custom fluid that stores the PotionType in the FluidStack's NBT data =P

I guess I could look into using the squeezer to get the fluid back out...

**Comment by mindforger** [comment]
i can imagine that would help :) thre are surely a few dudes spawning witches ... including me when using blood magic .... and all those potions need a use XD
