### ISSUE TITLE
Homing projectiles in turrets & drill head durability

### ISSUE THREAD

**Issue by Jhanter** [BluSunrize/ImmersiveEngineering#1934]
If you use Homing projectiles on turrets, these try to attack the player if they can.

The drill head when is used on a single block (with shift) take 1 durability, but, if you use in a 3x3 area, uses 27 (or some like that), and in a 2x2 10 durability . i don't know if is intentioned, but i report because i think is a little expensive.

Sorry for my english 😅

**Comment by malte0811** [comment]
I'll take a look at the second issue in a bit, I have a fix (well, I still have to test it) for some manual code IE doesn't use (but that is useful for IndustrialWires) as well.

**Comment by BluSunrize** [comment]
If you have the second thing covered Malte, I'll address the first thing:

Don't use them in turrets =P
Homing Cartridges are loyal only to their user. Just as a turret will gun you down when aiming for something behind you, homing cartridges will absolutely target you. Turrets are powerful, but ruthless, this is absolutely intentional =3
