### ISSUE TITLE
[feature suggestion] Powered lanterns on/off switch and wiring integration

### ISSUE THREAD

**Issue by Liiw** [BluSunrize/ImmersiveEngineering#1958]
Hello!

I love the mod and the possibilities it brings with the concept of wires and multiblock structures. I have a couple of suggestions.

I was using the powered lanterns and noticed that it stays lit througout the day-night cycle. While this is good for keeping out mobs from my base since I have darker corners here and there, it would be awesome if I could have a way to turn the light off (during daytime) while keeping the mob prevention function. For this, the lantern could accept redstone bundled signal (one color signal for light, another for mob spawn prevention), configurable via, for example, a GUI when rightclicking it with the hammer. 

The second idea is related to the first: Redstone-integrated power wires. These would be able to carry power as well as RS bundled signal. They would require special connectors and relays. These wires could be manufactured in a specialised multiblock powder coating station in which a wire (LV, MV or HV) is coated with redstone dust similar to electrostatic powder coating. These coated wires would also have to be cured in a furnace or maybe even a multiblock curing station. The powder coating station could be also used for coloring other items/blocks in the game. Along with the RS power wires there could be some sort of modulator-demodulator blocks to integrate and separate the redstone component from the power component.

Similar to the RS suggestion, it would be great if there were OpenComputers telecommunication wires. 

There could also be an "über" cable, containing within it many different functional cables (power, RS, OC, perhaps even ME network from AE2) similar to how the conduits from EnderIO function. For this cable, separate connectors, relays, modulation/demodulation units (or adaptors) would be required. Also either a separate multiblock assembly station to manufacture the über cable, or integrate some sort of module blocks to the assembler which permit it to assemble this cable.

Please let me know what do you think about these ideas.

**Comment by BluSunrize** [comment]
I'll try to file this into three ideas:
Lanterns at daytime
Redstone via powerwires
Other systems via wires
Bundled Wires

The first one is somewhat a thing already. If you use a vanilla light sensor, along with a redstone breaker, you are able to have the power for the lights cut in the daytime, therefor turning them off.
However, I disagree with them keeping their mob-spawn prevention, since this is the reason for their powerdraw. Light is effectively "free" in Minecraft, its the spawn-prevention that makes them require power, and I wish to keep the prevention+light associated, so I won't allow them to flatout block spawns when they're no on.

Redstone via powerwires would, somewhat be possible, I'm not very fond of the idea however. I do enjoy the aspects of having different wires for different purposes (we'll the to that for point 4).
Lore wise, I will rationalize this by the original concept of Redstone Flux (and by extension Immersive Flux) as done by KingLemming: http://teamcofh.com/docs/redstone-flux/a-primer/
RF is basically a mass of resonant waves and the energy contained. Since at it's core, its energy signature matches that of redstone, combining the wires would probably lead to interference.

Other systems have been attempted to be transferred over wires. I believe the Zetta Industries addon features wires to connect OC computers, the (no longer maintained) Immersive Integrations introduced the original redstone wires, and also featured ME wires for AE2, and the Industrial Wires mod by Malte has an array of wires for IC2 power transfer.
I can get behind some of these, Industrial Wires is basically the best approach to IC2 compat which doesn't require power conversion, and Redstone Wires were so awesome that I asked Unwritten for permission to put them in core IE, but some things, like ME2 feel too "digital" to be using what is supposed to be "analogue" wires. As such, I'm not fond of just doing *everything* with wires (hence the decision to do "normal" fluid pipes rather than wire-like hoses).

Lastly, bundling wires like EIO conduits. I touched on this for redstone coating already, and I'll expand on this: I dislike the idea. To me, back in Minecraft 1.2.5 to 1.6.4, it was a thrill to automate things and build big and impressive looking houses, mansions, factories to fit all the stuff (especially my piss-poor Buildcraft piping/TE Ducts). I've never gotten that same enjoyment out of EnderIO, because it's ability to put every connection (item, power, fluid) into a single block kinda took away from the complex and very visible pipework that I'd grown to enjoy. As such, IE tries to keep all three key in- and ouputs very different from eachother. Conveyors are entity-based item transports, pipes are instant, but small-dosed, fluid transmissions and power runs though non-corporeal wires, kept only linked to blocks through its endpoints. All of these are significantly different, and all IE machines generally feature its in- and output ports in different spots to make all the connections to it a bit more messy, yet factory-like.
I wish to keep with that idea, and therefor don't see myself making any universal, or bundled, wires.

**Comment by Liiw** [comment]
Thank you for your response! Fair enough, I understand that.
