### ISSUE TITLE
[Suggestion] Glassed Conveyor Belts

### ISSUE THREAD

**Issue by ToadsworthLP** [BluSunrize/ImmersiveEngineering#1967]
It can be annoying to walk besides your conveyor belts and collect the items it's currently transporting, so I suggest adding variants of the conveyors that are surrounded by glass to prevent that. On the visuals, it should just be a conveyor belt with a block of glass around it that is open where the belt is connected to others. Also, that would look great with colored glass and would be useful for color-coding (conveyors with different glass colors don't connect and look nice) your factories =D

**Comment by mindforger** [comment]
i would propose another solution, sticky conveyors

craft 8 conveyor belts around a slimeball to make them sticky

i have no idea how the lootmechanic is working exactly, but could you respect crouching close to a belt as a mechanic to still be able to loot stuff of the belt?

**Comment by BluSunrize** [comment]
I wish it was that easy. It's a downright pain in the ass to make players not pick up items.
Making conveyors immune to magnets was already a lot of special casing (although thankfully it works for the most prominent ones now, Botania, Bloodmagic, EIO).

Colourcoding is also a thing already, you can just rightclick conveyors with dye.
Having them not connect due to dye is for one, a lot more conditionals on rendering so worse for performance, and also entirely pointless. Conveyors currently only "connect" if you place them in the respective directions to do so. There is no merit to block any connections, since they can't transfer sideways anyway.

**Comment by TehStoneMan** [comment]
Just a thought regarding this. I assume you have the actual item on the conveyor belt, and moving the item along it. An alternative could be rendering a "fake" item instead (TESR ?), and passing the real item from conveyor to conveyor behind the scenes.

Done right, it won't look any different to the player, but avoid the issue of items being picked up entirely.

**Comment by BluSunrize** [comment]
That defeats the purpose of conveyors and their use however.
They use Entities since that doesn't require internal tracking. It simply moves any entity on top.
Plus having a TESR render it so noone notices a difference is basically impossible. The transitions would be jarringly obvious.

**Comment by mindforger** [comment]
jsut for testing purpose, did you try to reset the internal drop timer each time you move them? as far as my knowledge goes, player can only loot itmes of certain age to prevent them looting right after dropping ?!

**Comment by KnightMiner** [comment]
Part of the problem with that is age is used to keep track of the animation as well, items will freeze in their rotation.

**Comment by mindforger** [comment]
gnah okay .. but it was worth a shot ... nice to know btw. thx for info

**Comment by laz2727** [comment]
Well, these items are on the belt anyway, they don't need to rotate.

**Comment by XFactHD** [comment]
The EntityItem has two timers, one for the age and one for the pickup delay. As there is a method to set the pickup delay to 0, there should also be one to set it higher.

**Comment by ToadsworthLP** [comment]
I just forgot that your conveyors don't connect sideways anyways, so yeah, the don't connect rule is entirely pointless. But still, glass-coated pipes would look so nice AND be useful, though it sounds very hard to do. Can't you just copy-paste the part that renders items in BC's pipes or at least look how it works there or isn't it that easy?

**Comment by laz2727** [comment]
Can't you just increase the hitbox by 3-4 aabbs? :P

**Comment by BluSunrize** [comment]
@ToadsworthLP
 As I said, it would look different and the whole point of conveyors is that they use entities.
So no. I can't.

 @laz2727
Despite that being an ironic suggestion: No actually, I can't. Minecraft doesn't play well with bounding boxes bigger than the block. That's why multiblocks need "dummys" or "slaves" to simulate the bigger hitbox

**Comment by ToadsworthLP** [comment]
Ok, the grated conveyors you showed us on twitter count, too. I think I can close this now as we get that feature now (just with a different texture) =)

**Comment by BluSunrize** [comment]
it'll allow other blocks to be put on as well, like Glass.
And yeah, Morve requested it mid Februrary. Just took me a while to get to it again.
