### ISSUE TITLE
Potion Fluid Not Working

### ISSUE THREAD

**Issue by Faqueeze** [BluSunrize/ImmersiveEngineering#1974]
Hi,

I am using Immersive Engineering 0.10-57 for minecraft 1.10.2 with forge 1.10.2-12.18.3.2185
I am using no other mods.
I noticed several issues with the new potion fluid:
- Missing texture, pink and black checkers goo.gl/FoZHIn
- When any potion is brewed in the mixer, the texture in the mixer is a similar checkers pattern
- The only way I could transfer potion fluid into the bottling machine was by placing a fluid pump on top of a metal barrel with a potion goo.gl/OOeroX 
- If a bucket is filled in the mixer, it does not have any specified potion. A glass bottle can not be filled at all. goo.gl/MHnqNi 

If you need any more information, let me know.
Thanks.

**Comment by BluSunrize** [comment]
Buckets not being properly filled is a Forge bug. I have reported this to them already, see here:
https://github.com/MinecraftForge/MinecraftForge/issues/3757
There is a fix in the works, but it's not merged yet.

The texture issue is quite puzzling however.
Could you provide a list of the mods you are using? The easiest way to do this would be to create a debug crash, by holding F3+C and then putting the log on pastebin.

**Comment by Faqueeze** [comment]
Here is a screenshot with the texture issue in the mixer: goo.gl/ow1fUL. The blue and black is awkward potion and mundane potion, the pink and black is potion of swiftness.
Crash log: http://pastebin.com/Re2um925

The bottling machine will also not fill glass bottles with potions.

**Comment by omega025** [comment]
Can confirm the missing textures, and the inability of the bottling machine to fill bottles with potions.

**Comment by malte0811** [comment]
Happens in my dev env as well, I'll take a look now.

**Comment by BluSunrize** [comment]
It works fine in mine, that's the weird thing... .-.

**Comment by malte0811** [comment]
The missing texture is fixed, the other things were working for me. When you tried bottling a potion, did you use the "default" one that can be put into buckets or a proper potion? The former not working isn't really a bug since I don't think there is a "missing NBT" potion.
The proposed fix for the bucket issue was PR'd for the 1.11 branch BTW, so I don't think this will be fixed in 1.10. I had a look at the PR'd code, using ASM it would be possible to partially fix this (It would probably work if you don't use any machines from other mods to get the fluid into the bucket, it may be possible to fix some of those cases by "dynamic" ASM, but that sounds a bit dangerous to get wrong).
@BluSunrize you have a lot of unpushed code AFAIK? Does that code by chance add placable potion fluid blocks? If it does, that would explain why it is working for you, registering those blocks automatically registers the textures.

**Comment by BluSunrize** [comment]
I have a boatload of unpushed code, but it's all farming, and compat stuff. Placable potions aren't planned because a fluid with a TileEntity would be required and that sounds like a terrible idea.
So yeah, no, I don't have a block assigned to it and it still worked fine for me .~.

As for the fix, I will approach mezz to see if there is 1.10 plans for it, but I'd rather not bring ASM into it, because I don't want my head ripped off again by the Forge team, kthx.

**Comment by Faqueeze** [comment]
I used proper potion in the bottling machine, but when it filled a bucket, it gave me a bucket of the "default" potion.

Also, couldn't placable potions be added where it just gives an entity the corresponding status effect on contact, as biodiesel, ethanol and creosote already do? (Oh, a tiny bug, the ethanol only induces a second of nausea on the player, which isn't enough to have the screen distortion effect)

**Comment by BluSunrize** [comment]
Yeah but you kinda need to know *what* potion you placed to apply the effect. And given the fact that it's all the same fluid, yet there is a possibly endless amount of potions, that extra data of what *specific* potion it is needs to be stored, most sensibly in a TileEntity. And a fluid with a TileEntity sounds like a rather memory inefficient idea.

**Comment by hron84** [comment]
Just a wild idea: is there no way to store potion type in a NBT tag in the placed fluid block?

**Comment by malte0811** [comment]
Only using TileEntities. Since fluid blocks 'duplicate' infinitely, this would probably be a bad idea even when using non-ticking TE's.

**Comment by BluSunrize** [comment]
@hron84 at least read what I said =P
> that extra data of what specific potion it is needs to be stored, most sensibly in a TileEntity.

If it could be stored in a block, we wouldn't have the discussion.

Plus, malte fixed the core issue, so I'll be closing this.

**Comment by hron84** [comment]
@BluSunrize I assumed NBT tags could be stored in blocks. Good to know, thanks.
