### ISSUE TITLE
[Possible Bug][0.10-57] 2 wires in a connector

### ISSUE THREAD

**Issue by Jhanter** [BluSunrize/ImmersiveEngineering#1975]
If you link 2 or more wires in a stack and split it, and attach a every single cable to an other connector you can connect multiple wires in a single connector.
I hope I made myself clear 😅

http://imgur.com/a/qcRaz

**Comment by mindforger** [comment]
that was a thign in the past already with HV connectors, where did that fix go ?

**Comment by malte0811** [comment]
I guess you mean #919, which is probably one of the fixes I made in 1.7 after Blu started making 1.8. I think I gave up porting those fixes after it turned out that a lot of the issues didn't even exist after the 1.8 changes. I will re-implement my original fix (and any additional fixes needed for this specific problem) and PR that, I already have a fix for #1953 that I need to PR as well.
