### ISSUE TITLE
[Suggestion] Make core samples placeable in world as stone markers.

### ISSUE THREAD

**Issue by calloatti** [BluSunrize/ImmersiveEngineering#1980]
It would be great if core samples could by placed in world by right clicking. They would stand as a stone marker 2 or 3 blocks high with the texture of the in-hand core sample.

For reference:

https://previews.123rf.com/images/papabear/papabear1201/papabear120100007/11977460-Stone-mile-marker-on-a-hiking-jogging-trail-Stock-Photo-mile.jpg

https://upload.wikimedia.org/wikipedia/commons/8/85/Stone_marker._-_geograph.org.uk_-_108421.jpg

https://slm-assets0.secondlife.com/assets/2887699/lightbox/pic%20for%20tokugawa%20stone%20marker.jpg?1295810114

Once placed, looking at them would display a tooltip when using waila or similar, and right clicking on it could highlight the chunk borders for excavator placement. (right click again turns it off)

**Comment by mindforger** [comment]
make em not as wide as a whole block then please :) and 2 blocks tall should be enough

but the chunk border feature would be VERY awesome ... but in a slightly other way
maybe add it as a feature when wearing a sample drill, sample drill in hand + sneaking right cklick in air = toggle chunkborders (only the border of the chunk you are walking in, leaving the chunk should highlight the next chunk while active)

when you place down an sample and look at it, or holding it in your hand, the chunk it was taken from should light up instead of the actual chunk (when in rendering distance only)

**Comment by BluSunrize** [comment]
Donesies!

https://github.com/BluSunrize/ImmersiveEngineering/commit/62e69c9634539b0737e1869b2a87137b7c0a78e9
https://twitter.com/BluSunrize/status/845292087197253634

Core Samples can be placed, rightclick with a map to set a marker.
Sample drills show chunk bounds when held or looked at.
