### ISSUE TITLE
[1.10.2 - v0.10-57] Potions in Mixer then in Bottling Machine

### ISSUE THREAD

**Issue by VallenFrostweaver** [BluSunrize/ImmersiveEngineering#1983]
I've seen a few other potion issues (including the missing textures) but I can't seem to get any to bottle using the bottling machine. I have tried a few types but to no avail. Also, the Bottling machine seems to stop accepting the potion liquid after a little bit and then I can't empty it or fill it any more without breaking and retrying. So for the use of potions it seems to not work at all.
![2017-03-22_10 20 20](https://cloud.githubusercontent.com/assets/13642054/24195524/04dae86c-0ef2-11e7-8a50-d43aaca45d87.png)

**Comment by malte0811** [comment]
How did you transport the potion from the mixer to the bottling machine? The potion fluid has NBT data, which is somewhat unusual (but officialy supported) for a fluid. This causes issues with forge's universal bucket and might cause issues with other methods of fluid interaction.

**Comment by VallenFrostweaver** [comment]
I piped it in out of a Mixer via IE fluid pipe and into a metal barrel. I then took that barrel and placed it to insert into the Bottling Machine via IE fluid pipe as you see here. In the Mixer I see broken textures and in the Bottling machine they persist as well. The only buckets used were to insert a bucket of water into the drum that was feeding the mixer before brewing the potion.

**Comment by malte0811** [comment]
Fixed, the barrel was checking how much it could insert using a no-NBT version of the fluid contained in it. Using a different tank might work depending on how well the tank was implemented. Connecting the bottling machine directly to the mixer using pipes should work as well. Filling bottles seems to be working perfectly if there is enough fluid (as expected), since you are only putting in 80mB, bottles can't be filled.
