### ISSUE TITLE
Assembler and Cake - deletes buckets if no available output

### ISSUE THREAD

**Issue by TeeMee123** [BluSunrize/ImmersiveEngineering#1985]
Making cake (and other things like salt in pam's harvestcraft) in a crafting table requires consumption of fluid inside buckets but not the buckets themselves, leaving the bucket(s) in the crafting grid.
The assembler does a pretty good job at supporting this considering how rare such recipes are (and therefore how weakly tested it might be), by chucking them out as an output with the cake (or other product).
The issue is that if the assembler can't output a product (e.g. no conveyor belt attached to output I guess), the buckets can't be stored in the crafting grid or the cake storage slot (because there's cake there) so they end up being deleted.

**Comment by BluSunrize** [comment]
Well, for one, the buckets should go back into the inventory, but also, the assembler has fluid tanks for literally that reason. Pump water in.

**Comment by TeeMee123** [comment]
I had thought bottlers might have been intended for this

**Comment by BluSunrize** [comment]
The bottler puts fluids in containers. The Assembler uses fluids directly from its internal tanks.

Additionally, buckets shouldn't end up beign deleted, because the assembler crafts and outputs in a single tick,which means that any buckets in the invenntory that are use for crafting are then put back empty in the slots they themslves freed up.
Could you please provide screenshots of your GUI on how to reproduce the issue?
