### ISSUE TITLE
Suggestion or Issue : Can you make ethanol comperative with other mods?

### ISSUE THREAD

**Issue by XMertdx** [BluSunrize/ImmersiveEngineering#199]
Can you make other mods ethanol(like MFR) can be used to make biofuel?

**Comment by BluSunrize** [comment]
MFR doesn't add ethanol .-.

**Comment by mindforger** [comment]
i am updating this evening to test out, but in 0.2.3 i could not use forestry ethanol for fuel production and plant oil also was not compatible with seed oil, while technically both are the same product!

**Comment by BluSunrize** [comment]
They are not, because forestry's ethanol is their version of a biofuel. I'd be implementing a recipe to turn biofuel into biodiesel. .-.

**Comment by mindforger** [comment]
well not really!
there is:
- ethanol (poor fuel) but afaik registered as "ethanol" ... should not be burnable in your generator or outputting 1/4 power level as an idea but should be ore dicted
- biofuel from MFR ... but i think theirs isn't registered the right way at all as it's only usable in their machines so you could ignore it imho!
- fuel from BC .. should probably be compatible with your generator, so probably a candidate for ore dict
- rocketfuel from Extra Utilities, probably ore dicted to fuel anyways, dunno sorry :P
- biomass (forestry's biofuel AND base for ethanol) but unburnable in regular machines so ignore it imho

you COULD probably check for the presense of those mods and provide compareable recipes for your refinery :P or some way to make post processing of stuff in another refinery with adjustable mixing ratios to get compareable input(items) to output(power) ratios

**Comment by BluSunrize** [comment]
Well Forestry's ethanol is registered as "bioethanol". If it was registered as "ethanol", I'd already be using it. It is made by refining biomass, and is the highest level of fuel that Foresty in itself provides. As such, it is their version of biofuel, and also produces roughly the same amount of RF/bucket. Therefore, refining it into biodiesel is a bit of a waste of RF on the refinement process.
Biofuel from MFR I could possibly use, I'll look into it.
Fuel from BC has been supported since the dieselgen was first introduced, it's even in the book.
I didn't know XU added any sort of fuel.
Also Diesel (like actual diesel, from oil) is added by the new versions of Pneumaticraft and is also supported by IE's generator

I'd say we're doing pretty good on cross-mod currently =P

**Comment by 016Nojr** [comment]
"rocketfuel from Extra Utilities, probably ore dicted to fuel anyways, dunno sorry :P"

Extra Utilities doesnt add any fuel. Rocket Fuel is from EnderIO
