### ISSUE TITLE
Weird Coke oven glitch

### ISSUE THREAD

**Issue by ProxyPlayerHD** [BluSunrize/ImmersiveEngineering#2021]
I have not tried this with any other Multiblock... so this might not be the only case.

I constructed a Coke oven and the model of the oven itself... was off-center, each time i reactvated it it either added another off-center model or changed it.
not only does it look ugly, but when breaking the Sturcture to rebuild it over and over i noticed that i was making coke oven bricks out of nothing.
in the end i was able to make 2 Coke oven.
but the Glitch still remains.

here is a screenshot of how it looks, (pack, FTB Beyond, version 1.4.0 because the server can't update rightnow)
[http://i.imgur.com/3a7vyW3.png](url)

**Comment by ArukaAlter** [comment]
Is the server running on Sponge?

**Comment by ProxyPlayerHD** [comment]
as it seems, yes.
a Friend of mine found out that the Coke oven and Crude blast furnace like to face in a certain direction.
so he used the hammer to make them face in the wanted Direction and it works, the Model is correct.

it is still confusing why that happens in the first place

**Comment by ArukaAlter** [comment]
Search for older similar issues, this is another duplicate.

**Comment by cragrim** [comment]
I've got this issue as well on latest 1.11.2 version.
Screenshots: http://imgur.com/a/Nh4Er

Basically visual ghost blocks appear in a 3x3x3 offset to the coke oven. Removing coal and replacing it removes the ghost block. It stays through server restart.

Running Immersive Engineering 0.11 - 63

**Comment by BluSunrize** [comment]
Modlist, mate.

**Comment by cragrim** [comment]
List of mods:
https://paste.ee/p/JlLHx

Any suspects?

**Comment by BluSunrize** [comment]
Yeah, Optifine.
If you can reproduce it without, then it's a valid issue.

**Comment by cragrim** [comment]
I will test without it and report back.

**Comment by cragrim** [comment]
Tested without OptiFine but the issue is still the same. Could it be because I have 2 coke ovens next to eachother?

**New screenshots without OptiFine:**
http://imgur.com/a/oJDGr

Image 1: Ghost block visible on the left coke oven
Image 2: Taking out the coal blocks in left coke oven
Image 3: The ghost furnace has now disappeared in the left coke oven
Image 4: Ghost block visible on the right coke oven
Image 5: Taking out the coal blocks in right coke oven
Image 6: The ghost furnace has now disappeared in the right one as well

Anything else I can do to test it further to help you debug? 
Best Regards

**Comment by cragrim** [comment]
I've placed them 1 block apart and it haven't happened again!
I suspect its related to placing the ovens next to eachother.

![Screenshot](http://i.imgur.com/8hO2u3p.jpg)

**Comment by BluSunrize** [comment]
Odd!
Well I guess that's a fix? .-.

**Comment by ProxyPlayerHD** [comment]
but then why did it happen when i just placed a SINGLE oven?

**Comment by cragrim** [comment]
@BluSunrize
I wouldn't conside this a fix, more an easy workaround :P hehe

@ProxyPlayerHD
Did you have it right next to another ImmersiveEngineering machine that replaces the block rendering? Maybe it happens when two multiblock machines that both replace rendering are placed next to eachother in some directions. As it appears to be 1 block offset maybe its just a coordinate rounding error when looping through all rendered multiblock objects?

**Comment by ProxyPlayerHD** [comment]
no it was just standing on it's own.

strangly it does not bug out when you activate it with the hammer in total darkness

**Comment by mindforger** [comment]
doesn't that sound like the race condition thingy you had with sponge/cauldron earlier @BluSunrize ... something with optimizing light calculation bouncing into your renderer?
