### ISSUE TITLE
Feature Request: Make fluorescent tube glow if supplied with power

### ISSUE THREAD

**Issue by darthvader45** [BluSunrize/ImmersiveEngineering#2034]
It'd make a nice light source, but I'd like to be able to make it glow without having to stick it in the range of a tesla coil and risk getting zapped.

**Comment by deathaplenty** [comment]
The fluorescent bulb is an entity and does not put out any light.

**Comment by BluSunrize** [comment]
Also you can't supply power to it because it's an entity, and entities can't be supplied with wires.

**Comment by darthvader45** [comment]
Okay then.  It should emit light though.  Why does it have to be an entity?

**Comment by malte0811** [comment]
Because the Tesla coil has to check for all fluorescent tubes in a certain radius. There is a reasonably efficient builtin method for finding all entities in an area, but no such method exists for blocks (that I know of).
It would be possible (at least in theory) to make the tubes light up if placed on top of an Forge energy emitting block though (Forge Energy supports extraction). Or maybe add some sort of block specifically designed to light up tubes in an area? Something that emits large amounts of EM waves?

**Comment by BluSunrize** [comment]
It's an entity because it was programmed to be an entity. It was also made to *specifically* interact with Tesla coils, along with Faraday Armor.
It will not be changed to a block and will not emit light.

**Comment by malte0811** [comment]
I know that, I was the one who implemented them as entities! I wasn't talking about making them emit proper light, just about having them light up as they do near a TC, which would obviously be possible without needing blocks for it.
