### ISSUE TITLE
pig and cow farm issue

### ISSUE THREAD

**Issue by DanielK21** [BluSunrize/ImmersiveEngineering#204]
i use IE 4.0.0 in other version same the problem.. i set a farm with Stabilized Mob Spawner from ( Draconic Evolution by Brandon3055 ) (cow or pig) some conveyor from IE and at last the Crusher. However when i started the spawners cows goes to Crusher and when it kill Crusher won't drop the leather and Raw Beaf same with a pigs.. When i put spawner trought Ender IO and Minefactory Reloaded the work fine.. Please make it work with a Draconic Evolution :)

**Comment by mindforger** [comment]
@BluSunrize 
is it wise to register your event as lowest priority?

@SubscribeEvent(priority=EventPriority.LOWEST)
	public void onLivingDrops(LivingDropsEvent event)

wouldn't this imply the chance, that any other mod may spill the item before you could handle it and thus removing it from existence because you have no recipe for raw beef and leather? ... to mention, what i assume is happening here in this case probably

**Comment by BluSunrize** [comment]
The lowest priority is used here because of other mods that might add drops to the list.
Imagine mods like Xeno's Reliquary which add additional drops to monsters, those are handled by that event. Me using lowest priority is to account for those.

**Comment by BluSunrize** [comment]
Also, I just tried it and I can't reproduce it. I spawned a pig with draconic and it worked perfectly fine in the crusher

**Comment by mindforger** [comment]
but still, even IF there were addition drops, you would waste them in this particular case if the drop is already spawned and thus cancled? that is what i am concerned about ... 
and honestly i believe ther are pretty much man yother mods that @DanielK21 is using and one of them is probably spawning the items before you get a chance to collect them, because you drop the event because it is cancled ... 
i do not blame you, but imagine other mods doing a bad job in handling the onDropEvent ...
you might filter a bit to much in your event handler, can't you just suck in the items that are matching the itemlist in the event in case the event is already cancled? something like an temporary whitelist for items to pass through without being processed?

by the way @DanielK21 can you reproduce this situation with an skelleton spawner of the same type? if you get bone meal instead of bones from the crusher, my thesis could be confirmed

**Comment by BluSunrize** [comment]
Closed for lack of further info
