### ISSUE TITLE
Suggestion: Blueprints in Frames create Posters, like Maps

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#2043]
just abstract little white on blue drawings of the thing the blueprint is for :)

**Comment by BluSunrize** [comment]
While the idea is awesome, the problem is that blueprints can make multiple different things.
Thats why the Autoworkbench renders only the selected item :/

**Comment by TheGuyRunningSouth** [comment]
As a suggestion, possibly a cosmetic blueprint, made from say paper and one
of the blueprints, that serves that purpose in a frame and cycles through
which item is "selected" by crafting it by itself?

**Comment by MalkContent** [comment]
I thought of them having the same 128x128 res as the maps do
Made a little mockup for the Common Projectiles one:
![bluprint](https://cloud.githubusercontent.com/assets/7753414/25785422/197a3888-3380-11e7-80bf-d9c3285106dc.png)

**Comment by BluSunrize** [comment]
well, I'd honestly probably want to reuse the current blueprint rendering (all the more so because they are dynamic, more Blueprints are added through the recipe handler).
I already have all the methods for cutting the resulting items into pixels and shading them diagonally, as shown on the Automatic Workbench. That render should, in theory, be portable.
Also, ItemFrames are entities, so maaaaybe I can attach a capability or something to them in order to save which of the pieces I want them to render?

I'll investigate this tomorrow and see if I can come up with something.
