### ISSUE TITLE
your hammer crashes my system

### ISSUE THREAD

**Issue by Mitsunee** [BluSunrize/ImmersiveEngineering#2044]
here's your useless bug report to immediately close and a note to take a hint when people don't give a crap about sending in a bug report for something that's probably limited to their system/install and happens on a deprecated version anyways. But good job not offering any help, Lemming would be proud.

**Comment by malte0811** [comment]
And good job reading the [contributing guidelines](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/CONTRIBUTING.md). There is a link to them when you create an issue. Without reading the twitter conversation, this bug report makes no sense at all and is also missing things like a mod list.

**Comment by BluSunrize** [comment]
Good lord, the salt is real.
My whole point in having you file a report here was so that I could get more information on the issue.
Versionnumbers, system specs, etc! All the good stuff that is really hard to fit into twitter's 140 characters.

So, let's try that again, from the start, possibly without slipping in your dislikes for Java developers and Lemming in particular? None of that really does relate to the issue after all.

But if you go for those contribution guidelines and tell me which version of IE is installed, if you're using Optifine or other "optimizing" mods, your system specs.
Ideally, to accomplish all of that, load up your game and hold F3+C to generate a debug crash, chuck that on pastebin or a similar site and then we'll see from there!
