### ISSUE TITLE
Wires issue

### ISSUE THREAD

**Issue by nicholasnyn** [BluSunrize/ImmersiveEngineering#2050]
hey! so basically I had quite a problem with the wires! I've finished a huge bunker all connected and functional but every time I restart the game, every wire it's just gone. I've changed the whole system improving the wires. I've tried with different wires, transformers, capacitors... nothing seems to be working, what would you recommend me to do? 
By the way! I must confess that you're mod it's just wunderschön! hahah thank you very much.

**Comment by theunkn0wn1** [comment]
Can we please get the following information so we can properly help you and identify the root cause of your issue:
- Version information (Java, Minecraft, IE, Forge)
- List of installed mods
-  If possible minimum steps to reproduce


Oh, and you sure the wires aren't burning from trying to draw too much current through them?

**Comment by BluSunrize** [comment]
Pictures of your setup would also help.

**Comment by nicholasnyn** [comment]
Off course! 
java: version 8 update 121
minecraft: 1.10.2
IE: current version
Forge: current version for 1.10.2

blood magic, cavern, giacomosfishingnet, giacomosfoundry, grappelemod, guide-api, notenoughitems, minecolonies, pam's harvest, Optifine

I'm not sure, if I understand correctly the last requirement!

![2017-05-02_08 37 18](https://cloud.githubusercontent.com/assets/28278282/25620189/290564d8-2f13-11e7-857c-ce4454408a05.png)
![2017-05-02_08 36 13](https://cloud.githubusercontent.com/assets/28278282/25620188/29009250-2f13-11e7-87b9-59d133e244f0.png)

**Comment by theunkn0wn1** [comment]
Have you tried removing Optifine, it is known to cause many graphics related issues and IE does not support it. 

Please define 'current version' for both Forge and IE.
Be advised that your Java installation is out of date, please consider updating.

**Comment by mindforger** [comment]
the java version should be fine, the brekaking points was somewhere around 56 or was it 65, can't remember

but this looks like ou are overloading your cables! i see at least 6 cables combining into one cable, that is 2 cables to much to handle, it is most likely that your cables burn out through buffered power overloading it, never combine more than 4 cables into one .... also combining 4x(4to1) and then combining the 4 resulting cable will burn out your wires too, wires can only carry 4 times their connector value

**Comment by malte0811** [comment]
@mindforger by default you can combine 8 wires into one, see [here](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/Config.java#L42) and [here](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/Config.java#L89).
@nicholasnyn Are the wires actually gone or are they just not rendering/When you try to re-link the connectors, does it work or does it tell you that the connection already exists? Could you also upload a full log? Since you don't have that many mods, the log should not be too big to upload to [gist.github.com](https://gist.github.com) or [pastebin](https://pastebin.com). You can find the log in `<your MC folder>/logs/fml_client_latest.log`.

**Comment by MalkContent** [comment]
also ALL the wires burning off due to overload sounds strange
there is no reason a wire from a connector at a thermoelectric generator should ever burn off

**Comment by nicholasnyn** [comment]
Thank you all for you're help!
@theunkn0wn1  Here, my current forge version: 1.10.2 - 12.18.3.2281 and my current IE: 0.10 - 57 
@malte0811 Exactly! that's what I actually mean, the connections somehow keep existing but nevertheless, the whole system it's just off.

**Comment by malte0811** [comment]
Could you clarify what you mean by 'the whole system it's just off'? 1. Can you still see the wires? 2. Do they still transfer power? 3. Can you reconnect the connectors? You might have to vary the order in which you click on the 2 connectors?

**Comment by nicholasnyn** [comment]
I can't see the wires. They don't transfer any kind of signal or energy or anything at all. I'm unable to connect the wires, it says that there's still a existing connection. Besides, I've been forced to destroy the connectors and once I've done that, the cables drops!

**Comment by malte0811** [comment]
Is the order in which you try to connect the 2 ends of a connection relevant? I can think of one case (code-wise) where this would happen, in that case the message should change when you change the direction.
