### ISSUE TITLE
[Suggestion] add sound effect to the Breaker Switch

### ISSUE THREAD

**Issue by fermuch** [BluSunrize/ImmersiveEngineering#2068]
As suggested by direwolf20 in [this video](https://youtu.be/l0RCD2lrr60?t=177) (minute 2, second 57), adding a "bzzzzt" sound effect when activating/deactivating the breaker switch would make sense, as the ones in real life do.

Here is a song that could be used: https://www.freesound.org/people/sribubba/sounds/130153/
It's licensed under [Creative Commons 0](https://creativecommons.org/publicdomain/zero/1.0/), making it usable in the mod.

**Comment by malte0811** [comment]
That is just a click sound from an automatic circuit breaker, it would not make much sense for the knife switch IE has. A sound like [here](https://youtu.be/aSmMFog10D0) (around 15 seconds, I can't seem to make timed links on mobile) would probably be more appropiate. The issue is that the video I linked is under a non-commercial licence (see "original video" link in the description), I don't know whether CurseForge reward points count as commercial, but they probably do.

**Comment by BluSunrize** [comment]
Don't worry about it.
There's already plans. Just wait and see. (Or listen, in this case)
