### ISSUE TITLE
[BLU] HELP!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by MinecraftArchive** [BluSunrize/ImmersiveEngineering#2078]
@BluSunrise. Since IE is such a good mod and I approve in the next build can you add a config so that gaming with Intel Graphics cards like my brother can play with me. he cant he gets the small bottom left screen error.  can coferm its IE, and it wouold be nice if you know what does those Special textures and if you can add a cofig so we can get around it. Thanks

-cranky

**Comment by Joshwoo70** [comment]
Not even a crash log -_- please insert a crash log INTO PASTBIN AND UPLOAD IT HERE.

**Comment by BluSunrize** [comment]
...I'll file this under "Very young user", given the...uuh...somewhat unprofessional title.
To answer the question: Nope, I can't do that, because I legitimately have no idea *what* you need me to do.
I don't even know the error message.
If you provide me with the full error, word for word, then maybe I can give some advice? Can't guarantee it though.

**Comment by BluSunrize** [comment]
I'll close this due to lack of further info. I'll happily reopen if the OP produces more data.
