### ISSUE TITLE
[Suggestion] Steel Furnace

### ISSUE THREAD

**Issue by ReTeYeZ** [BluSunrize/ImmersiveEngineering#2091]
I really like the idea of the external heater but once you start building a proper factory the stone furnaces look kinda out of place. I'd say it should melt items at 150% the speed of a regular furnace to make up for the higher cost.

**Comment by mindforger** [comment]
Have you tried the arc furnace?

**Comment by ReTeYeZ** [comment]
I'm aware of the Arc Furnace but there's a huge gap between the external heater and that guy. Also with the huge energy consumption and maintance of the electrodes I wouldn't use it for simple smelting operations, rather for recycling, steel production and alloys.

**Comment by mindforger** [comment]
so you mean there should be an arc furnacer lite edition?
i have to admit, i kinda would also like the idea of a non electrified version of the arc furnace ... maybe remove the top layer from the actual arc furnace multiblock and add hoppers instead, could render almost the same but does not require the graphite rods and any electricity, it just operate exactly the same like the arc furnace but at half the speed and requires coke instead of coal for keeping the process running (and using 1.5 to 2times the amount of coke as it would require in any other furnace)

this way you can have a fast big multi-smelting furnace that is only available mid game (becasue of the heave steel requirement) with slight inefficient fuel handling that can be reworked into a electricity hungry arc furnace by breaking and changing the top layer only when you finally managed to get hands on the graphite rods

**Comment by ReTeYeZ** [comment]
Not exactly what I meant but yes something to fill the gap between mid - late game.

Maybe I wasn't clear enough, I meant a steel furnace that looks and works exactly like the vanilla furnace, except having a different texture and beeing a little bit faster of course.

So you can build your smelting factory with external heaters and vanilla furnaces early game,
and then you have the option to either use your steel to add/upgrade your furnaces (switch them out with steel furnaces) or save it up and go for the Arc Furnace immediatly/other machines.

Since the steel furnaces are (a little) quicker they'd stay a viable option late game (in combination with external heaters), you'd need quite a few though so it would also cost a lot of steel. The Arc furnace would still have its uses since it has other recipes. So nothing becomes obsolete.

**Comment by MalkContent** [comment]
I feel like functionally this would be a bad thing to have. There is nothing interesting or special about it. Textures aside, it's just "the same thing, but faster", for no good reason other than to justify the material cost. Then other mods have to compete with this and that's how you get power creep.

**Comment by PrincessRTFM** [comment]
I disagree. It's "the same thing, but faster", yes, but that's completely valid. Normal furnaces take a full ten seconds to smelt things. Thermal Expansion, for instance, offers three levels of augments for its Redstone Furnace that double the smelt speed with each one installed. For that reason, once I have the tech needed for it, I always drop the vanilla furnace and external heater combo for faster smelting (I still play on 1.7.10, though). We already have upgraded furnaces at mid-tier, why not make cooler looking ones?

**Comment by TheGuyRunningSouth** [comment]
Just a thought, but I'd say a solution to this would be to let the
preheaters work on vanilla furnaces. I know botania's manatide bellows can
speed them up, so a similar implementation might be possible, but I've
admittedly never looked into it, so that's just speculation. If it would
work it'd extend the usefulness of vanilla furnaces further into the IE
tree while still fitting the "feel" if the mod.

Again, just my opinion.

**Comment by BluSunrize** [comment]
Well the preheaters are called "Blastfurnace Preheaters" =P
That said, the external heater already doubles the speed of the vanilla furnace.

**Comment by MalkContent** [comment]
@PrincessRTFM My issue is not that there is faster smelting of sorts, but by having a vanilla furnace+
I am not very knowledgable about mods, but even I know 2 other mods that make vanilla furnaces smelt or smelt faster (TC bellows and that botania endothermic? flower thing). If you make a vanilla furnace clone that basically just smelts faster but is otherwise identical, and you keep your own external furnace heater to work with it, all the other mods' external heaters are out of a job. Or, y'know, you'd have to go to what I suspect to be a royal pita and make the vanilla furnace+ compatible with all the other heaters.

**Comment by PrincessRTFM** [comment]
Ah, okay. I misunderstood you. That's a good point, yeah.

@BluSunrize, I completely forgot the external heaters doubled the smelting speed. Does that compound with other speedup mechanics MalkContent mentioned? If so, is it arithmetic or geometric? I'd assume geometric, but I don't know how any of them work.
