### ISSUE TITLE
[1.11.2] Treated Wood's name is not translated for the Tinkers Construct material

### ISSUE THREAD

**Issue by KnightMiner** [BluSunrize/ImmersiveEngineering#2095]
Treated wood on Tinkers tool parts shows up as "material.treatedwood.name" instead of Treated Wood. [The line in the lang file](https://github.com/BluSunrize/ImmersiveEngineering/blob/1.11.2/src/main/resources/assets/immersiveengineering/lang/en_us.lang#L530) seems to be translating `material.treated_wood.name` instead of the proper name. (which if I had to guess changed from a non-case sensitive find and replace :P). Minor issue, but one nonetheless.

Using a private build made from 89890c6 on the 1.11.2 branch since issues should have versions.

**Comment by BluSunrize** [comment]
Yeah, part of the whole "what do we do with camelcases" disaster.
I'll look into it ^_^

**Comment by malte0811** [comment]
I have a few cases of that disaster fixed in my repo (but not this one, but e.g. ones related to bullets and case sensitive file systems), see the branch "case_sensitive_filesystem" (or something like that, the branch escalated into misc fixes quite quickly). I will probably PR those fixes today or tomorrow, I am still working on TESR model lighting (quite noticably broken when changing turrets to `ClientUtils.renderQuadsTESR`).

**Comment by BluSunrize** [comment]
Had to look up what that legacy bullet handler was. Didn't realize your 1.10 compat featured that too =P
Well at least someone is spotting all these casesensitive bullplops.
One of the main reasons 1.11 is in closed testing >_>

Anyway, TCon thingy is fixed, closing this.
