### ISSUE TITLE
[0.10-58] OpenComputers setEnabled(bool) for IE machines lost on chunk/world unload

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#2101]
Basically, you can setEnable(false) for all* the machines, but when you walk out of range or restart the world and come back, the machines will work as if the value was not set.
Don't know the cause, but maybe the computer based enabled value isn't saved or simply discarded upon reload.
*: tested with an Arc Furnace and a Fermenter *cough*

OC1.6.2.7

**Comment by malte0811** [comment]
When I started writing the computer compat I was using CC, cobra started implementing OC compat a couple of days after that. Since CC resets on chunk reloads I made the computer bits of the machines do the same (and cobra probably used the same "style" for consistancy?). I don't know whether it is easily possible to detect chunk reloads in OC, if it isn't, it might be a good idea to change the computer compat to be persistant as well, especially given that there is no CC compat any more AFAIK.

**Comment by MalkContent** [comment]
I'd just save any "set" values given by computers as long as there's an oc adapter in front of the machines control panel. Says the guy who doesn't have to do the work ^^

**Comment by BrisingrAerowing** [comment]
I don't think OC has a way to detect chunk reloads, as the persistence is supposed to be 'seamless', so I think changing the computer compat to be persistent as well would be the best course of action.

OC is all about the persistence across chunk / world reloads, and other OC addons / integrations have the same persistence setup as well.
