### ISSUE TITLE
[Request] Make shift ancor the players position on the side of Scaffolding

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#2105]
Like with ladders.

**Comment by BluSunrize** [comment]
Can't. Already trying my best in slowing you down, but I can't stop you mid air without some very strong jittering up and down.

Problem is that the isLadder() method doesn't work on this block, because you're not far enough inside it.
I've given this multiple tries in the past without a satisfactory solution I'm afraid.
