### ISSUE TITLE
[Suggestion] TE Phyto-gro support

### ISSUE THREAD

**Issue by Skillotic0703** [BluSunrize/ImmersiveEngineering#2135]
Can you support TE's phyto-gro, rich phyto-gro, and fluxed phyto-gro in the garden cloche please?

**Comment by TokkenGmr** [comment]
Even just minetweaker/craftweaker support for things like fertilizer and the base block(dirt, sand, ect..)

**Comment by PrincessRTFM** [comment]
That seems like the sort of thing that TE should implement through an API, IMO. Implement an interface, say, `IGardenClocheFertilizer`, with a `getMultiplier(ItemStack)` method (and maybe a `getDuration(ItemStack)` one too?) instead of looking for an item in another mod which may not be present. Also, having IE's API provide a way to tag items as fertilizer seems not only more customizable for the mods providing new fertilizer but also easier to maintain.

Just realized, in Direwolf's new Forgecraft series, didn't he say that Forestry Apatite was a valid fertilizer? How was that done?

**Comment by TokkenGmr** [comment]
I too was looking at the Apatite thing today, could not see how it was possible to be done

**Comment by BluSunrize** [comment]
The Forestry Fertilizer compat was released for 1.10 with Build 60.
I'm not handling Phytogrow for now. I'll maybe consider it again when CoFH updates to 1.11 or beyond.
