### ISSUE TITLE
[1.10.2] Crash with garden cloche

### ISSUE THREAD

**Issue by Skillotic0703** [BluSunrize/ImmersiveEngineering#2136]
https://pastebin.com/ndiigLxN
This is what happens when I try to put a hole stack of ender lillies by shift left-clicking in the garden cloche.
Edit: I'm using the last available version on curseforge.

**Comment by kmadstarh** [comment]
#2071 Crash with Garden Cloche and Ender Lily

**Comment by dja2000** [comment]
http://paste.feed-the-beast.com/view/0f941cc1
Got the same crash with ender lilly's, don't know if this ^ will help fix it :)

**Comment by scotty9090** [comment]
Same here, and unable to reload my game after - ended up having to edit this out with NBT Editor.  I can post my crash log if needed, but it looks identical to the others.  The funny thing is that I'm watching Soaryn grow ender lilly's on the Forgecraft server right now, but I guess that's 1.11.

**Comment by Umber0010** [comment]
it actually appears to be with all EU2 crops, I just tried it with a red poppy and it crashed the game aswell

**Comment by ChaosTherum** [comment]
So I ran into the same issue and for anyone on a multiplayer server I found a bit of a temporary workaround. If you log into the server and just repeatedly hit escape get into the pause menu. Find someone who is online then quickly unpause and teleport to them you can get away from it at least until this gets fixed.

**Comment by malte0811** [comment]
As noted by @kmadstarh this is a known bug (and a duplicate) that has been fixed in 1.11. The fix will be backported, probably once the 1.11 build is on curseforge. You can fix on servers this by having someone run `/setblock` to air on the position mentioned in the crash log (you will probably have to break the upper 2 blocks manually, but those shouldn't cause crashes).
