### ISSUE TITLE
[1.11.2] [59-104] Some crashes w/ JEI and drills

### ISSUE THREAD

**Issue by MrEvilCookie** [BluSunrize/ImmersiveEngineering#2142]
When fastly moving a cursor on top of the shader in the drill (or doing something similar and messing with it) will crash MC. It happens only if I do that fast, and it's slightly hard to reproduce.
[crash](https://github.com/BluSunrize/ImmersiveEngineering/files/1042439/crash-2017-05-31_20.27.28-client.txt)
[mod list](http://imgur.com/r9NE3pb) [part 2](http://imgur.com/BkZPnXU)
----------------------------------------------------------------------------------------------------------------------------------
Also, you can place seeds in the bottom slot of the garden cloche and it will display as missing texture (I will try to reproduce that on windows).
P.S. Sorry Blu, for that tweet :D

**Comment by MrEvilCookie** [comment]
And can I use git build in my modpack?

**Comment by BluSunrize** [comment]
No, you absolutely can not. IE 1.11 is not officially released.

**Comment by malte0811** [comment]
Re using git/jenkins builds for playing: I don't think anyone is going to complain if you use one in an SSP world (I do that myself and have done so ever since IE was on github). Just say that you are using one when reporting bugs.
Publishing/distributing such builds is probably a bad idea though, Blu doesn't like that at all.

**Comment by MrEvilCookie** [comment]
I deleted it from modpack for some time :D

**Comment by MrEvilCookie** [comment]
Drills also breaks only central block

**Comment by malte0811** [comment]
Fixed (actually fixed a week ago...)
