### ISSUE TITLE
[1.10.2]Conveyor belt glitch

### ISSUE THREAD

**Issue by NightmareTwilight** [BluSunrize/ImmersiveEngineering#2173]
Hello, I'm using IE 0.10-58 and I have noticed that sometimes (regular) conveyor belts get the same model as vertical ones with a regular one imputing into it, but not only that, sometimes it even acts the same way. I tested rotating them with the hammer to fix it, and while it does do that, as soon as I return to the same position it gets weird again. I suspect that it's internal, but just in case, here's my mod list:

- Avaritia 2.1.2.1
- Baubles 1.3.11
- BrandonsCore 2.1.8.104
- CodeChickenCore 2.4.1.102
- CodeChickenLib 2.5.9.267
- CoFHCore 4.1.2.157
- CookingForBlockheads 4.2.43
- CraftTweaker 3.0.25
- cyberware 0.2.10
- Draconic-Evolution 2.1.0.232
- EnderCore 0.4.1.66
- EnderIO 3.1.192
- ImmersiveEngineering 0.10-58
- ImmersivePetroleum 1.0.5
- jei 3.14.7.420
- Mantle 1.1.5
- Optifine HD_U_D8
- Pam's Harvestcraft 1.10.2j
- TConstruct 2.6.5
- Tesla 1.2.1.49
- ThermalFoundation 2.1.0.82

**Comment by BluSunrize** [comment]
Could you provide a picture please?

**Comment by NightmareTwilight** [comment]
The one to the left is only visual, but the right one acts as a vertical one.
![2017-06-13_11 46 08](https://user-images.githubusercontent.com/29397235/27076595-fb0cb932-502d-11e7-837d-a298036a6973.png)

**Comment by NightmareTwilight** [comment]
It seems that after closing and starting minecraft fixes this, however now different ones has bugged out:
![2017-06-14_13 27 07](https://user-images.githubusercontent.com/29397235/27130122-30cb219e-5105-11e7-9e8d-a85696006e2d.png)

**Comment by BluSunrize** [comment]
Can you reproduce any of this without optifine?

**Comment by Overato** [comment]
I second this bug, however with the latest build 0.10-60. It also appears to be world specific and tied to resource packs, but testing shows that it is mostly visual. A concurrent bug in affected worlds is the translucency of certain crops in the cloche, usually non-vanilla but sugarcane has been noted to be transparent. I have extensively tested this with all mods that tweak performance (foamfix and betterfps) and can confirm that it is per world and per resource pack. Older worlds seem to be more affected by this bug. I've included some screenshots of this happening, and Waila/TOP are reporting the correct blocks. I've also included a crash report for modlist purposes, (although the crash was due to low RAM)
[crash-2017-06-14_16.01.30-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/1076269/crash-2017-06-14_16.01.30-client.txt)

![2017-06-14_15 51 17](https://user-images.githubusercontent.com/8131582/27160332-47081b06-5128-11e7-92ca-81f04ab837ef.png)
![2017-06-14_15 51 52](https://user-images.githubusercontent.com/8131582/27160333-47225624-5128-11e7-8d70-be5561accd4f.png)
![2017-06-14_15 52 11](https://user-images.githubusercontent.com/8131582/27160336-4723b26c-5128-11e7-9021-a595b793f10a.png)
![2017-06-14_15 47 59](https://user-images.githubusercontent.com/8131582/27160334-47224d14-5128-11e7-9654-7d9330217671.png)
![2017-06-14_15 48 14](https://user-images.githubusercontent.com/8131582/27160338-47288576-5128-11e7-885d-bb34bf7bf411.png)

**Comment by rahangar** [comment]
The visual glitch happened to me as well.  I'm playing Age of Engineering version 1.0.3, which includes ImmersiveEngineering-0.10-61.   Restarting minecraft got rid of the glitch.

![2017-07-18_07 17 24](https://user-images.githubusercontent.com/3137077/28316703-7cfba022-6b89-11e7-978e-9dc408f647b1.png)

**Comment by JeremyCooper** [comment]
Was the source/fix for this discovered? I believe I have the same issue.

Minecraft version: 1.12.2

My mods folder contains:
- Baubles-1.12-1.5.2.jar
- BiomesOPlenty-1.12.2-7.0.1.2399-universal.jar
- BloodMagic-1.12.2-2.3.3-101.jar
- Bookshelf-1.12.2-2.3.553.jar
- Chisel-MC1.12.2-0.2.1.34.jar
- CodeChickenLib-1.12.2.jar
- CTM-MC1.12.2-0.3.2.18.jar
- CustomMobSpawner-3.11.4.jar
- DarkUtils-1.12.2-1.8.211.jar
- DrZharks MoCreatures Mod-12.0.5.jar
- FamiliarFauna-1.12.2-1.0.10.jar
- Guide-API-1.12-2.1.6-61.jar
- ImmersiveEngineering-0.12-85.jar
- immersivepetroleum-1.12.2-1.1.9.jar
- immersivetech-1.12-1.3.10.jar
- IronBackpacks-1.12.2-3.0.8-12.jar
- IvToolkit-1.3.3-1.12.jar
- jei_1.12.2-4.11.0.212.jar
- journeymap-1.12.2-5.5.2.jar
- LibEx-1.12.2-1.0.8.jar
- Mantle-1.12-1.3.2.24.jar
- NetherEx-1.12.2-2.0.8.jar
- Not-Enough-Items-1.12.2-Recommended.jar
- OptiFine_1.12.2_HD_U_E2.jar
- RecurrentComplex-1.4.7.jar
- roughmobs2-1.12.2_2.0.9.jar
- SereneSeasons-1.12.2-1.2.6-universal.jar
- TConstruct-1.12.2-2.10.1.87.jar
- Thaumcraft-1.12.2-6.1.BETA24.jar
- TinkerToolLeveling-1.12.2-1.0.5.jar
- twilightforest-1.12.2-3.8.654-universal.jar

![2018-10-01_20 04 43](https://user-images.githubusercontent.com/5621322/46327288-b3237d00-c5b5-11e8-9677-df488feae42d.png)
Those are covered vertical conveyors. Many other conveyors seem to randomly change to different visuals states but none of their actual function seems to be affected. Interestingly, if you rotate the corrupted conveyor with the hammer it displays correctly in the three other states but upon returning to the original orientation the visual effects become corrupted again.

**Comment by mindforger** [comment]
>malte0811 closed this issue in 4b3ad52
5 days ago
