### ISSUE TITLE
[1.10.2] Immersive Engineering crash?

### ISSUE THREAD

**Issue by Amkdux** [BluSunrize/ImmersiveEngineering#2178]
When I start-up Minecraft (through the Curse/Twitch Minecraft thing) it gets to Phase II, gets to Immersive Engineering, then crashes: http://prntscr.com/fk32gr

List of mods (SkyFactory3): https://www.feed-the-beast.com/projects/ftb-presents-skyfactory-3/relations/dependencies

Latest log: https://pastebin.com/7bygv42F

I could not find a crash log, if you could point me to where I would find it then that would be great. However, I don't think there is one.

**Comment by BluSunrize** [comment]
Crashlogs, if they exist, would be found in the crash logs folder, but given that this is a crash of the Java Runtime, it probably wouldn't have generated one.
First of all, to confirm that this is an IE issue, disable IE in the pack and try starting it again. SF3 shouldn't contain anything with a hard dependency on IE, so you should be able to just turn the mod off in the Twitch Launcher and then start the pack.

**Comment by Amkdux** [comment]
I couldn't find out how to disable it, so I moved it to a different folder on my Desktop. I'll get back and tell you if it works or not.

**Comment by malte0811** [comment]
Also try updating Java, you are using the version that comes with the MC laucher. It was released about 2.5 years ago, a lot of VM crashes have been fixed since then.

**Comment by Amkdux** [comment]
Where would I update Java @malte0811 ? Also, I did what @BluSunrize said and now it crashed when I got to Texture Manager on OpenComputers, hope it's not because of my Intel graphics.

**Comment by malte0811** [comment]
You go [here](http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html) and download the installation file you need (Probably Windows x64). Then you run that file as an Admin. You may have to set the Java version in the MC laucher under the profile settings, I don't know about the Twitch launcher since I rarely use Windows.

**Comment by Amkdux** [comment]
When you launch MC in the Twitch launcher it brings up the Minecraft Launcher before it starts playing, so it's basically the same.

**Comment by Amkdux** [comment]
Okay so I tried to launch it again and it did the same thing (With the Java version path changed)

**Comment by Amkdux** [comment]
Alright, so I managed to get SkyFactory up and running, but it **WILL NOT** run if I place Immersive Engineering in the mods folder.

The only thing I have found is that when placed in the mods folder and I start Minecraft with the Output log open, it shows usually (if I wait a few minutes) over 10k error texts saying:

###GL ERROR###
Invalid framebuffer operation

**Comment by malte0811** [comment]
A similar issue just came up in the Forge IRC channel, using an Intel chipset pretty close to yours. Neither are supported by Intel any more from what I can see ([source](https://www.intel.com/content/www/us/en/support/graphics-drivers/000005733.html?_ga=2.186847406.765975017.1498768505-935985883.1498768169)). Since this appears to be some sort of driver issue I'd suggest you try updating your graphics driver. Aside from that I don't think there is much we can do about this.

**Comment by Edy12334** [comment]
When I install Immersive Engineering on forge 1.12.2 I get this: 
https://imgur.com/tV682Lr
Help!
