### ISSUE TITLE
Crash when placing Capacitor Backpack into Crafting Table

### ISSUE THREAD

**Issue by angelnc1989** [BluSunrize/ImmersiveEngineering#2184]
Minecraft 1.11.2
Forge 13.20.0.2315
ImmersiveEngineering 0.11-62

[Crash Log](https://pastebin.com/X4yQqgwK)

I wanted to craft the Capacitor Backpack with a Diamond Chestplate. As soon as I place the Capacitor Backpack in the (vanilla) Crafting Table the game crashes. It doesn't matter if I place the Chestplate or the Capacitor Backpack first. Both items are gone after reloading the world.

**Comment by BluSunrize** [comment]
Can you try to reproduce this without mousetweaks please?

**Comment by angelnc1989** [comment]
Removed Mousetweaks, no crash.

**Comment by BluSunrize** [comment]
Okay, most likely a compat error with them then. I'll take a look at it later.

**Comment by ParaMotor** [comment]
Same crash without Moustweaks when right clicking it.

https://pastebin.com/PWzGFcbA1

**Comment by malte0811** [comment]
Neither this nor #2189 is a compat error, but it is something I haven't seen before:
`ItemStack#copy` is being called in both crashes. It only makes sense if it is being called on an empty stack in which the `item` field is still the cap pack (but empty because size=0). `ItemStack#copy` directly uses the `item` field. In a deobf env a transformer from Forge replaces direct references to `item` with references to `getItem`. `getItem` returns AIR for empty stacks, whatever the reason for the "emptiness" is (this is also the "direct" cause of the crash). So if an empty stack in deobf is copied we get a stack containing air, which is good. In an non-deobf env the transformer does not work (I'll have to talk to a Forge dev later to see whether that is intended). So we get an empty (size=0) stack with the cap pack as an item. IE's capability init assumes that `getItem` returns the item in the stack and not something else and crashes because it returns something else (air).

**Comment by malte0811** [comment]
Fixed for the next release.

**Comment by malte0811** [comment]
Warning: rant. Sorry for putting this here, but I feel like I need to put it somewhere.
I just talked to the ashole that is the lead developer of forge. After complaining for about half an hour about the method I used to DEBUG this issue (even though it gives more detailed information than his method, is less prone to errors and requires less digging through Forge code) he finally accepted that something was broken in 1.11. Except that my method shows that the ItemStack class isn't even hitting the transformer while his just shows that it isn't being transformed, which he blames on a bug in the transformer itself. He also spent quite some time saying that I broke something and that he wasn't going to dig through my changes to find what it was when those changes where exactly THREE added lines, all simple calls to System.out.println. I guess I won't be asking him about potential bugs any more and since I haven't seen anyone else familiar with things like the class transformers in Forge on IRC in some time, I guess I won't be reporting complex bugs to forge any more.

**Comment by BluSunrize** [comment]
Oh, you had a run-in with Lex in his dragon form. Don't worry, we've all been there before.
Without wanting to elaborate on this too much, let's just go with "Lex can be difficult to talk to". I've had experiences of "overly positive" (when meeting him in person, he's a really nice fella and let me couchsurf in the house he rented for PAX) to "infuriating" (when getting yelled at online for even discussing the sole existence of coremods).
For future reference, consider talking to mezz. He's calm and very nice to deal with, will hear you out and can explain when and why things don't get put into forge. There's a reason he manages all PRs.

Sorry you had to put up with that, malte. Hope it didn't sour your mood too much.

**Comment by malte0811** [comment]
It's fine, I was just a bit angry since he didn't seem to listen to me at all. What timezone is mezz in or more to the point at what time of day is he usually online?
