### ISSUE TITLE
Crash on "Exiting" workshop table

### ISSUE THREAD

**Issue by skittishtrigger** [BluSunrize/ImmersiveEngineering#2202]
Forge 12.18.3.2316
Sponge 1.10.2-2281-5.2.0-BETA-2401 (I know, I know)
MC 1.10.2 
Curse modpack "FTB Beyond" 1.9(Beta)
is crash on server: yes [4G ram max.  Allocating avg. 2.3G for 10-14 players. Avg. Tps 16.5-17]
is crash on single: No/can't reproduce

Client latest:
https://gist.github.com/skittishtrigger/4760b6866a851c4fbb3620aefffa622d

Issue: [On a server]
Place workshop table
open gui
Insert furnace
Insert coal
insert cobble stone
Watch for a second to make sure it works
Hit escape to exit to exit gui
Client crashes

**Comment by malte0811** [comment]
I am not sure how this is related to IE. It is possible that I don't see the full stack trace because I am on mobile, but the last mention of IE I can find is related to journeymap and much earlier. The workshop table is not from IE, it may be from Engineer's Toolbox? I haven't used that mod in a long time if ever.

**Comment by mindforger** [comment]
there is also IC2 a bit earlier in that error-stacktraces

**Comment by BluSunrize** [comment]
`There was a critical exception handling a packet on channel engineersworkshop
java.lang.IndexOutOfBoundsException: readerIndex(3) + length(1) exceeds writerIndex(3): UnpooledHeapByteBuf(ridx: 3, widx: 3, cap: 3)`

This is not an Immersive Engineering error.

**Comment by skittishtrigger** [comment]
Sorry about that. That was not meant for here. Way too tired to be posting issues.
