### ISSUE TITLE
[Suggestion] Tesla gun/cannon & tier 2 Faraday-like suit?

### ISSUE THREAD

**Issue by VallenFrostweaver** [BluSunrize/ImmersiveEngineering#2214]
We have had the Faraday suit for some time now but with it giving protection equal to Leather and the one benefit of low voltage tesla damage being ignored.  How about a Tier 2 version that ignores or has reduced damage or even no stun effect from High voltage Tesla and offers a bit more protection? Perhaps even a Tesla gun/cannon? With the new addition of the Capacitor backpack I would imagine this would be pretty slick.  If a tier 2 armor is a no go but a tesla gun is then the Faraday suit could have the benefit of taking no damage from the tesla gun. Just daydreaming here.

![tasla gun](https://user-images.githubusercontent.com/13642054/27436966-be552a2e-5758-11e7-86fa-c0d227f621eb.jpg)
![subjectdeltaconcepts1](https://user-images.githubusercontent.com/13642054/27436970-c188b878-5758-11e7-8a03-6e8b89d9a706.jpg)

Feel free to tell me to stop at any time now. :3

**Comment by malte0811** [comment]
Better Faraday suit: Probably not going to happen, the reason the normal one doesn't work for high power is that Blu wanted the TC to be useful as a weapon against other players. Before I added Faraday suits there was no low power mode, I added it specifically for use with the Faraday suit.
Tesla gun: I don't know whether Blu would want something like this in IE. If he does not want it: I was actually thinking about implementing one in IW. I am currently working on a different new feature that is going to take some time (and I am a bit busy IRL), so I don't know if/when I'll get around to it though.

**Comment by darthvader45** [comment]
IW?  What's that?

**Comment by VallenFrostweaver** [comment]
Immersive Wiring. A mod to convert to/from IC2 power.

**Comment by darthvader45** [comment]
Oh.

**Comment by BluSunrize** [comment]
Incorrect. Industrial Wires doesn't convert, it just transports IC2 power. It also has a bunch of other fancy things Malte came up with =P

Re: Tesla Gun: I considered it once upon the time. Making the railgun "convert" to it with an upgrade, replacing its sled with a shock emitter or smth. No concrete plans though, mostly because it'd be hard to find validation for another weapon. The revolver already does decent damage, the railgun just got buffed to oneshot things with Graphite Rods.
Only interesting thing about a Tesla cannon would be chain-lightning. But due to Minecraft's very flat armor + armor piercing system, it's hard to find good balance between fundamentally different weapons...

**Comment by VallenFrostweaver** [comment]
Well, short range + minor damage over time + stun in an area I think would be most excellent. No need to go crazy on making it so different. Maybe make it also connect with a Tesla coil and therefore allow remote charging of the Capacitor backpack via that as well? I love strange use items. If you still don't think a Tesla gun is wortht it then perhaps just a faraday suit + low voltage Tesla coil + capacitor backpack = no damage to self and can charge the backpack when in it's range? maybe an upgrade to the pack itself might allow you to charge your backpack when the tesla coil is on low nearby instead of tacking damage. Eh. Just tossing out some ideas. I love the Tesla coil and Faraday suits so I'm always looking for new ways to make them more useful.

**Comment by PrincessRTFM** [comment]
If you get to charge the capacitor backpack with no faraday suit, I feel like you should take damage as normal when the backpack is fully charged. There's no more room for the energy to get stored at that point, so it starts zapping you like normal again, you know?

**Comment by darthvader45** [comment]
Agreed.  Then we could use capacitor backpacks as temporary shields against getting zapped.  Though the AvP mod will have rubber suits which protect against electrical damage, so it could simply add support for the tesla coil and we'd have a way to be immune to low-voltage tesla coils.

**Comment by theishiopian** [comment]
I've thought about this before, so heres my two cents:

The main advantage of a tesla weapon is that the electricity arcs to targets, not between them, thus removing the need to aim. The best example of a tesla weapon in a video game, at least that I can think of, is Winston's tesla cannon in Overwatch. Its short ranged, but can deliver constant damage to everything in front of it, and doesn't need to be aimed. Another thing to think about is that a tesla weapon can't hit anything that isn't touching the ground, and the user would have to be shielded against the weapon's effects somehow. Both are because a tesla coil works by creating a circuit through the air to ground. The arcs jump to targets because people conduct better than air. Now, IE uses RF instead of electricity, so it may work differently, but if you want a tesla gun done properly, thats how you would do it.

**Comment by mindforger** [comment]
i hate to say it BluSunrize
>Industrial Wires doesn't convert

the wires do not convert but the mod contains converters :P those type of which i really LOVE and like in the style by hooking a phase motor to a DC motor as a generator to make AC from DC ... that is total my impression of how it would have to be done ... but i slightly disagree on the losses malte uses by default :P

**Comment by BluSunrize** [comment]
Oh, fair enough!
I wasn't aware he had added converters. The talk came up once but I must say I didn't keep up with development.
I stand corrected ^^

**Comment by malte0811** [comment]
@mindforger The idea was for the existing converters to be semi-portable and inefficient. I was planning to add proper big multiblock converters with better efficieny like ![](https://en.m.wikipedia.org/wiki/Rotary_converter#/media/File%3A500kW_Westinghouse_rotary_converter_(Rankin_Kennedy%2C_Electrical_Installations%2C_Vol_II%2C_1909).jpg) (I hope this works, I am on mobile and don't have preview) but never got around to it. I might look into that when I am done implementing some interesting suggestions for control panels as well as a unconventional ore processing method I am working on.

**Comment by mindforger** [comment]
soemthing like factorization? *nudge nudge*

**Comment by malte0811** [comment]
Sorry, nothing like factorization, no chemicals involved. The major use IRL isn't ore processing (but it has apparently been experimented with), but it is the only use that makes any amount of sense in MC. I also wanted to try out a concept I have been thinking about for some time now.
![2017-06-20_21 54 40](https://user-images.githubusercontent.com/10406104/27581361-c87ab4a0-5b2d-11e7-8ea0-19f12ca92e6e.png) (This is the smallest version)
I haven't made any textures for it yet, mostly due to UV-unwrapping not behaving as it should in my opinion. Can you guess what it is without checking the IW repo (I am not sure whether you know about this device, it isn't too common)?
Also we are going massively off-topic here...

**Comment by mindforger** [comment]
marx generator, but for ore processing? like the an "alternate ore cushing" ?

**Comment by BluSunrize** [comment]
By all means, keep rambling, I don't mind =P

**Comment by malte0811** [comment]
@mindforger yes. I wanted to add Marx generators for some time now and I recently came across something talking about using them to get diamonds and gold out of ore. I am making them work for all ores though, MC isn't that scientific. I am properly simulating the charging though.
The idea is to have this as a high-yield manual and slow way of processing ores (also quite expensive energy-wise), so if you have just 5 or so blocks of an ore (e.g. emerald) you could manually process it using the Marx and get more out of it.

**Comment by VallenFrostweaver** [comment]
How would you keep it manual? There are multiple "user" imitations out there.

**Comment by malte0811** [comment]
I don't mean forced manual. More like "quite hard to automate" (at least without things like remote block placement).
Also the output is a normal distribution with regards to the logarithm of the energy used per ore block, with a mean value that is different for different ores and (if the config option is enabled) even for different worlds (again a normal distribution), so you couldn't just place all the ores in the generator and expect good results. The sweet spots varying between worlds is meant to prevent people from just looking up what the ideal energy/voltage per stage for a specific ore is on the internet, something which I don't really like about most reactor mods.

**Comment by theishiopian** [comment]
I love how this started as a discussion of tesla cannons and it changed to ore processing XD

**Comment by BluSunrize** [comment]
Currently no plans for additional weapons in IE.

**Comment by darthvader45** [comment]
It seems marx generators generate higher-voltage from lower-voltage DC current.  Perhaps the pulsing nature of the output could be used in a more defensive manner?
