### ISSUE TITLE
Witching Gadgets Bug

### ISSUE THREAD

**Issue by charlieg5212** [BluSunrize/ImmersiveEngineering#223]
K so after multiple hours of taking out 1 mod added at a time it is definitely this mod that is causing the issue. I've added some extra mods to the FTB infinity pack, which had included this one, and upon adding it i cannot generate any new worlds in any type of terrain gen. Upon which i get this error. I dont have a crash report cuz i dont actually crash, i just click create new world and it send me back to the main MC menu. So heres the launcher log thing. Last thing, when i have this mod installed, and it gives me this error, and only when this is added, when i close out of MC(quit game button or x in the corner) the javaw.exe and java.exe processes do not end themselves. I have to manually go into my system manager and end their processes. Which works unlike the bug from years ago in mc 1.2. I hope this helps. And thanks for all the stuff, im loving IE. I hope this is an okay way to give u this lol.

http://paste.feed-the-beast.com/view/570d7f44

**Comment by mindforger** [comment]
Caught exception from MineFactoryReloaded|CompatThaumcraft
java.lang.reflect.InvocationTargetException
Caused by: java.lang.StackOverflowError
        at java.util.LinkedHashMap.&lt;init&gt;(LinkedHashMap.java:178) ~[?:1.7.0_71]
        at thaumcraft.api.aspects.AspectList.&lt;init&gt;(AspectList.java:13) ~[AspectList.class:?]
        at thaumcraft.api.aspects.AspectList.copy(AspectList.java:34) ~[AspectList.class:?]
        at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromCrucibleRecipes(ThaumcraftCraftingManager.java:567) ~[ThaumcraftCraftingManager.class:?]

looks like an infinite loop for some unknown reason ... i suppose not IE to be responsible, try clearing you configs for MFR Thaumcraft and other Thaumcraft related Mods, as your aspect lsit "stitching" goes nuts somehow ... probably try increasing your permgen size or meaybe your initial heap size (Xms - Parameter) 

Also there is an option i know in thaumcraft config to "clear your aspect list" maybe enabling this ONCE and turning it false after loading the world may help, but be aware this may fuck up your magical savestate a little!

**Comment by BluSunrize** [comment]
Ah yes. That wonderful bug which is so easily fixed, but noone ever bothers to read the WG FAQ. Go into the config for WG, disable transmutations. Fixed.
