### ISSUE TITLE
[Suggestion] Crane Arm warehouse multiblock and Requester blocks/wires

### ISSUE THREAD

**Issue by GoneNomad** [BluSunrize/ImmersiveEngineering#2232]
A giant Crane Arm multiblock(_32x32x5_?) that will pull items I want from the warehouse area it covers and put them in a labelled container on an outgoing conveyor. Delivering it to my/any location is a logistical problem that should be fun to solve.

But how do you choose what you want? You make maps of your warehouses, attach them to Requester blocks, and you can point at a 3x3 area with a tool/hand and it tells you what items/fluids were stored there at the last Inventory Scan.

Inventory receiving area would be in a corner of the Crane Arm, a 3x3 area with storage for items and fluids that will be automatically emptied into appropriate locations. Inventory should be updated as well.

Some form of auto-crafting with Requesters (new block/wire?) to the Crane Arm for the needed items would be nice. Requests would be boxed and labelled, you have to setup your system to deliver to those Requesters, which will drop it onto Conveyors into other machines.

**Comment by BluSunrize** [comment]
Lol sure, because that isn't a logistical and programming nightmare.

Tell you what, if you can program that in a clean, efficient and acceptable manner and feature the artwork, I'd probably accept the Pullrequest =P

**Comment by BluSunrize** [comment]
Well, yes, of course I could. 
There are countless amazing designs I could do, I can even think of some features of an implementation. 
Reason for that is that I have already considered adding things like that. 

But those things are on ice, for one, for now, and very far down on my ToDo.

**Comment by Jomik** [comment]
@BluSunrize I wouldn't mind doing an attempt at some algorithms for this. However my experience with modding in Minecraft is quite limited. I could write the Java implementation of an algorithm to select inventories, etc. perhaps.
If you're interested in this.
I can't do any artwork or the like though 😆

**Comment by Jomik** [comment]
@BluSunrize I wouldn't mind doing an attempt at some algorithms for this. However my experience with modding in Minecraft is quite limited. I could write the Java implementation of an algorithm to select inventories, etc. perhaps.
If you're interested in this.
I can't do any artwork or the like though 😆

**Comment by Bihlbo** [comment]
I'm trying to figure out what this idea intends to do, in the end. Would it be something similar to multiple walls of drawers from the drawers mod, if all your items were inputting into the drawer controller? Only, instead of all the items being insta-transported, you have a really cool robotic arm that looks like it grabs the item and moves it to the container associated with the item?

Or, are you trying to achieve what a complicated series of item routers, conveyor belts, wooden storage crates, and signs can already accomplish?

Or, is this an attempt to produce something that takes up a lot of space and has cool moving parts, but is functionally an alternative for a mod like applied energistics?

**Comment by mindforger** [comment]
Last one for me :)

**Comment by HappyPineapple** [comment]
Top one for me!

**Comment by BluSunrize** [comment]
Closing this, because it's probably never happening.

If an addon wants to do this, with some cool models and stuff, help yourselves to the idea.
