### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by bookerthegeek** [BluSunrize/ImmersiveEngineering#2235]
# Heyo #
So there I was, tweaking my modpack. Just minding my own business when I get to your Amazing Mod. And low and behold something new! What are these? And automated Workbench & the Mixer! Hm, I decide to go investigate these amazing contraptions....

### Automated Engineer's Workbench ###
What! This take Blueprints and Autocrafts! This gives me an amazing idea... But I'll need some help from you. I would like some (Say... 10 of them?) blank blueprints that can be configured via Minetweaker as a shapeless crafting recipe, with a limit of 9 or 16 total ingredients (Having the ability to specify stack size would also be nice). The ability to force the crafting of items in this would be amazing to force progression. Needless to say these would not be craftable in the normal Engineer's Workbench.
- [x] Yes / Maybe
- [ ] Nope

### Mixer ###
Next onto the Mixer. The first thought that ran through me head was Alloys, and any liquid that requires mixing with solid ingredients. Say... Thermal expansion Enderium. But then debilitating sadness as I realized both that their is no Fluid Enderium without Tinkers, but also that there is no item output on the mixer. I was thinking there would be, maybe an ejection port that spits the items out into the world, or an Inventory if it is right outside the ejection port. So my request to you would be to implement an ejection port for solid outputs.
- [ ] Yes / Maybe
- [x] Nope
***
Thank you for considering my request.

**Comment by BluSunrize** [comment]
Workbench:
Any blueprint that works in a normal workbench automatically works in an automated one. Not sure if I want to change that because IE has no reason to have this gating currently. Nothing inside IE itself needs it and that's usually what I go with when it comes to changing systems.
I have been considering adding a Crafttweaker handler for Blueprints though, so that recipes can be added externally.

Mixer:
That's a harder no, because adding item outputs to that machine would mean a complete rewrite of how it works. The current recipes for mixing fluids can't easily be expanded to items (especially due to their percentual processing) and the machine was very much made with concrete and potions in mind, not alloys, simply due to the fact that IE sports no way of melting metal into fluids either.

**Comment by mindforger** [comment]
oh, thats unluky because i JUST remembered the old "enrichment" methode this one mod (the name i forgot ... the one that used mirrors and solar steam boilers to produce energy with actual voltage and current) allowed to chemically treat ores to increase the yield by dissovling the dust in acid in a mixer, and recystallizing it to get more output from melting ... and i totally had in mind to make recipes with your mixer in that style :P

**Comment by malte0811** [comment]
Factorization?

**Comment by BluSunrize** [comment]
Yep that would be factorization, and you can still do that. You just need a "Ore&Acid Mix" fluid and an "Acid" fluid. Chuck acid in mixer, add dusts, output the other fluid to....I dunno, some other machine that dries things? Get more output =P
You wouldn't mix *molten* ore with acid anyway because the acid would flashboil into steam instantly.

**Comment by mindforger** [comment]
does IE has any machine that accepts fluid input and outputs items? i just can't think of any .... i wish i had an offline manual here XD

**Comment by KaiIsCool** [comment]
yes good point... you should release the manual as a pdf or something

**Comment by bookerthegeek** [comment]
Darn... How about a new multiblock called a crystalizer that mixes fluids and solids to output another solid? Since factorization is no longer alive, you could incorperate some of that. Would be pretty cool.

**Comment by BluSunrize** [comment]
Once again: usecase? =P

**Comment by mindforger** [comment]
more immerse and intense ore refining ;D havin the mixer outputting items would allow it to be used for some awesome recipes, also maybe for some magic mixing stuff!
the issue with only liquids is that most reactions are a fluid, mixed with something solid reacting to a new solid and some reacted fluid that can be recycled in annother process then

**Comment by bookerthegeek** [comment]
Well... You could go from (Excuse the lack of interesting names)
- Ore -> Grit -> Ingot
to
- Ore -> Item Byproduct 1 -> Liquid Byproduct -> Item Byproduct 2 -> Ingots
---
So...
1) `Ore` -> `Item Byproduct 1`
   - This can happen in the Crusher. No major mod mechanic changes required, I think. Would straight up double, and would be smeltable to an igot.
2) `Item Byproduct 1` -> `Liquid Byproduct` 
    - This would be be in the Mixer. Say mixing water with the Dirty Gold Grit to produce Liquid Gold Grit. Still no major changes required to the mod. Each `Item Byproduct 1` would output some amount greater than 1000mb of `Liquid Byproduct`.
   - And if you modified the Mixture to accept the External heater from the improved blast furnace, you could have it output molten metals if Tinker is installed. Straight to the casting Basins we go! 
   - Also, If Thermal Foundation is installed, we could use the three odd fluids you get from the mod drops (Forget the name off the top of my head) to increase the output, or maybe change the output, or maybe have multiple fluid outputs. Sort of how IC2 gives you tiny piles of silver when you process lead.
3) `Liquid Byproduct` -> `Item Byproduct 2`
    - This would require a new multi-block that outputs items and has an Item and Fluid Input. Would have a chance to output additional `Item Byproduct 2` per 1000mb of `Liquid Byproduct`
4) `Item Byproduct 2` -> `Ingots` 
   - When cooked in the Arc Furnace would have a percentage based chance to output more than one ingot. This would require, I think, some changes to the Arc Furnace to add the percent based output chance.

- Both the `Item Byproduct 1` & `Solid Byproduct 2` could smelt straight to ingots or crushed into grit.
---
Out of all of that, I can do everything except for the third step, and the additional outputs per ore processed. But I can straight up Double the ores going through the other three. I do this with a massive amount of Mine/Mod/Craft-Tweaker scripting, and a couple mods to add items and liquids. Number three can actually be accomplished currently if you have forestry by using the carpenter, but this is not ideal.

So.. What do you think? Please oh mighty JavaMan... if not an resounding Hell Yeah!, at least ponder upon the idea?

**Comment by BluSunrize** [comment]
I've said again and again that I am not adding an option for Ore Multiplication beyond *2

**Comment by mindforger** [comment]
we both said nothing to actually add somethign like that to IE directly, but giving the chance to use it that way :)

**Comment by BluSunrize** [comment]
Yeah but let's retrace this conversation:
I said I don't add machines to IE unless they are used in IE. The request for a Crystalizer was argued with the usecase of Ore Multiplication, which I said I'm not adding, which in turn was debunked with "It doesn't need to be in IE itself, just the option"
But as I said, Machines don't get added unless IE itself has a reason for them. That's why I asked for a usecase in the first place ^^

**Comment by bookerthegeek** [comment]
Ok.. How about 
- Mixing liquid concrete and bitumen into Asphalt blocks? (Yes addon added stuff)
- Output Solid Concrete Block when mixing Liquid Concrete and sand.
- Liquid Dye and Blocks into colored versions of those blocks?
- Automating Treated Planks! Input creosote and Planks, output Treated Planks.

Better? =P

**Comment by BluSunrize** [comment]
Well, your 4th point reminded me: Assembler is a thing.
Allows you to replace buckets of stuff with raw fluids =P

**Comment by bookerthegeek** [comment]
Wait... Assembler takes buckets.... Did you ever play with the [LiquiCrafter](https://ftbwiki.org/LiquiCrafter)? Could you add the internal tank capability to it? Preferably more than one internal tank.... And have it use more than one recipe at a time, like the [Auto Crafting Bench](http://ftb.gamepedia.com/Auto_Crafting_Bench), maybe using... BluPrints? ;)

**Comment by malte0811** [comment]
Unless I am misunderstanding what you want you should check whether features exist before asking for them to be added. The assembler has 3 recipes, outputs of recipes can be used as inputs for further recipes and it has 3 tanks it can use to replace buckets.

**Comment by bookerthegeek** [comment]
@malte0811 My apologies, I am not currently in game so can not check upon the function of the machine.

**Comment by BluSunrize** [comment]
Yeah the Assembler has been handling fluids for ages. It's one of the first things I made it do.
It also does up to three recipes, with the ability to use their outputs in succession.

Check out existing IE features before suggesting new ones! =P

**Comment by mindforger** [comment]
i still stand the point, when there only would be a machine that would accept and output both solid and liquid, this would open possibilites with no end! i fear i did not find any such machine yet and even if the assember would, it would be the by far less immerse approach to use an assembler for "chemical" processing

but honestly i can not think of any use for IE at all ... but the most fitting option would be to give the refinery an solid in and output

**Comment by Bihlbo** [comment]
I just want to voice my excitement to see the completion of "adding a Crafttweaker handler for Blueprints, so that recipes can be added externally."

**Comment by BluSunrize** [comment]
That's in the latest 1.11 release, actually. =P

I think I can actually close this issue? Someone poke me if I missed something.

**Comment by mindforger** [comment]
Still would love to see some Mixer/refiner/reactor multiblock with liquid and item in- and output... So not know any machine capable of this yet ... Would open a hell lot of crazy recipes
