### ISSUE TITLE
Through wall wire

### ISSUE THREAD

**Issue by Auzze** [BluSunrize/ImmersiveEngineering#225]
Hi.
Not so much a issues but a request.
Can you make a through the wall wire block.

I have been using the Galacticraft one but not everyone uses that mod.

Thanks

**Comment by BluSunrize** [comment]
Why? IE wires are not meant to go through walls.
I mean, for one they can, because you can place the wall after you've made the wire and the wire will still work, but otherwise, wires just randomly disappearing in a wall look really derpy.
If you want wires through walls, try Forge multipart or something else that makes it look good or go for capacitors in the walls that you attach connectors on the out- and inside.
