### ISSUE TITLE
1.11.2 forge 2388 IE 0.11 - 63 server crash single player

### ISSUE THREAD

**Issue by 5kedone** [BluSunrize/ImmersiveEngineering#2253]
hi guy's hope you can help my game now fails to start and says kicked from server constantly here are the fml logs link, im not sure if its your mod but it is one of the last errors in the logs 

https://drive.google.com/open?id=0B7hB__yQHjUDZjdCY0ZGOTdwR2c   sorry cant paste bin too large

**Comment by malte0811** [comment]
I've made a gist of the fml-client-latest log (gist.github.com usually doesn't not complain about log sizes), see [here](https://gist.github.com/malte0811/4f6f39979347f5c1f209c0e6bfb02b5f) ([Raw link since the file is quite large](https://gist.githubusercontent.com/malte0811/4f6f39979347f5c1f209c0e6bfb02b5f/raw/bd1a40efd870da5f2a442d30bed48d250536f53e/gistfile1.txt)). I'd say this is either an Embers or an IC2 issue, there are a bunch of network errors containing those mods.

**Comment by 5kedone** [comment]
humm will try a downgrade and see if that fixes it ? you want me to post fml logs to github too ? or is that way okay
