### ISSUE TITLE
[Suggestion] Fluid Router priorities

### ISSUE THREAD

**Issue by Terpo** [BluSunrize/ImmersiveEngineering#2268]
As fluids normally do not have any kind of priority system, the Fluid Router would fit perfectly. With this it would be possible to fill your tanks and then voiding overflow fluids with a Void Pipe / Fluid Trash Can or whatever.

**Comment by BluSunrize** [comment]
Come on. At least check if something is in the game already before you suggest it >_>

**Comment by BluSunrize** [comment]
I have to apologize. I must have misunderstood that suggestion. Thought this was a general request fora 
 Fluid Router (which already exists). Blame it on me handling an issuetracker at 2am.

Priorities, as in "always try green first and if not possible to white" or something like that? That's kinda sorta possible with the current system. If you set water to go out green, it should try there, and if it can't output it should try an unfiltered output instead. So by setting green to water and white to nothing, it should route it through green whenever possible and otherwise fall back on white. Is that the requested usecase or am I misunderstanding it?

**Comment by Terpo** [comment]
Haha, I was reading the E-Mail in the bed and was worried about it as I only read the manual, which is normally really helpful ^^.  And yeah, after thinking about it I came to the same solution because it seems to work like the good old diamond pipe for BC. Try filtered first, use unfiltered if it don't fit. 

This solution should already work for me, as I only have to fill a single tank from the top. Having a real priority system gets closer to a corner case. Its on your side if you want to implement something for it :). The current solution will work for me.
