### ISSUE TITLE
[1.12] Conveyor Belts uncraftable

### ISSUE THREAD

**Issue by Skillotic0703** [BluSunrize/ImmersiveEngineering#2286]
Immersive Engineering 0.12 - 65

**Comment by BluSunrize** [comment]
Could you, you know, put *any* further detail in that?

**Comment by Skillotic0703** [comment]
Using forge 1.12 - 14.21.1.2406
This is the only uncraftable item.
The recipe is not appearing in JEI.
I tried the 1.7.10 recipe and it didn't work! 3 leather, 1 redstone dust and 2 iron ingots.

**Comment by Skillotic0703** [comment]
Do you need other informations?
Like what mod is in my pack!
![image](https://user-images.githubusercontent.com/12701912/28038346-df882ef2-65be-11e7-9705-69799235a8eb.png)

**Comment by BluSunrize** [comment]
Well, that's one of those things I usually want to know, yes. That's why you're supposed to read the fracking contribution guidelines >_>

It works fine for me:
![Image](http://puu.sh/wGpZC/0a8be5f8f0.jpg)

Next up, you should probably upload your latest client log to pastebin and link that here.

**Comment by Skillotic0703** [comment]
https://pastebin.com/TU50FUMW

**Comment by Skillotic0703** [comment]
Sorry for not giving all these informations but as it was the only item that was uncraftable I thought that it was easy to track down!

**Comment by BluSunrize** [comment]
Yeah that log actually helps quite a bit. (That's why you should always give all the info from the start ;) )

I wish Forge didn't just flat out stop loading recipes when *one* of them fails, though. Stupid approach.

Anyway, I seem to have missed a component declaration, which I didn't spot in dev because I wasn't playing with a mod that adds charcoal dust.
I'll see to fixing this quickly.

**Comment by Skillotic0703** [comment]
Thank you!

**Comment by BluSunrize** [comment]
Fixed, built, pending approval on curseforge right now.

**Comment by Skillotic0703** [comment]
Thank you it works now!
