### ISSUE TITLE
[1.12 - v0.12-67] Railgun 50% chance to hit any entity without Capacitor Backpack

### ISSUE THREAD

**Issue by VallenFrostweaver** [BluSunrize/ImmersiveEngineering#2338]
You do only get 2 shots without the backpack but all shots passed through the entities if fired at the top 1/2 of them. I equip the capacitor backpack and no more misses at all. If you aim at the feet or from above to shoot through the entities top to bottom or reverse you can hit them but otherwise the hitbox seems to become 1/2 as tall and on the bottom of the entity.

**Comment by BluSunrize** [comment]
That's a *very* perculiar issue.
Could you provide some pictures of the environment you used to test that? O_o

**Comment by VallenFrostweaver** [comment]
Sure. I'm strangely getting mixed results now and the hitting top/bottom thing is false. I suggest to spawn in several pigmen and try to shoot one that is moving or had moved. This allowed me to reproduce it.
1st is the test world.
![ie test world](https://user-images.githubusercontent.com/13642054/28423400-cf8f8e54-6d62-11e7-9f70-7a114301f40d.png)

2nd & 3rd is the area I shoot and no damage on any entities but they had been moving before I shot them (though they had stopped where I took the shot and image)
![head shot](https://user-images.githubusercontent.com/13642054/28423405-d333156c-6d62-11e7-8648-aa2eb2231cc8.png)
![head shot 2](https://user-images.githubusercontent.com/13642054/28423406-d4d33e7e-6d62-11e7-9656-ad014ae317c0.png)

**Comment by VallenFrostweaver** [comment]
EDIT: Further note that the capacitor backpack doesn't have to be equipped for this to not register hits so forget that. It's just registering hits of the railgun on entities. I used steel rods for all the testing.

**Comment by VallenFrostweaver** [comment]
POST EDIT: It appears that I have no chance of missing if I aim at the feet. Jeez this is weird.

**Comment by malte0811** [comment]
I think I might know why this is happening, I remember revolver bullets having similar issues in recent 1.11 versions. When you updated to the new mappings it seems like you didn't notice one *nasty* change: `AABB#expand` became `AABB#grow` and `AABB#addCoord` became `AABB#expand`. So code calling `AABB#expand` compiles just fine, but does something different from what it is meant to do (I only noticed this because it completely broke entity raytracing in NBTEdit). The hitpoint raytracing in `EntityIEProjectile` calls `expand` and the call (calls?) was not changed when you updated mappings. Other pieces of IE's code are probably affected as well.
I don't have any IE workspace past 1.7 with me right now so I can't test this, but I think it may well be the cause of this.

**Comment by BluSunrize** [comment]
Huh, yeah that might be it. GG MCP team for terrible mapping changes. >_>
I'll look into folllowing that lead, thanks Malte ^^
