### ISSUE TITLE
[1.12] Treated Plank Recipe Issues

### ISSUE THREAD

**Issue by oitsjustjose** [BluSunrize/ImmersiveEngineering#2344]
So it seems as though there's a bit of an issue with the Fluid Container handling with the treated plank recipe. I've been testing with:

* Forge 14.21.1.2415
* IE 0.12-67

When crafting with a non-bucket fluid container, the container handling is odd; I've had it empty too much (2000Mb instead of 1000) or destroy the container entirely. [Here's a demonstration of the bug](https://puu.sh/wP5Sq/858374282f.gif).

Let me know what else I might be able to do to provide more info.

**Comment by KingLemming** [comment]
Okay, so here's what's going on. When you told me to address the container thing, Blu - I did, lol. In the only way that is really "logical" I suppose, as I mentioned.

So getContainerItem() drains 1000 mB and returns that.

Thing is, you're handling the drain through IFluidHandlerItem, but then you call ItemStack.getContainerItem(). You should call IFluidHandlerItem.getContainer() instead.

Yeah, confusing, I know. Sucks.

**Comment by BluSunrize** [comment]
I'm not calling getContainerItem anywhere .-.
For remaining Items, I grab the default list, and then iterate through, and drain fluid where applicable. After draining fluid I then call nothing else, no container checks or anything...

So what I guess is happening is that ForgeHooks.defaultRecipeGetRemainingItems gets all the container items and then I subtract from those again, huh?
Well, tbf Lemming, you told *me* that getContainerItem wasn't supposed to drain because it was imprecise, and now you did just that. xD

**Comment by BluSunrize** [comment]
Right, I've looked into this a bit more @KingLemming.
Testing with a Portable Tank (Basic) with 3000mB of Creosote.
When IE gets to the getRemainingItems method, both the default remaining (the container item) as well as the stack in the grid (which should be the component used) have had their fluid storage already reduced to 2000mB. The reason for that is found here:
https://github.com/CoFH/ThermalExpansion/blob/1.12/src/main/java/cofh/thermalexpansion/block/storage/ItemBlockTank.java#L115-L116
You're changing the value on the stack passed in. You need to make a copy, drain from that and then return the copy. Otherwise, you're manipulating the source stack, which leads to all kinds of terribleness =P

**Comment by KingLemming** [comment]
Here's the thing - my recipes don't have this problem. And I'm doing the same sort of trickery.

But yes, I agree that I probably shouldn't be draining from the tank because it's dumb and imprecise, but I figured if you were having problems with it then other mods would too and I'd have to add it to address them.

There's also literally nothing wrong with manipulating the source stack in getContainerItem.

Again - my recipes are working 100% fine with this as it sits.

**Comment by KingLemming** [comment]
Found the difference:

https://github.com/CoFH/CoFHCore/blob/master/src/main/java/cofh/core/util/crafting/FluidIngredientFactory.java

and

https://github.com/CoFH/CoFHCore/blob/master/src/main/java/cofh/core/util/crafting/ShapelessFluidRecipeFactory.java

I'm being a lot more thorough in how I do it. I guess I need to stop being lazy and PR this.

**Comment by BluSunrize** [comment]
Well, yes, there is something wrong with modifying the source stack. It's in the crafting grid, you're modifying it directly. You're not supposed to do that.

I did fix a minor mistake on my part that caused the tanks to be destroyed when emptied, but the dual-withdrawal is something you'll have to handle on your side, because I have literally no way to check it. If the source has been modified, I can't compare it to its container item to check if they are different, because they're literally the same. xD

**Comment by KingLemming** [comment]
I just linked two files that show why you don't need to do that comparison at all. I can do the copy, but strictly speaking, getContainerItem() is meant to be called for the resulting container, after the craft has completed. That's where vanilla calls it.

**Comment by BluSunrize** [comment]
It still should not be modifying the contents of the grid.

The reason it works in your recipe is because you don't call  ForgeHooks.defaultRecipeGetRemainingItems(inv) on everything, you substitute it for fluid handler stuff.
