### ISSUE TITLE
[1.10.2] Can't sneak on conveyors, certain Assembler recipes are broken

### ISSUE THREAD

**Issue by GunmetalGears** [BluSunrize/ImmersiveEngineering#2358]
I know that the last 1.10 build has been released, but I felt as though I should leave this here anyway.
In previous versions of IE, you were able to sneak on conveyors to prevent them from grabbing you; this doesn't appear to work in .10-.61. 

Also, unrelated, but the bug with some Assembler recipes is still present. The Assembler will attempt to make things such as coal or lapis blocks and will fail; even though the recipe calls for 9, the Assembler won't craft them until it receives _81_ of the item. This is an error with Minecraft itself I've heard, so I'm not sure if anything can be done about it here. Though, I would like a solution; Minetweaker perhaps?

**Comment by BluSunrize** [comment]
I can't reproduce either of these things in 1.12

With the conveyors, is that only on a specific type of them or any? Can you reproduce it with all of them (except the covered one, since you can't really get on that)?

That assembler thing especially is something that really shouldn't happen, code didn't change too much either. IS that reproduceable with a clean instance that contains no other mod except for IE?

**Comment by GunmetalGears** [comment]
It happens with all of the conveyors. Splitting, dropping, vertical, and
uncovered.

As for the assembler, yes, it still happens. Clean install with nothing
other than Forge and IE still does it.

**Comment by BluSunrize** [comment]
*shrug*
Dunno then tbh.
Definitely not an issue in 1.12 though! :D
