### ISSUE TITLE
Wire Rendering Performance

### ISSUE THREAD

**Issue by primetoxinz** [BluSunrize/ImmersiveEngineering#236]
https://www.youtube.com/watch?v=yotpDSs7L5Q&feature=youtu.be

**Comment by Madxmike** [comment]
Since Prime didn't seem to want to write anything...

**Background:**
When trying to investigate my low fps around our immersive engineering base Prime and I decided to check the F3 debug pie chart, and to our suprise we saw that tile entity rendering was taking up 25-30% of the total render time. This seemed a bit odd and we were confused until we noticed a massive fps jump when we went out of the rendering range of the wires leading us to find that the wire rendering was taking the majority of the tile entity render time.

**The Problems:**
1. Simply put, when IE wires are being rendered they take up an unreasonable amount of time to render.
2. The render distance for the wire is based off the closest connector to you and not the connector the wire is connected to. This leads to all wires being rendered even if you are only in range of a single connector.

**Solutions:**
Neither of us have looked too far into the code the find any possible solutions, but will try to if you don't figure something out first.

**Additional Thoughts:**
We think it may actually be problem #2 causing most of the issues as it causes every possible renderable wire to be rendered regardless of if it is in range or not.

Thanks for making such an awesome mod.

**Comment by Kubuxu** [comment]
Simplest solution would be to cache vertexes of wires.

Wile CPU sampling I found that in my base up to 30% of CPU time it is `Math.cosh` (wires rendering was almost 50%)

More sophisticated method would be to render it in ISBRH (I remember that it wasn't working before) or go totally custom and use display lists form OpenGL.

The first is the easiest, it will reduce CPU load, the last is most optimized, almost no data sent GPU and CPU when wire should be rendered.

**Comment by BluSunrize** [comment]
First of all, get the latest IE. Vertices on connections are cached now so the Math.cos stuff isn't happening per tick anymore.
If you see a single Tile creating all of the rendering lag, that is because one Tile in IE renders /all/ the wires instead of every single tile rendering their own.
Lastly, I have once before tried making wires ISRBHs,the problem is the forcing of chunk render updates, which is inconsistent.

**Comment by Kubuxu** [comment]
Sorry I haven't check it previously. It is better now.
If it is any use for you there is sampling profile of 0.4.4 wire renderer:
![sampling](http://i.gyazo.com/2f984bc0679d2306dfe59d323b73ccbb.png)

**Comment by BluSunrize** [comment]
Interesting, the brightness calculation is taking quite a bit of time...
Well, performance improvement is a long term goal, so I'll keep working on it, just don't expect any rapid changes in short time.

**Comment by Kubuxu** [comment]
We've solved it but we won't spoil your learning experience. OpenGL is good stuff to know:
![https://dl.dropboxusercontent.com/u/25172450/opt.png](optimization)

**Comment by BluSunrize** [comment]
The OpenGL is not a problem. I can render it just fine. The chunk updates bite me in the ass. xD
