### ISSUE TITLE
[1.12] Client crash tesselating

### ISSUE THREAD

**Issue by OreCruncher** [BluSunrize/ImmersiveEngineering#2372]
Playing the modpack [Radon](https://minecraft.curseforge.com/projects/radon) on a server.  Wandering the world I think someones base is at the periphery of my range.  [I am getting a hard crash](https://gist.github.com/OreCruncher/fc91f8b90b28e0f84c99d249b6b9ff48), and logging back into the server causes the same crash.

**Comment by BluSunrize** [comment]
Someone has a Fluid pipe connected to something that handles capabilities wrong.

The pipe is located at 490,71,-193, and whatever it is connected to is doing capabilities wrong. I don't catch that error because it violates Forge convention to return null for a capability.

Set that block to air, then teleport there and check what it was attached to, maybe we at least know what caused it.

**Comment by mororo** [comment]
My mistake, I did not even know that there was such a way.
thank you very much

**Comment by CplPibald** [comment]
I just got this error connecting an IE fluid pipe to a Steve's Carts Liquid Manager

**Comment by BluSunrize** [comment]
Well, I explained the reason and fix in the reply above. 
Might as well close this ^^

**Comment by CplPibald** [comment]
I only mentioned as an example if you needed one.  I don't think Steve's Carts even supports capabilities.  The last real development on that mod was 1.7 I think.
