### ISSUE TITLE
Revolver ammo damage config doesn't work.

### ISSUE THREAD

**Issue by 4AM-Campfire** [BluSunrize/ImmersiveEngineering#2387]
Playing MC 1.12, IE version 70. Only IE installed.

I am trying to change the damage of Armour Piercing Cartridges so that you can kill a zombie with a single headshot, but changing the damage numbers in the config doesn't change the damage they actually do. They still do the same as default.

Casual Cartridges have the same issue, but I've not checked the other ammunition.

**Comment by BluSunrize** [comment]
Could you please show me your changed config file? (Upload to Pastebin or something)

**Comment by BluSunrize** [comment]
Ah, actually, found the issue. Bullets load before the config.
Will fix.

**Comment by PrincessRTFM** [comment]
Side note: OP mentioned killing in a single hit _with a headshot_. I haven't been able to play MC in many months, since my gaming computer was wrecked by an asshole I was living with at the time, so I'm not up to date on all the new features and changes in IE. Have you found a way to implement headshots? If so, that's pretty cool!

**Comment by BluSunrize** [comment]
Headshots have been a thing forever. There's even an achievement related to it =P

**Comment by PrincessRTFM** [comment]
Well, that's what I get for not playing since 1.7.10. :P

**Comment by BluSunrize** [comment]
It was in 1.7 too =P

**Comment by PrincessRTFM** [comment]
In that case, the problem is that I'm a shitty shot. =P
