### ISSUE TITLE
Dropping conveyor belt dupe bug

### ISSUE THREAD

**Issue by Broff574** [BluSunrize/ImmersiveEngineering#2406]
Minecraft 1.12
Forge: 2443
Version: ImmersiveEngineering-0.12-70

Crafting a dropping conveyorbelt in a tinker's crafting station would sometimes not even show the recipe correctly and when crafted wouldn't use up the crafting materials.

http://prntscr.com/g5rz5a Proof of it not showing recipe.

**Comment by malte0811** [comment]
What other mods are you using? The recipe isn't special from what I can see.

**Comment by malte0811** [comment]
I know why the output isn't showing up, MC's default NBT dependent recipe ingredient checks for equal stack size (which probably works in vanilla since potions have a maximum stack size of one). And therefore 7 conveyor belts don't count as one conveyor belt. I'll fix that now, but until the fixed version is available you can just craft them one at a time.
I didn't get any item duplication while testing though, so a mod list would still be useful.

**Comment by Kris1432** [comment]
I can provide you with a mod list in about an hour

**Comment by Kris1432** [comment]
sorry, I totally forgot to get the list, i'll get this to you asap

**Comment by Kris1432** [comment]
https://pastebin.com/nWWpFpLy

**Comment by roboderpy** [comment]
Confirmed

WebM video - [d9bc005604_%pn_-2017-08-29_09-02-21.zip](https://github.com/BluSunrize/ImmersiveEngineering/files/1258903/d9bc005604_.pn_-2017-08-29_09-02-21.zip)
