### ISSUE TITLE
Issue: Assembler not accepting water for crafting recipe

### ISSUE THREAD

**Issue by Sixer601** [BluSunrize/ImmersiveEngineering#2412]
Hello! When trying to craft fresh water (Pam's Harvestcraft) in an assembler, using the assembler's function of using a tank as a replacement for needing to fill/refill a liquid container, the assembler does nothing. I am pumping in water using thermal dynamics fluidpipe. When I place a bucket of water in the internal inventory, the assembler works just fine. 

     Thanks,
          Sixer601

**Comment by PrincessRTFM** [comment]
Does the gui show water in the tank?

**Comment by Sixer601** [comment]
Yes, it does. It also shows other liquids and allows me to do those. just not the freshwater recipie

**Comment by Sixer601** [comment]
I would assume its a weird interaction after both being updated given it worked in 1.11.2, but doesn't work now. I would not know where to look to see how to fix it, if i could by changing something or adding a recipe.

**Comment by PrincessRTFM** [comment]
Keeping in mind that I'm not looking into the code of either mod, but I am a programmer and have done MC modding in earlier versions, my best guess is that Pam is no longer looking for fluid containers, but rather specifying items that logically hold water, OR something in IE is messing up with this individual recipe, probably because: a) there's only one item and it's the fluid container, so there's nothing physically in the crafting grid, or b) because it's water specifically.

Suggestions: look in [N/J]EI at the fresh water recipe. What items are shown? In JEI, you can hover over the item and it'll say "accepts any X" if it uses the oredict, I would assume it does the same with fluid containers. Also try the milk bucket -> milk whatever recipe, if that still exists. I know it was there in 1.7.10. Finally, try recipes that use water containers and also other items to see if it's failing with any water container.

Of course, if someone more knowledgeable (like Blu) comes in and contradicts me, ignore me. These are just guesses based on reported symptoms.

**Comment by BluSunrize** [comment]
Pam probably moved to a custom fluid ingredient, as she should. I'll get to handling it in due time, calm yer nips. 

If Forge had a proper Fluid Ingredient we wouldn't have this issue at all
