### ISSUE TITLE
Lower Turret Aiming

### ISSUE THREAD

**Issue by HappyPineapple** [BluSunrize/ImmersiveEngineering#2420]
So If i mount a turret on top of a wall it doesn't fire Help!

**Comment by malte0811** [comment]
Some general info would be nice. See [here](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/CONTRIBUTING.md).

**Comment by HappyPineapple** [comment]
Note: This Is a foced crash report.
[https://pastebin.com/H0QL6tD6](url)
see?
![2017-08-14_18 35 15](https://user-images.githubusercontent.com/30999331/29264370-2a135c90-8120-11e7-9cb6-2873cb4e67b3.png)
![2017-08-14_18 35 25](https://user-images.githubusercontent.com/30999331/29264371-2a170520-8120-11e7-88a5-f68452af35c7.png)

**Comment by HappyPineapple** [comment]
# Note: inverted redstone control and nothing happened.

**Comment by BluSunrize** [comment]
It doesn't search for targets that far down, because the render would look terrible collide with itself if it tilted that far.

**Comment by mindforger** [comment]
can it be placed upside down? like hanging from an ledge or sth?

**Comment by BluSunrize** [comment]
Nope it can't because effort and blockstates.

**Comment by mindforger** [comment]
alsways those damn blockstates ...

**Comment by HappyPineapple** [comment]
what is a "damn blockstates"?

**Comment by malte0811** [comment]
Blockstates are somewhat like metadata for blocks, but allow more and properly labeled values. You can see them in the right of the debug screen when looking at a block. Having a lot of them eats up memory since each of them has a model asigned to it (that is why 1.8+ needs so much memory).

**Comment by HappyPineapple** [comment]
What's metadata?

**Comment by PrincessRTFM** [comment]
Technically speaking, metadata is "data about data" - that's what "meta-" means, "about itself". In MC, "metadata" is additional data about things. For instance, items: they have an ID, which is how the game identifies what internal "object" the item represents. That's how handlers work, the game says "this item has this ID, which is associated with this internal bit of programming, and there's a handler for this event in that bit of code". But there's also "metadata", which is often called the "damage value", because it was originally used by tools to indicate how damaged they were. It's also used, for example, by wool to indicate what colour the wool is. Some mods use metadata to differentiate between their in-game items, which reduced the number of item IDs used back when numeric IDs were still the only kind. The thing is, metadata in MC is a number. I don't remember the width, but that's not important right now anyway - what matters is that there is a finite number of possible values for metadata in MC, and that severely limits how many "states" you can save in it when you have to account for overlap.

Overlap, here, means that you have to be able to specify "this thing has state0, and also state3, and also state4". I won't go into how programmers generally handle that, because it's non-"standard" math, but know this: when using numbers to represent potentially-overlapping states, the upper bound of the number grows exponentially.

**Comment by BluSunrize** [comment]
In any case, we are well past the cause of the issue.

Turrets can't aim down because the render would look shite, and they can't be inverted because I cba.
