### ISSUE TITLE
[Suggestion] Chemical Thrower - Multitank

### ISSUE THREAD

**Issue by Terpo** [BluSunrize/ImmersiveEngineering#2426]
Just saw Pahimar playing with your Chemical Thrower and had an interesting idea.

A workbench addon that does not increase the tank size but split the original size in 2 - 4 smaller ones. Switching through each tank could happen with a key binding. As far as I know the thrower can handle potions right? So this could be really useful if you want to buff yourself / teammates with the thrower instead of potions.

**Comment by BluSunrize** [comment]
That is actually a pretty excellent idea!
Multi Tank Drifting...ehh... chemical throwing. I can look into that!

Keybinds are...iffy, but unavoidable, I guess. They are easy to do in code, I just hate how many there are and how often they conflict. I wish there was another option, but alas, the Chemical Thrower already uses sneak+click to toggle its pilot light.

**Comment by Jhanter** [comment]
What about shift + scroll for rotate the tanks?

**Comment by BluSunrize** [comment]
That could work...

**Comment by HappyPineapple** [comment]
poilot light ?

**Comment by xenxero1** [comment]
Sneak-Scroll reminds me of Ars Magica's system with their spellbooks. Would be interesting to see the future possibilities of 4, maybe even 6 separate small tanks to rotate between.

**Comment by BluSunrize** [comment]
I was thinking three, actually.

And yeah, I've done shift+scroll for other things before, probably nicer than keybind.

**Comment by HappyPineapple** [comment]
ooh how about a backpack tank ?

**Comment by PrincessRTFM** [comment]
I don't much like shift-scrolling (hated it back in AM2), because it messes me up when I'm crouching, but this doesn't seem like the sort of thing I'd be crouching while doing, and it really is better than adding another two keybinds. I've literally run out of keys, I have to turn a bunch of keybinds off to let me use the most useful ones. I think part of it is that a number of mods allow keybinds for things they really don't need to, or have more keybinds than necessary.

Suggestion/request: in addition to the shift-scroll thing, please also add some kind of chat command to change tanks, cause then I can use the macro/keybind mod instead, and make shift-scroll disablable in the configs so I can avoid problems with crouching.

**Comment by KnightMiner** [comment]
Why not just add a keybind that is disabled by default?

**Comment by BluSunrize** [comment]
^ that
I'll add a config to disable it and an unbound keybind.
