### ISSUE TITLE
Applied Energistics 2 integration 

### ISSUE THREAD

**Issue by drmorgmd** [BluSunrize/ImmersiveEngineering#2434]
I don't know if it is possible to add AE2 cable integration to IE. For example be able to wire cables from relay to relay that way you can keep a theme. I just think it would be cool to be able to use the post with the cables instead of hiding them.

**Comment by kane-thornwyrd** [comment]
imho it's not IE relevant, more of a third party mod, like [Immersive Integration ](https://mods.curse.com/mc-mods/minecraft/232159-immersive-integration) was.

**Comment by drmorgmd** [comment]
Well that would be a cool to be updated to the newer versions of minecraft. I would definitely like to see that.

**Comment by kane-thornwyrd** [comment]
Well, try [Twitter](https://twitter.com/UnwrittenFun) or [CurseForge](https://minecraft.curseforge.com/private-messages/send?recipient=UnwrittenFun) or you can [open an issue in the mod](https://github.com/UnwrittenFun/ImmersiveIntegration/issues/new), but here is not the place, I guess, imho.

**Comment by BluSunrize** [comment]
Unwritten won't update, I'm quite sure. Too busy. That's why I ported RS wires to the main mod. 

I never liked the AE2 compat though, so I won't be porting that.

**Comment by PrincessRTFM** [comment]
Honestly, AE2-type storage mods just don't feel like they fit with IE. I feel like storage in an IE-based modpack should involve an input chest that conveyors items to storage chests through sorters, but then you have to actually go to the storage chest to get things back out. Admittedly, I don't like that kind of storage system as much, regardless of the mechanic used to sort things, because of the potential for overflow, but if you can assign priorities to the sorters somehow, so that you could have entire chests filled with whatever things you expect lots of and then overflow is dumped to a trash can, that'd be pretty good.

Anyway, yeah - AE2 compat just doesn't feel like it fits with IE.
