### ISSUE TITLE
[Suggestion] Add A Grapple Hook

### ISSUE THREAD

**Issue by HappyPineapple** [BluSunrize/ImmersiveEngineering#2441]
So We have the Engeneers shy hook but you need a wire to use it so I was thinking that a hand held fireing meckisum tobsoit a temporary cable for the sky hook so wdy think ?

**Comment by MalkContent** [comment]
I mean i can read through most of the stroke, but what does "tobsoit" mean?  
Also there was a grappling hook kind of thing that got removed (3d maneuver gear from attack on titan) because it didn't fit with the rest of the mod, iirc.  
Your idea might be more of a fit though, but try typing that out in more that a single sentence and using real words and stuff.

**Comment by BluSunrize** [comment]
Malk, harsh calling it a stroke. I would have just said "Rip English Language, ~500-2017" =P

Anyway, yeah, Maneuver Gear got removed because fuck syncing projectiles and doing player motion.
Grappling hook is unlikely to happen.

**Comment by HappyPineapple** [comment]
@BluSunrize more like rip auto correct 1995- 2017-18
