### ISSUE TITLE
[1.12.1] [v0.12-71] Game briefly freezes while opening an Assembler

### ISSUE THREAD

**Issue by MrBurd** [BluSunrize/ImmersiveEngineering#2449]
I've set up an Assembler multiblock, have not powered it, configured or added any item or fluid.
Upon right-clicking the multiblock to open the gui, the game lags for about half a second.

Console displays this message:

> [22:53:46] [main/WARN]: Something's taking too long! 'root.scheduledExecutables' took aprox 418.882077 ms
[22:53:46] [main/WARN]: Something's taking too long! 'root' took aprox 440.119366 ms

Indeed, checking the Alt+F3 profiler, immediately after opening the machine the root.scheduledExecutables part of the pie chart and spikes to >50% and quickly(within a second) drops back to about 0.10%.

If I have the root.scheduledExecutables part selected while opening, the [?]unspecified part of the pie chart is the one that spikes, all other parts("getBrightness", "checkedPosition < toCheckCount" and "checkLight") go unchanged.

I have tried using other IE machines such as coke ovens and advanced blast furnaces, neither of those displayed a lag spike upon opening.

This bug happens consistently even after rebooting the client and relogging multiple times.

**Comment by BluSunrize** [comment]
I'm finding myself unable to replicate this. My performance is stable and the scheduledExecutabes are not showing any noticeable spikes.
Could you possibly provide some additional information of your system specs?

Very close to the start of your console/logfile, Forge prints out "[FML]: -- System Details --" followed by a stat block. Could you please copy+past that?

**Comment by MrBurd** [comment]
Will do, expect results in a day or so.

**Comment by MrBurd** [comment]
Here you go: https://gist.github.com/MrBurd/89d0c0afdf0f0e4cc537cfda90ba3d23

Additional specs:
CPU: i7 920 @ 2.67GHz
GPU: NVidia GeForce 660 Ti
RAM: 20 GB DDR3

**Comment by BluSunrize** [comment]
Huh.
Yeah I'm a bit confused myself. Can you replicate this with just IE installed and no other mods?

**Comment by mindforger** [comment]
an I7 920 is not the fastest CPU in da house, maybe he notices the lag more clearly because your system runs way faster than his?

Blu, can you imagine any "sheduledTask" that has to do with recipes or maybe some ASM stuff when opening the GUI of the assembler

becasue what i recognized is sometimes when classes are unloaded and getting loaded again the garbage collector can sometimes take a long time to clean the memory, especially when they are compiled in the process (there is a JVM parameter that forces unloading for the sake of less GC cycles but causes the GC to run over bigger chunks of data then)

@MrBurd also reduce the assigned RAM down to 4GB or even less, when the GC is not optimized, you will have less GC cycles but the cycles will become very time cosuming, resulting in a few very very long lags whenever the GC is running
