### ISSUE TITLE
MultiBlock Ticking TE performance

### ISSUE THREAD

**Issue by cjm721** [BluSunrize/ImmersiveEngineering#2468]
All IE multi-blocks have every sub-block as a ticking TE. Per multi-block only one TE should need to be actually ticking the rest do not. On a server with nearly 10k IE TEs the simple if at the beginning of TEs add up (about 5% of the server tick). They are also not able to be optimized out by the JIT because the class has other instances where the entire method must be run.

**Comment by BluSunrize** [comment]
Alas, TileEntities can't be created well dynamically. The creation method for them supplies a world and a metadata, and that's it. Can't easily do a differentiation between ticking and non-ticking with that.

Plus, some of them use their update methods for animation or particles.

**Comment by malte0811** [comment]
What kind of server size are we talking about here? 10k seems quite extreme, are you sure this isn't caused by some sort of chunkloading/ghostloading/etc issue? This is the first time anyone complained about it IIRC, and they have ticked for 2 years now. I'd consider this pretty low priority, it is fixable without breaking compatibility though.
@sfPlayer1, you analyse server performance quite often, right? Have you ever seen anything like this (or any other performance issues caused by IE except for bad conveyor setups)?

**Comment by malte0811** [comment]
@BluSunrize that's the old ITileProvider method. The current recommended method is `hasTileEntity`+`createTileEntity` from Block, that `createTE` method has a blockstate parameter.

**Comment by BluSunrize** [comment]
Ah right
Well even with that, you'd still need unique blockstates for each master, which would be a massive and rather annoying rewrite .-.

**Comment by sfPlayer1** [comment]
I haven't looked at real world profiling data recently, so I can't provide any data. Multi-blocks and cables are however known to cause overhead from just their quantity alone.

There are two ways to control TEs:
- Use null for Block.createTileEntity, create them explicitly from the item placing the block. Once placed the TE id gets saved and a id->cls lookup and default constructor invocation on cls restores the TE instance (see TileEntity.create).
- Remove TEs that don't need ticking from World.tickableTileEntities after the fact.

IC2 uses both successfully, a more explicit approach in Forge could be more convenient though.

**Comment by BluSunrize** [comment]
Removing it retroactively sound like an immensly hacky approach.

**Comment by sfPlayer1** [comment]
The addition is strongly tied to the class hierarchy, which isn't always feasible to change - especially if it only needs to tick clientside or serverside. Removal is cheaper than letting it tick forever.

**Comment by cjm721** [comment]
Changing a TE after placement is not complicated. You can start them all out as Ticking then then they find they do not need to tick you can use World::setTileEntity and replace it.


Why I found this:
I got tired of all the tick issues on my servers so been using a profiler and going down the list looking for easy areas of improvement.

**Comment by malte0811** [comment]
I'll try to fix this, I think I've found a reasonably clean solution.
@cjm721 again, is 10k TE's realistic for your server? That would be roughly 130 arc furnaces, which are about the biggest multiblock I can think of right now. What version of MC, Forge and IE are you using? And is this a normal Forge server or something like SpongeForge?

**Comment by mindforger** [comment]
@malte0811 i know at least 3 guys that hollow out an entire mountain from around level 120 to almost bedrock to build their processing factory ... 130 arc furnaces(if i turn that down to be not only arc furnaces but also the required generators, squeezers/fermenters and refinerys to power them) is not so much as one would think, if you are this kind of player :P and those kind of players is more common than one would think in the first place :D

**Comment by cjm721** [comment]
In total I have near 50k TE loaded with about 20k of that being ticking TEs. I can get you the exact breakdown if you want but 2k of them are water mill, 1.5k coke oven 1k blast (from my memory). 

In general have about 10-20 people on constantly. Forge's current chunk loading issues are not helping but it did get me actually look at what where the top users.

**Comment by malte0811** [comment]
As it says in the commit message I hoped for a cleaner way to do this. One of the main issues is that I can't inherit static variables (probably the wrong term, I want to define `TEMetalPress.x`, `TEBucketWheel.x`, etc. in `TEMultiblockPart`, but still set/get them separately). This is obviously still a mess, but I'd like some opinions on the general approach.
I'll be away from coding until at least Sunday afternoon, possibly later, so don't expect any quick fixes.

**Comment by cjm721** [comment]
The asm code is a bit of a stinger but it looks like it would work. 

A possible cleaner solution could be to just make a wrapper that extends TE but not Tickable that delegates all calls to the internal TE. Would be a class with every single method of TE but should be easier to follow then ASM

**Comment by malte0811** [comment]
That would break every instanceof check in existance. And I didn't want to manually create a subclass of every multiblock TE.

**Comment by BluSunrize** [comment]
Hmm, I'm not sure if ASM is the best way to go about this.
I mean apart from other devs getting heart attacks when the abbreviation is only mentioned, but for the sake of code cleanliness, I think Player's idea of removal from the list may be rather sensible.
(Although I will admit, I have not actually checked how hard it is to remove them and keep them removed)

**Comment by malte0811** [comment]
That should actually be rather easy (may need an AT though). Keeping them removed also shouldn't be hard, they won't be readded every tick and they will be removed immediately after being added. Ghostloading may be an issue, but that is the case in many other situations as well. I'll try implementing this "soon".
BTW (I noticed this yesterday): There are 2 types of blocks that need to be dealt with: MB's (which I did in my commit) and `IHasDummyBlocks`'s (which I tried handling yesterday). The latter are relevant mainly due to waterwheels and are less easy to deal with since they don't have a common superclass.

**Comment by BluSunrize** [comment]
Oh right, those are a thing.
Well, we'll probably want a Utils method then, something like `Utils.removeTileFromTicking(this)` and just run that for the dummy ones affected.

**Comment by cjm721** [comment]
The ticking list is just a field variable in world so not hard at all to get via reflection (and cache the Field class) and then you can just remove yourself from. It will be O(N) for each TE so really O(N^2) due to it being a list not a set. It would be more efficient to add to your own to be removed list and then on post server tick do a remove if through the list to keep it at O(N) total.

**Comment by sfPlayer1** [comment]
Not worth it, N is small and the operation cost per N is cheap. The field (World.tickableTileEntities) is already public.

**Comment by malte0811** [comment]
I was going to say basically the same thing, but I'd like to add one more detail:
It wouldn't be O(n**2), it would be O(n*m) (n: total ticking TE's, m: multiblock TE's to be removed). n wouldn't really be small (20k), but m would be reasonably small (maybe a few 100). That+the fact that the code wouldn't run on a regular basis makes the extra remove list quite unnecessary.

**Comment by sfPlayer1** [comment]
For the record the overhead for the rather extreme 20k items (n), 100 random ones to remove (m) case is:
- individual ArrayList.remove: 0.6 ms
- ArrayList.removeAll(ArrayList): 0.8 ms
- ArrayList.removeAll(HashSet): 0.3 ms (not including set creation)

As one can see the overall cost isn't very significant in either case for such a rare operation. RemoveAll without a temporary set is actually slower for the given size ratio since removeAll does n*m lookups and 1 move, while individual removes do ~n/2*m lookups and m moves of length ~n/2.

**Comment by cjm721** [comment]
Talking worse case its still O(N*(N-#MultiBlockStructures)) (when all TEs are from IE). Thing is when a base is loaded with 10k + IE blocks 90% of those are going to be turned into non-ticking. So that remove is not going to be trivial, especially since chunk loading / unloading can happen many times per second. 

On average ya its trivial but on those few ticks it would be game freezing. Forge finally just implemented some stuff to make chunk unloading not take as long and this is basically just a subset of that same conversation. See: https://github.com/MinecraftForge/MinecraftForge/pull/4281

**Comment by malte0811** [comment]
There's that, a lot less messy than the other attempt (Yes, the commit note is slightly wrong).
I went for the central removal call after all, but not for performance. `update` is called while an iterator is running on `tickableTileEntities`. Since it's just a normal `ArrayList` removing TE's in `update` causes CME's.
`isLogicDummy` is separate from `isDummy` due to the mess of code that is called a current transformer, `isDummy` is used for placement and returns true for the top block, but that is the block running the logic.
I put the helper method in `ApiUtils` since it is relevant for addons (IW in future versions, IT, IP).

I'll push this to master once Blu confirms that this implementation is ok

**Comment by BluSunrize** [comment]
Yeah I like this version a lot more.
And I do agree with you, the current transformer turned out to be a massive pain in the butt, but I don't think it could easily be changed between versions.
Should definitely do something about it for 1.13 though, whenever that happens.

Otherwise, this looks solid, and if you managed to at least not have it crash, we should be alright.

**Comment by malte0811** [comment]
I've pushed it to master, the maven builds should be done in ~5 minutes.
@FerroO2000, @Flaxbeard, you might want to call this in your MB update methods as well.
