### ISSUE TITLE
Scale water wheel speed to max out at one row of flowing blocks

### ISSUE THREAD

**Issue by TheFurtivePygmy** [BluSunrize/ImmersiveEngineering#2474]
Currently, water wheels incentivize placing floating water blocks on top of the wheel, which looks and feels silly. A player is not likely to ever find a naturally-occurring, sloping river or waterfall. In the vein of the windmill height bonus being removed, water wheels should max out at one row's worth of flowing blocks.

**Comment by MalkContent** [comment]
Any naturally-occuring flowing water is an oddity, really. Outside of caves, your best shot probably is vertically flowing water from outside hills.
Also feeding a water wheel from top is a real thing:
![Water Wheel](http://www.waterwheelfactory.com/wpimages/wpcfee4419_05_06.jpg)

That being said, currently the most efficient way to drive a water wheel known to me is this:
![Munchkin Water Wheel](https://i.imgur.com/XDTetHZ.png)

Which drives the wheel at all sides but the upward going one.
Downside: It can feel a tad silly.
Upside: You have to come up with it.

Using/Abusing mechanics to your advantage is one of the fun parts of (modded) minecraft. When it's too stupid/unbalanced/whathaveyou the mechanics probably should be dealt with, ofc.

My point being: I feel like this instance is close to the line, but should be considered to be kept, because i think a good number of players enjoy stuff like wrestling an extra few IF/t out of it with clever thinking and the difference is small enough to not give a gamebreaking advantage.
I forgot what the issue with the height bonus was. Maybe it renders my point mute.

**Comment by BluSunrize** [comment]
Top feeding is very common practice, and one of the original ways I designed the wheel to work.

The thing with placing extra water on the opposite side and doing that little corner bit is a tad annoying, I do agree, but not very easily avoided. The waterwheels don't do a check of "if water there and there and there, spin this fast", they actually make use of the Fluid Block's flow vector. Minecraft has a method for its liquid blocks to specify a vector that indicates direction and strength, and is generally used to push entities around. That's the same vector I use to determine speed and direction of the wheel.
An excellent example to this is using a slower fluid, like lava or molten metal, they will make the wheel spin slower.

So given that, the code is very much designed to handle this dynamically and therefor allows for some tiny exploits. That said, it is very much up to the player and you get very little extra power from it.
If people want to be silly and MinMax it like that, so what. I take pride in the users that don't do that but instead build their waterwheels to look asthetic and pretty and integrated with their builds, even if that means sacrificing a few RF per tick.

**Comment by TheFurtivePygmy** [comment]
I want to be clear that I'm not talking about exploiting the mechanics. With the way Minecraft generates worlds, the only reasonable way to place a water wheel and have it look like a water wheel is to place it in one layer of water, which gives you about a third of the potential turn speed. I'm the kind of player who goes for aesthetics, but this is sacrificing a lot more than a few RF. There's a difference between building a pretty watermill that doesn't work very well and taking the time to build one that barely works at all.

Config options for max turn speed and turn speed per flowing block would be fine.

**Comment by EvilCooky** [comment]
If you want your Waterwheel to fit into the environment, you can just make your own river.
I did that on one map at the side of a hill.
Made river come out of a cave and run down the hill, then over my waterwheels.
Looked good and produced enough energy.

**Comment by ktole1999** [comment]
i have a man made lake that is dam'd up with water wheels integrated. who cares what the world generates. build it. :)

**Comment by BluSunrize** [comment]
Renderwise the speed is not adjustable, but there is config which allows you to buff the output of the kinetic dynamo, so you can still get worthwile power with a non-toploading waterwheel setup.
