### ISSUE TITLE
[1.12.1] enhancement request: Make it possible to blacklist items for garden closh

### ISSUE THREAD

**Issue by DietmarKrause** [BluSunrize/ImmersiveEngineering#2480]
For modpacks it can be usefull to have some seeds / items blacklisted for the garden closh while having other sseds still be working. There ist a heavy discussion going on in the pack All the mods 3 for MC 1.12.1. In the last update of the pack the garden closh is made unreachable. In my opinion it would be better to have a few seeds blacklisted if that is possible while others work fine instead of changing the recipe in a way to make it unreachable.

**Comment by BluSunrize** [comment]
I am unfamiliar with the issues the ATM devs are experiencing.
Could you please detail which seeds they have deemed imbalanced to result in a ban of the cloche?

**Comment by OrdinatorStouff** [comment]
Hello @BluSunrize ATM dev chiming in here:

Background: In a recent update a few days ago I customized the recipe for the garden cloche in ATM3 to one that requires quite a bit of work through multiple mods first before the cloche can be crafted. It's meant in a way that once that level has been obtained it's easy to continue to craft many of them just first getting over that initial "hurdle." 

Why: I've read many times over that you balance IE with vanilla in mind, and other mods (especially in larger packs) tend to upset that balance and I would agree. ATM3 is not an "expert" pack so the recipe change was upsetting to some, but in reality the alternative considered was removing/disabling the Cloche altogether due to lack of options in ways to "balance" it's usage with the rest of the pack's content. In our pack, we feel that with default power consumption, speed of crop maturity, and water/bone-meal requirements the Garden Cloche is "unbalanced" for everything the pack has to offer in terms of growables (including but not limited to Mystical Agriculture, for example).

@DietmarKrause I believe created this issue in hopes that having the option to blacklist some seeds would be a sufficient enough customization for us to decide to revert the difficult custom recipe. As a pack dev I welcome any mod's inclusion of customization configs and would appreciate such a blacklist/whitelist. Personally, I want our players to be able to have walls of cloches mass-producing growable diamonds and steel and anything else they want en masse, without a blacklist. Any crop that we deem fit to be enabled that can be farmed in parallel across chunks of tilled soil and automatic harvesters is also fit to be mass-produced via the cloche. The difference being the time/space needed to manage a large farm and slower speed of growth versus the convenience of having what amounts to a ~15x15 fully-automated crop field condensed into a single-block-footprint machine that sits neatly in the corner of your base is (in our opinion for our pack) enough to justify making "balance" changes. 

We love the Cloche, our players love it, I haven't met anyone who didn't really like the cloche, but in it's default state, it trivializes all other methods of automating growables. We wanted to make it something for our players to feel rewarded for working towards and earning and being proud of while still making it's *usefulness* just as convenient. 

For me, config options that I think would matter are power usage multiplier, water consumption rate, a requirement to need bone meal or other fertilizer (non functional without), and the aforementioned whitelist/blacklist of seeds would be useful too for any particularly overpowered mod seeds if applicable. I'm pretty sure I recall seeing other issues or requests for similar configs and while I would love for any of them to be added, I'm not sure if that would change my stance on our decision to "nerf" the crafting recipe even if they were.

Thank you for your mod and all that you do,
Ordinator

**Comment by BluSunrize** [comment]
Wow that was an indepth post.
I'm generally not too fond of making everythign overly configurable (due to heavy misgivings towards the FTB teams use of them in the past, and the resulting shitstorm about entitlement).

Now black- and whitelsits for the cloche are somethign rather difficult to achieve due to its inner workings. Specifically, it has a separate "recipe" for each plant. I can't do a configoption to allow people to just add seeds, because each cloche entry requires information on output, rendering and growth performance. It's simply too dynamic to be done with a simple list of strings.
Blacklists, while possible, don't really serve a use for similar reasons, because the only seeds supported are the ones me (or other devs) specifically write compatability for. The vanilla ones I basically hardcoded, and any from other mods can be disabled by disabling IE's relevant compat module.

Energy consumption already is configurable, it's the value "belljar_consumption" in the config.
Similarly, the amount of ticks one dosage of fertilizer (a mix of fluid+solid) lasts is defined by "belljar_fertilizer".
And lastly the amount of fluid consumed for each of those dosages is defined by "belljar_fluid"

Those three options provide the ability to adjust power and waterconsumption, as well as changing the duration a piece of fertilizer will last.

I haven't considered a "mandatory" fertilizer setting as this seemed rather harsh of an option, and is not one I am aware of with other automated farming machines.

**Comment by OrdinatorStouff** [comment]
After explaining the technical workings regarding seed use in the cloche I understand fully how white/blacklist configs would be overly complex for ultimately a niche "need"

I also was not aware of the config options already being included. I apologize for not being more thorough in investigation before posting those as embedded suggestions to my post.

As far as I'm concerned from a pack perspective, individual seed white/blacklist is not necessary; the mod integration compat options being sufficient as I'd think would be necessary for this situation.

As for the custom recipe in ATM packs I'll review and reconsider alongside those configs you mentioned are already available. I probably *could* find a happy "balance" with just those configs and its default recipe, but I made the recipe change for "flavor and style" just as much as for balance and as such might keep it how it is currently.

The Cloche is one of those machine/tools that is hard to quantify objectively because there are desired aspects of it that can't be measured comparatively (for example, the Cloche model looks amazing; something players **want** in their base or to make a factory out of). My decision in applying balance changes to the Cloche is about more than just the math of "in some other mod I can produce `X` crop output fully automatically per minute with `Y` RF and `Z` fertilizer" making the cloche match exactly because even if 1:1 statistically, there are subjective non-quantifiable traits that still make the Cloche more sought-after.

Thank you again for your time, @BluSunrize and the hints to those config options already present. As a pack dev I am highly appreciative of having those options available.

**Comment by BluSunrize** [comment]
I'll close this then, since all points seem to be covered.

Shoutout to the overwhelming politeness on this issue, btw, I thoroughly enjoy when the community interacts like this. ^_^
