### ISSUE TITLE
Looking at Toolbox Causes Crash

### ISSUE THREAD

**Issue by Koltanas** [BluSunrize/ImmersiveEngineering#2496]
Just Dowloaded the lates IE version 0.12-72 and I wanted to check if you really can use the toolbox now. Unfortunatley looking at the toolbox caused the game to crash(tested it twice)
Crash-Report:
https://gist.github.com/Koltanas/d33b1e8bd251422cfd21deca7b01ebdc

**Comment by malte0811** [comment]
This is probably my fault, I'll take a look once I'm back from Uni.

**Comment by malte0811** [comment]
Fixed for the next release. The cause was there ever since the placeable toolbox was added (The block thought it had 27 slots, 4 more than the item, probably because the TE is based on the crate TE), it just never was a problem before.
This might work around the crash/make the world usable again: Disable WAILA (probably in the mods folder, not in-game), take everything out of the box, break it (it won't drop anything and cause an error in the log, that's why you should take out the contents) and re-enable WAILA afterwards. And obviously don't place toolboxes on the ground until you have the new build. The item should work just fine though.
