### ISSUE TITLE
core mod being down loaded seperally

### ISSUE THREAD

**Issue by redo6565** [BluSunrize/ImmersiveEngineering#2509]
core mode is being downloading seperatly curse reading it has a non curse file.

**Comment by BluSunrize** [comment]
It's not being downloaded, it's shipped with IE. This is Forge's system convention, not my fault.

**Comment by redo6565** [comment]
actully it is being downloaded try it

**Comment by malte0811** [comment]
It is not being downloaded. It is inside the normal mod when you download it, Forge will extract it when you start the game.
If you want proof: download IE, put it in the mods folder. Disconnect you internet (disable wifi or unplug the cable). Start the game in offline mode and see whether the core mod is still "downloaded".
@BluSunrize sorry, I didn't expect the new guidelines to cause this sort of trouble (both this and the curse issue). I thought about technical issues, not about user reactions to unknown things.

**Comment by BluSunrize** [comment]
Yeah because when the mod dev tells you "It's not being downloaded" the correct reply is of course to disagree. <_<

Malte, for clarification's sake, do we *need* a separate binary? Because Forge's guidelines just say "Coremod must be the coremod only, and no extra library/features/apis/etc."
They don't actually *say* anything about a different jar file for it. I got thinking because I don't think anyone else does this with theirs. I'm all for pioneering stuff but maybe we misinterpreted it? :V

**Comment by malte0811** [comment]
If we don't put it in a different jar file we have more than just the coremod in the jar containing the core mod, that is how I understand these guidelines (IIRC doing that even logs a warning). It is well possible that we are the first to implement these guidelines in an actual mod. The only other implementation I've come across is @PaleoCrafter's demo mod. That demo mod as well as the comments on the coremod policy thread suggest that this is the intended method (+Lex approved of my implementation of the guidelines, so I'd assume I interpreted them correctly. I just can't dig out his exact response right now since that is on my old computer).

**Comment by BluSunrize** [comment]
Yeah I actually just poked him on IRC and apart from a few comments of "just not making a coremod" he confirmed that separate binaries are correct.
He also discouraged deleting the file upon shutdown. So I guess we'll just have to deal with continued user stupidity and keep telling them to delete the file when uploading to curse.

Let's see how many more issues we'll get in the next month due to peopel being to dumb to use a searchfunction. My guess is about 5.

**Comment by redo6565** [comment]
sorry i miss understood what said the first time.. thank you though
