### ISSUE TITLE
Crash On Startup

### ISSUE THREAD

**Issue by 0dikpah** [BluSunrize/ImmersiveEngineering#2522]
Minecraft 1.12.1
ImmersiveEngineering-0.12-71
Forge 1.12.1-14.22.1.2485
[crash-2017-09-23_18.33.09-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/1326672/crash-2017-09-23_18.33.09-server.txt)

**Comment by malte0811** [comment]
@Ellpeck this is on your side from what I can see. The code is passing the block breaker blockstate (`state`) rather than the state of the block to break (`this.world.getBlockState(coordsBlock)`) [here](https://github.com/Ellpeck/ActuallyAdditions/blob/master/src/main/java/de/ellpeck/actuallyadditions/mod/tile/TileEntityDirectionalBreaker.java#L87) since Ellpeck/ActuallyAdditions@1fe930b395485b060830a946b7beb9de27f999ec.
