### ISSUE TITLE
Using Engineers manual closes my client after a while

### ISSUE THREAD

**Issue by pixzi** [BluSunrize/ImmersiveEngineering#2523]
Hello, 

Everytime i go to use the manual, i can search for so long then it closes my client. I get no crash report and no shutter or anything to indicate it closing. I tried looking online for reasons and ways to fix it, but they relate to the immersive petroleum addon, whch i don't have. 

I'm using the most up to date version for 12.1.  My java is the most up to date too. 
I tried to replicate my issue on its own, it still happens. 

Thank you in advance.

**Comment by malte0811** [comment]
Is there a file called something like hs_err and then some number in your MC folder? Or maybe in the folder your launcher is in? The official MC launcher (which Curse/Twitch redirects to AFAIK) uses its own Java version unless you explicitly tell it to use the up to date Java you installed.

**Comment by pixzi** [comment]
okay, yes it does. I wondered what they were. So simply just telling it to use the latest java should help?

**Comment by malte0811** [comment]
Yes. Installing the latest Java won't help if MC still uses the old version. If setting the launcher to use the new Java installation fixes this issue please close it (you should be able to do that since you created this issue). If it doesn't I'd like to see the content of those hs_err files.
Re: latest Java. Java 9 was released just a couple of days ago. From what I understand Forge won't be able to run with Java 9 for now due to lots of internal changes. So you need to install latest Java 8, even if there are newer Java 9 versions.

**Comment by pixzi** [comment]
So far so good, it's not closed yet and been on it for about 5 minutes flicking through the pages/links. 

Yes, i'll remain using 8 for a while. Thank you for the heads up.

Thank you so much for the help, i really appreciate it. :D
