### ISSUE TITLE
[1.12.1] Server Crash on startup.

### ISSUE THREAD

**Issue by UnPure** [BluSunrize/ImmersiveEngineering#2533]
### Description of the issue:
The server crashed on startup.

### Crashlog:
https://pastebin.com/pLw4MqEP

### Versions & Modlist
**Immersive Engineering:** 0.12-72
**Forge:** 14.22.0.2475
**Modlist:** http://upclan.de/modpack/info/

//Edit:
This problem only happened once. After starting the server again i had no more problems.
I still think this should bre reported because it could happen again.

**Comment by mindforger** [comment]
that is a fun one and most probably not caused by IE ... i have found similar stack traces running into the same java.lang error for different mods ... 
https://github.com/McJty/RFTools/issues/1288
this one for example ... no solution just a guess that something or somebody is sending a command to the server causing a race condition in executing the command while the server still is starting

**Comment by malte0811** [comment]
@mindforger It's the server watchdog. It kills the server if a tick takes more than 1 minute (might be a different value). I'm not really sure why though, I moved most of the time-consuming stuff to a different thread.

**Comment by BluSunrize** [comment]
Yeah I've been seeing Minetweaker cause this. Fixed like three of those last Sunday at work.
Easiest work around, go into the server properties, find the max tick time and change the 6 at the start to a 9 or 12.
