### ISSUE TITLE
[1.12.2] Graphical issues on 74

### ISSUE THREAD

**Issue by PieExplosion** [BluSunrize/ImmersiveEngineering#2552]
### Description of the issue:
Fluid indicator on Tank isn't showing.  External heater looks... wrong.  Screenshot https://imgur.com/gb02aVO

Issues appeared after updating from Forge 2495 and IE 72.  Made fresh instance with just Forge and IE and issue persisted.

### Versions & Modlist
Forge 14.23.0.2512
IE 0.12.74

Java 8u144 and LWJGL 2.9.1

**Comment by kwpugh** [comment]
With the update, all the heaters on my server are invisible.

**Comment by malte0811** [comment]
Fixed. This bug was caused by Blu, Blom (a little bit) and me together: Blu added a hacky workaround in 1.8(?) that wasn't necessary any more in 1.11 since the method signature changed. Blom didn't remove it when he updated the method signature, he probably didn't even notice it though. And then I broke the workaround in d7743fa04543a11b89af18ff5a646c42f67d7901 (in a non-obvious way).

**Comment by kwpugh** [comment]
Did anyone report about tanks no showing their contents?   The bar is just off-white and doesn't indicate fluid type.

Not sure if it is related to above.

**Comment by kwpugh** [comment]
and you can't see into the core drill either.  is that related or a separate issue?

**Comment by Vitamin-Carrot** [comment]
Sweet - that is literally the only issue I have experienced thus far - now I am patiently waiting for next version - keep up the awesome work guys
