### ISSUE TITLE
Liquid concrete, make it take longer to dry.

### ISSUE THREAD

**Issue by darkshadow543** [BluSunrize/ImmersiveEngineering#2558]
Just a suggestion, but liquid concrete is hard to build with, even with a mold.  The main reason is that it dries too quickly.  Concrete in real life takes hours to harden enough to walk on.  In game, this would likely transfer to a few minutes.  In the game, it only takes seconds causing things like this.
![2017-10-13_15 46 58](https://user-images.githubusercontent.com/14943673/31564262-312232ce-b030-11e7-96f9-d714633cbc63.png)
Just please, make it take longer, like a few minutes, maybe, to dry.  It would be more useful that way.

**Comment by LazerusKI** [comment]
just wanted to ask the same. tried to create the floor of my factory by using the liqiuid in a mold by pouring a bucket out. Didnt work, formed mostly unusable tiles.
Then i tried to use the Fluid Outlet, which had the same result.
So to use concrete as a building material i either have to pour them into 1x1 holes...or just craft the shaped recipe

**Comment by lordfriend** [comment]
Agreed, I also tried to use a fluid outlet but still made a result just like your pictures shows. In current situation, this material is virtually useless to build some man-made structure.

**Comment by Waisse** [comment]
Old issue but it's still relevant. Making liquid concrete is not only a hassle to make vs its shaped recipe version, it is straight up worse to use. Make it form at least a few full blocks before drying up, thanks.

**Comment by MaverickMartyn** [comment]
I second this. I wanted to fill in a cave next to my underground compound, but the way it behaves makes it useless.
Pretty annoying, after I spent the time and resources to make it.

This could arguably be viewed as a straight up bug, rather than a suggestion, as the material is completely unusable.

**Comment by tehbeard** [comment]
Ran into this in a mod pack where I wanted an outdoor area to have a level concrete floor.

I even tried attaching multiple pumps to the outlet to try and speed up pouring so that the quick curing wouldn't cause issues.

No dice, seems to only be able to create a 5x5 "splotch" of full and half slabs.

Now I have a barrel of concrete panel and sheets that are fairly useless...

**Comment by sharlin073** [comment]
I use this feature to get concrete sheets or something, but yes, I'm pretty sure that this is not working as intended as well.

**Comment by BluSunrize** [comment]
Liquid concret was overhauled in **1.18.1-7.0.1-144**

**Comment by Enterprise12nx01** [comment]
> Liquid concret was overhauled in **1.18.1-7.0.1-144**

using this in 1.20.1 and this issue is still present, it dries almost instantly, using a fluid outlet has the same effect, barely get a few blocks out before it solidifies.
