### ISSUE TITLE
Feature Request: Energy Meter

### ISSUE THREAD

**Issue by JDuskey** [BluSunrize/ImmersiveEngineering#258]
I was wondering if it would be possible to implement an energy meter, with a prepay mode, so you can sell the energy to other players.

**Comment by theunkn0wn1** [comment]
I would like an energy meter so it is easier to identify the throughput of certain parts of complex power grids, like exactly how much RF is leaving a power station or how much a given section is consuming.

I also agree with the concept of metering for monetary gain in a multi-player environment as it would add an RP aspect to this wonderful mod. Though it should be down the the provider player to set what the fee is, whether redstone or gold...

however: it is currently possible to do what the OP is requesting as it stands, by combining other mods together. CC and EIO/TE capacitors distributing power over IE's cabling allows for a rudimentary system for monitoring and controlling power distribution. It would be more favorable to have a native method for doing the above, as a single Tile Entity device added to IE can do the function of at least 3 Tile Entities of using a combination of other mods, reducing overall load on the server by mitigating TPS loss due to a large quantity of Tile Entities the server has to handle.

As it stands, there is no mod/addon that i know of that has direct support for the IE power distribution system, in terms of monitoring power going through the system that is.

**Comment by cola98765** [comment]
ZettaIndestries mod is already adding that: 

![rfmeter image](http://i.gyazo.com/16c36ad4247aca457801cce43d8a2d24.png)

 If you don't like other of its' features you may disable them in mod config. It alread has prepaid mode and other stuff availible via OpenComputers component.

**Comment by BluSunrize** [comment]
1) Yes, definetly possible.
2) Zetta adds an energy meter, though I must say, it needs a different texture x3
3) TPS != TileEntities. One Tile doing the work of 3 is just as laggy as 3 tile entities splitting work, if you ignore the communication between them. Function is function, it will take the same amount of time no matter from where it's called.

**Comment by theunkn0wn1** [comment]
You misunderstood me, 3 TEs != 1 TE doing the same function as the three.

I was unaware of that energy meter, what mod is that from?

**Comment by Alex33212** [comment]
An energy meter would be nice... although, it would be best if kept in the late 19th/early 20th century look that this mod seems to have. Which, by the way, is pulled off very nicely!
