### ISSUE TITLE
Tools not storing Upgrades

### ISSUE THREAD

**Issue by LazerusKI** [BluSunrize/ImmersiveEngineering#2587]
Version: 0.12-74
Forge: 1.12.2-14.23.0.2517
Modpack: ATM3
Description:
Adding upgrades to tools (tested with Revolver and Shield) works, but when i wanted to add a shader i noticed that the upgrades were gone.
The two fields were empty, clicking them sometimes lets me remove the upgrade then (invisible item), but most of the time the upgrade is just deleted and the tool turns into an unmodified version. Only the shader stays on it.
Could this be related to the toolbox and crates not keeping their inventory?

edit: also when the revolver is put back into the workbench, all the loaded ammo gets deleted

**Comment by malte0811** [comment]
This is probably my fault. I'll look into it when I have the time.

**Comment by cam72cam** [comment]
I have found that in survival they are invisible, but I can pull them out.
When in creative they just disappear.

**Comment by malte0811** [comment]
I've finally started working on this, here's my progress so far: I can explain invisible items (desyncs), but no actual vanishing (and I didn't experience any so far). Fixing it may take some time, capabilities are really weird when it comes to syncing.

I assume all of this is happening on dedicated servers? I haven't managed to get any desyncs on the integrated server.

**Comment by malte0811** [comment]
I probably fixed this for the next release, even though it could use some work in Forge: the upgrades appear in the GUI due to a change made by the player. MC assumes that it doesn't need to tell the player about the immediate effects of that change because the client already knows what happened. This is fine in "normal" situations, but since the upgrade items are stored in a capability the client does not know about them.
I still didn't get any item loss, but I did come across some cases where clicking the empty slot didn't work even though the item was still there.

**Comment by cam72cam** [comment]
Try switching between creative and survival with a drill a few times.  That seems to have caused issues in the past for me.

**Comment by LazerusKI** [comment]
if its still needed, just switching to creative isnt causing this issue. just tried it in 0.12-75.
switching to creative and clicking on that item is. like when you want to move it to the workbench or to another slot on your toolbar. when it allready is on your hotbar you can scroll and select it without a problem, just clicking on it bugs it.
It also doesnt affect the chemthrower tank, just its upgrades.
