### ISSUE TITLE
Issue with Water wheel

### ISSUE THREAD

**Issue by JoeSGT** [BluSunrize/ImmersiveEngineering#2610]
Forge: 14.23.0.2540
Mc: 1.12.2
today i had compile the Immersive Engineering and use it in my singleplayer world
because it had more fixes that i want and i crafted an Water wheel and well it looks like this
https://gyazo.com/e26c661b70cbab5d2952828dac792e98
i went back to the curseforge released version 0.12 - 74 and this glitch don't happen
i feel that i should report this so it can get fix
anyways
thanks you

**Comment by malte0811** [comment]
Thanks for the report! The master branch is meant to be mostly stable, so you should report bugs found in custom builds (except when dealing with features added a few commits ago and that commit has something like "This is still WIP" in it). If you are using a non-CurseForge build you should either include the id/hash of the last commit before your build or the maven/jenkins build number.
I've seen this bug in my test world, but since I had tried things with the water wheel on a separate branch before that happened I assumed it was related to that. I'll look into it when I get around to it.
@BluSunrize when would be a good time to talk to you on IRC?

**Comment by JoeSGT** [comment]
sadly i don't know the Jenkins links that why i had to compile it
but sure i will report bugs I'm happy too and will post id/hash of the last commit 
thanks for fixing this issue
