### ISSUE TITLE
No Ore in world or very little

### ISSUE THREAD

**Issue by Dewie2000** [BluSunrize/ImmersiveEngineering#2611]
I have searched for quite a while now and after digging in a pattern I am not finding any IE ore. Just iron and coal. Plains and extreme hills have netted 0 bauxite or copper. I have over 200 iron and coal but no others yet. Is the distribution different from the previous versions? 

On another note, I noticed that a lot of people using signs to mark the piles of wooden crates as to the contents. Can we have a crate that has a label? Combine a crate and sign. It has to lose the name when you pick it up of course but that is ok.

Maybe even solar panels but that is another discussion altogether. 

Thanks
Dewie

**Comment by malte0811** [comment]
What version of MC, what version of IE? What other mods, what modpack? Is IE oregen enabled (should be by default, but might be disabled in a pack)?

**Comment by BluSunrize** [comment]
I love how the initial email I got was a full copy of the issue template, which was then edited, completely deleted and replaced with a post that entirely bloddy disregards it. >_>

**Comment by jbreving** [comment]
### Description of the issue:
No ores from Immersive Engineering appear in the world on multiplayer server (single player works fine).  
I encountered this originally with more mods on a server I'm trying to set up for my son. I tried removing some mods that affected world generation and tested on the server. No IE ores. I checked single player. I found the IE ores! I added some back, still found IE ores in single player. I added the last one back and found IE ores... That was confusing. I tried running the server after that with the world folder renamed. Log in and no IE ores... So I tried just IE on the server and in single player. No IE ores on the server. Yes IE ores in single player. So here I am. I'm going to figure out how to pregenerate a world in single player and set a world border for the server to work around this problem, but I thought you should know, especially since I see there's a poorly written similar issue.

### Versions & Modlist
Server runs:
forge 1.14.4-28.2.0
immersive engineering 0.14-95
and no other mods

**Comment by BluSunrize** [comment]
Wow, you put this on an issue that's 2.5 years old.

Make a new one. And before you do, actually use the latest verison of IE. We're on 96 now.
