### ISSUE TITLE
[1.12.2] Pipes don't work with Astral Sorcery Lightwells

### ISSUE THREAD

**Issue by Dragnier** [BluSunrize/ImmersiveEngineering#2624]
### Description of the issue:
Astral Sorcery Lightwells only connect to fluid pipes on their bottom. Your pipes connect but do not extract fluid from the lightwells. Even attaching a pump to the pipe will not cause it to extract.

A couple of mods with pipes that do work with the lightwells are Extra Utilities 2 and Inductive Logistics; so you might look at their code to see if there is any help there. I don't want to use those mods in the pack I'm putting together for myself though.

### Crashlog:
none

### Versions & Modlist
Forge: 14.23.0.2545
IE: 0.12-74
Astral Sorcery: 1.8.2

**Comment by superfluke** [comment]
Just to add onto the issue here in case the dev is not as familiar with the astral sorcery lightwell. The lightwells do not auto output their fluid and the fluid can only be extracted from the bottom of the lightwell. There doesn't seem to be any bugs here, but IE will not work because there is no way to extract fluids from the bottom of a block. If possible, it would be nice if a fluid pump set to pull could be extended by fluid pipes connected to it. 
![2017-11-18_17 23 36](https://user-images.githubusercontent.com/20022336/32985282-5aff26f8-cc85-11e7-943c-0a01fa622850.png)

**Comment by BluSunrize** [comment]
Well that would be why then.
IE pumps only work on direct contact so they can't pull from the bottom. Nothing to be done about it at this stage, I'm afraid

**Comment by Dragnier** [comment]
There is a distinct difference between "nothing to be done" and a refusal. I'd have honestly rather seen you just say no than to say it couldn't be done.

**Comment by BluSunrize** [comment]
You misunderstood my meaning. I meant that there is nothing to be done about your ingame set up atm to make it work.
A change in AS to allow side outputs would remedy, this, and so would a change to IE to allow pumps to pull from a distance. I've considered making that functionality available, I just haven't gotten around to doing so.
