### ISSUE TITLE
Cannot remove Manyullyn from the arc furnace using Crafttweaker

### ISSUE THREAD

**Issue by tgstyle** [BluSunrize/ImmersiveEngineering#2632]
Using

mods.immersiveengineering.ArcFurnace.removeRecipe(<tconstruct:ingots:*>);
or
mods.immersiveengineering.ArcFurnace.removeRecipe(<tconstruct:ingots:2>);

refuses to remove it from the arc furnace.

Forge: 2550
IE: 0.12-75
TConstruct: 2.7.4.34
Crafttweaker: 4.0.10

**Comment by tgstyle** [comment]
Also is there any reason why I cannot add custom recipes after removing them all by mold in the press?

mods.immersiveengineering.MetalPress.removeRecipeByMold(<immersiveengineering:mold:1>);

**Comment by BluSunrize** [comment]
The former is a simple explanation, but alas not a simple fix.
I currently register those compatability recipes for TCon in the init-phase which is after Minetweaker runs its stuff. It can't remove what isn't there yet.
It's not as easy to fix because atm TConstruct doesn't register its OreDict stuff in preInit (will need to poke boni on that)

The second one, I'm unable to reproduce.
I succesfully removed all recipes using the gear cast and added a new one using:
`
MetalPress.removeRecipeByMold(<immersiveengineering:mold:1>);
MetalPress.addRecipe(<minecraft:iron_bars>, <ore:nuggetIron>, <immersiveengineering:mold:1>, 4800, 8);
`
And it worked fine:
![image](http://puu.sh/yrl6o/4622a21bb5.png)

**Comment by KnightMiner** [comment]
Actually, it was my decision to register ores in init based on a comment by Lex saying that's the proper place (items are not even registered by preinit and it's messy to do it in the events). Anything removing recipes should really happen postInit.

**Comment by BluSunrize** [comment]
How old is that particular bit of information?
Recipes ahve their own registration event now, RegistryEvent.Register<IRecipe>, which is fired before init.
As such, if you want to use OreDict queries in that registration event, you have to add stuff to the Dict at the end of the Item and BVlock registration events (my bad for saying preInit up there)

**Comment by KnightMiner** [comment]
That is from the beginning of of 1.12. Oredict recipes are supposed to be registered regardless of if there are entries for the name, Forge does not care as long as items are added eventually. If the name ends up having no items, the recipe just never matches.

If you are going for an oredict output, just have your recipe .matches() method return false when there is no entries on the output.

For blanket scans of the oredict, that should always be done postinit; though that's the part where me and Lex disagree as he says registering oredict in postinit is acceptable as scans of the oredict should never be done.

**Comment by BluSunrize** [comment]
That is so much unnecessary effort in hiding them from JEI and stuff. Why make it so backass complex rather than just moving the registration forward? What detriment is there to it?

**Comment by KnightMiner** [comment]
Just the way Lex designed the system, I'd rather keep TiC complaint since its not a huge inconvenience. Plus, I think there were networking reasons to allow recipes to be sent from server to client and then determine things like oredict later down the line.

Anyways, why not make recipes not dependent on loading after oredict if its possible to do so? Allow people to register as late as they like. As far as I know JEI handles hiding recipes like that automatically anyways.

**Comment by tgstyle** [comment]
@BluSunrize I will do more testing on the second one to see if I have steps to reproduce or if I am just high =). I think it may have to do with removing all mold recipes for all types.

**Comment by tgstyle** [comment]
Today all of a sudden it is working, so just scrap that. If I figure out how to reproduce it again i'll submit a separate issue.

**Comment by BluSunrize** [comment]
@KnightMiner Craftweaker is not my work. I don't get to decide when they load the files.

All I know is that I use the recipe registry event where appropriate, and in order to allow TCon compat I'll probably just go ahead and reference the items directly rather than oredictign them.

**Comment by KnightMiner** [comment]
Oh, figured this was part of the way the arc furnace handles recipes. Might be good to leave a comment to Jared about this then, as it should be possible to load a reference to the oredict list so it updates rather than the current contents.

**Comment by tgstyle** [comment]
Don't mean to take this off topic @KnightMiner,  but as for ore dictionary entries crafttweaker has an issue removing recipes using tinkers ore dictionary entries. I have had to just specify the direct items and it works.
https://github.com/jaredlll08/CraftTweaker/issues/381

**Comment by Bufhimat** [comment]
Thank you gentlemen for explaining why this happens.
Since this ticket is still open, this works to remove the recipe from the arc furnace for me:

<ore:ingotCobalt>.remove(<tconstruct:ingots>);
<ore:ingotArdite>.remove(<tconstruct:ingots:1>);
