### ISSUE TITLE
[1.12.2] Wires fail to render in certain cases for Razor Wire

### ISSUE THREAD

**Issue by Flaxbeard** [BluSunrize/ImmersiveEngineering#2641]
Apologies if this issue has been reported already - a cursory search found nothing, but it's affected development of my addon (Immersive Petroleum).

### Description
When a Razor Wire block is placed into the world and connected to a valid LV wire relay / connector, in some cases it fails to render. For what it's worth, happens with my Portable Generator (extends TileEntityImmersiveConnectable as well). See picture below.

![image](https://user-images.githubusercontent.com/3607472/33508101-009a2936-d6be-11e7-8940-78717b180e0c.png)

### Steps to Reproduce
Place a LV Wire Relay in the world, and a block of Razor Wire in the positive x (east), positive y (up) or positive z (south) direction. Use LV wire to connect the two. The connection will succeed but will not render. 

### Versions
Forge 14.23.1.2556
Immersive Engineering 0.12-75

**Comment by malte0811** [comment]
Fixed for the razor wires. I had a look at your code, if the portable generator is a `BlockIPMetalDevice` (based on the 1.12.2 branch) you need to add the (unlisted) connections blockstate to it (`IEProperties.CONNECTIONS`). If your base block class is an exact copy of IE's base block class that should do everything, otherwise you will need to manually set it (look at `TEImmersiveConnectable.genConnBlockstate` for that). You should make it render on both solid and translucent, translucent is only relevant when only one half of the wire is rendered because the chunk the wire starts in gets culled.

**Comment by Flaxbeard** [comment]
Thanks for the fast fix and the solution!

**Comment by Flaxbeard** [comment]
It doesn't appear that ConnLoader supports JSON models - are the only things that can render wires OBJ models at this point?

**Comment by malte0811** [comment]
It should be able to load any model, even though I never tried using JSON models. You just have to register the model you want to use in `ConnLoader.baseModels`.

**Comment by benpankow** [comment]
Yeah that's what I'm doing - if add an OBJ to the baseModels map it works fine, but if I change it to a JSON model it doesn't appear to work

**Comment by Flaxbeard** [comment]
Yeah that's what I'm doing - if I add an OBJ model to the baseModels map it works fine, but changing that to a JSON model seems to break things.

**Comment by malte0811** [comment]
Can you be a bit more specific than "break things"? It is supposed to work with any model.

**Comment by Flaxbeard** [comment]
Sorry, meaning that the model does not show up and the wires do not show up. I can do some more toying around with it in a few days.
