### ISSUE TITLE
[1.12.2] Drill upgrades mysteriously disappearing on multiplayer

### ISSUE THREAD

**Issue by Flaxbeard** [BluSunrize/ImmersiveEngineering#2642]
Another bug that's come up when debugging my addon. There seems to be an issue either with the Engineer's Workbench or ItemInternalStorage.

### Description
After adding a drill head and upgrades to a Mining Drill, they mysteriously disappear moments later.

### Steps to Reproduce
Add a drill head and some miscellaneous upgrades to your Mining Drill on a multiplayer server. Close the Engineer's Workbench GUI, and open and close your inventory a few times. Your upgrades - and the drill head - are gone. Re-logging does not bring them back, nor does opening the Engineer's Workbench again.

### Versions
Forge 14.23.1.2555
Immersive Engineering 0.12-75-293 (from Jenkins, deobf copy)

**Comment by malte0811** [comment]
Did you test this in creative or survival mode? I was able to replicate the bug, but only in creative mode. It seems like the server is overriding the stack it has (with the proper inventory) with one send from the client (which doesn't have all information, or at least not in the same places).

**Comment by Flaxbeard** [comment]
Yes, I've only tested in creative. I can do more extensive testing in a few days if needed.

**Comment by malte0811** [comment]
I'm giving up on this bug for now. I know what is happening, but I have no idea why it is happening or how to fix it. I tested it with a revolver, but the issues are the same.
This is a sort of "backfeeding desync": The client has a mix of 2 versions of the item (not sure why), the creative inventory realizes that and tells the server to one of the versions, unfortunately the wrong one (that's how the creative inventory works in general from what I've seen, it seems to be possible to give yourself items with an arbitrary share tag by being in creative mode). The new version (with all new upgrades installed) of the client is stored in the `inventoryItemStacks` when the creative inventory is opened, the old version (the version that was put into the workbench) ends up in the actual slot. The old version is synced back to the server, but that doesn't just reset it to the old version since the stack the client has doesn't have the inventory capabilities, just the upgrade information itself.
The bug stops sometimes stops happening until the server is restarted. The revolver bullet GUI seems to be *partially* affected. When I started working on this, it was working, but still broke whenever an upgrade was installed. I tried that again yesterday, it broke as well, but stopped breaking at some point until a server restart.

**Comment by malte0811** [comment]
MinecraftForge/MinecraftForge#4580 is at least partially related to this.

**Comment by LouisTakePILLz** [comment]
I encountered the same issue with shields. I haven't tested with the other tools but they should be affected as well.

### Versions

- Modpack: SevTech Ages 3.0.8
- Forge: 14.23.4.2707
- IE: 0.12-82
- Java: 1.8.0_171 64-bit

**Comment by malte0811** [comment]
If this is in creative mode on a dedicated server there isn't much we can do about it (see the Forge issue I linked).

**Comment by mindforger** [comment]
@malte0811 have had a look at https://github.com/Selim042/ModJam_5/issues/4 he seemed to found a trick to do it, i did not check it but at least one related issue got solved

**Comment by LouisTakePILLz** [comment]
@malte0811 I encountered the issue in survival mode.

**Comment by DragonSlayer696** [comment]
Same

**Comment by mindforger** [comment]
Try reading a few comments, tl;dr; unfixable
