### ISSUE TITLE
Crash when using the manual.

### ISSUE THREAD

**Issue by mikeskey** [BluSunrize/ImmersiveEngineering#2663]
https://pastebin.com/VDbwPWDc

Opened manual...browsed manual...crashed. Literally did nothing else between the time the game started and it crashed.

Even though I already knew it was I made sure Java on both the machine running the game and the one running the server were both up to date and even checked to see if there had been an update to this mod and there hadn't been.

**Comment by mikeskey** [comment]
Don't worry about it, I figured out how to fix it on my own.

**Comment by mindforger** [comment]
let me guess, updated java runtime and set it in the launcher to use the system JRE ? :)

when you find solutions, please share them, (allthough this one is known already) because others searching for the same issues wouldn't mind to know the solution then

**Comment by mikeskey** [comment]
Actually mindforger that was NOT the issue. It was an issue with the extremely retarded twitch launcher and I have already chewed them out about it. I wish curse would have never sold out to twitch as since I and a lot of other have had nothing but problems. Curse worked just fine the way it was and then twitch had to get their greedy little paws involved.

**Comment by CoelacanthsKill** [comment]
Thanks for posting a clear fix /s

**Comment by mindforger** [comment]
@CoelacanthsKill 

to give an clear explanation for the common part of the issue


the minecraft launcher is coming with a built-in versioj of java 8 release25 being literally ages old now
you have to install a proper Java 8 (not 9 for 1.12 at least, also make sure to install the 64bit version, check with console and run "java -version" to double check) 

then make sure you setup in your running minecraft profile to use the system JRE instead of the built-in
you may have to select the path to the binary folder where the javaw.exe is sitting in

i have no clear info on how the twitch launcher works on your system, but for me it always provided options to tune everything in the twitch app itself and used them properly with the minecraft launcher then

**Comment by mikeskey** [comment]
@CoelacanthsKill 

Sorry but I didn't bother to post a fix here since mind seems to know everything about everyone there was no need to. With his ASSumptions that he made about my issue and the rudeness I received on my previous post I didn't really care to deal with him as he is obviously too good to talk to someone with an actual issue that is outside the normal run of the mill any idiot can fix it problem.

As I had stated it was an issue with twitch launcher in the end and not even anything related to this mod or java version. In order to fix my particular issue I had to do it in regedit as I had some issues a while back and ended up reinstalling windows and a few other things there was some issues that needed to be resolved before things worked properly. I had java installed correctly and had it set in minecraft to work the way it was supposed to and even set in twitch to work but after extensive troubleshooting and googling and talking to some really assanine tech support I finally got to the bottom of the issue and got it fixed. There was no point to go into detail on the fix however as it is an issue only effecting me and nobody else therefore it's all information that would be useless to anyone else and furthermore unless you know what you are doing the average person should not even open regedit ever so that was not something I wanted people to be doing based on an issue I had. I am familiar with those things but the majority of the community here and minecraft community in general is not. Considering the attitude and responses I have gotten from the problems I have posted here I can assure you that none of these folks have the slightest clue what I'm talking about anyway.

Sorry if you ran across this trying to fix an issue you had and it wasn't helpful but I do hope you got your problem solved if you had one.

As for mindforger....well arrogance and assumptions led to the responses he got from me and that's all there is to it. I'm sure someone else will have to chime in and get the last word here or make me look like an ass but I really couldn't care less at this point. My stuff works now and that's all I really cared about.

**Comment by CoelacanthsKill** [comment]
Thank you for pointing me in the right direction- Twitch Launcher: File > Settings > Minecraft > Launch Method > JAR Launcher 

Java version: 
Mine is manually set to the latest, 1.8.0.151 64bit (as of a week ago)

**Comment by mindforger** [comment]
@mikeskey i have absolutly NO idea where i was anywhere near rudeness in my ONLY other answer to you ... I just explained there were 3 launcher versions ... Just because you feeling butthurt because you acted like an ass first by not posting ANY explanation and me scolding you for it does not mean for you to ass out in other by not clearing up Things like in this exact case... If you have issues with the way someone acts... He may not be aware ... Just TELL it... I would have said sorry because i NEVER MEANT IT MEAN IN ANY WAY ...
