### ISSUE TITLE
[1.12] Fatal issue, drill crashes the server when breaking certain tile entities

### ISSUE THREAD

**Issue by Frontrider** [BluSunrize/ImmersiveEngineering#2669]
### Description of the issue:
The drill has issues while mining Thermal dynamics ducts, its either leaves the block in the middle (the one I'm pointing at) behind, or crashes the game.

Edit:After consulting with King Lemming, the cause seems to be that you inform the block that it was broken, after you broke it.
What I get from the crash, is that you expect the duct's blockstate, from the air what replaced it after you broke it.

### Crashlog:
https://pastebin.com/L3mjGMM3

### Versions & Modlist
ie 0.12-75

**Comment by BluSunrize** [comment]
As far as I am aware, I'm calling all methods related to block breaking in their relevant order, the crash seems to be more nested in the Thermal mods.

**Comment by KingLemming** [comment]
Blu,

I'm just going with Occam's Razor on this one, but every other AOE breaking item that I've tested works fine - and I have a few of them in my own mods.

I haven't been able to test this with IE, however, because on the latest version, I can't even get the drill head to equip on the drill. (It correctly stores it in the drill's inventory, but does not actually use it.)

**Comment by malte0811** [comment]
Please don't close unfixed issues, from your edit it seems like this is an IE bug (at least according to @KingLemming).

**Comment by Frontrider** [comment]
It got a hotfix on the side of Thermal Dynamics. With the latest version of that, the glich no longer persists, and it looks like that block was the only one affected by it.
