### ISSUE TITLE
[1.12] Post Crash 

### ISSUE THREAD

**Issue by artdude543** [BluSunrize/ImmersiveEngineering#2676]
### Description of the issue:
When placing two posts near each other and then proceeding to use the Hammer to bring out the stands the adjacent post seems to perform a connection test and then crashes out the client and shortly after the server crashes.

After this trying to re-join the world the client crashes; making the world broken in essence.

### Crashlog:
 [Gist](https://gist.github.com/artdude543/16de9e79e8f46f5301e2be95c2ca0ace)

### Versions & Modlist
IE: 0.12-75
Forge: 14.23.1.2566
Mods: All mods active from the D20 FTB Pack (1.4.0)

Have tested this in a world with just IE and get the same issue.

**Comment by malte0811** [comment]
![2017-12-18_22 36 24](https://user-images.githubusercontent.com/10406104/34129397-4abaf78c-e444-11e7-8a00-4e05c09d24c3.png)
Is that what you tried to do? Because "placing 2 posts near each other" is not the best description for a crash that happens in that specific setup.
I have a fix for this, but found another crash that happens when you put ANOTHER arm below this, I'll fix that and push in a minute.
