### ISSUE TITLE
Visual Artifacts Warning

### ISSUE THREAD

**Issue by Zsashas** [BluSunrize/ImmersiveEngineering#2677]
[16:29:18] [main/WARN]: Texture immersiveengineering:textures/blocks/metal_multiblock_silo.png with size 88x88 will have visual artifacts at mip level 4, it can only support level 3. Please report to the mod author that the texture should be some multiple of 16x16.

**Comment by mindforger** [comment]
You forgot to das version information and additional mods list like requested in the guidelines. 

This is an optifine warning and if i remember correct it is already know @malte? But i can not remember the response :p

**Comment by malte0811** [comment]
No, this is just Forge (might even be MC itself). It is known and I'll fix it later today if I can get Blender to behave.

**Comment by Zsashas** [comment]
Mod: 0.12.75
Forge: 2565
MC: 1.12.2

**Comment by BluSunrize** [comment]
So for one, this isn't an error, everything works just fine despite this warning.
It's been around for ages and I've been entirely too lazy to fix it, because, as said above, it has basically zero impact.

It's simply caused by Haz not making his textures power of 2 and me being to lazy to fix it for everything.
