### ISSUE TITLE
metallic slab issue

### ISSUE THREAD

**Issue by bakaxyf** [BluSunrize/ImmersiveEngineering#269]
* cannot place the same kind slab on the doubleslab
* [gif] (https://drive.google.com/file/d/0B7-sQxp-PWE3cjJjdGJIQkRkblE/view)

**Comment by theunkn0wn1** [comment]
OK... if i understand you correctly, the issue is as follows:

-------------------------------------------------------------------
Issue: cannot place half-slabs in world that exceed two slabs (1m) in height.
-------------------------------------------------------------------
Info: slabs must be the same type (e.g. Lead slabs on Lead slabs)

-------------------------------------------------------------------

Steps to reproduce:
[1] Load world
[2] Equip any IE Half-Slab item
[3] place half slab on ground
[4] attempt to place a half-slab of the same type directly above the one from step [3]

-------------------------------------------------------------------
If that is the case, able to repo with FTB Infinity (1.9.0) with no other added mods
IE build 0.5.0 SHA: aae0fcac37281664526e2ebfb2f20209864e98c5

**Comment by bakaxyf** [comment]
The second.
When walking on the slab player will "fall" into blocks
[more intuitive gif](https://drive.google.com/file/d/0B7-sQxp-PWE3ODVxQVZxOG1OLTQ/view)

**Comment by theunkn0wn1** [comment]
@bakaxyf, created new issue for that bug.
#276

**Comment by BluSunrize** [comment]
Yeah please don't add new stuff to closed issues, that makes it really confusing to include in commits

**Comment by bakaxyf** [comment]
My fault. I won't do the same next time.
