### ISSUE TITLE
IE is crashing with recent Forge

### ISSUE THREAD

**Issue by cpw** [BluSunrize/ImmersiveEngineering#2692]
I added logging and produced this:
https://gist.github.com/cpw/642285a8cd09a80b1bc137291068ec18

Forge commit https://github.com/MinecraftForge/MinecraftForge/commit/9fdb79ae7aa0f9f7f99ed4271e34d014a9a329ef requires that the defaultState NOT be null.

Pull https://github.com/MinecraftForge/MinecraftForge/pull/4615 is debating this behaviour at present. I suggest you either fix or explain why you cannot shortly.

Note that the getDefaultState() method is annotated NOT NULL.

**Comment by cpw** [comment]
Closing, because https://github.com/BluSunrize/ImmersiveEngineering/commit/be1a46778796092e3ac834442d9c7195b85c25a0 seems to have fixed it.

**Comment by malte0811** [comment]
I don't know whether I should shout at you for making a duplicate issue or laugh because you thought we didn't know about this, or the cause of it (it took about 10 minutes of looking at the git history to find the problem once I knew it only happened with new forge builds). Just look at the list of linked issues at the bottom of #2672, which are essentially all issues that have been opened in the past couple of days.
I agree that we should do a new CurseForge release. The problem with that is that Blu seems to be taking a break from IE dev (no idea whether it is a christmas break, no time or burnout) and while I have collaborator access to this (github) repo I don't have any sort of special access to the CF project (and I'm not supposed to publish IE builds, and I don't have the right signing certificate).

**Comment by miuirussia** [comment]
@cpw how to add logging about models to forge?

**Comment by BluSunrize** [comment]
It's a mix of things @malte0811 
I've been busy with Uni the past few weeks and now I am finally enjoying some break time over Christmas. I'll see to putting out a new build in the coming days.
