### ISSUE TITLE
[1.12.2] Drill heads don't work, Drill doesn't accept drill heads

### ISSUE THREAD

**Issue by Thaumatarge** [BluSunrize/ImmersiveEngineering#2709]
![image](https://user-images.githubusercontent.com/34694089/34462978-5d7abdca-ee4f-11e7-8e0d-a542f7e199e1.png)
I have no idea what is causing this, but the drill just doesn't like any of the drill heads.

I am running the 1.12.2-76 version of the mod, Forge 14.23.1.2585, and this isn't caused by any conflicts as I have tested it without any additional mods, and it still happens.

**Comment by KingLemming** [comment]
Yep. Same here.

**Comment by malte0811** [comment]
Where you in creative mode and/or on a server? The capabilities are misbehaving on servers in creative mode, but they worked fine under normal circumstances last I checked.

**Comment by Thaumatarge** [comment]
I was in creative mode, not on a server, but this shouldn't happen.

**Comment by Thaumatarge** [comment]
I just tested crafting the drill instead of giving it to myself, as well as the head, and nope, it still doesn't work.

**Comment by Thaumatarge** [comment]
It stores the drill head, but it doesn't notice that it is there, taking the drill out and putting it back in shows that the drill head is installed, it just doesn't properly register.

**Comment by malte0811** [comment]
1. I just tested, it is a bug (in SSP) and I'll see whether I can fix it tomorrow.
2. No, it shouldn't happen. But I tried to fix it for 2 days and there is an open issue in the forge repo that is propably the root cause, so I stopped working on fixing what I consider to be one of the less important cases (creative mode on a server, most players won't ever encounter that).

**Comment by malte0811** [comment]
Fixed. I'll push the fix once I have a proper internet connection (probably wednesday).

**Comment by themartin1** [comment]
i had the same problem, but i noticed before installing immersive tech ( solar and boiler) & immersive petroleum, the mining drill  had worked fine with upgrades and drillhead, but then i lost it after i had applied the 2 other mods and when i then tried to spawn a new drill and upgrades i would not accept in the workbench. probably some compat between those mods since they are dependend on the immersive engineering core?

Martin.

**Comment by BluSunrize** [comment]
1) This is a closed issue
2) Nothing "depends" on ImmersiveEngineerign Core, except for IE itself. That file simply contains ASM code which is, by Forge convention required to be a separate binary. It is NOT a library, and other mods do NOT use it.
