### ISSUE TITLE
[1.12.2] Powered lanterns sometimes break the grid

### ISSUE THREAD

**Issue by Paul17041993** [BluSunrize/ImmersiveEngineering#2731]
When wiring up powered lanterns, you can come across certain locations that, upon connecting the lantern, break the entire grid and prevent all the lanterns from operating, even across transformers. This can occur with moderately low power grids using MV and many transformers, spread out over a large area, and upon breaking, power is nolonger drained at all.

Now, here's some more shenanigans; if I put a HV transformer between the source capacitor and the MV grid for the lighting, it doesn't fix the issue, but does in fact introduce a new issue that it then cuts the power draw by two thirds (82RF/t using standard MV, vs 33RF/t with the extra transformer), which potentially means that the transformers aren't isolating the grid sides correctly and messing up the pathing...

- IE 0.12-75
- forge 2555

**Comment by Paul17041993** [comment]
Assuming they don't already have this; I strongly suggest giving the transformers residual capacitance (like they do IRL), just enough energy for the max current of the low side, and each side can pull and push to this mini capacitor depending on the connectors on each side.

This will greatly increase the reliability and performance of the grid code, as currently it seems that using capacitors to change voltage is the only reliable option as transformers don't appear to work correctly as standard grid objects...

**Comment by Paul17041993** [comment]
<img width="1494" alt="screenshot_99" src="https://user-images.githubusercontent.com/3912867/34806738-ed1ee47e-f6d8-11e7-913d-8080c003ccef.png">
<img width="1568" alt="screenshot_100" src="https://user-images.githubusercontent.com/3912867/34806741-f11fe1e0-f6d8-11e7-9551-76dd82395d72.png">
(there's also a 3rd screenshot of a top view of the whole grid, but github doesn't like it...)

**Comment by Paul17041993** [comment]
ok so I placed various connector loops around the MV wires in different places, then removed them, and now the grid issues have vanished entirely... I call shenanigans...

I still believe that transformers should isolate grids more than they do however, if something weird happens on a sub-grid it shouldn't really propagate to the other grids and just break everything...

**Comment by Paul17041993** [comment]
I've come to the realisation now actually that any number of lanterns can randomly break the grid, of which if the grid does break you can either move the most recent lantern or continue to add more lanterns and it'll fix itself...

**Comment by Paul17041993** [comment]
@malte0811 transformer windings (and the core as well), choke coils and long lengths of wiring can hold a significant amount of residual charge, in fact for large IRL power grids this charge can be as much as megawatts. This charge can remain present for as long as a week as well if atmospheric conditions allow.

**Comment by Paul17041993** [comment]
ok well, I've put a few of these around the MV side of the grid, effectively simulating residual capacitance, and it's fixed all the weird shenanigans completely;
<img width="1588" alt="screenshot_101" src="https://user-images.githubusercontent.com/3912867/34818514-1f4479d8-f70f-11e7-990a-ebdc7bc588ab.png">
though of course it limits the flow rate, but for the purpose of lighting that's perfectly fine.

**Comment by malte0811** [comment]
I tried to replicate this, but wasn't able to break anything major. The current transformer will not reliably work at these small power values per transfer (each lamp takes 1 RF), aside from that everything is working as intended for me. It would be great if you could create some sort of minimal setup in a clean singleplayer world. What other mods do you have installed? I see TD, what else? This issue seems to be quite specific to something in your setup, so this is probably unfixable without more information.
Re: transformers storing charge: Yes, any coil has a capacitance. But when everything is turned off, that capacitance is essentially shorted by the coil (it will oscillate for a short while, but not enough to be relevant here). A charge can never be megawatts: A charge is measured in Coulombs, what you mean is energy, which is measured in Joules.

**Comment by Paul17041993** [comment]
well without using the fluxduct 'relays', it's purely just IE, with MV coming of a single MV capacitor and post transformers splitting the MV off to separate LV grids.

The problem seems to be related to chunks and chunkloading, if some lanterns on one of the LV grids are unloaded, and you add a lantern to a separate LV grid, it breaks the MV grid completely, but if you section off the MV grid into separate areas it's at least a lot less likely to occur.

I've also found another issue that can apparently occur, where the central MV grid just drains as much energy as possible while still providing power to the secondary MV grids, to fix it I had to break the connectors as it seems like at least one of them ended up becoming a form of nullifier...

**Comment by malte0811** [comment]
I finally managed to replicate this issue (or at least a very similar one), I'm going to assume they are the same for now. My issue is caused by some weird behavior in the energy loss calculations, not chunk loading. It might look like it's chunkloading related since the issue only happens with high loss (/long) capacitance connections connected to low power outputs. Please try setting wire loss to 0 in the config, does that fix it?

**Comment by Paul17041993** [comment]
they still flicker/brown on chunk loads and unloads with the loss set to 0.0 for all 3 wire tiers, so all it seems to do really is make the RF use consistent as it should be...

**Comment by ljfa-ag** [comment]
Bumping this because I ran into problems with lamps in my SevTech singleplayer world as well. For some reason, the lanterns were not getting power even though there was enough available in the grid.
Weak power sources seem to play a role here, since, paradoxically, when I remove the connection to my weak power source, it works again. Also paradoxically, running another machine can make the laterns light up too.

After some fiddling around, I managed to replicate it in a test system, which roughly corresponds to the topology in my singleplayer world:
![2018-05-04_22 35 13-text](https://user-images.githubusercontent.com/3437174/39652513-1284e498-4fee-11e8-92b2-9cb0e9c6ca59.png)
![2018-05-04_22 35 44-text](https://user-images.githubusercontent.com/3437174/39652521-1ab6ec06-4fee-11e8-8122-5ef12e64c441.png)
![2018-05-04_22 36 01-text](https://user-images.githubusercontent.com/3437174/39652526-2076276a-4fee-11e8-8d7c-fe45987104fd.png)
![2018-05-04_22 48 16-text](https://user-images.githubusercontent.com/3437174/39652534-2728f38a-4fee-11e8-9f35-46729469e5c7.png)
The Metal Press is not having any issue getting power. As soon as it stops running, the lantern turns off again.
![2018-05-04_23 03 36-text](https://user-images.githubusercontent.com/3437174/39653107-03e6244a-4ff0-11e8-9cd0-0e236a49bee9.png)

**Comment by Paul17041993** [comment]
Yea, I found the priorities for them are rather broken as the lanterns themselves don't have an internal energy storage, however wire connectors do, so I since build the lanterns on their own dedicated grid and make sure the whole grid is chunkloaded.
