### ISSUE TITLE
[suggestion] Fluid Evaporator 

### ISSUE THREAD

**Issue by EvilCooky** [BluSunrize/ImmersiveEngineering#2745]
Just a little idea I had recently.

We already have potions as fluids and at the moment we can bottle them up to drink them or spray them around.
But what if we could saturate an area with a potion effect?

The Fluid Evaporator takes potions and sprays them into the air, causing everyone in the area to gain the potions effect. It could also evaporate other fluids, maybe causing some different effects, like an easily igniteable gas when you pump diesel into it.

For a crafting I'd suggest something with a fluid pipe, a heating element and some iron bars in it.

**Comment by BrisingrAerowing** [comment]
This would be interesting. It might also be usable for spreading some kind of fire retardant. Would be cool for automated fire suppression systems.

**Comment by Koltanas** [comment]
I think such a block would be also good for easy fire traps or getting rid of creosote oil

**Comment by PrincessRTFM** [comment]
Maybe something like this for the effects...

for every fluid registered:

0. if fluid is a gas (like steam, for instance), skip it
1. apply individual fluid-specific effects (potions, similar)
2. check fluid properties (flammability, temperature, etc) and apply generic effects based thereon (non-flammables at normal temps could extinguish fires, high temps (Thermal Foundation/Expansion's pyrotheum?) could _start_ fires instead, that sort of thing)
3. anything that can't be given an effect (properties aren't valid for any of the auto-calc ones, doesn't have a fluid-specific one) could be a fallback handler - allow evaporating but don't do anything, allow evaporating but break the evaporator, forbid evaporating, etc.

Also, it should be carefully specified HOW it saturates the potion into the air - boiling is right out, because some fluids don't seem boilable, and hot steam can cause burns, fluids don't naturally "evaporate" in MC, but an aerosolizer like perfumes use would probably work fine.

**Comment by BluSunrize** [comment]
Immersive Petroleum has a flarestack to deal with excess fuel.

Potions can be sprayed by checmthrower turrets, you can make them target friendlies.
