### ISSUE TITLE
[Request] Config option to prevent crates from keeping their inventory when broken

### ISSUE THREAD

**Issue by the-realest-stu** [BluSunrize/ImmersiveEngineering#2748]
Crates holding their inventory when broken makes inventory management a total non-issue as soon as you get access to treated wood, which is really early. If a packmaker wanted inventory management to be more of a challenge like it is in vanilla, the only option would be to remove the recipe for crates, or at least make the recipe more expensive. The problem with that is it prevents crates from being used as regular storage, which sucks because they look a lot nicer than chests. A config option to prevent crates from holding their inventory when broken would solve this.

**Comment by BluSunrize** [comment]
No. The sole entire point of crates is having them keep storage. If you remove that, they are just expensive chests.
Recipe changes are your way to go.

**Comment by the-realest-stu** [comment]
I'm guessing the answer is no, but would you accept a pr that added this option? I mean, if it's disabled by default, then it can't really hurt to have.

**Comment by BluSunrize** [comment]
Yeah, still a no ^^

**Comment by the-realest-stu** [comment]
Seems pointless, but I guess that's to be expected from you. I guess I'll have to go with plan C, then.

**Comment by damien5314** [comment]
Just wanted to chime in since I found this thread after searching for a similar config. I was thinking more along the lines of just being able to adjust crate inventory size. I'm still very early game in my playthrough, but decided to opt out of using the crates so shulker boxes feel more exciting to unlock. If I could adjust the inventory to maybe 4-8 slots that would probably feel more balanced for the point in the game where they're accessible. Thanks for listening ✌️

**Comment by BluSunrize** [comment]
What's with people necro-posting 4 year old things recently...
