### ISSUE TITLE
[BUG Report] The spark works in issure

### ISSUE THREAD

**Issue by Lazy-Rabbit-2001** [BluSunrize/ImmersiveEngineering#2764]
Yeah, the version of my Forge is 2608, but when the Arc furnace is settled and the spark of it will "fly" everywhere in a random time.
If I have time, I'd like to report the screenshot.

**Comment by BluSunrize** [comment]
Screenshot would be very helpful because I have no idea what you're saying.

**Comment by malte0811** [comment]
I *think* I know what you mean: The arc furnace is meant to produce some sparks, but only when it is running. Right now it will emit sparks no matter whether it's running or not because I commented out a line for debugging and didn't re-add it. The molten metal render also isn't perfect in build 76, it is quite dark during the day.
Screenshots of how things are supposed to look:
![2018-02-03_19 50 03](https://user-images.githubusercontent.com/10406104/35770448-cc4d8df4-091b-11e8-970d-7b44a332244b.png)
![2018-02-03_19 50 11](https://user-images.githubusercontent.com/10406104/35770454-d99cd7a8-091b-11e8-97f0-b3acf27bc00c.png)

**Comment by BluSunrize** [comment]
Fixed on master
