### ISSUE TITLE
[Suggestion] Some logistical changes to make certain existing blocks/items more useful.

### ISSUE THREAD

**Issue by laserlemons** [BluSunrize/ImmersiveEngineering#2793]
First off, sorry if this isn't the best place for suggestions, I couldn't find a designated place for them.

Here's a list of things I think would make sense to change:

- **Unstack filled barrels and crates.** Right now, barrels and crates will stack if their inventories match. I think that's a problem for fairly obvious balance reasons. If this were fixed it would give players a reason to use the multiblock tanks and silos instead of chests full of crates or barrels.

- **Config option for picking up full barrels and crates.** Crates completely void the purpose of shulker boxes. The option to disable that would be nice since their cost is WAY less. Also, I think the recipe cost is still justified by the fact that they are visually pleasing, can be reinforced, and allow for the creation of toolboxes. As for barrels, it'd just be nice to have the option, especially if the next suggestion was implemented.

- **Add barrel minecarts.** This would help automate the process of transporting liquids without needing a long-distance pipe. They could interact with pipes and pumps for insertion and extraction.

- **Combine LV connector and relay functionality.**  This would make wiring in tight spaces much less bulky, as well as give LV connectors and wires more use in general.

- **Restrict capacitors to their respected connectors.** This would fix the fact that transformers are completely useless and in turn make wiring more interesting.

- **Restrict machines to specific voltage connectors.** This is a more drastic change but as it is, you can use HV wires for everything. That means that the myriad of different utilities made for power management in this mod aren't being used to their full potential. The combination of the last two suggestions would give each type of wire, connector, relay, transformer, capacitor, and breaker its own use case and allow the creation of fun and complicated power networks.

**Comment by malte0811** [comment]
1. It isn't a bad idea in principle, I'm not sure it's a good idea either. Getting things out of a silo is a lot easier than getting things out of a chest full of crates.
2. #2748
3. Minecarts and related things are @SkySom's responsibility. This was in MoarCarts (OpenTransport?) in 1.7.10, I believe a new version is in progress.
4. Relays and connectors were explicitly separated in 1.8.
5. and 6: Would be great if we had our own power system. Since we use RF/FE, we can't really restrict based on "voltage" since we have just one number.

**Comment by BluSunrize** [comment]
All of the above with explicit emphasis on Number 4.

**Comment by MauveCloud** [comment]
The first suggestion in that list wouldn't help that much toward encouraging the use of silos instead of chests of crates - a silo is 7 blocks high and 3 blocks in the other two dimensions and stores as much as 24 crates/chests, while even with non-stacking crates, you could fit 27 of them into a single chest (54 with a double chest, more with some of the variants from the Iron Chests mod), making it still a more attractive option unless you need automatic extraction of the contents.

**Comment by laserlemons** [comment]
I think suggestion 1 could be counted as a borderline bug. If you fill a full stack of crates with identical items you can hold 110,592 items in a single inventory slot. You could then fill a silo or shulker box or whatever with those.
