### ISSUE TITLE
[1.12.2][Feature Request?] Modtweaker -  Arc furnace recipe without slag

### ISSUE THREAD

**Issue by brut3force** [BluSunrize/ImmersiveEngineering#2801]
### Description of the issue:
I was trying to add some recipes for the arc furnace with the help of Modtweaker. After reading through the documentation on the wiki I saw that it is required to add a slag output to a new recipe. I tried to multiply the output stack by 0 but that only gets me "Error executing {[0:crafttweaker]: immersive.zs}: stack cannot be null". Is any way to create "nothing"? After searching for some time my google fu failed me.
While it is not a deal breaker just to add dirt as the additional slag output but it would be nice to make it optional, if that's possible.

### Versions & Modlist
IE: 0.12-76
Forge: 14.23.1.2571
Modtweaker: 4.0.6
Modpack: https://www.curseforge.com/minecraft/modpacks/automaton 1.1.0

**Comment by MauveCloud** [comment]
"Required" in crafttweaker/modtweaker recipes usually means there has to be an entry there rather than omitting it, but it's often allowed to use "null" there, which might work better than multiplying an output stack by 0 (there are some weird edge cases like GregTech configuration circuits that aren't supposed to be consumed by the processing recipe where you need to multiply an input stack by 0)

**Comment by brut3force** [comment]
"null" works fine, no more slag.
Thanks
