### ISSUE TITLE
[0.12-77] - No damage from uninsulated wires

### ISSUE THREAD

**Issue by ChronosWS** [BluSunrize/ImmersiveEngineering#2815]
After upgrading from -76 to -77, I find no damage from uninsulated wires.  Verified on but LV and HV wires.  Verified config enableWireDamage=true in configs.

**Comment by malte0811** [comment]
Screenshots? Are they connected to a power source? If so, what kind of power source?

**Comment by MauveCloud** [comment]
Also, do you have any machines actively running from these uninsulated wires?  If they're just sitting there with full internal energy buffers (either due to redstone signals or lack of input materials), the wires won't be transmitting any power, and that might explain the lack of damage.

**Comment by malte0811** [comment]
It shouldn't but might (That was an issue before, but it should be fixed).
I have a different idea on what might cause this: Please try placing a block so that it blocks a connection. This should cause the wire to drop (as an item). If that works the essential bit of code works (assuming you didn't disable blocks breaking wires).
Do you still have the old IE core in your mod folder (ImmersiveEngineering-0.12-76-core.jar, or even older ones)? If you have, try deleting that. I'm not sure how well forge handles multiple versions of the same coremod, if it only loads the old version the wire damage can't work.

**Comment by dieffenbachj** [comment]
I also had this problem; deleting tons of old coremods from the mod folder fixed the issue. Not sure why they were all there because this is basically a fresh install but oh well.

**Comment by gellis12** [comment]
I'm having this issue in 0.12-89, and have narrowed it down to the wires not causing damage after a server restart. If the wires and broken and replaced, they'll damage players again.
I've only tested it with a power source feeding into the wires when the server is stopped and restarted, so I'm not sure if shutting off all of the power generation on the network before the server restarts will solve the issue.
