### ISSUE TITLE
[Request] Capacitors directly connected to each other share energy

### ISSUE THREAD

**Issue by Lorelando** [BluSunrize/ImmersiveEngineering#2831]
I know something similar has been requested in #2488.

However, chaining capacitors efficiently becomes tedious rather quickly, especially as their connections (when touching directly) still seems to be limited by 1/4 the value of the respective wire tier.

Thus having them share the energy or removing the limit on their direct connection to each other (the one without wires) would make building power banks more enjoyable.

Minecraft 1.12.2
Minecraft Forge 14.23.2.2611
Immersive Engineering 0.12-77

**Comment by BluSunrize** [comment]
They are not limited to a quarter, they are limited to the in- and output rates of a connector. The "wire tier" is often misinterpreted, it solely serves so that you can combine up to 4 wires into one for longer distance transport rather than running 4 parallel lines.

Allowing Capacitors to transfer at higher rate between eachother might be an idea though (and better than making it an actual multiblock), I may look into that.
