### ISSUE TITLE
[1.12.2] IE fluids can be used to fill glass bottles with water

### ISSUE THREAD

**Issue by build2stone** [BluSunrize/ImmersiveEngineering#2849]
Creosote oil,  plant oil, ethanol, biodiesel and liquid concrete source blocks can all be used to fill bottles with water. 

Steps to reproduce:
Right-click any of the above fluids' source blocks with an empty glass bottle.

Mods used:
-Forge 14.23.2.2624
-Immersive Engineering 0.12-78

**Comment by Lorelando** [comment]
This seems to be a problem that comes with either Minecraft or Forge itself, and I'm guessing [Hooks for filling glass bottles #1841](https://github.com/MinecraftForge/MinecraftForge/issues/1841) might be part of the answer.

Basically, getting water bottles from any fluid is the default MC/Forge behavior.

**Comment by malte0811** [comment]
I'll wait until MinecraftForge/MinecraftForge#4619 (or an equivalent new PR) is merged. Water bottles are filled for every block using the `WATER` material. I can use custom materials for IE's fluids, but those don't have the basic properties of water (e.g. slowing and pushing entities) since that is determined by a hardcoded check for `Material.WATER`.

**Comment by BluSunrize** [comment]
We can't fix it from our end,
