### ISSUE TITLE
Suggestion- Farday Suit

### ISSUE THREAD

**Issue by CTH999** [BluSunrize/ImmersiveEngineering#2888]
The [Faraday Suit](http://sci.waikato.ac.nz/physicsstop/2011/07/the-faraday-suit.shtml), which is based off of the [Faraday Cage](https://science.howstuffworks.com/faraday-cage.htm). The main use of the faraday suit is to protect people from high-voltage wire. So, it should protect you from the wires based on scientific fact. Also, water should have some sort of effect on non-insulated cables, but I think that would be a lot harder :)

However, It's just a suggestion. Since it's your mod, it's your choice!

Thanks!

**Comment by BluSunrize** [comment]
I believe @malte0811 is already looking into the first part of that.

**Comment by malte0811** [comment]
Re: Faraday suit: See #2837. I want to make that work, but @BluSunrize wants the Tesla coil to work as a base defense against other players as well as mobs. I have an idea how to make that work while keeping it reasonably scientific. The idea is to connect a capacitor to the tesla coil in a way that will make it discharge into whatever the arc/streamer hits. This results in arcs like [this](https://www.flickr.com/photos/pslawinski/22660864248/) (the box on the right is the capacitor, assuming this image is what I think it is), rather than [this](https://www.youtube.com/watch?v=Ixtb5sXJdFc) (sorry, couldn't find images. I wanted both to be of the same coil). That, plus a bit of handwaving to scale it up, could destroy Faraday suits when hit (like [this](https://www.youtube.com/watch?v=MOzNioSGf8U)).
The TC just by itself would work as a defense against mobs, with some sort of capacitor upgrade to make it effective against players in Faraday suits. I haven't discussed this with @BluSunrize yet, he may have different/better ideas or not like my idea.

Re: water: I might do that at some point if I have too much/enough time. It should be possible, but could get a bit tricky in places.

**Comment by BluSunrize** [comment]
I mean, our Tesla coil already has the option of killing people in Faraday suits, when used in high-power mode. I see no reason to change that?

**Comment by malte0811** [comment]
Realism, though I'm probably overthinking this.
A tesla coil in normal operation generally won't destroy properly built Faraday suits, no matter how much power you put into it (I know that for certain up to 30 or 50 kW). If it did (at a pulsed power input of ~512 RF/tick, which is roughly 25 kW according to my numbers), a high-voltage power line (at 4096 RF/tick or 200 kW, and at a lower voltage) would destroy it even more. With a capacitor upgrade it would be plausible (or at least not absolutely impossible) for a TC to destroy Faraday suits that work with HV power lines. As I said, I'm probably overthinking this.

**Comment by CTH999** [comment]
@malte0811 No, you aren't overthing it.

Also, what all of you are saying makes sense!
Can't wait to see what happens!

**Comment by DoomRater** [comment]
If you ask me, Faraday suits are already underpowered pieces of armor vs a sword or anything else.  If someone wants to bypass a tesla coil with them, let em- just makes it easier for the turrets to turn them into swiss cheese.  Or maybe exposure to water could make the Faraday suit worthless, so if you're REALLY determined you can add a chemthrower turret with a water spray that does the trick.  How many other uses does shooting water have anyhow?  "Emergency fire extinguisher"?

**Comment by CTH999** [comment]
@DoomRater I have to agree personally, though, It would also be cool if the Chem Turret auto targets flames...

Well, just a though though!

**Comment by malte0811** [comment]
The Faraday suit will work against/with live wiring in IE build 81. I didn't implement the idea from my last comment, they don't really fit with IE (too complicated, too scientifically accurate).

**Comment by DoomRater** [comment]
Protection against live wiring is a super good use case for them.  It's serving the same purpose as the radiation suit in IC2, but more obviously.

**Comment by kragnoth** [comment]
Thank you.  Looking forward to this getting pushed to modpack.
