### ISSUE TITLE
[Bug] Wires partly not rendering on server until reconnecting to the server or reattaching the wires

### ISSUE THREAD

**Issue by Lorelando** [BluSunrize/ImmersiveEngineering#2893]
Lots of wires stop rendering on remote server upon restarting the MC client until reattached or reconnecting to the server. This could be a mod conflict or a world loading problem.

A more detailed description of how when it happens and when it doesn't:
- Loading the world locally in any way, either through the client or through a server hosted on my PC does not reproduce the bug.
- Connecting to the remote server for the first time after starting the MC client causes the wires to only partially render. Reconnecting completely solves the issue. Restarting the server without restarting the client has no influence. After restarting only the client the wires partially stop rendering again.
- Connecting to the remote server while both client and server only have IE installed (but with the old world, no OptiFine) still produces the same bug. This is the entire [fml-client-latest.log](https://gist.github.com/Lorelando/d3dbaa7fc7d6c5e67ad744ce78b23f9c)

Minecraft 1.12.2
Minecraft Forge 14.23.2.2611
Immersive Engineering 0.12-79
(and more)
[Full Modlist](https://gist.github.com/Lorelando/27ffd6744d0c62961c709bfb7332e712)

**Comment by malte0811** [comment]
Interesting. I'm pretty sure I'd have noticed this one if it happened in my dev environment.

**Comment by glindsey** [comment]
I believe I'm seeing a similar problem. I originally thought it was because I had upgraded to Optifine C9, so I wasn't going to report it since Optifine isn't supported by IE devs. But after I saw this issue, I realized I'm seeing the same problem. I'm still only seeing it with Optifine enabled, however in any case I see a whole bunch of concerning log errors. Here's a breakdown of what I see:

- First connect to server after starting client:
-- Log contains a whole bunch of lines reading "`[main/ERROR] [immersiveengineering]: TileEntityImmersiveConenctable encountered MASSIVE error reading NBT. You should probably report this.`"
-- If _not_ running Optifine, wires appear to render normally.
-- If running Optifine, wires do not render. Tested with C8 and C9, same results.
- Subsequent connects to server after starting client:
-- Log errors no longer appear on connect.
-- Whether or not Optifine is running, wires appear to render normally.

In any case, it appears the issues with Optifine rendering stem from these "massive NBT errors" showing up on the initial connect.

I'd post my entire modlist, but for some reason F3+C seems to have no effect on my client. If it would help I can dump the directory listings of my mod folder on both the client and server; just let me know.

**Comment by Lorelando** [comment]
@glindsey You have to press and hold [F3] + [C] and I think it only works if you have a world loaded or are connected to a server.
Weird that you get the bug only with OptiFine, I'll have to narrow down the cause on my side as soon as I work out why something else entirely isn't working on my server :P

**Comment by glindsey** [comment]
Some additional info: just connected to my server while in an area with no IE wires present; once I teleported to an area where there _were_ wires, I got the dozens of "`MASSIVE error reading NBT`" errors, followed by a "`Tesselating block model`" crash. (This is still with Optifine C9 running.)

Full crash log is available at https://gist.github.com/glindsey/b1d71e9059abaf854f7284b0ca4389b6.

I'll disable Optifine for now and reconnect, let you know if I have any further errors.

**Comment by Lorelando** [comment]
I have done the whole test again with only IE 79 installed on both the client and the server, while the old world (usually run with the full modlist) was loaded. Upon connecting the first time it again doesn't render some wires. This is the entire [fml-client-latest.log](https://gist.github.com/Lorelando/d3dbaa7fc7d6c5e67ad744ce78b23f9c) taken from the client.

**Comment by glindsey** [comment]
Hey, I just confirmed I'm getting the same issue without Optifine. Disconnecting and reconnecting to the server fixes the problem.

**Comment by malte0811** [comment]
Fixed, sorry for not fixing this earlier.
There were 3 things that would have made this quicker (in descending order of speedup):
1. Proper error logging for this error (added that now).
2. Me not trying to figure this out by looking at code on GitHub while tired. I looked at the code involved a few days ago, missed the one call that caused this, saw a similar call a few lines down and decided that that call couldn't cause the error because of the lines between the calls.
3. Me not trying to change the output for an error in NBT reading by changing the error handling for NBT writing. That took about an hour, because I thought IDEA was just not properly updating the code.

**Comment by glindsey** [comment]
Oh hey, no problem! I've been coding for 15 years, I completely understand how bugs can elude a person, especially when you're tired. Glad to see you found the culprit!

**Comment by Xlaits** [comment]
I'm also seeing this, but I'm not sure which version if IE I'm running anymore. I'll have to check and update it if I'm using an older version.

**Comment by Mr666dd** [comment]
Hello, I sometimes do not display wires, high-voltage. The error was on 1.16.5, and on 1.12.2, I also use Optifine. Error on the server. And also sometimes the wires "disappear", I do not know what this is connected with.

**Comment by BluSunrize** [comment]
Optifine is not supported, and you're necroposting on an issue closed 4 years ago.
