### ISSUE TITLE
[Crash] Something about Drills and Itemfluidhandler

### ISSUE THREAD

**Issue by Volkaeno** [BluSunrize/ImmersiveEngineering#2934]
I was trying to make a modpack on the twitch launcher, and IE was a part of it. However, every time I tried to start it, it crashed during the initial startup. [Here is the crash report](https://pastebin.com/9Yygd10f) Even with just IE and forge it gave the same crash

**Comment by mindforger** [comment]
> IELoadingPlugin (ImmersiveEngineering-0.12-79-core.jar)

outdated "core" files are not removed automatically, so you have to remiove the outdated file i noted here

this is a bug with forge and nothing that can be done about it, because forge forbids to remove those file on launch and it has to be bundled with the mod-jar file and gets extracted automatically by forge

**Comment by malte0811** [comment]
This is a Forge issue, all capabilities are being initialized to `null` in the latest forge version. I'm debugging this right now, see the Actually Additions issue I linked above for future updates.
