### ISSUE TITLE
[Suggestion] Thermoelectric generator is too OP!

### ISSUE THREAD

**Issue by ExDomino** [BluSunrize/ImmersiveEngineering#2976]
Hello,
The problem is about the Thermoelectric Generator. It is too OP! It generates too much energy.

When a windmill is capable to generate only 50 RF/t during thunder if placed over y>201 and need specific installation (clear zone of 7 blocks in front of it), the Thermoelectric Generator can generate 62 RF/t alone, underground and everytime, days and nights.

I suggest to reduce the energy output of the Thermoelectric Generator by 10 by default. So set its multiplicator settings at 0.1 instead.

Thank you in advance.

**Comment by BluSunrize** [comment]
uhh...what version of IE are you playing on?

**Comment by ExDomino** [comment]
You have nerfed the thermoelectric generator in very latest releases?

**Comment by BluSunrize** [comment]
No but windmills work quite different from what you're describing.

**Comment by ExDomino** [comment]
You really don't consider that thermoelectric generator is too OP ?
So when an user can create only 10 of them, and generates more energy than a nuclear reactor, without any fuel, that is completely a normal and intented behavior?

**Comment by malte0811** [comment]
I agree that they are a bit OP, but the same applies to all solar panels (even more since they don't have the (small) risk of setting you or your house on fire).
What kind of nuclear reactor are you talking about? Big/extreme reactors (the only reactor mod I ever actually used) will easily go up into the kRF/tick range with quite low fuel consumption using the default configs (at least they did in early 1.7.10). And with bigger reactors the energy to fuel ratio rises AFAIK.

**Comment by BluSunrize** [comment]
IE currently doesn't have a nuclear reactor, and I don't ballance around other mods, so yes, I consider them to be a reasonably fair mid-game powersource.

Now given your lack of consideration for our issue template in reporting this, I'm closing this issue.
