### ISSUE TITLE
Loading Crash in relation to IE

### ISSUE THREAD

**Issue by SwordsmanJoe** [BluSunrize/ImmersiveEngineering#2994]
Crash report states that IE was invalid/not supported and refused to load past a certain point
 log - https://gist.github.com/SwordsmanJoe/c1710a8c482f4c121ae0b3e94d618600
crash report - https://gist.github.com/SwordsmanJoe/95fa69c797dc95182a696bc8030ca7ec
using ImmersiveEngineering-0.12-81 and ImmersiveEngineering-0.12-81-core in forge-1.12.2-14.23.3.2675

**Comment by malte0811** [comment]
That is an interesting crash. Is this modpack available anywhere? Could you try a couple of things:
1. Update Forge to latest (and maybe try recommended too).
2. Try with only IE installed (this shouldn't crash, I just tested it). If it crashes you can skip 3.
3. Do a binary search on the mods you have installed: Remove half of them (keeping IE), see if it still crashes. If it does, remove half of those mods and repeat. If it doesn't take those mods out and put the ones you just removed back in. Test if it crashes with those mods. If it doesn't come here and tell us, otherwise remove half of the mods and repeat.

**Comment by SwordsmanJoe** [comment]
WIP modpack that I've been making on and off for the past several months. Not yet released. New reports found as well:
crash report - https://gist.github.com/SwordsmanJoe/2d783589aacab93e866b8f5d009a1e2c
latest log - https://gist.github.com/SwordsmanJoe/6b13c1dab372bbb3746fdddee1fafdc2
using forge-1.12.2-14.23.3.2690

**Comment by BluSunrize** [comment]
Please employ the methods Malte described above. Especially step 3, the binary search, is important in order to identify the possible cross-mod interaction that is causing this.

**Comment by SwordsmanJoe** [comment]
Looks like it is in relation to simple fluid tanks. Which is weird because there wasn't a problem with it before
crash - https://gist.github.com/SwordsmanJoe/e1b6f06f843d0e7a124b7afba4c1f681
latest log - https://gist.github.com/SwordsmanJoe/e7e29dce2df367a16649d275914945f5

**Comment by SwordsmanJoe** [comment]
And in forge-1.12.2-14.23.3.2691
log - https://gist.github.com/SwordsmanJoe/cdee9c58cad568cb49535475ca8d628f
crash - https://gist.github.com/SwordsmanJoe/72a44c79ec93e3517041200cee89646f

**Comment by malte0811** [comment]
This on their side.
@Zarathul please don't package other mods API classes in your mod, for 2 reasons:
1. It will cause crashes like this one if the mod the API is from is signed (or you decide to sign your mod).
2. If we update `ITool` in some way and your version gets loaded first (like it got here) any calls to new methods in `ITool` would cause some nasty error/crash.

**Comment by Zarathul** [comment]
I worked around the problem on my end .... kind of.

> It will cause crashes like this one if the mod the API is from is signed (or you decide to sign your mod).

That's why APIs, in a perfect world, should really be their own thing and not get mashed together with a mod, unless you want the API to be unusable without the mod.

> If we update ITool in some way and your version gets loaded first (like it got here) any calls to new methods in ITool would cause some nasty error/crash.

I'm pretty sure the API annotation in package-info was introduced to specifically solve that problem. Unfortunately it doesn't work anymore if you sign the API.

Since you don't want others to package your API, what's the usage policy on the thing anyway? Is it supposed to be used only in combination with IE? I mean, that' s the only way it works now.
