### ISSUE TITLE
[1.12] Cloche deletes seed/dirt item when destroyed via top/middle block

### ISSUE THREAD

**Issue by randomlypickedname** [BluSunrize/ImmersiveEngineering#3024]
### Description of the issue:
Garden cloches don't drop their items when a player destroys the center or top block.

### Versions & Modlist
Forge ver 23.3.2678
IE ver 0.12-82
[Modlist gist](https://gist.github.com/randomlypickedname/f523ee419ecdb4e05057d5906a51c97d)

**Comment by Fireztonez** [comment]
I get the same issue with the Garden Cloches, with Immersive Engineering 0.12-88, with forge 14.23.5.2806...

Can you take a look, because this is probably not bad for vanilla Seeds, but for last tier Mystical Seeds, this is little anoying when you have to craft a new one, because the cloche delete all the content (Including outputs slot).

Please just tel me if you need more informations or something from me question to be able to fix the issue...

Thank's
Fireztonez
