### ISSUE TITLE
[1.12.2] South-facing windmill lag

### ISSUE THREAD

**Issue by Hexawolf** [BluSunrize/ImmersiveEngineering#3035]
Immersive windmills cause major lags on low memory available for Minecraft.

### Versions & Modlist
Immersive Engineering: 0.12-82
Forge: 14.23.4.2705
Modlist: https://goo.gl/DwhHeE
Configs: https://hexawolf.me/git/Hexawolf/config

--

I'll try reproducing this issue with minimal instance when I'll be able to do so. I am also ready to heavily collaborate on detecting and fixing this issue.

Though FoamFix and OptiFine is listed in modlist, I've been able to reproduce this bug without them, just Minecraft explicitly requires more memory. This does not occurs if 4 GB is allocated and FoamFix is used, but this is too much for a single mod.

**Comment by BluSunrize** [comment]
If you can reproduce this in a test instance and test world, I'd love some pictures of the setup.

**Comment by foxcpp** [comment]
This problem is closely related to VoxelMap. Logs are flooding with following when it happens:
```
[16:51:12] [Voxelmap LiveMap Calculation Thread/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.OutOfMemoryError: Java heap space
```

I reproduced it with just following mods installed and 1 GB of memory allocated to Minecraft:
```
ImmersiveEngineering-0.12-82.jar
jei-4.9.2.196.jar
LagGoggles-4.1.jar
mod_voxelMap_1.7.0_for_1.12.2.litemod
```
Without VoxelMap everything is fine.
With 2 GB memory everything is fine too.
What I built is on screenshot here: https://imgur.com/ND1pgOM.
Removing windmill from south side solves problem too.

**Comment by malte0811** [comment]
I've been able to replicate this (at least the OOM errors), I'm debugging it now.

**Comment by foxcpp** [comment]
Any updates?

**Comment by malte0811** [comment]
I contacted the author of VoxelMap (@MamiyaOtaru) via CurseForge, but didn't get a reply yet. I assume this is caused by some little detail about windmills triggering some bug in VoxelMap. Since VoxelMap is closed source and obfuscated I don't really have a chance of finding either the detail or the bug myself without a massive amount of work.
