### ISSUE TITLE
[1.12.2] Chemical Thrower causes disconnect

### ISSUE THREAD

**Issue by EscolarProgramming** [BluSunrize/ImmersiveEngineering#3065]
### Description of the issue:
If you craft a Chemical Thrower, fill it with lava (we've only tested it with tis liquid, maybe the issue is also with other) and right-click it, you (and all players in a radius of ~8 chunks) are kicked from the server with the message "The server you previously where went down", but the server is still running and after a few seconds you can join again. Only players in this limited radius are affected and minecraft does not crash, you get only kicked. But it's still annyoing ^^

### Crashlog:
https://pastebin.com/JFsAvjsg
In the log of the console there's only the message "<Player> lost connection: Internal Exception: io.netty.channel.unix.Errors$NativeIoException: syscall:read(...) failed: Connection reset by peer"

### Versions & Modlist
https://pastebin.com/7siy1KcB
We're using the FTB-modpack Continuum.

**Comment by JoeSGT** [comment]
https://github.com/HexagonMC/BungeeCord/issues/207
To get more information on this issue
it seem that it's caused by Bungeecord but no fixes has been made also this didn't happen a few version back i am unsure what version of immersive engineer that didn't had this issue but can you please fix it somehow xD please?

**Comment by EscolarProgramming** [comment]
Yes, we are using BungeeCord (HexaCord to be exact)
