### ISSUE TITLE
[1.12] Rendering issue with IE blocks

### ISSUE THREAD

**Issue by ospis12** [BluSunrize/ImmersiveEngineering#3069]
### Description of the issue:
Metal press, wooden posts, Air preheaters.
Screenshots: https://imgur.com/a/b1nqCkO
save file: https://www.mediafire.com/file/xjp346i4c3hsxm3/Nudna+sobota.7z

### Versions & Modlist
Issue in FTB Continuum 1.3.1

**Comment by BluSunrize** [comment]
Out of interest, does this happen if you put them one block higher?

**Comment by ospis12** [comment]
Sorry for not giving answer earlier. If I  put one block higher, no render issue...

**Comment by malte0811** [comment]
That's a known issue that would take more time to fix than it's worth.
MC doesn't just have the horizontal chunks you might know from chunkloading, the world is split vertically as well, into 16x16x16 cubes. This is used for better rendering performance: cubes/chunks you can't see aren't rendered, and only one cube needs to be updated when placing a block.
All IE machines are rendered by a single block, in the case of posts this is the bottom block. When you place a post on level 63 (or any 16×n-1, n a natural number) and look up, the bottom block of the post is in a chunk you can't see. Therefore it isn't rendered and, since it renders the whole post, the post in temporarily invisible.
