### ISSUE TITLE
[Suggestion] Extendable Wooden Post

### ISSUE THREAD

**Issue by Sm0keySa1m0n** [BluSunrize/ImmersiveEngineering#3087]
As Immersive Integration seems to be dead I think an extendable wooden post would be a great addition to the mod, the current wooden post is very short and it would be a fantastic feature being able to extend it. I've attached an image showing what I'm on about.
Thanks in advance.
![vztsvqj](https://user-images.githubusercontent.com/26169906/42396097-405b902e-8158-11e8-99a3-3d386b064f8d.png)

**Comment by BluSunrize** [comment]
There's an addon for this

**Comment by Kiefy** [comment]
Imagine loving a mod so much that you want to help improve it, and the dev can't even be bothered to read your suggestion and just closes it instantly.

The "addon" only existed in 1.7.10.

**Comment by josephtarbit** [comment]
This now exists in the form of [Immersive Posts](https://www.curseforge.com/minecraft/mc-mods/immersiveposts) for anyone looking for a solution.

**Comment by BluSunrize** [comment]
And it existed as that addon when I made the issue response, closing this issue =P

Hence *why* I closed it, because TwistedGate does wonderful work, and I see no reason to "absorb" his project.

@Kiefy has since removed their response to this issue but... I get emails, so I saw it anyway. Good job.
