### ISSUE TITLE
Suggestions: Stuffs and Stuffs

### ISSUE THREAD

**Issue by RamWerkz** [BluSunrize/ImmersiveEngineering#3108]
Hello just a few suggestions, to those who don't understand and want to complain, I sent a comment to check if and where to suggest things so chill before you chat me out.
Sandbags: Just some hemp fabric and sand, mostly for decor maybe some blast resistance
Bayonets: Allow the bayonets on the chem thrower, rail-gun and maybe drill~(just for giggles)
Reinforced Faraday: I get it Faraday is supposed to be weak but something to protect you from tesla-coils but maybe add a reinforced Faraday armor recipe. It could also have some debuff

**Comment by RamWerkz** [comment]
Derp~ Don't use github much, I assume this should go in the "Pull requests" :P

**Comment by BluSunrize** [comment]
Nope, issues is the correct place to put it =P

**Comment by malte0811** [comment]
Sandbags seem a bit useless, and I don't think they'd be that explosion resistant.
Bayonets on the other weapons+drill wouldn't really work IMO, I feel like they're a bit heavy to hit people with a small blade with any acuracy. It also doesn't feel like it's "new" in any way. What might be interesting would be an upgrade to the railgun that extends the rails a little bit outside of the "housing": The rails are connected to some serious HV capacitors, touching them (or getting hit with them) would be quite dangerous.
A more powerful Faraday suit isn't going to happen, though I'd still like one. See #1169 for details, but @BluSunrize essentially wanted TC's to be useful against players as well as mobs, which it wouldn't be if players could evade the damage for a fairly low cost.

**Comment by BluSunrize** [comment]
Adding to this (now that I actually have time to phrase a full reply):

- Sandbags are an interesting idea. With Minecraft not really featuring floods, that negates one of their prime function. I can see them being somewhat explosion resistant (though IRL they are usually more there to catch the shrapnel). My biggest issue is getting a good model for them, because sandbags are usually kinda "droopy". Having a single one would be lower than a slab, and having multiple would require them being in a sort of "pile". Would be a very complex model, all the more so if one wanted to make them connect.
- Bayonet: On the drill this is very pointless, given that the drill with all augers already inflicts some rather potent melee damage. The Chemthrower is already a short-range weapon, it wouldn't really benefit. The Railgun would, allowing you to go into melee when you don't have time to charge anymore, but on the other hand that also takes away from its ideal as a long range weapon. Plus, it's a whole new mess of modeling =P
- Faraday Suit is designed to be low-armor. I don't intend to change that because I want people to chose between protection from zapping and protection from zombies. When the time finally comes that I get to implement the power armor I've been wanting to do for about 2 years now, I may very well have a Faraday upgrade however. That project remains on ice however until Hazard or I actually model the damn thing.
