### ISSUE TITLE
Ideas for the lazy individual (i.e. me)

### ISSUE THREAD

**Issue by CTB33391** [BluSunrize/ImmersiveEngineering#3120]
- This
 may already be in the mod but I never saw it in the manual: an excavator would continue to output from the deposit, but way slower. Kinda like Immersive Petroleum and Factorio. Could be a config option, disabled by default.

- Some way to automate speedloader loading. Could be pretty cheap and load in batches. To compensate loading special ammo would require an extra thing built onto it before finalising, and only able to load a single type of ammo.

**Comment by PrincessRTFM** [comment]
The issue I see is that it'd be _too_ useful, I feel. Throw down a bunch of excavators to compensate for reduced output and your factories will be fine. Fill a barrel with your preferred ammo and load it into the machine, then when you get home you can dump your empty speedloaders into a bin and by the time you've put your stuff away and all that, there's a fresh pile waiting for you. I guess it would be offset by the need to manually make the ammo at the workbench, at least. Personally, I'm lazy as hell, but even I don't really like the idea of a full ammo production chain from raw materials to finished speedloaders... I want more than just "let me hit the factory outlet and restock my everything", because if I reach that point, when everything everywhere is automated, why play the game any further? Yes, it's nice to set up automation, but I want some things to still require manual intervention, or else I might as well not play.

**Comment by BluSunrize** [comment]
I'll second both of those things.

Excavators run out specifically so that you *don't* have infinite materials from a single spot. You are supposed to move them after the vein is empty. If you don't want that, you can use commands to cheat and make it infinite.

The second one I had previously considered, but tbh, loading speedloaders is really easy. Grab a stack of bullets and drag it once around the slots. Takes less than 10 seconds.

**Comment by BluSunrize** [comment]
Yeah but just because Flaxbeard does that for his stuff doesn't mean I want it for mine =P

**Comment by Euphemios** [comment]
There is a recipe for loading speedloaders but it doesn't work in the assembler for some reason, it shows up but won't output anything

**Comment by PrincessRTFM** [comment]
I wouldn't be surprised if the speedloader recipe either a) wasn't a "normal" crafting recipe with the vanilla handler or b) had special magic to prevent the assembler from crafting it, specifically so that you have to do it by hand.
