### ISSUE TITLE
[1.12.2] Strange Interaction between Immersive Engineering, Pam's Harvestcraft and Astral Sorcery

### ISSUE THREAD

**Issue by Eresorm** [BluSunrize/ImmersiveEngineering#3122]
With all three mods installed the Assembler Multiblock can't craft some Pam's recipes. It shows the recipe but doesn't output anything. Without Astral Sorcery installed everything works as expected. 
I have reported this on the AS Github already. #https://github.com/HellFirePvP/AstralSorcery/issues/816
Handcrafting the recipes works in any case.

![2018-07-19_22 32 16](https://user-images.githubusercontent.com/36823423/43017590-f3974b66-8c56-11e8-902a-f3e060a716b8.png)

From my testing it seems that only recipes that use things like the Pot are affected, but only if they also output a Pam's items.

Used mods:
- IE: 0.12-84
- Pams: 1.12.2u
- AS: 1.12.2-1.9.3
And the previous Version of each mod respectively
Forge Versions:
- 14.23.4.2705
- 14.23.4.2729
- 14.23.4.2739

**Comment by Doomgull** [comment]
This is likely an NBT matching issue.

**Comment by crazycarl** [comment]
I have found that updating to Immersive Engineering version 0.12-87 fixed these issues for me.

**Comment by rinart73** [comment]
Updating IE to 0.12-87 didn't fix the issue for me.
IE: 0.12-87
Pams: 1.12.2za
AS: 1.12.2-1.10.3

**Comment by mindforger** [comment]
@rinart73

Can you append more details please? Or pastebin a forced crashlog ( hold f3 + c) until the game crashes ... While ingame, not in the menu

**Comment by rinart73** [comment]
@mindforger 

From what I can see, it happens if recipe has any of the following Pam's items: Mortar and Pestle, Juicer, Saucepan, Pot, Mixing Bowl, Bakeware, Skillet, Cutting Board. So basically, any item that is used in the recipe but not consumed and usually just stays in the crafting window unchanged after crafting finished, unlike food ingredients or bucket of water.

I tried to remove Astral Sorcery and Assembler worked as it should.

Forced crashlog: https://pastebin.com/Ti46bhCb

**Comment by crazycarl** [comment]
Yes, the issue actually came back for me as well.
I've been digging in the source code and find the problem seems to be related to [this line](https://github.com/BluSunrize/ImmersiveEngineering/blob/0da084dcd169070f4a1f7eed9290026dd395b681/src/main/java/blusunrize/immersiveengineering/common/util/Utils.java#L121) .

Replacing it with just a dumb "return true" makes it go away, but I'm sure that introduces new bugs. This also happens to fix [the Custom NPCs issue.](https://github.com/BluSunrize/ImmersiveEngineering/issues/3270)
Does anyone know what the `ItemStack.areCapsCompatible()` function  does? I haven't been able to find documentation on it.

**Comment by rinart73** [comment]
I did some digging and the reason why Pam's cooking utensils don't match is that Astral Sorcery adds an NBT record to them for some reason.
So here is the serialized NBT for Mortar and Pestle.
recipeQuery.query (ItemStack): `{id:"harvestcraft:mortarandpestleitem",Count:1b,Damage:0s}`
And here is the actual ItemStack in the assembly inventory: `{ForgeCaps:{"astralsorcery:cap_item_amulet_holder":{}},id:"harvestcraft:mortarandpestleitem",Count:1b,Damage:0s}`

**Comment by Doomgull** [comment]
The record is added, because it's a non stackable item. It's the cleanest method to grab all equipables, without having to maintain a completely separate list or config file containing all of the potential equipped items that might be impacted by the amulet. I did point this out 5 months ago.

**Comment by crazycarl** [comment]
So it sounds like this is just a check to see what operations can be done with an item. I bet Custom NPCs is doing something similar. Is this not important to crafting? If so, we could just make a different NBT check for the assembler that ignores this part.

**Comment by rinart73** [comment]
If I understand correctly, something is just wrong with the ItemStacks from Recipe. For some reason, Assembler retrieves items from a recipe, but they don't have this specific NBT record. Because of this, assembler thinks that items don't match.

**Comment by GhaladronOG** [comment]
I'm still having this issue in ATM 3. Running AS 1.10.20, IE 0.12-92 and PH 1.12.2zf. Is there any hope of a fix in the near future? Building a large food factory and I love the IE aesthetic so I hope there's some kind of solution available.

**Comment by Worf2340** [comment]
I'm having a similar issue, but I don't have Astral Sorcery installed. Here is my mod list: https://i.imgur.com/A0cm0nb.png

**Comment by sirNacati** [comment]
Same Problem can't actually craft ;/

**Comment by ZenithAstralis** [comment]
I just ran into this bug as well; the same issues, though I haven't tried removing Astral Sorcery yet.
AS 1.10.23
IE 0.12.92
Forge 14.23.5.2854

And a similar thing with crafting torches with a creosote bucket, 1 wool block, and 3 sticks, even when that same assembler makes treated wood just fine.

**Comment by Brycey92** [comment]
I know this was last commented on over a year ago, but was it closed because it was fixed or because it won't be fixed?

**Comment by BluSunrize** [comment]
Same as with the other issue you asked about.
