### ISSUE TITLE
[1.12.2] [Enhancement] Update Thaumcraft Support

### ISSUE THREAD

**Issue by TechnoMysterio** [BluSunrize/ImmersiveEngineering#3129]
Updating IE's Thaumcraft support for Thaumcraft 6 would be excellent. I already saw the Thaumcraft support code left from earlier versions, which mentioned support for things like the Chemthrower throwing Thaumcraft fluids (liquid death, purifying fluid, flux goo) and External Heater support for the Essentia Smeltery, so updating that file would be a good step to take for mod compatibility's sake. I suppose aspect support would be good too, but I know that's a right pain for larger mods with lots of blocks and items.

IE: 0.12-84
Thaumcraft: 6.1.BETA19
Forge: 14.23.4.2739

**Comment by Wotzinator** [comment]
and maybe thaumic bullets(like the botania and blood magic Bullets)

**Comment by PrincessRTFM** [comment]
Doesn't TC have a system like Equivalent Exchange where it iteratively scans recipes to construct aspects for things based on the aspects of their ingredients? I know TC5 did, because a certain mod added a circular recipe that caused a stack overflow on load, but I don't know if it's made it into TC6 yet. If so, depending on completeness of course, couldn't a modder just specify aspects for their base ingredients, register their crafting handlers with TC somehow (I expect custom handlers would need that, but might be wrong), and let TC handle the rest?

**Comment by BluSunrize** [comment]
Thaumcraft does not have an option to register my own Recipe Handlers for calculation.
The Thaumcraft compat I offered previously is being re-implemented however, including the Fluids.

The external heater compat has already been restored, see here:
https://twitter.com/BluSunrize/status/1025386313439223809

**Comment by PrincessRTFM** [comment]
Ah, never mind then. But hey, the return of the old compat is nice!
