### ISSUE TITLE
[suggestion] add content

### ISSUE THREAD

**Issue by GabrielCruz120102** [BluSunrize/ImmersiveEngineering#3136]
Add content present in the Immersive Petroleum,Immersive Railroading and Alternating Flux add-ons.

**Comment by mindforger** [comment]
why not keepingnthe addons liek they are, so they can be maintained from their makers more effective?!

**Comment by GabrielCruz120102** [comment]
To reduce the risks of content discontinuity in these addons.

**Comment by mindforger** [comment]
well that would mean he had to invest time and brain to rip code from the still active addon mod devs and take over their effort and code or let them participate in the main repo .... all this comes with a lot of effort and headache ... don't you think this would be unfair towards the addon makers to rip off their stuff to plunge it into the main mod and then additionally have to deal with their bugs also? 

Or do you think having mutiple people working on different parts of a repo makes it anywhere more stable and managble at all? 

i would understand the request if some addon mod actually was discontinued but other than that it just sounds rude and not well thought through as a request

**Comment by BluSunrize** [comment]
First of all: LOL.

Second of all: No.

Thirdly: All of those mods are created by *different people*. All of these projects have their own developers who have invested lots of hours into them. So ignoring any possible license issues, simply "absorbing" or "copying" their work would be a real dick move.
IE absorbed some of the II content after 1.7, upon me having express permission from UnwrittenFun because he didn't plan to continue the project. I don't forsee myself doing that with any of the ones mentioned above.

Lastly: I wouldn't want some of the addon mods content in IE, because I personally don't think it fits the style. All the more reason for it to remain an addon and thus optional.
