### ISSUE TITLE
[1.12.2] Drill Head Dupe Bug

### ISSUE THREAD

**Issue by LiEyWe** [BluSunrize/ImmersiveEngineering#3161]
### Description of the issue:
If I put the Drill in the Workbench and remove the drill head, it is removed in the UI but not in the drill itself. When I break the workbench and place it again, I can get the drill head again out of it.

Sometimes, ALL upgrades (augers, lubricator, large tank) disappear from the drill. But I can not reproduce it reliably.

I've made a video to clarify this issue: https://www.youtube.com/watch?v=vHFzqmeoWa4&feature=youtu.be

Also, I am playing on a dedicated server.

### Versions & Modlist
https://pastebin.com/8D4LeRGn

Edit by @malte0811: Fixed both links

**Comment by mindforger** [comment]
>Also, I am playing on a dedicated server.

with sponge or similar or with plain forge?

also your crashlog link is broken

**Comment by LiEyWe** [comment]
> with sponge or similar or with plain forge?
just plain forge

> also your modlist link is broken
[https://pastebin.com/ML7tSc32](url)
hope this works now...

**Comment by mindforger** [comment]
yes :)
thx for the info, i was assuming maybe some odd behaviour from sponge there

**Comment by malte0811** [comment]
I can't reproduce this. I think I can guess why the upgrades are disappearing, the fix will require a Forge build later than the current recommended one (>=14.23.4.2718). I'll implement the fix and then maybe talk to Lex about getting a new recommended build. The duplication my be caused by the same issue.
