### ISSUE TITLE
[1.12.2] Lag caused by razor wire in single player

### ISSUE THREAD

**Issue by Iasus** [BluSunrize/ImmersiveEngineering#3163]
Running Immersive Engineering 0.12-84 as part of Direwolf20 pack v2.2.0, Forge 8.0.99.99 per DW20 pack. 

Blocks of razor wire in the world cause lag in single player game.   I had approx 75 blocks of razor wire placed and they caused significant lag in world.   Reproduced by removing razor wire, lag stopped.  Replaced razor wire, lag returned. World did not crash.

**Comment by malte0811** [comment]
What kind of lag? Low FPS or block update lag, entity rubberbanding, etc?
Some screenshots would be helpful, especially of the power connections. Is there a single power source on the wire network supplying the razor wires or multiple small ones?

**Comment by Iasus** [comment]
Low FPS and lag updating when putting items in crafting station (Tinkers') or crafting grid (Refined storage) is how I first noticed it.  There were low FPS issues to.

I did not have it hooked up to power - the razor wire blocks were just placed in world.  I'll put some back and reproduce and put some screenshots up later.

**Comment by LemADEC** [comment]
Confirmed on ImmersiveEngineering-0.12-84: everything a block updated happens in an area with Razor wire, a lag spike is observed and average FPS drops.

**Comment by malte0811** [comment]
I was able to reproduce the issue yesterday, I'll try to fix this and #3121 today. It might just be the high-ish quad count, I'm not sure.

**Comment by malte0811** [comment]
I did some testing, I'm pretty sure this is purely caused by high quad count. The razor wire has about 300 quads (give or take some depending on where it is, whether it has the wooden sides). That is roughly the same quad count as for 5 wire connections (they have 64 quads each, 4 quads in each of the 16 sections), and I wouldn't be surprised if a chunk update in a chunk with 375 wires would cause some FPS drop.
