### ISSUE TITLE
Copper not spawning. (IE 0.12-84, MC 1.12.2)

### ISSUE THREAD

**Issue by Ampmasterful** [BluSunrize/ImmersiveEngineering#3167]
Had set up a server for me and friends using the modpack ATM 3. was looking for copper for about 2-3 hours, and dug a 2k block long mine shaft at y level 50 and couldnt find any copper, then i went caving and still none. I isolated the mod and ran my server using only IE (with jei and jer) and still nothing.

The game never crashed but i thought that copper was about as common as iron, but with different spawn values and zone.

Forge version: 14.23.4.2705
Minecraft version:1.12.2
jei version:4.10.0.200
jer version:0.8.7.41
IE version:0.12-84

Pastebin of debug crash: https://pastebin.com/JPPPHm6b

**Comment by BluSunrize** [comment]
Show me the config file that ATM3 ships for IE.

**Comment by Ampmasterful** [comment]
i thought of downloading a new version (standalone form cuse) but not about the config that ATM 3 provides

Pastebin link: https://pastebin.com/jdpknsZv
 thanks for your time.

**Comment by Ampmasterful** [comment]
wait, looking through these config files, the vein size is set to 0, would that be the issue i assume? if so then what is the default value.

Thanks again

**Comment by PrincessRTFM** [comment]
Yes, that's it. If the vein size is set to zero, none of it will spawn. Either the modpack is trying to use a different mod's copper (should be fine, thanks to oredicting) or you're supposed to create it somehow (or someone messed up somewhere).

**Comment by Ampmasterful** [comment]
alrighty thank you. do you happen to know the default values for vein size or a place i can get them. i assume forums or wiki

thanks.

**Comment by Ampmasterful** [comment]
Alright, i fixed it. because i hosted the server manually it was easy to fix and it was all to the help of you guys. thank you so much, im gonna go add my mods back (we arent using all of ATM 3 but we have around 40, for optimization purposes and for the sake of our sanity, only having revisited minecraft recently and never really played mods.)

Thanks again.

**Comment by PrincessRTFM** [comment]
Sorry, somewhat belated response, but the most reliable way to get the original vein sizes is to delete (or, more advisably, move/rename) the configs and let the server regenerate them. Personally, I advise copying all config files before making any changes from the mod's defaults. As for the second bit, be careful when editing a modpack because things like this can happen where suddenly the one thing that was enabled is removed and there's no way to get the equivalents, and because any custom crafting recipes (like from Crafttweaker) may be broken as a result.
