### ISSUE TITLE
Randomization not random in excavator.

### ISSUE THREAD

**Issue by Steelsoul30** [BluSunrize/ImmersiveEngineering#317]
Please note that using the random seed in some manner doesn't ensure randomization.
Lets call (chunkX^2+chunkZ^2) = y for simplicity
Now notice that for all y that are divisible by 8, meaning binary ...xxxxx1000
whichever random number you add to it and then XOR by the same number, you still get a number divisible by 8.
Example: seed is .....1101
seed+y = .xxxx0101 (dont care about higher bits)
answer XOR seed = ...xxxx1000

This means that the player can calculate chunkX^2+chunkZ^2 (even easier using F3) and know that if he is in a chunk divisible by 8, no matter which server on which world, he will find minerals in that chunk.
The seed doesn't come into play.
For example, the following chunks will always have veins: {90,130} {94,130} {98,130} and so on and also their symmetric counterparts.
To get better randomized results of both veins and MineralMix use any not dependent combination of functions. (for example, just a XOR).
While doing that keep in mind that you'd like all servers to have more or less a uniform distribution of veins and types regardless of the seed. but not the same location on every server. (Types of veins aren't uniformly distributed by config weights at the moment because of the dependency of the seed on itself)

P.S. Awesome exciting mod! Goodluck

**Comment by BluSunrize** [comment]
Doesn't really impact the game though, does it? Even Random.nextInt() is never truely random. And honestly? I never bothered to calculate that stuff. I just wrote down numbers from the top of my head and hoped that they would be random enough. The reason I don't use Java's Random.class is because that would mean it changes every time info on the chunk is requested, in turn meaning that the mineral would change with every operation of the drill or excavator. I would have to cache it after the first time, and I didn't want to =P

**Comment by Kubuxu** [comment]
I noticed non-uniform distribution in my part of s world. Every two chunk stripes contains about 5 times more deposits than other (we were scanning stripes of length about 60).

Solution would be to use 2D Simplex Noise, which is implemented in MC already.
It is unique type of noise that for give seed variable and coordinates returns values. It is unique as average feature distance is constant.

IE's ore generations could be implemented on only one instance of such noise.

Let's say that simplex returns values in range 0-1 ( I don't remember implementation details of MC's simplex).
Values from `0` to `1 - perChance` yield no ore.
Values from `1 - perChance` to `1` return ores according to weighed ore distribution.
By controlling feature size you can decide if ores should be grouped and so on.

As you said Random is not what you are looking for. You were looking for seeded 2D noise.

**Comment by Kubuxu** [comment]
It should have been `oerChance`.

I can't change that as I am on a phone.

**Comment by BluSunrize** [comment]
Problem is, there is no real "custering" to the ores, since it's one vein per chunk and then should have some empty space again. I don't want a group of 5 chunks connected to eachother to all have the same ore, which is what that noise gen sounds like. Unless I get severely bored of it or someone talks me into changing it, I'll keep to the current system and just accept the fact that it might be predictable.

**Comment by Kubuxu** [comment]
It is possible to make simplex work like that. You have to just play with parameters.

**Comment by Steelsoul30** [comment]
I am sorry you didnt understand the meaning of what I wrote.
I never suggested to use rand.nextint(). I know that you need to maintain the same ore map for every server restart. You can do it and still maintain pseudo-randomness. As it stands, the core sample drill is "useless" as you know that all the following chunks have a vein. {(+-)4n,(+-)4n for all n=0,1,2,...} and {2+(+-)4n,2+(+-)4n for all n=0,1,2,...}

**Comment by Steelsoul30** [comment]
Despite everything you wrote before closing this issue, you went and changed the system in the new version. I am glad to see you took the comments to heart. I guess "someone talked you into changing it". Too bad that in the current implementation you get the very thing you didn't want - a chance of same type ore clustering... but I am sure you'll work that out to your liking.

**Comment by BluSunrize** [comment]
In fact, it was myself that talked himself into it. I used the excavator on ForgeCraft and got annoyed that I got a guaranteed vein every 4 chunks. xD
