### ISSUE TITLE
In case of disk full condition, ImmersiveEngineering destroys it's files

### ISSUE THREAD

**Issue by bothie** [BluSunrize/ImmersiveEngineering#3194]
In case of disk full condition, ImmersiveEngineering destroys it's files

Current world (after attempt to reload):
```
$ ls -l data/ImmersiveEngineering-SaveData.dat
-rw-r--r-- 1 minecraft users       0  2. Sep 16:47 data/ImmersiveEngineering-SaveData.dat
```

Last backup:

```
$ ls -l data/ImmersiveEngineering-SaveData.dat
-rw-r--r-- 1 root root     624  2. Sep 14:02 data/ImmersiveEngineering-SaveData.dat
```

**Comment by malte0811** [comment]
We don't do any direct file operations. The file in question is created using `WorldSavedData`, which is part of vanilla Minecraft. If you wanted to you could probably report this to Mojang (after finding some issue caused by this in vanilla), but I doubt they'd do anything about it. They'd probably say any issues caused by a full disk are your fault for letting the disk fill up.
