### ISSUE TITLE
Unable to attach wire to redstone connectors after reloading game

### ISSUE THREAD

**Issue by calloatti** [BluSunrize/ImmersiveEngineering#3204]
### Description of the issue:

Create a new world. 

Place some redstone connectors and connect them with redstone wire. Exit world, reload world.

![2018-09-09_12 07 09](https://user-images.githubusercontent.com/12817862/45265968-1e9c8380-b42a-11e8-9f54-c23f53e61ee3.png)

Place a new redstone connector, try to connect new connector to old connector with redstone wire.

![2018-09-09_12 07 35](https://user-images.githubusercontent.com/12817862/45265975-396ef800-b42a-11e8-81c1-19390c78a851.png)

"You cannot attach this wire here" message displayed and wire does not connect.

![2018-09-09_12 07 51](https://user-images.githubusercontent.com/12817862/45265983-47bd1400-b42a-11e8-9ad4-305fd825fc90.png)

### Versions & Modlist

https://paste.ee/p/aszoL

Same error as #3060

**Comment by malte0811** [comment]
I can't reproduce this with my standard IE testing instance. Is the modpack you use available somewhere (aside from the updated IE version)? If it isn't (or if you want to) it would be great if you could do a "binary search" on your modlist to find which mod is causing this (remove half of your mods, see whether it still happens. If yes, repeat on this half of your mods, otherwise test that it happens with the other half and continue with that).

**Comment by calloatti** [comment]
I will try the find what is causing the problem.

**Comment by calloatti** [comment]
I can reproduce the problem testing in a new instance with  just:

Forge 14.23.4.2750
ImmersiveEngineering-0.12-86-457
immersivetech-1.12-1.3.10

So I guess the problem is Immersive Tech.

**Comment by calloatti** [comment]
Related:

https://github.com/FerroO2000/Immersive-Tech/issues/67

**Comment by malte0811** [comment]
https://github.com/FerroO2000/Immersive-Tech/issues/74#issuecomment-419811811
