### ISSUE TITLE
Suggestion: Generate excavator veins based on a heatmap, making some areas rich in certain minerals

### ISSUE THREAD

**Issue by TheDeviantCrafter** [BluSunrize/ImmersiveEngineering#3220]
Right now, each chunk gets minerals on what appears to be an entirely random basis. You may find tens of thousands of copper ore in one chunk, and nothing but rock in the one next to it. This isn't how real life works, and to be honest, I think it could be more fun.

I'd like to see the excavator mimic real life veins using a heat map. In most areas, ores would be fairly uncommon, with occasional small and medium sized veins. Every hundred chunks or so, you would find an area that's rich in one particular mineral.

This area would cover a circle between 5 and 25 chunks in diameter. Any excavators placed in this area have a drastically increased chance of finding veins of that mineral, and veins tend to be larger.

**Why I think this would be more fun:**

- You could put more thought into prospecting an area. If you find an unusually rich area, you could check nearby chunks to see if you found a rich area.

- Finding a sufficiently large area would feel like hitting an actual gold mine. Tracking down and scouting a potential rich area would be much more rewarding than the current system.

- You would be encouraged to set up dig sites with several excavators. This is a mod that likes to encourage large factories and other projects. This would be a great reason to start one.

- By encouraging the player to set up several mining outposts for different minerals, they would also want to set up a transportation system to move ores to their main base. This would be a great reason to use Immersive Railroading.

- Setting up several mining outposts is a major project. It would add a lot of content for players to enjoy, increasing the amount of playtime a normal player can get out of the mod, all without too much effort on the part of the developer.

- If Immersive Petrolium uses the same method, players could build actual oil fields.

**Comment by willvette** [comment]
Another plus would be for multiplayer servers, forcing players to trade and export in bulk for what they lack. for example: player A is atop a Rich Iron Deposit and Player B, who's about 1000m away, is atop a Rich Coal deposit, both are needed for en'mass Steel production thus trading is a must.  

Personally though I'd like to see this as more of an option, keep what it is now as default but allow this as a alternate config option for modpacks and servers.

Yet another option would be to make the perlin noise generator for the deposits configurable.  That way one can make a heat map like distribution how ever they see fit.  Maybe combined with a in-game admin command that'll show the deposits as a floating ores near the top of the map on a per chunk bases.

**Comment by BluSunrize** [comment]
Tbf, the system is no longer fully random (like it used to be), it now avoids generating duplicate veins within a certain radius.

One of the things to put to consideration is that by default, IE's ore veins output a very large amount of ore. Usually one vein of copper is enough to sustain your average player base for a long time. Same for any other material really. While "trading" is a possibility on MP servers, I would think the majority of users plays singleplayer, or in server play, plays on their own, without an active trading element.

Additionally, making a large area the same mineral would require players venturing *even further* to find what they are looking for because suddenly the amount of uninteresting veins has greatly increased. 

Now, one of the features recently implemented was that cartographer villagers sell maps to certain veins. I want to see if I can, in line with that, increase the amount of hints/leads/directions a player gets to find the ores they're looking for. Still in design on how to expand that.

Lastly, and quite importantly, a word on the code-based approach:
IE currently only generates an ore vein when it is needed. The first time someone uses an excavator or sample drill in a chunk, that is when the mineral for the chunk is set. Doing it this way results in less data that has to be saved with the world (rather than having extra data assigned to every chunk during its generation); which is done to keep save file size lower than it'd otherwise be.
If I were to build "heatmaps" or the likes (mind you, I'd need to figure out how to do that first too. Never worked with noise generators and the likes), that would mean saving a *lot* more data than currently necessary, and I'd prefer to avoid that if possible.

**Comment by willvette** [comment]
@BluSunrize I see, the system in use is generated on the spot.  But a hint system might improve the chances of finding a desired vein.  Two ideas come to mind: 
Surveyors Kit, that can scan multiple chunks around the player and give a approximate location of ore chunks but not telling what they are.  However there is a margin of error and the kit may see a ghost vein or overlook a hidden vein.
Geologist Villager, who sells geological survey maps to a player showing veins and their approximate location, similar to the treasure map mechanic.

**Comment by BluSunrize** [comment]
Closing this, given that mineral veins were completely reimplemented in the last release.
