### ISSUE TITLE
LV,MV,HV wires randomly vanish when connecting new wires.

### ISSUE THREAD

**Issue by calloatti** [BluSunrize/ImmersiveEngineering#3221]
### Description of the issue:

LV,MV,HV wires randomly vanish when connecting new wires.

https://youtu.be/fl_KTXgAzA8

### Crashlog:

https://paste.ee/p/mKEuF

### Versions & Modlist

https://paste.ee/p/GQltP

**Comment by malte0811** [comment]
Sorry for the delay, I was busy with other things.
Is there any chance this is caused by the wires burning out/overloading? There's currently a bug where the particles for that don't show (at least not where they are supposed to be). It looks very much like that, the wires only vanish when the complete connection from the cap bank to whatever is at the other end exists. This shouldn't happen with the default IE configs, but if you/the modpack creator changed them this could easily happen. Could you upload your IE config?

**Comment by calloatti** [comment]
The config used was not the default, the limits for wires and connectors had been raised. Will try to find config and post it.
