### ISSUE TITLE
Performance issue. Belljar. 1.12.2

### ISSUE THREAD

**Issue by Mr-Krab** [BluSunrize/ImmersiveEngineering#3228]
-    SpongeAPI: 7.1.0-ff990df
-    SpongeForge: 1.12.2-2705-7.1.0-BETA-3448
-    Minecraft Forge: 14.23.4.2747

- Plugins (27): Minecraft, Minecraft Coder Pack, SpongeAPI, SpongeForge,  FastAsyncWorldEdit, BeanCore, CatClearLag, CommandSync, EconomyLite, GriefPrevention, Holograms, HuskyCrates, HuskyUI, LuckPerms, Nucleus, PlaceholderAPI, ProjectCore, QuestItemHelper, SkyClaims, StackBan, UltimateChat, UniversalMarket, VirtualChest, VirtualTool, Wasted, WorldEdit, spark

- Mods (51): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, AI Improvements, Auto Crafter, BiblioCraft, CoFH Core, CoFH World, CodeChicken Lib, Console Filter, Construct's Armory, CraftTweaker JEI Support, CraftTweaker2, CreativeCore, CreativeCoreDummy, CustomNPCs, Dungeon Mods, Ex Nihilo Creatio, Fishing Net Mod, Hammer Core, HoloInventory, Immersive Engineering, Immersive Tech, InstantUnify, Iron Chest, ItemPhysic, Just Enough Items, LagGoggles, MTLib, Mantle, McJtyLib, Mekanism, Mod Tweaker, MrCrayfish's Furniture Mod, Parachronology, Quick Leaf Decay, Redstone Arsenal, Redstone Flux, Solar Flux Reborn, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Tinkers' Construct, Tree Chopper, UniDict, VanillaFix, WanionLib

All the necessary information you can see in the timings and profiler.

https://timings.aikar.co/?id=21a3c7a9d8834919839b7b6509749ff5
https://sparkprofiler.github.io/?HV14wCjfJC

**Comment by malte0811** [comment]
This is most likely not caused by IE. If you look in the profiler data you'll see that 72.25% of the server time is spent on updating the cloches (called belljars in code). However when you look a bit deeper you'll see that most of that time (70.83% of the total server time) is spent on inserting the output into thermal dynamics itemducts. Most of this is copying item stacks, which takes a very variable amount of time (more with sponge than without it).
