### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by Radical-One** [BluSunrize/ImmersiveEngineering#3239]
### Items
As you know, there are some items such as the revolver, railgun and chemical thrower that make some feel that there should also be other ranged weapons, e.g. pistol, machine gun etc. There's also the shaders which you can use to decorate the weapons, and I feel there should be and ultra-rare one that players can customise to their desire.

### Blocks
One common issue I find and a lot of other people probably find is that some block models don't load and instead show you the pink and black checkerboard block. Could you please patch this soon for future update as this mod is central to one of my projects? Also found is that the conveyer belt sometimes doesn't allow you to place on a certain block, making it hard to get things working.

### Multi-Block Structures
(The one I hate the most of all) I just recently found out that a lot of multi-block structures have changed in one of the recent updates, making it hard to find a correct tutorial as the FTB wiki is outdated. Could you please keep changes to multi-block structures minimal if possible? Ever since I updated to a newer version of one of the FTB modpacks, I have literally spent days fixing all the outdated multi-block structures (e.g. the bottling machine).

### Mod Intergration
Some mods (e.g. EnderIO) integrate with others (e.g. Tinker's Construct), adding on new items and tools (e.g. End Longbow etc.). I feel the same should be with Immersive Engineering, adding on new items (e.g. Constantan pickaxe)

However, Immersive Engineering is still a great mod and is a great addon to Minecraft. :1st_place_medal: :+1: :+1: :+1: 

Radical-One

**Comment by BluSunrize** [comment]
Not sure if troll or not, simply due to the terribleness of the attempt. For the sake of entertainment, I'll indulge you a bit and answer by category:

Items:
No. IE doesn't need any more guns. And there is rare shaders. They are fancy and animated. Having users customize their own completely defeats the point and the inspiration for them.

Blocks:
I have had no reports of broken models. Should you encounter such problems, feel free to file a *proper* report for it, with version number, pictures, etc.

Multiblocks:
LOL. They are one of this mods entire points. Multiblocks is what we are about. What makes IE interesting. If you're using the FTB wiki, that's your own fault, they are absolutely terribly maintained. Use IE's manual, that one is actually written by us and has the correct info.

Mod Integrations:
Are already a thing, mate. [This](https://github.com/BluSunrize/ImmersiveEngineering/tree/master/src/main/java/blusunrize/immersiveengineering/common/util/compat) is all the mod integration we add. Among that is for instance, a Constantan material for TCon.


For future issues, I'd recommend checking your sources. IE is still a great mod though, I totally agree.
