### ISSUE TITLE
Caught exception from Immersive Engineering

### ISSUE THREAD

**Issue by Prasodym** [BluSunrize/ImmersiveEngineering#3241]
### Description of the issue:
when update I get a crash gibs a solution?

### Crashlog:
https://pastebin.com/i5HvQpyq

### Versions & Modlist
Modlist can be seen in Crashreport

**Comment by BluSunrize** [comment]
Try remove the file "ImmersiveEngineering-0.12-80-core.jar" from your mods folder and see if that fixes it.

**Comment by wamc2017** [comment]
Try downgrading forge to 14.23.5.2766, in 2767 there were some changes to the PotionHelper, which may be the cause of this issue: https://github.com/MinecraftForge/MinecraftForge/commit/0fb884462394fe604ce19f0b3113be81a4b5d805

**Comment by malte0811** [comment]
Thanks @wamc2017. Looks like they just ignored binary compatibility for people working with a class explicitely made public by forge.

**Comment by malte0811** [comment]
Don't know what I was thinking when I closed this...

**Comment by ProsperCraft** [comment]
Same issue with the now recommended 2768

https://gist.github.com/ProsperCraft/eefa2fd334d07d401e91af572a1be486

**Comment by mindforger** [comment]
>Try downgrading forge to 14.23.5.2766, in 2767 there were some changes to the PotionHelper, which may be the cause of this issue:

**Comment by ProsperCraft** [comment]
Yes, 2766 works, I released TownCraft with that version and will wait on 2768.

**Comment by ubergeek77** [comment]
[From](https://github.com/BluSunrize/ImmersiveEngineering/issues/3241#issuecomment-427113945) @ProsperCraft 
> 
> Same issue with the now recommended 2768
> 
> https://gist.github.com/ProsperCraft/eefa2fd334d07d401e91af572a1be486

I can confirm this issue as well. I couldn't use 2766 though. For the sake of saving time for people who may be reading this and had the same issues as me, the solution at the moment is to use Forge 2760, because:
- Forge 2766 crashes with "java.lang.VerifyError: Operand stack overflow; Exceeded max stack size," interacting poorly with one of my mods (no easy way to tell which one)

- Forge 2765 does the same exact thing

- Forge 2764 crashes with "java.lang.ExceptionInInitializerError" from the mod IronChests

- Forge 2763 once again, as with 2765-2766, "java.lang.VerifyError: Operand stack overflow; Exceeded max stack size"

- Forge 2762 will load, technically "works," but by itself causes ***severe*** performance issues, with or without mods. Even with just Vanilla 1.12.2, no mods, and only Forge 2762 installed, there is very bad stutter while moving, and extremely violent camera shaking while in water. It's basically unusable.

- Forge 2761 has the same performance issues as above, even with no mods

- Forge 2760 doesn't seem to have performance issues, so that must have been a 2760->2761 change. And it works properly with all of my mods too.

I guess until IE gets updated for the latest recommended Forge build (2768), I'll be sticking to 2760 for now. I just hope none of the mods I use gets an update I would want that also ups the Forge requirement before then.

**Comment by Azanor** [comment]
The MixPredicate change breaks Thaumcraft as well. https://github.com/Azanor/thaumcraft-api/issues/48#issuecomment-427256588

**Comment by BluSunrize** [comment]
Feels like Forge kinda dropped the ball on that one >_>

**Comment by TimGoll** [comment]
AT some point I got [this bytecode crash](https://gist.github.com/TimGoll/3d478dae70b7d459b2e5fbfe71a76f28). Maybe this helps fixing the problem!

**Comment by dave75vgnut** [comment]
I have same problem it crashes with latest Forge version but works on 1.12.2-14.23.5.2765 for me

**Comment by T145** [comment]
On this edition of "Forge screws up everything" ...
