### ISSUE TITLE
[Suggestion] Several Ideas

### ISSUE THREAD

**Issue by willvette** [BluSunrize/ImmersiveEngineering#3251]
Lately I’ve been having a lot of Immersive Engineering ideas, thus I’m posting them here as not to cause Spam

**Conveyor Reader** - a Conveyor variant that detects entities (can be W/B listed, mobs are identified by common drops) and produces a red-stone pulse 
**Conveyor Piston** – a Conveyor variant that pushes entities off a conveyor to one side when triggered by red-stone
**Plated Conveyer** – doesn’t actively push entities but allows them to glide with inherited momentum like ice, can also be slopped forming a sliding ramp for speed and direction.

**I, Truss, and Girder Beams** - purely for decoration but may be used in structures: rusty Iron, silvery Aluminum, and darkened Steel Beams that acts like full block fences. They are bolted to solid surfaces and other beams.
**Concrete Beams** - purely for decoration but may be used in structures, concrete that acts like full block fences but is thicker.
**Duct Blocks** - mostly for decoration but may be used in structures, sheet metal is recombined to from this variant of plated metal blocks (think HVAC systems, also compatible with chisel).  Steal Duct Blocks may be combined with Conveyors to make Ducted Conveyors.

**Surveyor’s Kit** - can scan multiple chunks around the player and give an approximate location of ore chunks but not telling what they are. However, there is a moderate margin of error and the kit may see a ghost vein or overlook a hidden vein.
**Seismograph** - can detect small tremors within multiple chunks around itself and give an approximate location of ore chunks but not telling what they are. However, there is a small margin of error and the seismograph may see a ghost vein or overlook a hidden vein.  It is buried (needs stone or dirt in all 6 directions and be above Y64) and it’ll read once a day at noon, the more time that has elapsed the more precise its readings become.  Nearby noise will adversely affect its readings giving a ghost vein.

**Support Ore Veins** – these ore veins are uncommon and are widely spread out but are unneeded for the core of the mod.  Yet they improve some processes or devices in some beneficial way to make locating and excavating them desirable: 
- _Potash_ can be refined into phosphate fertilizer for garden cloches or used as an ingredient in concrete (replaces clay/slag but makes 6 per crafting).  
- _Kaolinite_ can be made into Porcelain and used as a replacement for insulating glass along with other decorative uses, it can be dyed too.  
- _Tungsten_ can be used to improve the steel drill head, ‘wired’ for double vacuum tubes, arc furnace electrodes, and AP Cartridges.
- _Asbestos_ refined into fibers and can be used in place of hemp fibers and made into fire-proof insulation (tiny chance for indefinite negative effect while held [disappears w/ death]).
- _Silt_ outputs lots O’ clay 50%, plenty of sand 30% and some gravel 20%, soft material so the excavator works twice as fast.
- _Lime_ outputs 50% Limestone, 30% Lime, and 20% bone meal.

**Lime** – limestone can be crushed into lime, mixed with water and sand makes mortar or crafted with iron grit to speed up the steel making process (it’s a flux).  1 bucket of mortar crafted with 8 bricks makes 3 brick blocks.

**Fuel Generator** – this has been suggested before but a generator that runs on Ethanol (or Gasoline from I.P.) would make a nice stepping stone between LV kinetic and HV diesel generators.  Like the Refinery to Diesel generator ratio; one fermenter equals enough Ethanol for two Fuel Generators, one to keep the system running and another for player usage.
**Extruder** – this multi-block structure will take in up to two fluids and an optional item and cast them together.  If feed liquid concrete, it’ll produce concrete blocks.  But if steel bars are added, it’ll produce reinforced concrete with higher blast resistance.  Lava and water will produce stone and TC molten metal become ingot/blocks in bulk. 

**Phased Voltage** – Phased High Voltages is only useable via a multiblock transformer structure, PV relays (3 HV relays and two additional insulating glass), and PV wire coil (HV wire crafted with Steel wire for reinforcement).  The transformer structure converts up to 16,384 rf/t (via 4 HV ports) in one direction (set by engineer’s hammer) and outputs 3 Phased Voltage connecters (the connecters appear with the multiblock structure; thus, the PV lines can’t be used for anything else).  Each wire is an independent phase, combining two or three phased lines into a single relay will cause it to explode, touching a live wire in anyway is potentially lethal, and all three must be used as power is evenly split among all three.  The benefits of such a system is transmission distance loss is reduced to 1/3 that of HV wires thus tripling the possible distance and there isn’t any upper limit to the maximum RF that can be transferred (like the Cryo-Stabilized Fluxduct).

**Comment by BluSunrize** [comment]
Ohhh, big suggestion post, and not completely nonsensical and unfitting either!
I'll go through in order then:

**Conveyor Reader** - The strip curtain does mostly this and works with any kind of conveyor (or any doorway, hole, water channel, etc.) It emits a redstone signal on an entity passing. Admittedly, can't be whitelisted, but an effect like that could be achieved for items with an item router. Just route the item you want to detect off to the side, then feed it back in

**Conveyor Piston** - yeah seems kinda neat. If anythign though, I'd want to make a vanilla piston somehow do this and integrate with a conveyor. I'll take a look in that direction some time.

**Plated Conveyer** - is that a conveyor at that point? Isn't it just a metal plate? =P Unfortunately Minecraft doesn't really support "slopes" in matters of momentum and colision boxes which makes the second part of this very hard (and unlikely) to be realized. 

**I, Truss, and Girder Beams** - Ehhhh. I'm bad at making actually decorative stuff. Plus, I recon you could achieve this easily with chisels & bits and an IE steel block.

**Concrete Beams** - see above, though this one is at least easier to model and texture

**Duct Blocks** - Duct conveyors is what framed conveyors are, since you can disguise them with sheetmetal. Beyond that, this'd just be sheetmetal with a hole in the middle :V

**Surveyor’s Kit & Seismograph** - I currently don't have plans for items that make vein finding easier, I'd rather focus on the use of NPCs for that.

**Support Ore Veins**
- Potash: Maybe, but a "fertilizer" vein is usually just a disappointment to most players (remember Apatite from Forestry and how silly large their veins were?)
- Porcelain: maaaybe for decoration, but we already have terracotta in that area. HV insulation will remain using insulated glass.
- Tungsten: While neat (and already supported as a material for AP ammo) I don't intend to add more metals to this mod.
- Asbestos: I don't think fireproofing is a necessary gameplay element, since 90% of materials in this game are already fireproof. Plus, a "cancer"-debuff seems in very poor taste.
- Silt: That's a good one. Clay tends to be a rare comodity when playing with IE, I've been wanting to add more procurement for that one. Wouldn't be able to affect the excavators speed however without rewriting the whole mineral system (again!) or hardcoding it on the excavator itself, so the speed thing will probably not be included
- Lime: Limestone is a neat decoration material, I may add this vein as a compat for mods that add limestone themselves (pretty sure Chisel has it?), because IE doesn't have the necessity to have this material in itself. Not planning for a steel-accelerator, simply due to the fact that it'd require a rewrite of blast furnace mechanics.

**Fuel Generator** - adding what is effectively a smaller diesel gen feels a bit meh towards what is one of IE's first and really cool machines. Plus players would just chain those if they were cheaper rather than building the big one. Mind you it'd still rely on a squuezer, fermenter and refinery, which could eat up a lot of its produced power.

**Extruder** - considered it previously (although then it would have had the role of what is now the metal press). Consideration A is modeling an extruder; It'd look very blocky and ugly (looking at you, Assembler). Consideration B is that it'd be far more thematic if IE worked with molten metals, but it doesn't. As such most of its usecase would be making concrete, which can already be made quite efficiently in the Assembler.

**Phased Voltage** - No. IE will never add a category beyond HV because it doesn't need it.

**Comment by willvette** [comment]
On iPhone, I’ll make a full response later:
 I’ve been thinking about the problem around my fuel generator suggestion, it occurred to me that it is like a gas engine, needing maintenance every now an then.  Add the cost of needing 8 spark plugs that’ll burn out at arbitrary times.  Reducing energy output by 1/8th but it still consumes fuel at the same rate.  Plugs can only be replaced while the engine is off and manually by a player, with 4 on either side of the engine.
Players like set and forget energy sources, but by making the fuel generator need intervention to maximize output and efficiency.  They’ll want to move on to the next source as fast as possible.

**Comment by BluSunrize** [comment]
Diesel doesn't use sparkplugs :`D

**Comment by willvette** [comment]
I guess you overlooked the part about the fuel generator’s fuel; it runs on ethanol (or gasoline from I.P.) not diesel, lower tier fuel for a lower tier generator.  Alcohol cannot ignite by pressure alone thus needs spark plugs.

**Comment by PrincessRTFM** [comment]
For the gas gen, what if instead of outputting that much power, it only produces enough to run its own production machines and a trickle (lv/mv) for running other things? Make it a little cheaper but also less effective/efficient, so that it's better to make one diesel gen than half a dozen or more gas ones?

For the silt vein, the excavator would still have to break through the ground in its way to _get_ the silt, so no speed boost sounds good to me, personally.

Tungsten/limestone: I know chisel had limestone in 1.7.10 and I imagine they still do, so that'd be cool. But why not do the same for tungsten? If some _other_ mod adds it, support a vein for it, otherwise there's no effect.

**Comment by willvette** [comment]
**Conveyor Reader** – I didn’t think of that for items but how would I go about sorting mobs?
**I, Truss, and Girder Beams** / **Concrete Beams** – I’m bad at chisel & bits ☹ and I’m sure I’m not the only one, thus I suggested it for that convenience
**Duct Blocks** – simply an alternate texture for the sheet metal block, no big deal
**Surveyor’s Kit** & **Seismograph** – the concept for these was that it would cost something besides energy, Surveyor’s Kit accuracy and Seismograph time, to locate desirable veins.  But alas you want to go the NPC route, fair enough.
**Support Ore Veins** – the main idea of the support veins is that they aren’t required to complete the mod.  But rather help the player along if they happen to find one of the veins or make it a goal in upon itself to tap all vein types.  I ended up thinking of this after commenting in the heat map veins suggestion, an unrequired set of ores that would be wanted for their multiple uses.
**Lime** – the original idea was to increase brick block yield via mortar, but that is now moot due to the silt vein increasing clay availability.  The steel flux was shoehorned in later, after deciding that each new ore needed at least two uses.
**Fuel Generator** – IT RUNS ON ETHANOL!  Ethanol is made from the fermenter, and pure alcohol needs a spark to ignite.  Sparkplugs creates a headache when the generator scales up in number, costing resources to replace each failing plug.  Plug replacement cannot be automated in anyway posable, as it is inserted on either side (no gui), the player must pull out each plug looking for the one(s) that failed. The only external indicator of a failed plug is a drop of energy output of 1/8th per failed plug.  
**Phased Voltage** – awe, ho well at least I tried singling out the purpose to pull it away from just a higher tier suggestion.

**Comment by Silfryi** [comment]
While it is true that right now I would not use a fertilizer vein, I've been thinking and tinkering with the configs to make the cloches slower by default (currently 8x), but same speed as normal with fertilizer with fertilizer. With this, I think a fertilizer vein would be much more useful, plus it makes the cloches less useful when spammed without fertilizer. PHV sounds cool, but dunno if it's the way to implement less loss, as it is pretty close to a new power transfer tier.

**Comment by willvette** [comment]
PHV came about based upon a set of images of a player making a High Voltage Transfer Station within modded minecraft.  While the default max transfer limit of HV wires is 32,768 rf/t seams high, some mods surpass that like Extreme Reactors or Draconic Evolution.  PHV was an idea to transfer these energy sources over long distances when in absence of an "Energy Tesseract".  Pulse it would've be semi-grounded in realism, as high voltages are often separated by phase for long distance transmission (why do you think HV power lines have a denominator of 3 wires).
