### ISSUE TITLE
IE 0.12-86 Crashing MC And missing items

### ISSUE THREAD

**Issue by JBlaNkB17** [BluSunrize/ImmersiveEngineering#3257]
I'm having a problem with the mod, many items do not appear and what I need to do now is the kinetic dynamo, but it does not appear, and when I enter the "engineer's manual page" in "power, wires and generators / power generation" The game closes. What can it be ?

Print: https://i.imgur.com/X3ikQdN.png
Crashlog after open the "engineer's manual page" in "power, wires and generators / power generation":
https://pastebin.com/EfsZU25x

Forge: 14.23.5.2768

**Comment by wamc2017** [comment]
You're using a very old ctm version from september last year. Update to [0.3.2.18](https://minecraft.curseforge.com/projects/ctm/files/2584026) and the crash should be gone (you may need to update chisel as well...)

**Comment by Ashendale** [comment]
Adding to this, I also got a crash after updating - haven't even been able to get into the game.

https://pastebin.com/TwWjY2V7

**Comment by malte0811** [comment]
Thaumcraft has the same issue IE 85 had with the new Forge builds. It looks like they don't have a build with a fix yet, I'd recommend using IE 85 and the old Forge version for now. I didn't think of this issue when I wrote the fix, otherwise I'd have added code to keep compatibility with the older Forge builds.

**Comment by malte0811** [comment]
I'm going to close this since all issues here seem to have been resolved.
