### ISSUE TITLE
[1.12.2] Cubic Chunks Compatibility

### ISSUE THREAD

**Issue by Adam-R-Kaminski** [BluSunrize/ImmersiveEngineering#3284]
Mods presend while testing: only IE and Cubic Chunks + Cubic World Gen.
Dear Mr. BluSunrize.
I sincerely ask you to add compatibility with Cubic Chunks https://github.com/OpenCubicChunks to Immersive Engineering.
Basically 70% of the mod works with Cubic Chunks and nothing crashes fortunately but:
- As Cubic Chunks is a different chunk system - excavator, sample drills and every other machine which bases on chunk veins, don't work above 256 and below 0. If you could in some way implement additional sections for Cubic Chunks like 256 to 512; 512 to 768 etc. or just assign veins to single cubic chunks whatever is easier for you.
- Any machines including conveyor belts don't auto load chunks - so say we have conveyors that outreach player's render distance and you drop several items on it so those items are spaced like 2 meters one from another. As soon as items will disappear from rendered chunks they are still there but they aren't being transportes further and they get all compressed into one place (so theyre no longer spaced 2 meters one from another). Same rule applies for every machine - for example arc furnace doesn't keep on working when out of render distance.
Those are all issues as for now i will post more as i go on testing.

**Comment by BluSunrize** [comment]
Come on, at least get my username right. It's in the URL.

Regarding issue 1: I hadn't heard of cubic chunks before today, but it sounds like a rather invasive mod, if it changes vanilla chunk layouts. Supporting that would probably require some major changes to IE's current implementation of the Excavator.

Issue 2 is a lot more straight forward: Yeah, IE blocks don't load chunks and that's *good*. Chunkloading is a major performance impact, that's why you do as little of it as possible. That's why there is specific chunkloader mods to do this. Install Weirding Gadget or any other chunkloading mod and use those.

**Comment by Adam-R-Kaminski** [comment]
I just updated malisis core (component of CC, and seems that excavator started working correctly, WITH sample drill working correctly too. BluSunrize do you think you can do something about those conveyor belts? Try talking to Barteks2x (dev of CC) on their GitHub, several other mod developers successfully managed to add compatibility, including such mods like Orbis (new great world editor for MC), Little Tiles, Thut's Elevators, Mekanism and many more, i think i even heard of Thaumcraft and Terrarium.

**Comment by BluSunrize** [comment]
They don't work at all. The whole point of unloaded chunks is that the blocks in there don't tick, otherwise Minecraft would never be able to handle the load.
That's why you use chunkloaders (personal recommendation: Weirding Gadget by AtomicBlom) to keep the few chunks that you want to keep working loaded.

**Comment by malte0811** [comment]
I'm going to close this since the second point isn't an issue and the first point seems to have fixed itself on your end (I also don't see any reason why it shouldn't work, the excavator code completely ignores the Y-level).
