### ISSUE TITLE
(Suggestion/Question) Mineral Deposits

### ISSUE THREAD

**Issue by LazerusKI** [BluSunrize/ImmersiveEngineering#330]
A few things i was wondering about...

1) There are only Metals, but no Crystals
Is there a reason why it cant dig up for example Diamonds or Redstone?
Thats the one thing im missing so far and i hope those vanilla ressources will be added in the future

~~2) Pyrite
The list shows Pyrite as 100% Iron, after reading an article on wikipedia, i read that pyrite is actually Iron and Sulfur in a 1:2 ratio.
Now...a few mods (like Thermal Expansion) add Sulfur as ressource, so wouldnt it make sense to add Pyrite as Ore that can be grinded into 1 Iron and 2 Sulfur when Sulfur is detected as available ressource?
(or simply digging up Iron and Sulfur in 1:2 ratio)~~

3) Galena and Lead
Both of these deposits are nearly identical, Silver and Lead are exact opposites (58:42), so is Galena (50:50) really needed?

~~4) Quarzite
Is it Nether only or does it exist on the overworld too?~~

~~5) Other Ressources (config option)
What about a way to configure mineral deposits? 
For example a way to add a mystic deposit with Thaumcraft Ressources (Shards, Amber etc), 
or adding more ressources to existing deposits, like Rubys, Certus Quartz, BoP Gems etc to a "Crystal Vein" mentioned above.
or simply just stuff like Granite, Marble and those cosmetic blocks.~~

**Comment by Kubuxu** [comment]
1. IDK
2. If you have something that adds Sulphur, Pyrite will yield it.
3. IDK
4. It is also in Overwrold. It will also contain ie. Certus Quartz
5. Look for LodeLoader on Curse.
Sample config here: http://hastebin.com/azegevifas.json

**Comment by LazerusKI** [comment]
Thanks ;)

**Comment by cobra** [comment]
[NEIIntegration](http://www.curse.com/mc-mods/Minecraft/225251-nei-integration) can show (look into the config) and dump the ore dictionary. Some other Mods might also add stuff doing this.

**Comment by BluSunrize** [comment]
prety sure that I am includng Certus. THe reason I didn't do one for Redstone and Diamond is because there are not really any mineral veins to contain them, and I tried to keep it close to realism =P

**Comment by LazerusKI** [comment]
Which deposit has Certus then?

Also atleast Diamonds and Coal have "veins"
Coal:
https://www.youtube.com/watch?v=aT2SNX8irCc
http://icons.wunderground.com/data/wximagenew/n/nanapoo/163-800.jpg
Diamond:
http://www.allaboutgemstones.com/diamond_geology.html
https://en.wikipedia.org/wiki/Kimberlite
"Kimberlite is an igneous rock best known for sometimes containing diamonds."

And well...Redstone...think we havnt found a vein yet

**Comment by BluSunrize** [comment]
Quarzite should contain Cetus Quartz.

**Comment by xenoflot** [comment]
Quartzite does indeed contain Certus Quartz, personally verified.

I'll add my voice in that I'd like to see Coal deposits. Since coal is such a major requirement in IE, and dense coal veins are very much a RL thing, I'm a little surprised that it's not in already. Perhaps diamonds and emeralds could be rare/very rare drops in coal deposits? They're just compressed carbon after all.

As your time and interest permit, I'd also like to request cross-mod support for things like Mekanism's Osmium. If you don't want to go writing those definition files yourself, perhaps just move mineral deposit definitions into the config file so we can customise and add new deposit types.

Thanks again for a great mod!
