### ISSUE TITLE
Crash using Crusher API with low energy costs

### ISSUE THREAD

**Issue by VadersFist0501** [BluSunrize/ImmersiveEngineering#3301]
### Description of the issue:
Crusher recipes with Energy Requirements of 10 (as far as I have found) reliably crash. Reloading my dev build and throwing the crushed item in occasionally works, but any heavy usage of the crusher and then crushing of an item requiring 10 RF will crash. Changing the requirement to something like 10,000 (more in line with the mod itself) fixes the issue entirely. I suspect it has something to do with low energy values, like 10 (and not restricted to the number 10).

### Crashlog:
https://gist.github.com/VadersFist0501/58a05b33c9fb43c0be25cff766fb7779

### Versions & Modlist
[ImmersiveEngineering-0.12-86-469]
[Thaumcraft-1.12.2-6.1.BETA25-api]
*this is a dev build... so I don't know how important this information is

**Comment by malte0811** [comment]
If the crusher would be using less than 1 FE per tick it will cause issues, including this crash. Fixing it would be (IMO) more trouble than it's worth, since the crusher isn't really meant to use tiny amounts of energy. If the energy isn't an integer multiple of the time only `time*floor(energy/time)` FE will be consumed but again, I don't feel like fixing this is worth the time (the difference would probably be in the order of 1% for IE's recipes).

**Comment by VadersFist0501** [comment]
I guess that makes sense, but I thought it would be worth reporting as it did seem to be a rather odd crash. It took me a while to figure out why it was breaking, and after all the testing I did I just wanted to make sure that is was documented.
