### ISSUE TITLE
[1.12.2]The blueprint of Engineer's Workbenck Rendering

### ISSUE THREAD

**Issue by SihenZhang** [BluSunrize/ImmersiveEngineering#3324]
Mod Version: 0.12-87
Forge Version: 14.23.5.2796
Description:
Rendering of blueprint of Engineer's Workbench maybe has something wrong.
![](https://i.imgur.com/LvfJS4I.png)

**Comment by BluSunrize** [comment]
I... don't see the problem, I'm afraid?
Could you please elaborate?

**Comment by SihenZhang** [comment]
So...The blueprint rendering just like this? :thinking:
I'm just like a fool...

**Comment by BluSunrize** [comment]
It's supposed to look like a piece of paper hanging down :V

**Comment by PrincessRTFM** [comment]
It's... kind of only-barely-on now, though. Which looks a bit unrealistic. I mean, a bit of the edges hanging off would look great, leaving all of it on but skewed instead of perfectly straight would be a good look, having half the thing hanging off I could even see, but... how is it supposed to (a) stay on and (2) be usable with so little still on top of the bench? There's, at a rough guesstimate, 20% at most of the thing on the top of the bench.
