### ISSUE TITLE
[Suggestion]Concrete overhaul and sound effects for tools

### ISSUE THREAD

**Issue by Filvandrel** [BluSunrize/ImmersiveEngineering#3341]
Hello!
I really love the mod, and I thought I might add some feedback. :)
First, the concrete system. It is a very cool feature, but the way it is implemented now is kinda lacking compared to IC2's foam system for instance. It would be really cool, if it would be changed by:

1. Increasing the solidyfing time to for instance 30/60 seconds, so it would be more stable instead of creating random sized blobs around.
2. Making it possible to add up to the existing concrete layers, instead of counting is at a full block, when it is not a full block. Like you know, if there are blocks of heights 0/5 size of normal block, 0/3 size of normal block etc. it would be nice if another concret bucket that we pour on it, would fill the remaining block space untill it becomes a full block, instead of adding another layer on top of not full block. It would make it easier to fill large spaces, instead of making a hole, filling it, breaking, and then putting down individual slabs.
3. Adding the ability to paint the solid concrete, so we could have some color options to choose from.

Second, the tool sounds. Is it possible to add idle and active sounds to the drill for instance? Like we had in 1.7.10?

**Comment by BluSunrize** [comment]
Concrete needs a big overhaul, I agree. Unfortunately, fluids are incredibly fiddly in MC and I really just extended that system in an attempt to make the work easy on me.
Having it flow into an "existing" partial concrete block is probably the trickiest part of this, since that requires giving such blocks logic, but I will look what I can do.

As for tool sounds: The Drill never had sounds, nor were any sounds removed from IE. There was nothing in 1.7 that isn't currently in 1.12.
And I would add sound if I had some. =P

**Comment by PrincessRTFM** [comment]
I... okay, on the surface this is only tangentially related, but I was thinking of the knife switch sound, and I suddenly want a sound-only resource pack, specifically for IE, made entirely by Direwolf20.

**Comment by MaverickMartyn** [comment]
An alternate solution to the concrete problem, that might be easier to implement than adding to existing dried blocks, could be the one mentioned here: #2580

**Comment by BluSunrize** [comment]
Concrete was overhauled in 1.18.1-7.0.1-144
