### ISSUE TITLE
[1.12.2] fluid pipe crash server with industrial craft 2 fluid ejector and buildcraft pipes

### ISSUE THREAD

**Issue by MEXAHOTABOP** [BluSunrize/ImmersiveEngineering#3345]
### Description of the issue:
crash when buildcraft pipe transport biomass to fermenter and fermenter with fluid ejector is full and try eject biogas to the pipe what connected to semifluid generator (as i understand)

![](https://cdn.discordapp.com/attachments/222068802546958348/531855435871813645/unknown.png)
where wood block must be pipe

modpack https://yadi.sk/d/7_K3MRvY-exqdA
broken world from sandbox https://cdn.discordapp.com/attachments/222068802546958348/531854385211244545/crash.zip
fixed world from sandbox https://cdn.discordapp.com/attachments/222068802546958348/531855880065646592/New_World.zip

### Crashlog:
https://gist.github.com/MEXAHOTABOP/7a7982c4bc9527bc376cb7c8d0a1ee27 (from server)

### Versions & Modlist
forge-1.12.2-14.23.5.2768
minecraft 1.12.2
mcp 9.42
FML 8.0.99.99
forge 14.23.5.2796
opencomputers|core 1.7.3.146
buildcraftlib 7.99.20
buildcraftcore 7.99.20
buildcraftbuilders 7.99.20
buildcrafttransport 7.99.20
buildcraftsilicon 7.99.20
buildcraftenergy 7.99.20
ic2 2.8.105-ex112
jei 4.13.1.225
forestry 5.8.2.380
buildcraftcompat 7.99.20
buildcraftfactory 7.99.20
buildcraftrobotics 7.99.20
codechickenlib 3.2.2.353
forgemultipartcbe 2.6.0.79
microblockcbe 2.6.0.79
minecraftmultipartcbe 2.6.0.79
trackapi 1.1
mantle 1.12-1.3.3.39
tconstruct 1.12.2-2.11.0.106
immersiveengineering 0.12-88
immersiverailroading 1.4.1
mrtjpcore 2.1.3.35
nei 2.4.2
opencomputers 1.7.3.146
openglasses 2.0.6
projectred-core 4.9.0.86
projectred-compat 1.0
projectred-integration 4.9.0.86
projectred-transmission 4.9.0.86
projectred-fabrication 4.9.0.86
projectred-illumination 4.9.0.86
projectred-expansion 1.0
projectred-relocation 1.0
projectred-transportation 1.0
projectred-exploration 4.9.0.86
tinkersoc 0.6

**Comment by malte0811** [comment]
This is a strange one, and I'm not sure it's fixable/don't know how to fix it without changing how IE pipes work from the player's perspective. What happens is that the pipe reports it can fill the heat generator on the corner twice, once from the front, once from the right (10 mB each). When we actually try to insert the fluid this obviously doesn't work, since both 10 mB were the space remaining in the same tank. The problem is that a block where those are two completely different tanks wouldn't look any different from as far as the API is concerned.
One workaround to fix this specific case would be to allow only one side to be filled at once, but that stops working once we're inserting into either a multiblock tank or other teleporting pipes. I'll probably look at some other mods with teleporting pipes to figure out how they deal with this issue, if they deal with it at all.

**Comment by Antaiir** [comment]
I had the same issue some time ago. I fugured out, that IE pipes don't like it, when 2 different fluids trying to enter the same pipe at the same time.

Try to avoid pipe layouts, where pipes with different fluids can connect to each other. If biomass AND biogas reaching the same pipe, it WILL crash.

regards
