### ISSUE TITLE
[1.12.2] Regular LV wires stop electrocuting after some time

### ISSUE THREAD

**Issue by roman-virgil** [BluSunrize/ImmersiveEngineering#3352]
Uninsulated lv wires stopped electrocuting after some time and a few server restarts. If the wires are removed and replaced they will function normally again.

Full modlist:
alternatingflux
architecturecraft
chickenchunks
chisel
codechickenlib
computercraft
ctm
immersiveengineering
immersivepetroleum
jei
pam'sharvestcraft

![hurt](https://user-images.githubusercontent.com/45502854/51065558-652f0400-15fd-11e9-8a5b-d6acc29109c9.png)

![not_hurt](https://user-images.githubusercontent.com/45502854/51065562-6b24e500-15fd-11e9-87b1-e3e60bc037a8.png)

**Comment by grundyboy34** [comment]
Yeah I'm noticing this bug on my server as well.
All non-insulated wires will electrocute as normal, until a server restart, in which all the ones that were already placed stop causing electrocution. Basically the bug seems to be that wires only electrocute if they were placed after the server/world loaded.
