### ISSUE TITLE
Game Crash while starting

### ISSUE THREAD

**Issue by ProxyPlayerHD** [BluSunrize/ImmersiveEngineering#336]
The game crashes before Forge was done loading.
i don't know what happened but i uploaded the Crash report, i hope it helps.
[Crash report](https://db.tt/GGiOJCFf)
in the Crash report is a list of all Mods i used, maybe it's incompatible with a mod, or I made a mistake.

**Comment by theunkn0wn1** [comment]
Preliminary analysis of crash: Not enough RAM. Can you please allocate more RAM to your MC instance and try again?

**Comment by ProxyPlayerHD** [comment]
i'm sorry but i can't give it More RAM i only have a total of 6GB and i gave the game 4GB. My Computer would start lagging when i give the Game more RAM.

*sigh* maybe i have to wait until i can give my PC more RAM (8GB or so)...

**Comment by theunkn0wn1** [comment]
I can see ~4GB allocated to MC, if your PC only has 6 GB then yeah, don't give java more than 4.

From what i can tell based on the crash log provided, you just don't have enough memory allocated to run that pack of yours. I would suggest removing mods you don't need if you really want to play with IE in the same instance, though that pack does seem small as it is.... 

Sorry mate, memory is the problem here, and I have not seen a memory-leak issue with IE so it is unlikely a bug with IE causing your crash.

**Comment by BluSunrize** [comment]
try adding "-XX:MaxPermSize=256m" to your launch arguments. This looks like an out of PermGen error.

**Comment by ProxyPlayerHD** [comment]
how do i add arguments?
because i just copied **-XX:MaxPermSize=256m** and added it in the version.json file next to **"minecraftArguments":**. and it didn't work. i think i did something wrong...

**Comment by theunkn0wn1** [comment]
Strange, but if that works OK.

I have found through testing that an MC install *with* Fastcraft uses less memory and launches quicker than the same install *without* fastcraft, with over 0.5 GB Difference. but hey, if that works for it works. You can close this ticket as your issue appears to be resolved.

**Comment by BluSunrize** [comment]
Closed then, I guess? ^^
