### ISSUE TITLE
Engineers manual unreadable

### ISSUE THREAD

**Issue by Zero-Enna** [BluSunrize/ImmersiveEngineering#3383]
In 1.7.10 and now in 1.12.2 I can not read  the manual's text which has put me off from attempting to use the Mod. I would really like to fix this but all I can see that helps is setting my GUI to Auto which makes everything to big and hurts my eyes. Is there any way to make the manual GUI set to auto but not my normal GUI? 
![2019-02-11_14 31 42](https://user-images.githubusercontent.com/47540332/52591534-cd922080-2e09-11e9-8792-75315f208a2c.png)

**Comment by Zero-Enna** [comment]
Why does my screenshot look good but in game its so bad 🤦‍♂️

**Comment by malte0811** [comment]
The manual should be readable at any GUI scale. Seeing what happens to the font would be helpful, since you say the screenshot looks okay you could try taking a screenshot "1 or 2 levels higher up": either Ctrl+PrintScreen (or some other general purpose screenshot tool) or, if that doesn't work, literally taking a photo of (the relevant section of) the screen.

**Comment by Zero-Enna** [comment]
I had to use my phone but this is what it looks like for me.
![20190211_163422](https://user-images.githubusercontent.com/47540332/52598405-3930b980-2e1b-11e9-90ac-8334c4015daf.jpg)
