### ISSUE TITLE
Railcraft Support

### ISSUE THREAD

**Issue by Inonedn** [BluSunrize/ImmersiveEngineering#3390]
Could there be an option to either disable contents that railcraft or this mod shares vice versa? via steel, coke ovens

**Comment by BluSunrize** [comment]
Am I understanding this right, you want an option to remove Coke Ovens from IE?

**Comment by TeamSpen210** [comment]
That is my understanding, yes. Plus Crude Blast Furnaces possibly. Though there's not much point in that, both mods have pretty much the same coke-oven functionality and you'll get the same result. Recipes are similar, you'd get either version of the multiblock at the same time. I assume the creosote fluids are interchangeable.

**Comment by PrincessRTFM** [comment]
The multiblock you get depends on which mod you use to make it - use the RC coke bricks, you get an RC coke oven, use IE ones, get the IE oven. The fluids are definitely interchangeable, I've crafted IE things from RC creosote. _Removing_ the structures seems entirely unnecessary to me though. If it's a personal pack, just don't use one of them. If it's not, you can use CraftTweaker to (a) remove the recipes for the one you want blocked, or (b) if it's IE, change the output of the Engineer's Hammer recipe, because Blu has implemented an NBT tag that lets you block creation of specific multiblock structures. The only thing you wouldn't get is the in-game manual saying "you can't make this", but you can set up the modpack to inform users of that.
