### ISSUE TITLE
[Suggestion] Custom Minerals in Immersive Engineering Config

### ISSUE THREAD

**Issue by ConnorMiner** [BluSunrize/ImmersiveEngineering#3402]
When checking Immersive Petroleum's config file, I found that there is a way to add custom fluid reservoirs within it's configuration files. When checking Immersive Engineering's config file for the same with minerals, I came up empty. Now, I know that Minetweaker allows for the addition of custom minerals, but it could be much simpler to edit the config itself to tweak, remove, or add minerals on the fly and check them in game, rather than having to restart the game (if that's even possible).

**Comment by BluSunrize** [comment]
Nope, it's specifically a Minetweaker functionality and I intend to keep it that way.
It would be incredibly messy to do it in the config, it'd be a nightmare on formatting, etc., and it wouldn't allow adding them without restarting the game anyway, because during launch a bunch of things depend on the Excavator loading.

So yeah, it's gonna stay an MT function, sorry ^^
