### ISSUE TITLE
[Suggestion] Tectonic Agitator

### ISSUE THREAD

**Issue by GeoTerra** [BluSunrize/ImmersiveEngineering#3418]
I realize that this is a really niche request but I'd love to see a machine dedicated to "collapsing"/filling in caves below ground (so, its Y-level and down) to help with underground construction (won't run into caves containing mobs) and restricting mob spawns. The area of effect could be the chunk the machine is in plus each chunk immediately around it, resulting in a 3x3 AoE. Optionally, it could destroy any ores in that area.

As for construction of the machine, my initial idea is for a downwards facing piston, a Heavy Engineering Block and something else. Power costs would definitely be high, probably something in the ballpark of 4k RF/t.

I'm open to discussion on this topic should you wish. Thank you for your time and this incredible mod.

**Comment by Blue-Beaker** [comment]
I think it need to be expensive because it will be too powerful.
And how to form it(from up to down): 3*3 HV coil block with a HV capacitor in the center, 5*5 heavy engineering block, 5*5 downwards facing piston, 5*5 pattern created using steel blocks and aluminum blocks
the pattern determines which chunks to be collapsed/filled relative to the chunk of the machine: steel block for collapsing the chunk, aluminum block for not collapsing chunk
Maybe stepping work style: 100k RF for collapsing a 1*1 column of blocks(transparent blocks like chests,torches and wood fences will be destroyed in the process,not dropping items excluding items in containers, which will be popped out to the surface)
And a block called vibration absorber(cheap) which will protect blocks in that column from being collapsed. The machine will still cost power for the protected column but can't collapse that column.

**Comment by cbrintnall** [comment]
It'd also be nice if conveyors could be moved with pistons.

**Comment by Mushguys** [comment]
What happens when you use this device over a dungeon/mineshaft/stronghold?

**Comment by VariableVixen** [comment]
It gets filled in, and maybe any monster spawner is also destroyed in the process? So, y'know, don't do this over a stronghold.

**Comment by TeamSpen210** [comment]
For items in chests, it probably should destroy them. It shouldn't be of any real use in finding resources in the area, just destroying all the air.

**Comment by VariableVixen** [comment]
That too! In fact, maybe it should have a list of blocks, not just air, that will be destroyed (without drops) and turned into stone (or cobblestone?) including spawners and chests. Probably also torches... things that you'd expect a miniature-earthquake-inducer to wreck, basically.

Actually, the replacement blocks could be a mix of stone, gravel, dirt, and maybe even sand, to represent how you're literally shaking the ground until it settles and that's _going_ to roughen up some materials...

**Comment by BluSunrize** [comment]
I have no plans to implement this.
