### ISSUE TITLE
[suggestion] Stone Variant Veins

### ISSUE THREAD

**Issue by willvette** [BluSunrize/ImmersiveEngineering#3437]
An uncommon type of veins that have vast quantiles of stone’s overworld variants; Granite, Diorite, Andesite, and Marble (mod compact).  That can all be tapped with excavator.  Also, tapping a empty location will produce unlimited cobblestone and gravel.

**Comment by mindforger** [comment]
you can configure that yourself using crafttweaker

i removed all veins and replaced them with custom veins without empty buckets but loads of cobble sand and gravel and just an ore block every 5ish shovels

**Comment by TheToric** [comment]
@mindforger  Could I see your config? im having trouble getting mine up and running. It supposed to add entried to the engineers manuals, right?

**Comment by PrincessRTFM** [comment]
Also, I don't think there's (currently) a way to set chunks without veins to produce "cruft" like that, although it'd be a really neat feature to be able to, say, mark a particular vein as "default" so that instead of generating normally, its contents are used in any chunk that doesn't _have_ a vein. Similar to an old (and, AFAIK, never implemented) request to be able to set a default or fallback output for the crusher, so you could have it dump out scrap.

**Comment by mindforger** [comment]
https://pastebin.com/NDzt7h7s

but that is old and may not work in the current version of IE, so some adjustments needed

**Comment by BluSunrize** [comment]
These are a thing now btw. Igneous Rock vein was added for 1.14
