### ISSUE TITLE
[Bug]Bottling machine failed to work after some time of game play

### ISSUE THREAD

**Issue by mzldh** [BluSunrize/ImmersiveEngineering#3477]
### Description of the issue:
Bottling machine has a chance of **consuming liquids yet not turning the input item into the pre-set output item**. This issue kept showing up when I was playing survival mode. At first everything works well but after some time of game play there's a chance that this will happen. 

It is worth noting that this issue will go away for a little while after rebooting the game, but come back after some time in the game.

I know the script isn't wrong because the recipe worked, I suspect it has something to do with the ram and lag build up over time in game play. Also once this issue occurs, the recipe will be broken forever until fixing it by rebooting the game.

I haven't tested the issue with other bottling recopies that came with the mod, but here's the crafttweaker scripts I wrote:
mods.immersiveengineering.BottlingMachine.addRecipe(<machinemod:fuelcan>*1, <machinemod:fuelcan:1000>*1, <liquid:gasoline>*1000);

mods.immersiveengineering.BottlingMachine.addRecipe(<cfm:item_soap>*1, <rustic:tallow>*1, <liquid:oliveoil>*1000);

I've post an issue at the crafttweaker bug report post as well, I'm not sure this issue is on them because this sort of recipe script worked flawlessly in previous IE versions from a modpack I played last year.
 
### Crashlog:
The bug didn't crashed the game, no crashlog was generated. 
### Versions & Modlist
Minecraft: 1.12.2
Forge: 14.23.5.2837
ImmersiveEngineering: 0.12-89
Mod List:
https://pastebin.com/474RqmAQ

**Comment by BluSunrize** [comment]
Can you reproduce this with a recipes from base IE?

**Comment by Sigma-One** [comment]
Can not confirm with IE's own recipes, but I'm experiencing the same issue, but I can only complete one crafting operation before the thing breaks.

**Comment by TimTinkers** [comment]
I'm experiencing the same issue with custom CraftTweaker recipes.

**Comment by GreyWynaught** [comment]
I am having the same problem on the same build of the mod, but I am on forge 14.23.5.2823. The bug happens anytime I try to fill a second glass bottle after filling a first one. Both the second glass bottle and its fluid is destroyed. Afterwards I have to reload the world or any more bottles will not be filled and fluid will be lost. This only happens when attempting to fill a bottle with a fluid. When fluid is put into Jerrycan or bucket, no fluid or container is lost.

As a side note the only shared mods between OP and me are Gravestone, Jei, CodeChicken mods, NoMoreRecipeConflicts, and obviously immersive engineering.

**Comment by dynata-hu-robert-szepesi** [comment]
This issue still exists in 0.12-98 version released on Jun 6, 2020 for MC1.12

**Comment by BluSunrize** [comment]
Yeah and we ceased all support for 1.12 years ago.
