### ISSUE TITLE
Placing Garden Cloche chrashes the game in RFTools void dimension

### ISSUE THREAD

**Issue by BjornPijnacker** [BluSunrize/ImmersiveEngineering#3487]
Crash log https://pastebin.com/4iz6U5ng
Mod list https://pastebin.com/kFkZiXnq

**Comment by BluSunrize** [comment]
Update Java, your version is heavily outdated.
Then try again and see if you can reproduce it.

**Comment by BjornPijnacker** [comment]
I cannot update Java as this is the version installed by the game itself.
Installing Java on my system will make the game not run

**Comment by BluSunrize** [comment]
That's....not how that should work at all.
Please look at some tutorials regarding using more recent Java versions with Minecraft. The one shipped with the launcher is **4 years old**
It's older than the first ever release of Immersive Engineering. Go update.

**Comment by mindforger** [comment]
@BluSunrize there is currently a bit of confusion around java because oracle put a login-wall around all older JDK/JRE downloads where you are required to enter details as if you were working at an company (i used oracles HQ as a reference XD)

you can get to the point whre you can actually click the download just like normally but the moment you hit the download button oracle requires you to login

i did not test yet all those alternative JDK8 downloads like the one that is provided without any login or registration requirement by amazon (called coretto if i remmeber correct, exact same thing but no official oracle support)

>Installing Java on my system will make the game not run

can you elaborate that "not run" part a bit more, so you can be helped a bit more specific :) 

because yes, this old version will make your modded experience miseable at some point, IE was just happen to be the first of many oddities you may encounter with this old JRE/JDK

**Comment by BluSunrize** [comment]
@mindforger 
https://java.com/de/download/

This works perfectly fine and allows me to download the latest version of Java 8, which is what I'm recommending. I'm not recommending to download *old* releases, but current ones. And 1.8_52 is from 2015.

**Comment by mindforger** [comment]
it was the JDK only then :D .. my fault ... 

it was an optifine thing where youa ctually need the JDK to work around a bug when this came up
