### ISSUE TITLE
[suggestion] set of ideas that could be added to the mod

### ISSUE THREAD

**Issue by bobodoustaud** [BluSunrize/ImmersiveEngineering#3570]
(is it the good place for suggestions?)

1) reduce the sensitivity of the mouse when zooming with the railgun (when you zoom 5x the sensitivity is divided by 5 etc.)

2) increase the speed of the bars coming out of the railgun (because it's way too slow for a sniper rifle)

3) add a "laser weapon" that consumes lot of power, that can overheat and where you need to have the second hand free to use it (it should be quite massive). It is also able to break blocks and damage players (it could also to be able to ignite entities). Players can protect them from the laser by making polished silver plates and combining them with with their armor pieces (like the capacitor backpack, but for every armor pieces) that reflects the laser beam but doesn't protect against the fire effect (but it overheat when you are exposed to the laser too long and it loose all his laser immunity if its happens).

this weapon could also have a block variant and orientable mirrors

4) make sure that the drill and the railgun can be used only if the second hand is free, or add a animation where the player holds the tool with two hands

5) could you also add a minigun or something of that kind that shoots a lot of bullets with low accuracy

6) it could be cool if the reload animation of the revolver were more realistic (with cartidges coming out of the charger, a side opening charger instead of a knick charger, and an animation with the speedloader , bullets physics with bullets falling down (but recoverable, it can be made with a sort of entity who in contact with the ground becomes a recoverable item but does not float like vanilla items)(video for the inspiration : https://www.youtube.com/watch?v=9WasgRxx6r4)

7) a speedloader for the chemical thrower (a fluid bottle) with a cool animation

8) it could be good if you add a sort of big motorbike for travelling around the map (with slope physics?)

**Comment by PrincessRTFM** [comment]
I don't have any other way to vote "cool"/"nah" on your ideas, so...

I'm with you on 1, 2, 4, and 7. I like the animations part of 6, though I'm not a fan of the falloff. I'm not at all with you on 3, which feels like it should practically be a separate mod, and I'm indifferent on 5 and 8.

**Comment by BluSunrize** [comment]
So, number 1 I can look into, but I don't think it's possible to influence mouse speed and acceleration for mods.  
Number 2 is not easily done because fast moving projectiles do not work well in Minecraft.  
Number 3, 5, 6 and 7 all fall into the category of "IE is not a gun mod" and "IE is not a weapon mod". The revolver has already received a hillarious amount of development time for how small of a feature it is. Animations in Minecraft are real fucking hard, and what you see on the revolver is probably some of the best work I have ever done. I can't do anything more complex.  
Number 4 is partially implemented. Two-handed animations are as good as it's gonna get. Actively preventing the use of an item is doable, but also not cool for people who for instance want to use that kill-tracker from Matter Overdrive in their off-hand. So I'd rather not implement a "blockage" when the second hand is in use.  
Number 8 I won't do, vehicle entities suck.

**Comment by bobodoustaud** [comment]
ok

**Comment by BluSunrize** [comment]
Right, I investigated the mouse speed thing, and there are no events in that part of code that I could use to hook it.
I'm closing this, since that the was the last non-discarded point.

**Comment by mindforger** [comment]
Can you force cinematic mode? Is that even still a thing?
