### ISSUE TITLE
[Feature Request] Electrocution when touching wires.

### ISSUE THREAD

**Issue by Sataana** [BluSunrize/ImmersiveEngineering#358]
Would it not be a great idea if there was a config to turn on getting hurt when walking through power lines.
Or when you are touching them with bare hands?

**Comment by rjp2525** [comment]
+1

**Comment by Bambiiable** [comment]
+1

**Comment by theunkn0wn1** [comment]
+1, BluSunrise could do something similar to Forestry bees, applying a status affect within a radius of a given block source. Instead of a radius, check for a player within range of the projected wire path.

IE all ready scans the blocks between two connections for validity, something similar could be used to check if a player is between the two points, thus in contact with the wire.

Damage should be proportional to the voltage, LV is safe while MV is harmful and HV being deadly.
On player damaged by wires, power should be drawn from the network and consumed as player damage. If there is no power in the network, such as an open breaker, the wire would not be 'live' and safe to approach.


By adding Electrocution to IE, it can be used to create, to an extent, realistic and immersive traps that use RF. These same traps could be used in mob farms. 

With electrocution being a hazard, it would add another good reason to have the breakers, and make upgrading an existing IE power network more immersive. Perhaps if a player attempts to wire from a live connector to any other point he would be electrocuted, as he was foolish enough to handle live wires with his bare hands. IE could add special equipment\tools specialized in handling live wires as to mitigate the harm of working around live wiring and add further specialization for players whom are playing in an RP style of server.

**Comment by BluSunrize** [comment]
No.

Because you do not want me to do that to your servers.

**Comment by malte0811** [comment]
(Sorry in advance for the necro-posting. I remembered this when thinking about wire loss, specifically why HV isn't used everywhere IRL)
I think I've found a way to do this that doesn't kill servers. This involves a second patched-in (ASM'd) method call. There is roughly 0.1% difference in the time used by the relevant method (0.8 vs 0.9%) with ~390 chickens.
Code (Proof of concept): malte0811@ee5ee784244a99a326ca5dd514f2c7225840c75b (There is some general net handler cleanup in there as well). The idea is to build a map of all blocks (`BlockPos`'s) containing wires (This would need to be changed to all blocks within some distance of a wire). `Entity#doBlockCollisions` already iterates over all blocks the entity is touching, so it is easy to patch in another call. The runtime (per block touched by an entity) should be mostly constant since it is just a hash map lookup in most cases (when not touching a wire).
@BluSunrize do you want this (as a config option) for IE? If you don't want it I might make it into an addon at some point, along with some other wire/loss system ideas.

**Comment by theunkn0wn1** [comment]
Well thats one way to necro a really old post. But yeah, if it can be implemented without killing the server i am all for it... may have to redesign some of my bases as not to kill me but that just promotes healthy wiring practices
