### ISSUE TITLE
[Suggestion] Conveyors anger

### ISSUE THREAD

**Issue by Gravelll** [BluSunrize/ImmersiveEngineering#3582]
Conveyors, although REALLY COOL (love what you've done :3), have some ugly bits I would like to address. Here are my ideas (with pics):

- Covered conveyors can have ends sealed off, for such examples as turns and the beginning of a line. 
![CONVEYing my idea](https://user-images.githubusercontent.com/56456152/66686736-62c20f00-ec4e-11e9-89fa-3665b8581cdf.png)

- Steel structural arms can connect to covered conveyor elevators to make the corners enclosed in scaffolding. same for chutes.
![elevator idea](https://user-images.githubusercontent.com/56456152/66686493-a5cfb280-ec4d-11e9-9809-596997a97210.png)

- Elevated Conveyors look like they should be able to fit a structural arm underneath them. I bet you can and i'm just dumb, but on the off (maybe decent) chance it isn't possible than it should be. I mean, look at it. 
![Arm and a leg](https://user-images.githubusercontent.com/56456152/66686939-00b5d980-ec4f-11e9-9898-4a872d42eeb1.png)

- Covered Conveyors should be able to work with chutes. Simply have the top side open up as if it were another conveyor. 
![chute to nowhere](https://user-images.githubusercontent.com/56456152/66687356-635ba500-ec50-11e9-82b2-09d51bddfbe8.png)

- Now on to normal conveyors, i know right. You know those little steel guard rails on conveyors. yeah so copy the first suggestion but instead have it with those. 
![it hurts](https://user-images.githubusercontent.com/56456152/66687474-b7668980-ec50-11e9-9e12-2c74714b1dc6.png)

thats about all i wanted to put forward, thank you for reading.

**Comment by BluSunrize** [comment]
I do wish you had numbered these for easy replying, but I'll just do it then!

1) Covered Conveyor Walls  
This would require tracking 4 times as many states on these (closed on one side, closed on the other side, closed on both sides, open); increasing the amount of cached models for them by a factor of 4. I don't want to deal with that.

2) Lift covers  
Unfortunately, the way items are moved by vertical conveyors involves them being sort of "thrown" at the top, to reach the next conveyor. Items in motion are always a bit random, so if one were to cover them there, there is a pretty high chance they'll collide and break the lift.

3) Slopes under Conveyors  
Those are two separate blocks. You can't put two blocks into the same space. That's just not a thing in Minecraft. I could **fake** it, by making the conveyor render a support below it. It willd double the model count, but I can look into that for 1.14

4) Chutes into Covered Conveyors  
Covered conveyors are never open to the top. They never have been, because they are expressly designed to be walked on. You can however use chutes to insert into any of their sides. That should be good enough.

5) Additional Walls
See 1).

**Comment by PrincessRTFM** [comment]
For point 2, you can use Chisel&Bits to just put bits in a plane shape across the four "closed" sides, leaving the other two and the centre open. I've done that myself, actually.

For point 4, does that mean that an item falling through an IE chute onto the top of a covered conveyor will be put onto the conveyor, or did you mean we can hoppers?

**Comment by TeamSpen210** [comment]
Chutes won't insert through the top, but you can rotate them to be diagonal, so they insert through the side.

**Comment by PrincessRTFM** [comment]
Oh, I didn't remember I could do that. Also didn't know they'd insert like that, neat!
