### ISSUE TITLE
[1.12.2] Chemical Thrower causes severe fps lag

### ISSUE THREAD

**Issue by DarkEyeDragon** [BluSunrize/ImmersiveEngineering#3593]
### Description of the issue:
Chemical Thrower causes severe FPS drop when firing ignited liquids (Creosote Oil) with particles set to `All`

![image](https://user-images.githubusercontent.com/6131099/68080036-cd9cdb00-fdf3-11e9-9245-2d1349d61264.png)

With minimal particles:
![image](https://user-images.githubusercontent.com/6131099/68080048-f2914e00-fdf3-11e9-9ae8-59ba51104c56.png)

Note: I get about 100 FPS when im not throwing any liquids out.

This is only for ignited fluids.

### Versions & Modlist
IE version: 0.12-89 (wasnt mentioned in patch notes of 90->92 though)
Modpack: Sevtech Ages (shouldn't be relevant in this case)

**Comment by DarkEyeDragon** [comment]
Maybe using a less detailed flame particle/texture by default might be better here. If i spray around for like a second me and my friends pretty much can't play because of the fps drop and need to wait for the flames to dissapear.

**Comment by malte0811** [comment]
Does this happen with just IE? You seem to have some mod installed that changes fire rendering (even with minimal particles), it could be related to that.

**Comment by DarkEyeDragon** [comment]
Yeah it works fine with just IE. Didn't even consider that there might be a different mod messing with it. Well that solves this issue then.

**Comment by SolStar2** [comment]
I've encountered a similar issue and did some digging.
1. setting particles to low doesn't do anything because
2. the flame "particles" are actually flaming entities.
3. if you have a poorly optimized lighting mod it can cause massive lag if it treats flaming entities as light sources.

solution:
a. try a different lighting mod. ([lucent](https://www.curseforge.com/minecraft/mc-mods/lucent) worked well for me)
or
b. disable flaming entity lights in your lighting mod config file.
or
c. disable your lighting mod.
