### ISSUE TITLE
chem thrower turret projectile TPS crash

### ISSUE THREAD

**Issue by bobodoustaud** [BluSunrize/ImmersiveEngineering#3654]
loading a chunk that contains a chemthrower turret shooting on a snowman creosote (to dump a coke oven) takes very long to calculate (the server crashes if a tick takes more than 1 minute). The chunk was chunkloaded using the weirding gadget mod.

Crash report : https://pastebin.com/p5vzv0WX

Thanks for reading !

**Comment by bobodoustaud** [comment]
the chunk seems to be corrupted because it crashes mcedit when i try to load it.

have someone a solution to remove the erroring etityes or the entire chunk?

**Comment by ace10102** [comment]
move yourself to spawn then run /kill @e[type=immersiveengineering:chemthrowershot]
i just encountered the same issue and i can provide a bit more info on it.
basically a chemthrower turret in a lazy-loaded chunk still functions because it's a tile entity and not an entity, so it finds nearby entities and attempts to shoot at them, but because the chunk isnt loaded to the entity-processing level, all of its projectiles are spawned then immediately unloaded, meaning they never despawn and the target its shooting at never dies, causing the entity count to increase as long as the turret has ammo which eventually causes massive tps issues. in my case the turret managed to generate a whopping 279010 projectile entities. which i was able to find the coords of, kill using the above command, then teleport to the offending turret and surmise the context.

**Comment by bobodoustaud** [comment]
Thanks !
