### ISSUE TITLE
[cosmetic] show metal pouring out of arc furnace

### ISSUE THREAD

**Issue by cobra** [BluSunrize/ImmersiveEngineering#371]
The arc furnace model is rather static and doesn't show what it's currently doing besides the glowing electrodes signalling "hot" and "inactive". I think adding a stream of molten metal pouring into the cauldron would be a nice addition. This would be similar to TConstruct's faucet (minus the update lag inducing casting basin showing the current amount of poured liquid) and the excavator showing the ores in the buckets of its wheel.
I don't know yet how to handle the needed textures/colours. Either a generic texture with a one-fits-all colour like orange with some exceptions (config option?) or some fancy dynamic colour generation (how?! It's not just a texture needing some transformation after all).

**Comment by BluSunrize** [comment]
yeah, I considered that one, and then scratched it at the account of people then also asking for a rendered metal in the bucket.
That again isn't really doable because of the furnaces ability to have a mix of items in the output slot.
I'll take it into consideration, but it's low priority.

**Comment by cobra** [comment]
Right. Well, that's a point for a generic one-fits-all orange-ish colour. Could also be something like orange unless there's a special material present, then use the first special colour. Alternatively round robin the present material colours.

**Comment by BluSunrize** [comment]
cooled down metal isn't all orange though .~.

**Comment by mindforger** [comment]
can't you reuse the registered fluid textures? like the tinkers smeltery?

like, when the smelting process is done, take the liquified version of whatever output has been finished and fake a stream of liquid with it's liquid texture or alternatively a default bright orange as most of liquid anything is normally glowing from red to white over orange

you do not need to show anything inside the container when there is something in the output, as you have multiple output slots. wich would be confusing imho

**Comment by WolfieWaffle** [comment]
I don't really know what arc furnaces are like IRL, but maybe you could add an visible electric arc, instead of pouring metal. It would look really cool, even if the arc of an arc furnace isn't visible in real life. I think it also really needs a sound effect, maybe a deep electric humming, because it seems like it should make some noise.

**Comment by VermillionX** [comment]
Sparks pouring out at the front and near the electrodes while active could be a simple addition with a great deal of effect that doesn't need to change between material types like metals.

**Comment by kane-thornwyrd** [comment]
Having electrodes glowing and emitting sounds and particles accordingly would be amazing ! I'd love to see Immersive Engineering becoming the Botania of Tech/Realistic mods !
![molten iron](http://www.wksu.org/news/images/29715/Furnace-08.jpg)

**Comment by WolfieWaffle** [comment]
I like the sparks idea! It would make it feel really powerful. (Also having configurable smelt times, but that's a different issue :P)

**Comment by BluSunrize** [comment]
No. No configureable smelting times.
Graphical stuff I will look into over the following days.

**Comment by WolfieWaffle** [comment]
OK, that's fine. I was just looking for a reason to use it over the TE induction smelter, because currently it's more expensive and smelts slower. I don't normally like things where one feature is superior in all cases, so you have to chose which machine to use, but if you add the graphical effects, I might just use the arc furnace purely for its awesomeness. Anyways I'm probably derailing the issue, sorry :/. Would sound be included in this, because so far the furnace is silent.

**Comment by BluSunrize** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/01e384ad751770d90f6d391e95fffb27b90efc45
This commit adds sparky particles and molten metal.
Sound is planned, will happen in due time
