### ISSUE TITLE
[1.14.4] Immersive Portals and Better Foliage cause crash while rendering IE blocks

### ISSUE THREAD

**Issue by facetorched** [BluSunrize/ImmersiveEngineering#3855]
When exactly these two mods are installed (with their dependencies) along with IE, the game crashes. It happens when I place down an immersive engineering block or load a chunk that has an engineer's house in a village. It has happened every time I have tried it in single player. Also, removing any one of the three mods fixes the issue.

crash log: https://pastebin.com/3XkmDzAB

Modlist:
forge-1.14.4-28.2.11
ImmersiveEngineering-0.14-95
BetterFoliage-2.5.0-Forge-1.14.4
immersive-portals-0.15(for+mc+1.14+with+forge)
Kottle-1.4.0
MixinBootstrap-1.0.3

**Comment by malte0811** [comment]
This looks like a bug in BetterFoliage to me, they are passing `null` as the model data [here](https://github.com/octarine-noise/BetterFoliage/blob/aa91aed58e3b1fe117c7332c3fa587879e231761/src/main/kotlin/mods/octarinecore/client/render/BlockContext.kt#L69). They should be passing `EmptyModelData.INSTANCE` instead. I'm leaving this open for now since I'm not sure that I fully understand the problem, from my reading of the code it should crash without Immersive Portals as well.

**Comment by facetorched** [comment]
You are actually correct:
[](https://github.com/octarine-noise/BetterFoliage/issues/293#issue-601861833)
My tests were poorly conducted since I forgot to check whether better foliage was successfully loaded. It turns out that better foliage requires MixinBootstrap so when I removed  immersive portals AND MixinBootstrap it appeared that the issue went away. In reality, better foliage was simply not loaded and for some reason didn't notify me of this.
I'm not sure if I am correct but I think this issue should be closed
