### ISSUE TITLE
[1.14.4]crashes when looking at immersive tab in creative

### ISSUE THREAD

**Issue by detecjack** [BluSunrize/ImmersiveEngineering#3877]
Description of the issue:
when you are in creative mode and go to immersive engineering tab and scroll far down the game freezes for few seconds and then crashes immediately   

 Crashlog:
https://pastebin.com/5idVDvzg

 Versions & Modlist
modlist: https://pastebin.com/51wLNNe3
IE:0.14-96
Forge:28.216
(i hope i am doing it right)

**Comment by BluSunrize** [comment]
Can you reproduce that crash without optifine?

**Comment by snitxmhm** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/3857#issuecomment-630734120
Will this problem be solved in the future? It is my previous problem. I really want play the game with shader. Thank you.

**Comment by BluSunrize** [comment]
If Optifine stopped doing bullshit hacks to the render, maybe. But we can't keep going out of our way to fix the things they break. Our code is perfectly valid for an item model and only breaks when OF is installed.
I can't *tell* you why it breaks, because I don't know what exactly Optifine *does* to the render code.

I'd love to fix it, but I can't diagnose it, so I'm just stumbling around in the dark.
