### ISSUE TITLE
Document current transformer comparator behavior in manual

### ISSUE THREAD

**Issue by ghost** [BluSunrize/ImmersiveEngineering#3920]
Current Transformers could be made more useful if they were RF equivalents to Probe Connectors by outputting an analogue redstone signal based on ratio between the max capacity of the attached wire and the RF/t being transmitted.
This would allow Current Transformers to be used for overload protection systems, for example, or some other automation of the power grid.

**Comment by malte0811** [comment]
You can attach a comparator to it to get just that effect. Note that the signal will probably seem quite weak since (in my experience) wires are rarely close to their maximum transfer rate.

This currently is not documented in the manual, I'll keep the issue open (and rename it) to remind me that I need to change that.
