### ISSUE TITLE
[Suggestion] Extractor progress feedback

### ISSUE THREAD

**Issue by xenoflot** [BluSunrize/ImmersiveEngineering#393]
If would be helpful if the extractor was able to provide feedback on its progress.

Possible methods:
* Animation stops when the mineral deposit has been completely mined.
* A right click gives an in-chat report on the health of the mineral deposit (same as the sample drill)
* Indicator lights on the multiblock (not sure if this is possible). Perhaps just a single error light that comes on if it lacks power or the mineral deposit is at zero.

Cheers!

**Comment by cobra** [comment]
\*Excavator
I think the wheel animation should only stop when it's no longer consuming power. Whether or not the excavator should switch off automatically is a game design question.

I'd like to add some possibilities:
* buckets stay empty after exhausting the deposit (instead of showing the ore it's mining)
* redstone output/comparator support. Either digital or analog - outputting 15 when exhausting the deposit could be used for an automatic shutdown mechanism and indicator light.

**Comment by xenoflot** [comment]
In the version I'm running (0.5.4), buckets DO show empty when the deposit is exhausted and the wheel keeps running.

It's reasonable that the wheel should keep spinning while its drawing power. Perhaps it could stop drawing power (and spinning) once the deposit is exhausted.

The right-click to get the deposit status is probably the simplest and most effective.

**Comment by BluSunrize** [comment]
The Excavator shouldn't know what it's digging. I don't want to change this, because it makes the Excavator a bit more of a manual thing to manage. If you don't watch out, you lose power. I actually like that as a balance =P

**Comment by xenoflot** [comment]
hmmm OK. I can appreciate that view. Thanks for the reply!
