### ISSUE TITLE
1.15.2 game crash when open the inventory and invisible strucktures

### ISSUE THREAD

**Issue by Skyboy444** [BluSunrize/ImmersiveEngineering#3934]
The problem is, that there are a lot of blocks wich were invisible, like transformers and relays and connectors and other many Blocks/strucktures!
The other problem is, that when I open the Immersive Engineering Inventory, and scroll down, the game stops and crashes! 
I hope you'll fix that soon, because such a good mod may not have thies problems !

**Comment by BluSunrize** [comment]
Please edit this report to follow the issue template.

**Comment by ItsPapoPlayz** [comment]
I can use other inventories sections but when I click on the immersive engineering section, it says "Saving World" and the game just closes. I'm using the Alpha 1.15.2 Version.

**Comment by mindforger** [comment]
let me cite PART OF the issue template:


### Crashlog:
If your Minecraft instance has crashed, a file will have been generated in the folder `crash-reports` of your minecraft folder. To understand what has happened, we need to know the content of that file. But please don't just put it directly in your report (that makes it hard to read), upload it to a site like [pastebin](http://pastebin.com) or [gist](http://gist.github.com) and put a link in the actuall bug report.

would be nice of you if you could check the other points in the template also :)

**Comment by Zekrom64** [comment]
Had a similar issue with crashing, but in this case when I tried to view some IE item in JEI. This is the info in my case:

[crash-log](https://gist.github.com/Zekrom64/86ba42a1ad0c6be93985895a1752d542)
IE - 0.15-99
Forge - 31.2.9

I'll test removing some mods to see if it is an interaction with another mod.

**Comment by Zekrom64** [comment]
Seems to be a conflict in my case with the preview version of OptiFine for 1.15.2, not sure if that was the case for the original post. The issue also occurred when viewing items in the creative inventory, and seemed to be coming from item rendering code.

**Comment by ItsPapoPlayz** [comment]
Here is mine. https://pastebin.com/Mzpyx8qJ

**Comment by BluSunrize** [comment]
Fixed by this PR #3938

Next version should remedy this. In the meantime, play without Optifine.

**Comment by ItsPapoPlayz** [comment]
Optifine was the problem?

**Comment by connorcodes** [comment]
This is my issue currently! Many items like relays, wire connectors, and transformers failed to generate textures due to the Optifine preview for Minecraft 1.15.2

I have disabled Optifine and now everything appears. 

Unfortunately a very valuable component of Optifine is the ability to set the game to no rain and always day. These two features are almost as important as immersive engineering to me.

I played the game on MacOS 10.15, with 50 other mods installed that seem to have no conflict (besides your wires electrocuting my colonists occasionally)

Please fix guys! :)

Edit: turns out Minecraft has built in commands for these things I mentioned so I’m doing fine without Optifine for now!

**Comment by BluSunrize** [comment]
Lawl.
I saw the email, and was like "none of those things need optifine, I do this in every single of my dev worlds, with two commands"

Glad you figured that out.

Anyway, optifine issues have been fixed for future releases, you just gotta be patient a bit longer.

**Comment by connorcodes** [comment]
Sounds good, thanks for fixing! Good job on the automated turrets by the way, last time I used your mod years ago I didn’t see them so they are new to me. Very useful for defending my colonists from the Minecolony mod.

Quick question though, why do the turrets consume so much constant power? Is there an easy way to leave them always-on without sucking up power from my generator? I have them on creative capacitors right now because I’m still learning how power stuff works in the mod. Like for example, could I use a line of pressure plates that activate the turret for a period of time or something?

**Comment by BluSunrize** [comment]
I don't want to have those discussions in this issue, this is the wrong place for it.
Please take it to the discord, which you'll find linked on the CurseForge page.
