### ISSUE TITLE
[Rebalance] Change recipe for blast bricks

### ISSUE THREAD

**Issue by BluSunrize** [BluSunrize/ImmersiveEngineering#3961]
Currently, acquiring the blast furnace requires going to the Nether and killing blaze. This makes it not only impossible to play IE in a peaceful world, it's also just a major pain in the ass.
We need a better recipe for blast bricks.

Additionally, it might be interesting to have a recipe that *creates* blazepowder? Maybe something with sulfur. Unsure about that part.

This post is open to ideas, discuss below!

**Comment by Vaelzan** [comment]
The first thing that comes to mind is to keep the outer ring the same but replace the blaze powder with a piece of IE concrete - my reasoning being that the ingredients in IE concrete are somewhat similar (as close as one could get without introducing new items) to IRL mortar that would be used to hold the bricks together, forming a block.

**Comment by ghost** [comment]
A recipe for blaze powder would be cool to go with other mods that use it. It could be a combination of sulfur with metal grits (maybe iron) and quartz.
Alternatively, a new recipe for blast could use a new resource analogous with fibre glass, rock wool or asbestos. One way would be to crush and then smelt insulating glass.

**Comment by TwistedGate** [comment]
> The first thing that comes to mind is to keep the outer ring the same but replace the blaze powder with a piece of IE concrete

Personaly i like that idea, just instead of using a concrete block one could use the concrete filled bucket.

Why? Because you technicaly only need one bucket of concrete to get like infinite stacks if you're using it a certain way. Which i think would break the recipe and make it far too easy.

**Comment by BluSunrize** [comment]
Can't get liquid concrete without a mixer.
Mixer requires steel.

**Comment by voidsong-dragonfly** [comment]
Maybe replace the blaze powder with a pipe? IRL blast furnaces need airflow and flue flow throughout so it would make sense for the blast furnace to have some internal ducting.

**Comment by notadevtho** [comment]
Instead of using blaze powder you could use magma blocks, which spawn naturally in the overworld (underwater ravines and drowned ruins). It keeps the "fire" theme of blaze powder and makes you explore a bit the 1.13 water update.

**Comment by JStocke12** [comment]
Personally, I like both the idea of a blaze powder recipe and the magma blocks, but I think that they should be mutually exclusive. I kinda like the "blaze powder recipe" idea more, but the problem then becomes what items to use? In the texture it appears to be actively burning, but there aren't any irl perpetually burning materials.

I like the sulfur, but only sulfur wouldn't make sense. However, I don't think that going to the nether is the problem, more finding a fortress and fighting a blaze, so I was thinking maybe something like "crushed netherack", since netherack has an ability to burn indefinitely. It may be a bit inexpensive, so it might be a smart idea to add other materials, but that would be up to your discretion. (possibly uranium grit?)

**Comment by JStocke12** [comment]
*I didn't realize that sulfur was post-steel, you could add nether sulfur ore.
