### ISSUE TITLE
[Suggestion] Config to set fluids to Flammable

### ISSUE THREAD

**Issue by UnseenAcademical** [BluSunrize/ImmersiveEngineering#4089]
I haven't seen this requested yet, apologies if I'm repeating something that has been investigated earlier. I'm wondering if its possible to set an option where you can toggle fluids like creosote or ethanol as flammable. I know that because of the typical fire mechanics we will likely wind up with fire "floating" over any flowing blocks since they don't fill the full block.

Ideally, the fire would consume the source blocks one by one, leaving a pool to slowly burn itself away (possibly with lots of smoke). I've thought about making fluids able to be used as fuels (say, in furnaces) but this seems like a more balanced way to make fire interact with fluids. After all, currently I can extinguish a fire by throwing pure grain alcohol on it which seems... incorrect.

Thanks again for this great mod, and double thanks for making a push to 1.16 so quickly. Looking forward to seeing how we can make it interact with custom biomes. :)

**Comment by BluSunrize** [comment]
Custom fire mechanics are not very feasible for implementation. Vanilla fire has a specific way it behaves and customizing that is either impossible or simply not worth the effort.

The whole "fire floats above the block" is exactly why I never bothered making IE's fluids flammable again, because it looked stupid anyhow.
