### ISSUE TITLE
[1.15.2] Dupe with Fluid Pump, infinity iron

### ISSUE THREAD

**Issue by Serega007RU** [BluSunrize/ImmersiveEngineering#4101]
### Description of the issue:
You need to break the Fluid Pump in the already assembled Bottling Machine. After you break it, the Bottling Machine will sort it out and the Fluid Pump will drop out as a drop and remain in the world for half. This second half of it can be broken again and the second time Fluid Pump will drop out as a drop. Fluid Pump can be melted into iron and thus duplicate it. Forgive me for my poor English.

### Crashlog:
There is no crash in this problem

### Versions & Modlist
Forge 1.15.2 - 31.2.31
Immersive Engineering 0.12-98

### Note:
In this video you can see this problem, sorry that it is not in English
https://youtu.be/2-dZhAXabhE?t=135

I am sure that this can work on 1.16.1, unfortunately I can't test it, minecraft crashes as soon as I enter the world. Yes I saw that already other people send issue about this crash

This question is a duplicate of #4096 (and a little #4095 ) because I thought that you started ignoring me or simply stopped noticing it so I created a new question

If you have any questions or comments, please do not immediately close the issue.

**Comment by BartolomeoDR** [comment]
somewhere I've already seen it

=)))

**Comment by LordZZT** [comment]
Confirmed this still an issue in 1.16.5-4.2.1-131.
Looks like this is only an issue involving the bottling machine, because it is the only multi-block structure that uses a multi-block structure.

Safe bet would be to add a hook for when multi-block structures are broken; That way in cases like this you could confirm that the Dummy/Main block of the pump is broken, and to remove the block instead of letting it be harvested.

Steps to replicate:
1. Create Bottler
2. Harvest Water Pump (Both Main/ Dummy Work)

[Example on Imgur](https://i.imgur.com/JAyCNSw.mp4)
