### ISSUE TITLE
[0.6.0-pre] Crash without Hydraulicraft

### ISSUE THREAD

**Issue by miuirussia** [BluSunrize/ImmersiveEngineering#413]
http://pastebin.com/HDDDqF14

**Comment by cobra** [comment]
What Hydraulicraft version (api/deobf, version) did you use to build IE?

**Comment by miuirussia** [comment]
I don't use Hydraulicraft

**Comment by cobra** [comment]
But gradle isn't even able to compile IE without HC?

**Comment by miuirussia** [comment]
Yes

**Comment by miuirussia** [comment]
I think we need use reflection not direct calling methods in compact

**Comment by BluSunrize** [comment]
First of all: Pastebin your damn crashlog.
Secondly, you must build IE with Hydraulicraft.
Thirdly, you cannot use reflection to implement an interface.

**Comment by miuirussia** [comment]
1) Done)
2) I builded with Hydraulicraft, but I don't want to play with Hydraulicraft.
3) Understood

**Comment by cobra** [comment]
Tried it myself with Hydraulicraft version 234 from k4-u's maven as described on the HC github readme, using both api and deobf version for building (not at the same time, ofc). Crashes when launched from a normal launcher and from idea with HC set to "provided" (add to classpath at compile time only, not at runtime). Runs perfectly fine with the api jar loaded (from multiMC and idea), but crashes without it before even checking whether Hydraulicraft is loaded.
I don't know wtf is happening here, but I'm no expert for this sort of stuff. Either I'm doing something wrong when including HC or IE is broken.

relevant log snippets from my idea run: https://gist.github.com/cobra/0aca05335785042ff3fb

**Comment by malte0811** [comment]
i think (have not tested this yet) that adding something like [this](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/blocks/metal/TileEntityConnectorLV.java#L33) in `blusunrize.immersiveengineering.common.util.compat.hydcraft.IETrolley` would fix this.

**Comment by cobra** [comment]
Just tried this, but it still crashes for me with the same error. I'm wondering why it's already crashing at `modules.add(new HydCraftHelper());` which is just a simple string assignment, nothing involving any HC at all.

**Comment by BluSunrize** [comment]
I don't quite understand how it crashes, and @malte0811, I can't use the API annotation, because @K-4U does nto provide a package-info file

**Comment by cobra** [comment]
Either I'm doing something wrong, or adding package-info, recompiling HC and using this version instead, as well as having the `@optional` annotation doesn't change anything. welp.

**Comment by malte0811** [comment]
Ok, this crash is confusing me: i added `-verbose:class` as an jvm parameter in my test instance. The output shows that the last and only class from the `compat.hydcraft` package that is being loaded is the `HydCraftHelper`, which does not even directly reference `IHarvesterTrolley`. I would have expected the vm to crash when loading the `IETrolley`, which it does not even do. my next guess would be that gradle does some "compile-magic" which results in a direct reference in the bytecode, which i don't really know how to track down

**Comment by cobra** [comment]
Yep, that's consistent to the crash logs and code. There is the register code in `init()`, but this isn't going to be used at this point in time.
I'm seeing quite a lot of other classes being loaded after loading `HydCraftHelper`, namely few waila and a lot of cofh and enderio (from testing the other issue, sits in my eclipse/mods folder) classes; there are also some `[Client thread/INFO] [EnderCore]` log entries in between these loading messages.
The last "normal" and first error line in my log don't seem to be related in any way:
````
[Loaded cofh.thermalexpansion.network.PacketTEBase from jar:file:/home/<…>/src/ImmersiveEngineering/eclipse/mods/ThermalExpansion-%5B1.7.10%5D4.0.3B1-218-dev.jar!/cofh/thermalexpansion/network/PacketTEBase.class]
[22:32:32] [Client thread/ERROR] [FML]: Fatal errors were detected during the transition from INITIALIZATION to POSTINITIALIZATION. Loading cannot continue
````

I don't think that gradle is doing anything weird here at all - I'm testing/debugging in idea, which should build IE all by itself and launch the gradleStart class without touching gradle at all.

**Comment by cobra** [comment]
Disabling parts of the HC compat code shows:
- calling `HCApi.getInstance().getTrolleyRegistrar().registerTrolley()` is not a problem, `HydraftHelper.init()` doesn't get executed when (not)\* trying to register `null` instead of `new IETrolley()` and Minecraft won't crash.
- Simply (not)\* instantiating `IHarvesterTrolley test = new IETrolley()` without doing anything (api and register calls removed) with this object also doesn't crash.
- Instantiating such an Trolley object and then registering `null` doesn't crash.
- ONLY instantiating an IETrolley and then registering this object (`test`) crashes.
- Of course registering `new IETrolley()` also crashes, that's the unmodified version I started with.

I added debug output to [ImmersiveEngineering.java:91](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/ImmersiveEngineering.java#L91) to show which modules are initialised and which are skipped - this output doesn't ever show up when crashing, only when minecraft is loading correctly, always logging "skipping mod compat module for HydCraft".

Yes, I updated to HC 235 already. Didn't change anything (yet).
\* code is modified, but never executed, because HydrauliCraft isn't loaded - as it should be.

**Comment by theunkn0wn1** [comment]
If any of this helps,

Was able to reproduce the OP, built with the API of the latest HC(api) and IE builds.
[crashlog](http://paste.feed-the-beast.com/view/b29ea305) built with gradle version **2.4** against Java JDK JAVA_VERSION="1.8.0_60"

Error occurs at the beginning of mod init phase 3, (5 of 7)

HC is NOT installed in my test instance.
The only modification made to either mod was the version number of IE (changed to ...``0.6.0-preC``) in the `build.gradle` file

**Comment by cobra** [comment]
That's the exact same crash log, just with more mods inflating the log. Sorry, can't see anything unknown.

**Comment by XFactHD** [comment]
You might want to look at the way MineMaarten solved this problem.
https://github.com/MineMaarten/PneumaticCraft/tree/master/src/pneumaticCraft/common/thirdparty

**Comment by malte0811** [comment]
malte0811@03b038f4296ecd84ed34c97e679c61d545f204a1 fixes this. I think the problem was that `registerTrolley` takes an `ITrolley` as a parameter, this apparently results in direct references to `ITrolley` in the bytecode. I changed that (and only that) call to use reflection instead, this prevents the crash. If no one finds a bug in that implementation i will pr it in a few hours.

**Comment by cobra** [comment]
Another way: checking for the mods before adding their modules in `IECompatModule`.
````
if(Loader.isModLoaded("HydCraft")) modules.add(new HydCraftHelper());
````

But the reflection solution looks more robust, my solution was from experimenting which code was executed when and which was not before crashing.

**Comment by K-4U** [comment]
I would most definately go for checking if the mod is loaded. You should do that with all mods. Or use @Optional

**Comment by miuirussia** [comment]
Yes, I think using isModLoaded would be more appropriate.

**Comment by cobra** [comment]
@K-4U well, `@Optional` in `IETrolley` didn't help avoiding the crash, the problem is the `registerTrolley` call. Checking `isModLoaded` before trying to register the Trolley didn't help, it's the simple existence of this register call in the compat module (even when it's never run at all) which is causing the crashes. I'm really no expert in this field, but I'm a bit concerned about this behaviour.

BTW, semi-related: what about config options for the compat modules? Would this be desirable? Checking a config setting before adding the individual modules avoids the crash in the same way as checking for the mod, so this could be an emergency measure when a mod breaks something.

**Comment by cobra** [comment]
I've implemented this "adding only loaded mod compat modules" for all mods in https://github.com/cobra/ImmersiveEngineering/commit/e2989dbe576e1d86dcb42aa0961266bc3ef9d391.
This isn't intended as a competing PR, I just had have half of this laying around already and considered it useful for testing. I won't PR [my branch] (https://github.com/cobra/ImmersiveEngineering/tree/checkModsForModCompat) unless there's consensus that this is really the way to solve this correctly.

**Comment by K-4U** [comment]
Well. Or @BluSunrize, have a look at how i do it:
https://github.com/K-4U/Hydraulicraft/blob/master/java/k4unl/minecraft/Hydraulicraft/thirdParty/ThirdPartyManager.java#L35-L53

**Comment by BluSunrize** [comment]
I'll see to it myself, the compat stuff needs a bit of reworking anyway ^^
