### ISSUE TITLE
[1.16.1] Client crash upon unloading of wire connector

### ISSUE THREAD

**Issue by dierks-m** [BluSunrize/ImmersiveEngineering#4152]
### Before reporting:
This seems to be similar to #4111, but the crash log looks different

### Description of the issue:
Having chunks unload due to view distance when walking away causes a client crash - the dedicated server continued on running.
I have not experienced this before when walking the same direction.
I have, so far, unfortunately been unable to reproduce the issue. I do have the suspicion, that the wire network was partially loaded for some time before being completely unloaded, because I spent quite some time in the area right before the chunk that would cause it to completely unload. It then crashed when I walked that one chunk further.

### Crashlog:
[crash-2020-07-30_19.51.04-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/5002973/crash-2020-07-30_19.51.04-client.txt)

### Versions & Modlist
IE 0.16-109 on commit https://github.com/BluSunrize/ImmersiveEngineering/commit/c9a0852410f5c5b4244ac6477728a80f36006b72 - I just built that jar locally for the newer Forge version, as it wasn't available on CurseForge yet; running on
Forge 32.0.97

**Comment by malte0811** [comment]
Quick intermediate report on this: I've been able to reproduce this issue, as well as some non-crash issues in 1.14 with similar setups. It seems like `TileEntity#onLoad`, `TileEntity#onChunkUnload` and `TileEntity#remove` have some strange behaviors on the client, and that behavior differs between MC versions. I'm still working out how I can deal with that without breaking other things.

Edit: I'm labeling this as both bug and crash since it's a crash on 1.16, but occurs as a non-crash bug on 1.14 (and probably in one form or the other on 1.15 as well).

**Comment by burshaz** [comment]
Not piling on, just adding my crash to the info
[https://pastebin.com/6Y21eiFw](url)

IE 0.16-109
Forge 32.0.88

On a server and was currently the only player online.  The server does not crash and no IE wires in my location on the server.
