### ISSUE TITLE
Server crash: Exception ticking world 1.16.1

### ISSUE THREAD

**Issue by iggydus** [BluSunrize/ImmersiveEngineering#4183]
**Description of the issue:**
We are running a dedicated apex server that has random crashes since the new update. There seems to be no specific action to trigger the crash as it happens while doing different random actions. 

**Crashlog:**
https://pastebin.com/0iPLrwBp

### Versions & Modlist
Forge 1.16.1 - 32.0.106
IE 1.16.1-3.1-112

**Comment by BluSunrize** [comment]
How often has this occured? Do you have more crashlogs like these?

**Comment by iggydus** [comment]
I will get more crash logs to you later today. 
If i am playing for 2 hour it will happen around 4-7 times

**Comment by mindforger** [comment]
looks like a vine tried to replace your fake light, maybe you missed a hook there or try t hold on to the block too much (as it looks like an adjacent vineblock tries to set a propery on your fake light which is only expected to exists on vineblocks)

either vine blocks dont do typechecks or forge did not catch that or it is in your ballpark to catch that since your fake light looks like air :D 

or throw a warning to cut down vines around floodlights, since the may cause fire hazards XD

**Comment by iggydus** [comment]
https://pastebin.com/EZE4QZwC
https://pastebin.com/BsYE44Sa
https://pastebin.com/dtnkAF2P
https://pastebin.com/tDHE0v8H
4 more logs from previous crashes

**Comment by iggydus** [comment]
> looks like a vine tried to replace your fake light, maybe you missed a hook there or try t hold on to the block too much (as it looks like an adjacent vineblock tries to set a propery on your fake light which is only expected to exists on vineblocks)
> 
> either vine blocks dont do typechecks or forge did not catch that or it is in your ballpark to catch that since your fake light looks like air :D
> 
> or throw a warning to cut down vines around floodlights, since the may cause fire hazards XD

So i didn't follow all of that but i cut down the vines next to the floodlamp light area. Will see if the crash persists and update

**Comment by iggydus** [comment]
That seems to have fixed it. Haven't had a crash in past 2 days
