### ISSUE TITLE
Excavator ticks down depletion on empty veins

### ISSUE THREAD

**Issue by lycc193** [BluSunrize/ImmersiveEngineering#4197]
### Description of the issue:
First,I set excavator_yield to **128** through the config.

When I used CoreSampleDrill for the first time, it showed Expected Yield: 98ores.
![image](https://user-images.githubusercontent.com/25812011/89911192-b7923580-dc23-11ea-98f3-d7a9484c3ce9.png)

But when I put down the bucket wheel, only 91 ore was excavated and no longer produced.
![image](https://user-images.githubusercontent.com/25812011/89911300-d7c1f480-dc23-11ea-8731-fe963caf6258.png)
![image](https://user-images.githubusercontent.com/25812011/89911309-dabce500-dc23-11ea-9245-8cbada6c4636.png)

Using CoreSampleDrill again, it shows Expected Yield: -45ores
![image](https://user-images.githubusercontent.com/25812011/89911382-f0caa580-dc23-11ea-98b4-f363a793594d.png)

nbt data:
![image](https://user-images.githubusercontent.com/25812011/89911413-fa540d80-dc23-11ea-8ffa-344acd39c63e.png)

---
There are two main problems in this process
1. The mineral vein cannot be fully excavated
2. Expected is displayed as a negative number

### Versions & Modlist
minecraft:1.16.1
forge:106
ie:3.1-112

no more mod, only one

**Comment by BluSunrize** [comment]
The excavator has a chance to fail at excavating things. That means it consumes one unit of the vein's yield, but doesn't actually give you any blocks. That's **intentional behavior**

Additionally, this fail chance increases with the distance of your excavator from the center of the vein. If you put it further away, you get less. That's also **intentional behavior**.

The negative yield however is not intended. Could you please provide more details? Was this a core sample you took *after* the excavator was done?

**Comment by lycc193** [comment]
Yep, Core Sample Drill was used again when the excavator was not producing

**Comment by lycc193** [comment]
I tested the nbt data again. When the excavator stopped producing, the bucket wheel did not stop running, and the depletion was still increasing, which resulted in the generation of negative numbers.

**Comment by BluSunrize** [comment]
Yeah that's the real issue, it should stop depleting once the vein is empty.
