### ISSUE TITLE
Diesel Generator not working

### ISSUE THREAD

**Issue by James-T-Oudvoure** [BluSunrize/ImmersiveEngineering#427]
When I build a diesel generator, I'm unable to get it to work. I started having problems in my survival world, but when I made a creative world to try and figure out what's wrong, it still wouldn't work.

I have bio-diesel in a Thermal Expansion tank hooked directly up to the generator with a pipe. I can see the diesel going into the generator, when I put a certain amount into a tank and hook it up, it gets sucked out of the tank, into the pipes, and out of the pipes. But the generator never activates, the fan doesn't move, and no sound ever plays.

![2015-09-16_20 41 55](https://cloud.githubusercontent.com/assets/14304823/9922972/96541972-5cb4-11e5-8342-db630821c88f.png)

This is my current setup. Please excuse that aperture to the left, that's an automatic minecart nuke maker that I used to blow up the generator.

Also, I've heard that you can use conveyor belts and bottles of bio-diesel to fuel the generator:

![2015-09-16_20 48 08](https://cloud.githubusercontent.com/assets/14304823/9922976/a09e7558-5cb4-11e5-9cef-d60cc4834426.png)

As you can see,

![2015-09-16_20 49 38](https://cloud.githubusercontent.com/assets/14304823/9922979/a5d55fc8-5cb4-11e5-8746-79081ebc0a09.png)

 I've tried this.

**Comment by bart1ebee** [comment]
It needs to have some where for the power to go

**Comment by James-T-Oudvoure** [comment]
Alright, thank you. But, there's still the question of why the conveyor belts don't put bio-diesel into the generator.

**Comment by theunkn0wn1** [comment]
Able to reproduce the secondary issue reported here, the generator does **not** accept IE's own fluid containers.

Because those ports only accept Forge fluids, not items. as far as i can tell, the book does not state anywhere what input methods are accepted. 
Below is my setup, 
![image](https://cloud.githubusercontent.com/assets/3110986/9925001/53c99e64-5cba-11e5-858f-99a62f7cf836.png)
Using IE conveyors to input to the generator, the output power is being voided by the trash can from Extra Utilities. I also tested by pumping the same fluids in via pipes (TD) and that method works fine.
IE version [0.6.0_pre](2fec12bbd2ec1a4981de46236e278bc4124c2857)

@BluSunrize, I don't presume this is the proper behavior?

**Comment by BluSunrize** [comment]
Yeah I don't know who told you you could conveyor's but that's definitely not a thing.

Issue solved
