### ISSUE TITLE
suggestion: anvil repair for heavy plated shield

### ISSUE THREAD

**Issue by kuroyure** [BluSunrize/ImmersiveEngineering#4287]
it would appear they are not currently repairable in an anvil, welp, lets *fix that*

**Comment by TeamSpen210** [comment]
They should be repairable by a Steel Ingot, but the method is using an old tag name:
https://github.com/BluSunrize/ImmersiveEngineering/blob/71a5d51dbfb2a74e68e437c75cb81a6151cd38ea/src/main/java/blusunrize/immersiveengineering/common/items/IEShieldItem.java#L204-L208

If you create the `immersiveengineering:ingot_steel` tag, it should work then. As an aside it would probably better to use tag wrappers/optional tags instead of this method, to avoid the lookup each time.
