### ISSUE TITLE
[1.15.2] Revolver doesn't fire.

### ISSUE THREAD

**Issue by wacinton** [BluSunrize/ImmersiveEngineering#4360]
### Description of the issue:
A fully loaded revolver does not fire. 
I first noticed the issue in the Valhesia 2 modpack, but tried minimal installs to find which specific mod caused the issue. 
I reproduced the issue with only Immersive Engineering and The Midnight installed, with Forge 31.2.45. 

I believe this to be related to issue [4194](https://github.com/BluSunrize/ImmersiveEngineering/issues/4194) but as that issue was closed without being resolved, I decided to see exactly which mod was causing the issue. 

### Versions & Modlist
Minecraft 1.15.2
Forge 31.2.45
ImmersiveEngineering-1.15.2-4.1.0-122 
themidnight-0.5.9 [The Midnight](https://www.curseforge.com/minecraft/mc-mods/the-midnight)

**Comment by BluSunrize** [comment]
Yeah, remove Midnight and it'll work.

**Comment by BluSunrize** [comment]
To elaborate on this a little more:

Midnight has had that bug in for quite a while, there have been previous reports. Their team has been made aware of the issue, back in June:
https://github.com/Cryptic-Mushroom/The-Midnight/issues/424
Their official stance appears to be that the update to 1.16.1 takes precedence, and as such this will not be resolved.

Fact of the matter is, the issue is actually really easy to fix, they would just have to remove this line, or at least only apply it for *their own items*:
https://github.com/Cryptic-Mushroom/The-Midnight/blob/old/1.15.2/src/main/java/com/mushroom/midnight/common/world/rift/EntranceRiftGenerator.java#L68

To give a brief overview of what goes on:

- What they do there is making *any* item do its swinging animation when right clicked.
- That cooldown is the same one used when equipping the item. So you can't swing a sword immediately after switching to it.
- The revolver is supposed to not let you fire until the weapon is fully raised, and thus relies on that cooldown. 
- With Midnight triggering that same cooldown on every rightclick, the Revolver can never fire.

If they just removed that line and released a new 1.15.2 build, that'd probably fix it. But as it stands, we can't do anything about this. It's on them to fix.
