### ISSUE TITLE
[1.16.1|123] [Modinteraction] Quark Inventory Sorting Buttons on Engineer's Crafting Table in bad position

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#4370]
As title, see picture
Mod versions are same as from the server
![grafik](https://user-images.githubusercontent.com/7753414/95755278-80ccb000-0ca4-11eb-9246-fb86fab1b2d5.png)

**Comment by BluSunrize** [comment]
Quark has a config for this. Look for  "Ignored Screens" in the "general" section. Add `blusunrize.immersiveengineering.client.gui.CraftingTableScreen` there to fix this.

Unfortunately, there is no way for us to do this programatically, because last time I checked, Quark didn't have any IMC message support for this. Feel free to bring that up with their team, if they get an IMC handler for it, I'll happily exclude IE's screens by default ^_^

**Comment by MalkContent** [comment]
drats. ty!
