### ISSUE TITLE
immersive engineering-optfine crash 1.16.3

### ISSUE THREAD

**Issue by IchigoGames** [BluSunrize/ImmersiveEngineering#4441]
### Description of the issue:
optfine runs fine before loading shaders it will also work after loading shaders but as soon as i try to use shaders and a resource pack at the same time it crashes this may be something i should post on optfines issue tab if so just let me know. the only reason i posted this on here if from looking at crash report it might have something to do with this mod.

### Crashlog:
https://pastebin.com/cSuaqaSN

### Versions & Modlist
Minecraft 1.16.3
Forge 34.1.42
ImmersiveEngineering-1.16.3-4.1.1-127
OptiFine HD U G5
my modpack The Final Frontier 2

**Comment by malte0811** [comment]
Optifine is not supported, especially (from me personally) when the goal isn't playable FPS but shaders.  
I've seen this crash before (unless there's two very similar ones), it seems to be caused by OF using a different vertex format with and without shaders. As far as I know we are getting the current vertex format from the correct source (`DefaultVertexFormats.BLOCK`), if @sp614x can tell us what we should be using instead I can look into doing that.
