### ISSUE TITLE
Add Compiling guide!

### ISSUE THREAD

**Issue by Kosti1** [BluSunrize/ImmersiveEngineering#45]
Title tells everything?

**Comment by BluSunrize** [comment]
...seriously?
You completely missing the point. The only people who should be able to compile this are those that know java code and minecraft modding. Because I can be sure that they can give me insightful bug reports on the matter. If I made a tutorial on how to compile this, that'd kinda defeat the purpose.

**Comment by Kosti1** [comment]
ok
