### ISSUE TITLE
[WIP] Allow inverting Fluid Outlet behavior

### ISSUE THREAD

**Issue by Recaiden** [BluSunrize/ImmersiveEngineering#4615]
### Description of the issue:
Fluid Outlets output fluid automatically (on sides configured to output) and turn off with a redstone signal.
It would be convenient if a Screwdriver would invert this behavior, so that a redstone signal allows output.
It is possible to get the desired behavior using redstone torches, but inversion is possible with many other IE blocks.

### Versions & Modlist
ImmersiveEngineering-1.16.4-4.1.2-129

**Comment by BluSunrize** [comment]
I have started work on this, but noticed in the process that the fluid outlet is currently pretty borked and doesn't actually fill areas up nicely anymore.
As far as I can tell, it's been broken since March of last year. I will look into fixing it as part of this issue, but it will not be done for the next release.
