### ISSUE TITLE
Garbage Collection runs out of Memory

### ISSUE THREAD

**Issue by Steamdroid2000** [BluSunrize/ImmersiveEngineering#462]
I added this mod and about six others to FTB Infinity (v1.10.1) for Minecraft 1.7.10, but it stops loading soon after. It talks about IE not initializing, and causing an error instead, thus causing the crash. I have a link to the pastebin.com page it is pasted to here. I hope it's just a mod incompatibility, because I really want to use this mod with the (most of) others.

http://pastebin.com/ymJEgg79

**Comment by cobra** [comment]
Your forge version (1291) is too damn old. Please update it to 1.7.10-10.13.4.1448, there have been some changes to the oreDictionary in the meantime. See also #436.

**Comment by BluSunrize** [comment]
^ this

**Comment by Steamdroid2000** [comment]
Thank you. However, another issue has risen. I've tried updating AOBD like in another post, but it didn't help. Here is the pastebin.

http://pastebin.com/cHZWaTeK

**Comment by BluSunrize** [comment]
Too many mods. Your Garbage Collection refuses to play nice. I don't know my way around java arguments, so I'm going to let someone else tackle this.

**Comment by XFactHD** [comment]
If you are playing on the FTB launcher, try increasing your ram, if you are playing on the regular minecraft launcher, try increasing the value in the following JVM argument: -Xmx1G under "Edit profile".
Don't allocate more than half of the ram your computer has.

**Comment by cobra** [comment]
That's a new one. Especially with that much memory - I didn't expect that running it with 5618MB of heap will fail during loading.

Oracle's docs say:
>-XX:+UseGCOverheadLimit
Enables the use of a policy that limits the proportion of time spent by the JVM on GC before an OutOfMemoryError exception is thrown. This option is enabled, by default and the parallel GC will throw an OutOfMemoryError if more than 98% of the total time is spent on garbage collection and less than 2% of the heap is recovered.

Increasing the heap size even more doesn't look very promising to me, but you're definitely running out of memory. How much RAM do you have in total? You could try giving java even more memory to consume, even though that's a bad idea - after reaching a certain threshold, minecraft runs worse.

There might be a serious bug in one of the mods. Have you tried starting Infinity without your additions?

@XFactHD look at the JVM arguments in the log. Max heap size is at over 5G: -Xmx5618M
(did I mention I hate Infinity because of its infinity-ness regarding everything?)

**Comment by XFactHD** [comment]
Sorry, I didn't look at the JVM arguments in the log. The crash occurs when IE is loading the texture map for the revolvers. FastCraft could be involved in the crash, but @Steamdroid2000 would have to test this.

**Comment by cobra** [comment]
It's not really a crash, java is simply out of memory and garbage collection can't free any more. I doubt that fastcraft is the problem here. I also doubt that IE has something to do with that, it's just a more or less random victim of insufficient memory.

Profiling might give some more details of what's going on, but you should have sufficient knowledge and resources to get anything useful out of that.
I certainly won't debug any of this unless it can be narrowed down to a small fraction of the whole modpack.

**Comment by Steamdroid2000** [comment]
Thanks for the help guys. I'm going to see what happens if I disable fastcraft and a few others. I hope it helps.

**Comment by Steamdroid2000** [comment]
But its weird, as this thing was able to run Monster with few problems other than frame rate.

**Comment by Steamdroid2000** [comment]
It works now, and i have started a new world. Thanks guys.
