### ISSUE TITLE
[Feature Request] Fluids as soil option in cloches

### ISSUE THREAD

**Issue by UnseenAcademical** [BluSunrize/ImmersiveEngineering#4632]
If there is not a separate machine planned for growing blocks in fluid soils, I'd like to request that buckets of fluids be an option for soils in the cloche.

Ideally speaking it would allow for arbitrary fluids so that modpack creators could set up multiple fluid based recipes. Not only would this allow for growing coral/kelp in water, but also Bumblezone's honey crystals in sugar water for example. Unless all crystal-type growing would be in a different machine, which would also be able to handle things like amethyst.

Thank you!

**Comment by BluSunrize** [comment]
You can literally already do that.

```json
{
  "type": "immersiveengineering:cloche",
  "results": [
    {
      "item": "minecraft:blaze_powder"
    }
  ],
  "input": {
    "item": "minecraft:nether_wart"
  },
  "soil": {
    "item": "minecraft:lava_bucket"
  },
  "time": 560,
  "render": {
    "type": "crop",
    "block": "minecraft:nether_wart"
  }
}
```

That recipe json allows you to plant netherwarts using a lava bucket as soil, which makes them grow blazepowder. It's a nonsense recipe, but proof of concept:

![](https://i.imgur.com/BvDQ1wG.png)

I even made it render properly in world, for this very exact reason:

![](https://i.imgur.com/Zn8zD1O.png)

This has been a feature ever since the Cloche was addded. You just needed to try it.

**Comment by UnseenAcademical** [comment]
I am trying with kelp added by datapack and it isn't working:

{
  "type": "immersiveengineering:cloche",
  "results": [
    {
      "item": "minecraft:kelp",
      "count": 1
    }
  ],
  "input": {
    "item": "minecraft:kelp"
  },
  "soil": {
    "item": "minecraft:water_bucket"
  },
  "time": 640,
  "render": {
    "type": "crop",
    "block": "minecraft:kelp"
  }
}

EDIT: Never mind, misplaced datapack file.
