### ISSUE TITLE
[1.16.5] Compatibility with Create

### ISSUE THREAD

**Issue by FrannDzs** [BluSunrize/ImmersiveEngineering#4645]
### Description of the issue:
Hello! How are you? I hope it's ok!. I love the project, although I have problems with Create 0.3e, and it is that the 2 mods have their copper_ore but the name of the item is different so I get 2 different copper ore, although their id is the same (forge:copper). This causes me some confusion.

### Crashlog:
*No crash

### Versions & Modlist
Forge 36.0.21
Minecraft 1.16.5
ImmersiveEngineering-1.16.5-4.2.1-131
Create - mc1.16.3+4+5_v0.3e.jar

**Comment by Algester** [comment]
you can have a world gen whitelist for ores so you can only have 1 set of ores in world gen

**Comment by BluSunrize** [comment]
This is not an issue. This is absolutely intentional.

Both ores are "tagged" as copper ore, meaning they can be used in the same recipes. As can their ingots and plates and whatever. You can use them interchangably.

Adittionally, IE has a config option to disable ores from spawning in the world, and I am sure Create has similar options.

**Comment by FrannDzs** [comment]
Hello! Thanks for the clarification and a thousand apologies for the inconvenience! Regards!
