### ISSUE TITLE
[Request] Optional Ore Tools

### ISSUE THREAD

**Issue by IdrisQe** [BluSunrize/ImmersiveEngineering#4662]
I'm honestly amazed I couldn't find any past issues for this, but what's the stance on adding a config option to give us tools/weapons for all the metals added by IE, rather than just Steel?

Some smaller modpacks I've tried making in the past haven't had any other mods that add these ores, leading to an annoying issue where if I want, say, Copper tools as a bridge between Stone and Iron, or Silver swords to use thematically with the Consecration mod, I need to go and install another entire mod which adds ores (which I then need to disable and unify into IE variants) just in order to gain access to material tools. 

It would be so much nicer if we could just get a config option, even if off by default, that added in Copper, Silver, Lead, Nickel, and Aluminum tools. Maybe even individual options to enable each at your discretion (for example I don't think Aluminum or Lead tools are all that realistic given the softness of said metals... Silver is passable since it's close to the same hardness as Gold, which already has tools by default)

Armour on the other hand is far less important and (as far as I know) there's a lot less historical precident too for armour being made of unusual metals- it's usually just Iron and Steel, maybe some Copper way back... And the difference range between most armour tiers these metals would fit into is already much slimmer than with the tools.

**Comment by BluSunrize** [comment]
Basically all of these are terrible materials to make tools out of. Silver swords to fight against magical creatures, sure. But a copper axe? It'd blunt in record time. A lead pickaxe? You strike a rock and it bends.
The reason IE doesn't add them is because they are just bad materials for impact-based tools. They are much more materials for science and engineering.

So no, no plans what so ever to add this.
