### ISSUE TITLE
Create Coupling doesn't work on IE Minecarts

### ISSUE THREAD

**Issue by IdrisQe** [BluSunrize/ImmersiveEngineering#4663]
### Description of the issue:
The Minecart Coupling from Create does not function on Immersive Engineering Minecarts, despite working fine on Vanilla Minecarts and those added by the More Minecarts mod. Not sure if this is an IE or Create issue, since Quark's Chain-Coupling feature and More Minecarts' Coupler both work on IE Minecarts just fine.

Linking the issue in both repositories.
https://github.com/Creators-of-Create/Create/issues/1137

### Versions & Modlist
Minecraft 1.16.5
Forge 36.0.42
Create 0.3e
Immersive Engineering 4.2.1-131

**Comment by BluSunrize** [comment]
If it works with Quark, I figure this might be an issue with Create? Plus I have no idea how coupling works either.

I'll close this for now, if the Create folks can indicate some flag or method we are missing to make our stuff compatible, I'd love to make it possible!!

Just reply here if this issue turns out to be on our end, and I'll reopen it =)
