### ISSUE TITLE
Too many getTileEntity() calls

### ISSUE THREAD

**Issue by ZeroNoRyouki** [BluSunrize/ImmersiveEngineering#467]
Hi there!
I was reading through your code when something that caught my attention: you call World.getTileEntity() a lot, even when you have already called it once for the same world location and getTileEntity() is not the fastest function around.

For example, in TileEntityExcavator.updateEntity() you call it 5 times for the same world location

You really need just one call. 

The same thing goes for other function that compute and return a value that you need to use, like the master() method of your multiblocks tile entities

I'm just pointing this out because I really love to play with IE

**Comment by malte0811** [comment]
I have started working on this, have improved about half of the methods that call `getTileEntity` yet. There are more calls to this in the code than I had expected.

**Comment by cobra** [comment]
Yeah, I noticed that as well. Do you want to split that refactoring work? I would help out doing some of this.

**Comment by malte0811** [comment]
Yes, some help with this would be nice as i will not have any time to work on this tomorrow. You now have write access to my fork because i just went through an alphabetical list of the methods used, meaning that many edited files still have some "bad" calls in, and by keeping it all in one branch we would avoid a LOT of merge conflicts. Please push any changes to the branch getTECalls (the one i pushed to) in my fork.

**Comment by cobra** [comment]
Okay, so you're done for now? How did you get and sort this list? I'm normally using intellij idea which is able to group the method usage search results, so I'd prefer getting the same type of list.

**Comment by malte0811** [comment]
Sorry for not answering sooner. I use eclipse and have not tried intellij yet, so i dont know whether this is possible with intellij: i used the "call hierachy" function in eclipse, this shows a list of all methods calling a specific method in alphabetical order. If intellij has this feature i recommend you to limit it to ie source code since mc itself contains many calls to getTileEntity

**Comment by cobra** [comment]
I can't seem to get the same with idea, but that doesn't matter. Eclipse works as well. Idea groups the usage by classes first, then by methods. That search function is really awesome, having a ton of options including overrides and scope.

**Comment by cobra** [comment]
Replacing these getTileEntity calls also helps finding (and deleting) useless operations like null checks after instanceof checks or duplicate code. I'm removing such operations when I can't see any other need for them. (Idea is automatically checking for and highlighting such cases)

Reworked most of it, only updateEntity calls are still to be done. I try to rework those tomorrow, but I'll update this post before starting to avoid conflicts and duplicate work. The branch can be merged without conflicts at the moment and still builds and works as far as I could see. I'm still unsure how to handle the pipe code pushed to master after you started this branch. Pull and merge master into this branch or PR and start another branch?

**Comment by cobra** [comment]
starting updateEntity rework.

**Comment by ZeroNoRyouki** [comment]
in the ItemBlockMetalDevices.placeBlockAt() method I will do something like this:

TileEntityConveyorBelt tile = (TileEntityConveyorBelt)tileEntity;
TileEntity dummyTE;

// other code

else if((dummyTE = world.getTileEntity(x+fd.offsetX, y+1, z+fd.offsetZ)) instanceof TileEntityConveyorBelt) {
	TileEntityConveyorBelt con = (TileEntityConveyorBelt)dummyTE;
	// other code
} else if((dummyTE = world.getTileEntity(x+fd.offsetX, y-1, z+fd.offsetZ)) instanceof TileEntityConveyorBelt) {
}
and so on

**Comment by cobra** [comment]
That's a possibility, but I where I'm coming from, doing anything like this is usually explicitly forbidden.
But yeah, there are some other things going slightly against my usual style (:P), so I guess IE's rules are a bit more relaxed and we could do that. The worst thing that could happen here is a crashed MC instance, not a dead person, so…

**Comment by ZeroNoRyouki** [comment]
Why it's forbidden if I may ask?

**Comment by cobra** [comment]
It's too easy for assignment get either misread and/or corrected to a comparison (`=` vs `==`) or getting broken when changing something. Pure human errors, but that's the same for a lot of memory problems. Depending on the environment there's a ton of forbidden stuff which is usually working for desktop software - sometimes even using malloc (C) is not allowed.

Another cause for skipping this was that this method is not really time-critical and having two getTileEntity calls instead of one isn't that bad - not like the [watermill's updateEntity method](https://github.com/BluSunrize/ImmersiveEngineering/blob/356e944c338a1446d44f19e2d61eb5739e6235b2/src/main/java/blusunrize/immersiveengineering/common/blocks/wooden/TileEntityWatermill.java#L54).

**Comment by ZeroNoRyouki** [comment]
Got it

Yeah that method was where I started to thing that something was wrong :)

**Comment by cobra** [comment]
Me too, especially after taking the for loops into account, yielding a maximum of 22 calls in total AFAIR.
I haven't done any profiling on that (not yet - might be interesting to see some effects) and I do hope that the JVM is doing at least some optimisation here.

**Comment by ZeroNoRyouki** [comment]
The only optimizations you could get there are on the coordinates computation. The getTileEntity() call cannot be ommited.

The real problem here is a design one: the game logic behind a multiblock is split between a singleton and the multiblock tile entities (that carry multiple instance of the multiblock data for nothing). A better solution would have been using a single class to handle the game logic and data (one for each multiblock in the world) and using the tiles only as light connection point between the in game blocks and that class
