### ISSUE TITLE
Vanilla Furnaces Lose Items

### ISSUE THREAD

**Issue by AgentCPU0** [BluSunrize/ImmersiveEngineering#4681]
Vanilla furnaces powered by an external heater can cause items to vanish completely when placed inside to smelt. This has been reported before, but every thread on the subject was closed, including the original thread. If there's an explanation, then please say something, because this is not a fun bug at all. Please, either fix it or remove the External Heater completely

**Comment by mindforger** [comment]
How about following the issue template and providing the required Information to be able to help you? How should one understand your issue without knowing anything about your setup

**Comment by AgentCPU0** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/3619

Do I need to, especially when they already did, and it was since closed? And the block is still broken. Explain that. It's one thing to not give the requested report. It's another to take that kind of report and brush it off as if they have no clue what's going on

**Comment by malte0811** [comment]
As I said in that issue, the user reporting it was using some non-standard server software, some Forge-Bukkit-Hybrid. Those are not supported, as stated in the [contributing guidelines](https://github.com/BluSunrize/ImmersiveEngineering/blob/1.16.5/CONTRIBUTING.md#other-mods). If you are not using any such server software (or other mods on the list of unsupported mods), then this is a valid issue **once you add the requested information**. Otherwise it's invalid, just as the other one.

**Comment by BluSunrize** [comment]
Yeah what malte said. I'm closing this. Open a new, properly formatted issue, if you use a normal server.
