### ISSUE TITLE
[1.16.5] Fluids from other mods works like water in IE recipes

### ISSUE THREAD

**Issue by Tander** [BluSunrize/ImmersiveEngineering#4682]
### Description of the issue:
Basically in each Immersive Engineering (and Immersive Petroleum) recipes some (not all) fluids from other mods works as minecraft:water:

![javaw_2021-03-03_14-24-09](https://user-images.githubusercontent.com/1059805/109798873-561bcd80-7c2c-11eb-975e-8684ad312da3.png)

![javaw_2021-03-03_14-24-13](https://user-images.githubusercontent.com/1059805/109798878-57e59100-7c2c-11eb-8523-515fc3b33502.png)

![javaw_2021-03-03_14-24-22](https://user-images.githubusercontent.com/1059805/109798886-59af5480-7c2c-11eb-93ca-0bbb77408978.png)

![изображение](https://user-images.githubusercontent.com/1059805/109799031-8ebba700-7c2c-11eb-8b49-a83fab3ea376.png)

### Versions & Modlist
Complete mod list to reproduce the bug:
forge-36.0.44
ImmersiveEngineering-1.16.5-4.2.1-131
jei-1.16.4-7.6.1.71
YungsApi-1.16.4-Forge-4
BetterPortals-1.16.4-0.3.1

Also happens with Create and The Undergarden (at least what I tested)

**Comment by malte0811** [comment]
That's because those mods mark their fluids as water ([example for Create](https://github.com/Creators-of-Create/Create/blob/b1dc36d3582f9232b30e86aca8473e933a6a0b77/src/generated/resources/data/minecraft/tags/fluids/water.json)). They do that because many parts of of MC are hardcoded to assume that water is the only fluid with certain properties, e.g. you'll notice that IEs fluid do not push you around. The check for "is this water" is the same in both cases (recipes and pushing the player around), so there's not much that can be done about this from the perspective of a mod. This needs to be fixed in Forge, and someone (I think KnightMiner from Tinkers Construct) is working on it, but it's a rather large and complex task, so don't expect a fix in Forge too soon.
