### ISSUE TITLE
Engineer's Workbench messes up inventory

### ISSUE THREAD

**Issue by Bricktricker** [BluSunrize/ImmersiveEngineering#4724]
### Description of the issue:
I have a dedicated server with 5 mods installed: Apotheosis, Farmers Delight, Immersive Engineering and placebo. Every time I interact with the Engineer's Workbench and place a blueprint (testet with common projectiles) into the left slot the inventory of the player gets shuffeld and some items are dublicated. Opening a chest afterwards reverts the inventory back.
Removing any mod other than Immersive Engineering fixes this issue.

Opening the workbench:
![workbench-inventory](https://user-images.githubusercontent.com/30354257/111498159-01a34280-8742-11eb-93b8-178f34086156.png)

Opening a chest afterwards:
![chest-inventory](https://user-images.githubusercontent.com/30354257/111498282-1b448a00-8742-11eb-91d2-be86ccffa52c.png)

### Versions & Modlist
Minecraft: 1.16.5
Forge: 36.0.43
IE: 4.2.4-134
Apotheosis: 1.16.3-4.4.1
Placebo: 1.16.4-4.4.1
FarmersDelight: 1.16.3-0.3.2

### Logs
client.debug.log and server.debug.log: https://gist.github.com/Bricktricker/116fcbf6d5dd0770409e63eb9210f9ff

**Comment by BluSunrize** [comment]
So removing Apotheosis or placebo fixes the isue? O_o

**Comment by Bricktricker** [comment]
Either removing framers Delight, Apotheosis or Apotheosis and placebo fixes the issue. Only removing placeo is not possible because Apotheosis has a dependency on placebo.

**Comment by Drakoflame** [comment]
I know this is an old issue, but I'm coming here to report that I believe Placebo is the issue, but only in multiplayer. A friend and I are playing with the Engineers Life 2 modpack, and when I connect to his world via LAN connection, the Engineers Workbench breaks (as Brickticker showed above) making it impossible for me to use the table, as well as most of the other interfaces either don't work, don't properly update animations, or need to be given a block update to make their models render properly (I experienced this issue with the iron pipes in single player as well). I went into a single player world, thinking that maybe it was because I had Optifine installed (which is known for causing every issue ever), but the workbench rendered properly in my singleplayer test just fine.

**Comment by merphle** [comment]
I also see this problem in an Engineer's Life 2 server (modpack v1.03; IE 1.16.5-4.2.4-134). Putting a blueprint into the workbench (a) causes player inventory & hotbar to all get visually rearranged (which reverts to original correct state after clicking on one of the items in player inv), and (b) doesn't update the UI to show which items can be crafted in the workbench. This makes it very difficult to progress, since we can't craft the metal press molds or other workbench-only items.

**Comment by merphle** [comment]
I tried disabling the FastWorkbenchMinusReplacement mod (client only first, then both server and client), but it didn't help.

I also tried disabling Placebo and ToastControl (which requires Placebo) in both server and client, but it also didn't help.

**Comment by merphle** [comment]
Someone on the Engineer's Life 2 Discord mentioned a workaround:

After booting the pack up, load into a local single-player world for a few seconds, then exit back to the main menu and connect to the multi-player server as normal.

Issues resolved in multiplayer by taking this workaround:
1) Engineer's Workbench messing up inventory when placing a blueprint into the appropriate slot.
2) Engineer's Workbench being unable to craft anything when placing a blueprint (the craftable items don't appear).
3) The Metal Press doesn't animate when pressing items (the piston doesn't plunge)
4) The Crusher doesn't make noise when crushing.

**Comment by merphle** [comment]
Upgrading the Engineer's Life 2 modpack to version 1.04, which includes IE v1.16.5-5.0.0-135, seems to have fixed the above issues.

**Comment by BluSunrize** [comment]
That's great to hear, I'll finally be able to close this then.
