### ISSUE TITLE
1.16.5-4.2.2-132 Garden Cloche not working consistently 

### ISSUE THREAD

**Issue by kadnkson** [BluSunrize/ImmersiveEngineering#4746]
The garden cloche sometimes works and at other times with identical set up does  nothing. including when the two are built next to each other

Curse Forge Minecolonies Official 1.16.5 v1.4 IE version 1.16.5-4.2.2-132
Also, please try testing an issue in a minimal instance, with just IE, Forge and maybe JEI. That makes elminating compat issues easier.

**Comment by BluSunrize** [comment]
Despite being told to use the issue template, you did in fact not.

**Comment by kadnkson** [comment]
I literally put the information in as I read the template?

**Comment by BluSunrize** [comment]
You deleted the template, instead of filling it out. In fact, you kept one of the instructions standing.
You did not provide screenshots.
You did not produce a debug crashlog.
You did not read the contribution guidelines.

"sometimes works and sometimes does nothing" is not in any way descriptive of your issue.
