### ISSUE TITLE
[Feature] Add support for Create to IE's Kinetic Dynamo

### ISSUE THREAD

**Issue by Slatebreaker** [BluSunrize/ImmersiveEngineering#4790]
Currently, there exists an emergent way to convery RF into Create's stress units (su): Hook up an external heater to a furnace, redstone power it to keep it permanently on, and hook up a flywheel from Create to that furnace.

![image](https://user-images.githubusercontent.com/69188984/115172417-94038100-a108-11eb-8381-48074d103dc0.png)

This allows us to power large mechanical Create contraptions with RF. However, there is no inverse; we can't take energy our Create contraptions produce and convert it into RF.

I propose utilising the kinetic dynamo to convert stress units into RF, allowing for a lot more creative forms of power generation. This would allow seamless transfer of mechanical energy into electric energy and vice-versa, without much work.

![image](https://user-images.githubusercontent.com/69188984/115172783-53f0ce00-a109-11eb-8237-c4c88c4ac8a7.png)

Here are some facts to consider:

* An external heater consumes 8RF/t and will single-handedly power a flywheel.
* Currently the flywheel handles 16,384su. *That is quite a lot.*
* This kinetic dynamo runs at a speed of 16 RPM.
* 1024su / 8RF/t = **128 su/RF/t**
* Therefore, the kinetic dynamo **should not produce more than 1/128 RF/t/su** or else it would be grounds for an infinite energy exploit. 

In terms of how much power the kinetic dynamo produces, the nature of Create is that the RF produced and stress produced would need to be proportional to the speed the shaft rotates. An example of a possible formula might be:

* **RF/t produced = speed/4**
* **stress imparted = speed*1024**

(This would give a power factor of 50%, and mean that without any speed modification, if you plugged a flywheel directly into a kinetic dynamo, it would use all 16,384 stress units and only produce 4su. These formulae should be tweaked to taste.)

Obviously, this is a very simplistic way for Create's and IE's energy systems to interact with each other, but it's fairly elegant.
As it currently stands, Create's machinery is ludicrously cheap to power with RF; that would have to be fixed on their end by nerfing the flywheel, but until then, the above formulae would allow for the mods to interact fairly with no additional blocks added.

**Comment by BluSunrize** [comment]
No. I do not want power conversion to Create. I have said this many times before.

Create has an awesome, unique energy concept. It benefits from being nothing like the other tech mods. It **does not need to be convertible**. Let Create be awesome on its own. ForgeEnergy does not make everything better. In the case of Create, I think it'd make it worse.

**Comment by BluSunrize** [comment]
Addendum:

The "exploit" of using the external heater to produce energy for Create is something I had pointed out to @simibubi ages ago, and encouraged them to disable it (by checking if the furnace is actually smelting stuff, instead of just being on). They are of course within their own right to not do so. But that does not change my stance that I will not support Create -> FE conversion on our end.

**Comment by Slatebreaker** [comment]
I guess I got caught up a bit in the moment of my idea; and now I realise that yeah, making Create support FE is not something IE should do at all; if that were to be implemented it should be done on Create's terms.

**Comment by mindforger** [comment]
>An external heater consumes 8RF/t and will single-handedly power a flywheel.
Currently the flywheel handles 16,384su. That is quite a lot.

since create uses a vanilla furnace to operate and produces this much SU i think this might be an balancing issue on their side because there are quite a few mods that would allow alternate (external) fuel sources that would make it OP pretty quick

this could easily be prevented on their side by using their own kind of furnace so the heater does not work on it

and correct me if i am wrong but technically i could power 5 flywheels off of one heater with only 8rf/t which would make it kinda ludicrous ?!

**Comment by SpottyTheTurtle** [comment]
There's an addon mod that allows for conversion between RF and SU, it's called "Create crafts and additions"

**Comment by Derpford** [comment]
So the Create 0.5 update has completely reworked the Furnace Engine; now it's the Steam Engine, a multiblock that requires multiple heat sources (*NOT* furnaces, but Blaze Burners, or Campfires for a reduced output). It still produces a hell of a lot of power, though.

In addition, Create Crafts and Additions appears to have dropped several features, mostly because the removal of the original Furnace Engine meant that several of their blocks stopped working. Also, CCA's implementation of SU->RF has been suffering from various bugs.

I think it's worth bringing IE/Create interop back up, in light of these changes. (I also kind of want to do a Create->IE tech progression, and would rather not wrangle CCA into the mix to get there.)

**Comment by BluSunrize** [comment]
I stand by my original point:

> Create has an awesome, unique energy concept. It benefits from being nothing like the other tech mods. It **does not need to be convertible**. Let Create be awesome on its own. ForgeEnergy does not make everything better. In the case of Create, I think it'd make it worse.

**Comment by SpottyTheTurtle** [comment]
I agree with Blu here, Create functions perfectly fine with it's own system of power, as do many other tech mods. There's no reason to make power from one mod and then use it to power another mod when A: the two aren't inherintly compatible and B: you can just, idk, follow the progression of the other mod, it's designed to work on its own, not rely on someone to patch in a conversion between it and another mod.

**Comment by Derpford** [comment]
I don't really like that Create has windmills and waterwheels, and IE has windmills and waterwheels, but neither of them are interoperable. I appreciate Create's power system! At the same time, I want to have a tech progression from the mechanical age to the electrical age, and I want to have a way to take my steam boiler automation and use it to power IE's crusher so that the ore output from my Create tunnel bore can be boosted even further. I know Create wasn't built with IE integration in mind, but that's the kind of modpack I feel like making.

**Comment by BluSunrize** [comment]
May I suggest learning to mod then, to make that compat yourself? =P
