### ISSUE TITLE
 game crash 

### ISSUE THREAD

**Issue by gagaos** [BluSunrize/ImmersiveEngineering#4806]
Hello my game crash with "Immersive Engineering" and "Immersive Petroleum" please help me.

my log:
https://paste.ee/p/k8F0L

**Comment by gagaos** [comment]
(I am using version 1.12.2)

**Comment by BluSunrize** [comment]
Support for 1.12 was canned over 10 months ago.

**Comment by gagaos** [comment]
Please i just want to have fun

**Comment by mindforger** [comment]
try with IE versions 81 up to 89 (last known 1.12) and see if one fixes it, i could not find the commit that fixed the issue but it was a forge compat issue and you either had to downgrade forge (dont know which versin since i could not find the original issue) which put you in trouble with AE2 or try to upgrade IE and hope it works :D

edit: also don't ask the author to support ages old mod versions please, he is working for free and wiht limited capacity, you can't expect him to support all versions at the same time

**Comment by gagaos** [comment]
**Thanks thanks**
