### ISSUE TITLE
[1.16] External heater accepts power from top only

### ISSUE THREAD

**Issue by DocterDum** [BluSunrize/ImmersiveEngineering#4843]
### Description of the issue:
Regardless of orientation, the external heater accepts power from top only.
Used Mekanism cables in screenshot as they show the issue clearer, but it occurs with LV connectors as well

### Versions & Modlist
Minecraft 1.16.5
Forge 36.1.4
ImmersiveEngineering-1.16.5-4.2.4-134

DW20 1.16 Pack v1.9.0

### Lastly (you may delete this from the report itself)
Issue occurs single-player, not open to LAN. Other scenarios untested.
Issue occurs with freshly crafted and placed external heater
Rotating with Immersive hammer or Crescent hammer does not fix
Using Mekanism cables or a flux point, it can be seen that the top is the only side that ever connects, and the heater only accepts power when rotated to face the top

![image](https://user-images.githubusercontent.com/7615222/120752248-b2a0c880-c54c-11eb-8677-6c90ad30bc85.png)

**Comment by mindforger** [comment]
>Used Mekanism cables in screenshot

you forgot the screenshot 

also your report is a little incomplete

>The easiest way to get these lists is a crashlog, you may force one with F3+C.

**Comment by DocterDum** [comment]
Edited to add the screenshot and logs attached below.

P.S. Might be worth editing that to say 'hold F3+C', just pressing does something completely different.

https://gist.github.com/DocterDum/b0dc7dcdabe6d964f9107586f1ad0803

**Comment by BluSunrize** [comment]
Can you please verify that this issue still exists when using Immersive Engineering 1.16.5-5.0.0 ?

**Comment by BluSunrize** [comment]
I presume given that you closed this, updating IE has fixed your issue?

**Comment by DocterDum** [comment]
No, I didn't try it, I simply disagree with the way you're handling issues. I believe that this will come down to a matter of opinion, I reported the issue so 'you can better your mod', not 'because I need the issue resolved' (aka a helpdesk). 

If this were a helpdesk and I was asking for a problem to be resolved, I'd happily provide x, y and z info and help out with troubleshooting, that would be fine because I'm asking something of you. 

But I don't think that's what issues are for, and that's not why I reported this. I reported the issue to (voluntarily) provide you information to improve your mod, and I'm then being asked to provide info in specific formats (See crash log section of 'new issue'), test things which you could have tested yourself, and reading things like 'IE and Forge versions are mandatory. *Note that saying "latest" is **not** valid.'. That just does not line up, it's like giving a beggar money and them then asking for more.

Even as a voluntary action, I could understand if I didn't provide enough information and you needed more, but I told you EXACTLY what the issue was, gave you the MC, Forge and IE versions, as well as a full mod list (DW20 1.16 Pack v1.9.0), and gave you a list of other things I'd tested to fix it. I've already gone out of my way to provide as much relevant information as I can, and instead of, 'thanks, we'll look into it' I get, 'Oh can you provide (irrelevant) crash logs' and 'Oh can you try a different version'.

Again, you're free to disagree with all this, your project, run things how you like, but I don't need a helpdesk...

**Comment by BluSunrize** [comment]
I'm glad to hear that you report issues voluntarily, because I don't think anyone would pay you for them.

Note that our development of this project is also entirely voluntary. I do this in my spare time, because it's fun and enjoyable to me. It gets considerably less fun when I have to deal with things like this.
Notably, I disagree with the comparisson of a beggar asking for money, because *we don't ask for issues*. They are things that basically everyone involved dislikes having to deal with, so being able to fix and close them quickly and efficiently is key.

And the person who can contribute to that the most is the person reporting! Because *you* have the issue. It's reproducible in your setup. You are our best chance at debugging it, because it's apparent on your end. That's why we rely on *your support* in helping figure this out. And that includes asking you to try it with a different version, as well as attempt to reproduce it with just IE installed.

So yeah, getting just ranted at because we ask for more information on this issue feels pretty bad! Ya hate to see it. Have a good day, and please be nicer to mod developers in the future!
