### ISSUE TITLE
[Suggestion] Snowballs become valid railgun ammo

### ISSUE THREAD

**Issue by atenfyr** [BluSunrize/ImmersiveEngineering#4850]
Railguns can use ender pearls as ammo, and can fire some other very unconventional ammunition such as blaze rods and tridents, so why not snowballs/eggs, just for fun? It'd be pretty funny to have a "snowball fight" using the railgun.

**Comment by BluSunrize** [comment]
Snowball wouldn't hold their shape as well as a blazerod or a pearl. That's the "science" reason.

The pratical reason is that snowballs are very boring projectiles that basically don't have any unique property (except being able to damage blazes). There's no excitement or benefit from launching them with a railgun, which is why I'm not interested in doing it.
