### ISSUE TITLE
Unpacker doesn't unpack clay or sandstone

### ISSUE THREAD

**Issue by charliegreen** [BluSunrize/ImmersiveEngineering#4939]
### Description of the issue:
Clay or sandstone blocks simply do not enter a metal press with the unpacker mold attached, despite being 2x2 storage blocks. The manual suggests that the unpacker should be able to unpack these items, and without this behavior it's unclear (to me at least) how to automatically create clay balls from clay.

### Versions & Modlist
These are the mods I'm using:
```
ImmersiveEngineering-1.16.5-5.0.2-137.jar
ImmersivePetroleum-1.16.5-3.3.0-5.jar
jei-1.16.5-7.7.1.118.jar
```
With forge 36.1.0 and Minecraft 1.16.5.

**Comment by BluSunrize** [comment]
The machine can only unpack things that actually have an uncrafting recipe.
You can put a block of iron in a crafting table, and it will make iron ingots.
You can *not* put a block of clay in the table and get 4 clay balls out. Because vanilla does not add a recipe for this.

The packing and unpacking molds base themselves on these recipes.
