### ISSUE TITLE
[1.17.1] Can't equip or attach Capacitor Backpack

### ISSUE THREAD

**Issue by Sheenus** [BluSunrize/ImmersiveEngineering#4958]
### Description of the issue:
What it says on the tin: Can neither equip the Capacitor Backpack in any armor slot, nor attach it to any chestpiece using the crafting GUI. 

### Crashlog:
This issue did not generate a crashlog.

### Versions & Modlist
Minecraft 1.17.1
Forge 37.0.44
_MixinBootstrap-1.1.0
ImmersiveEngineering-1.17.1-5.0.2-pre.138
jei-1.17.1-8.0.0.14
journeymap-1.17.1-5.7.3rc3

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/cd43da0fc0a2725e70e01c3d692bfaeb00d47582 fixes the IE side of the issue. You can manually place the backpack in the chest slot. Other methods of equipping it (e.g. shift-click) won't work due to a missing Forge patch, so I'll leave this open until that is re-added.
