### ISSUE TITLE
The server crashed due to multiple blocks. Procedure

### ISSUE THREAD

**Issue by Nqwq** [BluSunrize/ImmersiveEngineering#5022]
Recently, when I played a server with Immersive Engineering, the multi-block structure of this mod frequently crashed the server, which prevented us from playing normally. The reason is that the server crashed due to the cross-block structure. It is said that this has been a bug for a long time, and I hope the author can fix this bug. According to the response of the server administrator, there is no error report, so I cannot provide the error report. I am very sorry, but I still hope you can fix this bug.

**Comment by BluSunrize** [comment]
No. We can't help.

Without a crashlog, there is literally nothing we can do to investigate this issue. We need the information from crashlogs to figure out what part of the code went wrong. You didn't even provide us with a version number!

And if the server crashed there *has* to be a log. That's how Minecraft works, it generates logs when it crashes. If your server admin can't find it, then that's on them.

Please, the next time you want to report an issue:
1) get the log file from the server
2) actually respect the issue template. Because you *completely* ignored it, which means we lack even the most basic information, such as version numbers.
