### ISSUE TITLE
[1.16.5] NoSuchMethodError in IE creative tab

### ISSUE THREAD

**Issue by TwistedGate** [BluSunrize/ImmersiveEngineering#5026]
### Description of the issue:
Opened IEs to get some stuff for testing, scrolled down all the way and got the crash below

### Crashlog:
https://gist.github.com/TwistedGate/594de67758a21b7cbd44c6ada5222717

### Versions & Modlist
Forge: `1.16.5-36.2.0`
IE: `1.16.5-5.0.4-139`
(in ip-dev, no sign of anything related to ip tho)

**Comment by malte0811** [comment]
I was going to say that I wasn't able to reproduce this in IP dev… And then I remembered about binpatching vs source patching. Because FG has two pretty much *completly independent* ways of getting Forge into MC. One patches the class files (as binary files, this is what happens in "prod" as well), one patches the decompiled sources (using the files you see in the Forge git repo). And the method causing the NSME has a tendency to have different behavior in those two modes. Everything works fine when using binpatched MC, but source-patched MC isn't happy about it at all. The good news here is that it should only affect addon development, so we don't need to get a CF build out for it; it will probably still be "fun" to fix.

Extra bit of fun about FG: It is not designed to allow the user to pick whether source- or binpatching is used. If you open the project in an IDE it will source patch, and there's nothing you can do about that. If you just launch from a command line it will binpatch, and the only way to force it to source-patch is to run the `eclipse` task (which one wouldn't guess without being told about it). And once you have source patched binaries, FG won't go back to binpatching unless you delete them again. All without giving any indication of what it's doing…
