### ISSUE TITLE
[Suggestion] Structural Engineer trades

### ISSUE THREAD

**Issue by Zahkriiven** [BluSunrize/ImmersiveEngineering#5080]
Hello!
I've been using the villagers for some of their useful trades and I've noticed the structural engineer is missing master level trades and has only 1 expert trade. Other villagers except the outfitter have more trades. So I thought on some possible trades to fill the missing ones.
Level 3
- 1 emerald for 4-8 concrete. The current concrete trade feels expensive as its not that hard to make. Maybe reduce the scaffolding to compensate, 4-8 steel scaffolding is pretty cheap in my opinion.
Level 4
- 1 emerald for 2-3 wooden post
- 1 emerald for 1-2 steel post or 1-3 aluminum post
- 2 steel or aluminum wallmount for 1 emerald
Level 5r
- 1 emerald for 2-4 structural cable connector
- 1 emerald for 2-4 steel or aluminum structural arm
- Ore vein map (moved from level 4)

I don't want to step over game design decisions but I felt that their are missing due to lack of attention. of course ignore this if its intended as it is. I use the structural engineer as source of build materials to have more time building and less farming, specially scaffolding. 

PS: the slag trade isn't more appropriate for the machinist as they have the coal coke trade?

As always, thank you for the time dedicated to the mod!

~ Zahkriiven

**Comment by BluSunrize** [comment]
Thank you for the comprehensive post!

I took quite a few of these into consideration and redesigned the trades for the engineer. They no longer deal with slag, but instead posts. The orevein map has indeed been moved to expert tier.

I opted out of steel & alu structural arms / slopes for expert trades, because the game picks 2 of the available options which in testing lead to having them accept the two arms, but not sell a map. I want the orevein map to be guaranteed. Instead they will accept leaded concrete on expert, giving that block another reason for existing =P
