### ISSUE TITLE
[suggestion] Speed Upgrades for Crusher

### ISSUE THREAD

**Issue by mikeloeven** [BluSunrize/ImmersiveEngineering#511]
One thing about the crusher is that compared to other ore processing blocks its rather slow possible due to it's power input being limited to 80 RF/T.

I would like to see upgrades (preferably stackable) that drastically improve its operating speed by allowing it to utilize high energy RF networks 500 - 1000 rf/t

Generally speaking though one would have expected a massive multi block crusher machine to perform faster (and use more power) than a moderator upgraded single block ore processor such as the TE pulverizer or IC2 macerator due to its sheer size and power

**Comment by theunkn0wn1** [comment]
I second this idea.. IE's crusher has the exact same problem I have with the Railcraft Rock Crusher, its too darn slow and impractical given its price tag! I would much rather use TE for my ore-crushing abilities because it is both faster and it is can be upgraded. We, as most players, need reason beyond "it looks cool" to use the Crusher as it currently exists for the same reason I don't the rock crusher.

If you don't want to change the existing crusher.. please add an Industrial Crusher that is much more expensive to build and maintain that will allow for better ore processing rates for us powercreeps out there :3

IE's Crusher is a relativity massive, and cool looking, means for processing ores and metals alike, yet it is slower and more expensive than TE for the same functionality. For huge, powerful blades that can crush anything that it is fed, including animals and players, it just breaks the immersion that it takes so darn long to crush anything of use....

**Comment by cobra** [comment]
You can already speed it up via the config. The recipes define the total energy needed and the speed value taken from the config defines how much RF is used per tick. Setting this to 1000 makes it crush things really damn fast. Setting it even high should allow for up to one item per tick (I don't know if it can really do that or is limited to one item per two ticks, but that doesn't really matter).

I still wouldn't be opposed to upgrades. I've been thinking about how to upgrade the arc furnace to auto-balance the inputs to allow parallel processing with automatic inputs of less than a lot of stacks. Technically, this is rather simple, but I'm unsure about the upgrade mechanism. Have an upgrade slot like TE/Mekanism? Right-clicking the multiblock with an upgrade item (like Mekanism's factory upgrades)? Placing an additional block performing the upgrade on top of the multiblock?

**Comment by theunkn0wn1** [comment]
Changing configs is one thing, the defaults are another.

The best way, IMO, is to add onto the existing mb. Perhaps by making the
device bigger, or at least more expensive should suffice. TE`s upgrade
system just does not fit well with the multi block structures. Perhaps by
expanding the face(s) that accepts power the crusher can support higher
voltages, by expanding the input face they would increase items processed
per tick. So on, so forth.

**Comment by cobra** [comment]
Expanding the multiblock would need new or more dynamic models, this is not going to be easy.

**Comment by theunkn0wn1** [comment]
Yea.. Was just a thought. Though would look even more impressive in MP
builds.  I do like your idea about replacing certain blocks, as it sounds
much easier to implement though that does limit just how creative upgrades
can get.

**Comment by mindforger** [comment]
just as an idea, how about an additional (moderately expensive) upgrade block, that connects to the crusher like a fence connects to an solid wall, something like the upgrades for ender quarry

**Comment by VermillionX** [comment]
You're aware that the Crusher operates at 4x the speed of a Pulverizer, right? With speed augments on the pulverizer to match the crusher's speed it consumes 320 RF/t as opposed to the Crusher's 80 RF/t.

**Comment by XFactHD** [comment]
@theunkn0n1 if you want an industrial crusher, you could suggest it to UnwrittenFun (ImmersiveIntegration), he has already added an industrial coke oven.

**Comment by BluSunrize** [comment]
Yeah, try listening to @VermillionX. The crusher might seem slow to you, but
1) I've already buffed it for 0.6
2) It has an unlimited inventory, so you can keep chucking into it
3) For gods sake, stop comparing it to TE. Just because Lemming chose to make his pulverizer out of line OP does not mean I have to compete with it. IE's goal is not to be like the other RF mods. I'm trying to do things /right/ that is why the crusher is expensive as it is. OreDoubling is supposed to a challenge. but TE and EIO have spoiled the users.

**Comment by VermillionX** [comment]
That's not to say that there couldn't be other upgrades that do something other than the generic power cost/speed/boosted chance things.
Maybe switching out a part of the multiblock for a specialized hatch block as an alternate/secondary output for the machine; or a fluid tank attachment for watering the crusher's grinding wheels that (if supplied with water) yields sand/gravel/goodies as an output for grinding ore. Something different like that...

**Comment by mikeloeven** [comment]
I never asked the crusher to compete with TE and be buffed out of the box i merely asked for the opportunity to install upgrades down the line.

**Comment by theunkn0wn1** [comment]
@BluSunrize, I understand ore-doubling is supposed to be a challenge, but how exactly is a slow ore-doubler supposed to be challenging? I tested the crusher and it feels just as slow as in 0.5 and earlier, about 4 seconds per item for most items@ 20 TPS, i physically timed a handful of vanilla and IE items from the moment the item entered to the moment the output came out. 

you need not compete with TE and the others, sorry for bringing them up again, all we ask for is the means to make your machines all the more usable for the endgame. some of the ideas brought up by @VermillionX would well fit IE. I welcome the idea of adding-onto my machines, expanding their MB structure in the process/replacing parts thereof, to make a more expensive and more powerful machine.

**Comment by cobra** [comment]
Did you check your config file? It might still have the old value.

**Comment by theunkn0wn1** [comment]
Il flush my configs and retest, that might be the case.. il update this once that is done..

**Comment by VermillionX** [comment]
One size doesn't need to fit all. It just needs to fit IE, which it does.
The "challenge" that you can't see comes from if, by using other mods, you need more speed; you solve the problem by making another Crusher. Now you have the challenge of finding the right space for it, enough power so that both machines are operating at full power, ensuring the outputs don't overflow and that you have enough generators to supply the power.
Of course, if you use certain mods that take away all those problems, you're removing your own challenge.

**Comment by theunkn0wn1** [comment]
If it fits as is, then why do we want upgrades at all? It appears that I have become blind of the point as i have 'been spoiled' by mods that remove that challenge, and thus lost perspective as to what it is we seek. Upgrades that improve speed are a luxury that I can live without, upgrades that improve functionality, such as ore recovery, is what I seek. I simply want the crusher to be worth while over the usage of other mods, give me reason to apply the challenges that IE brings rather than shelter in the comfort of the others. 

I am in love with the power transportation system IE brings, though I cannot fully engage with its ore refining system due to lack of incentive. While I know the power transport system can be upgraded, that gives me incentive to use the wires, yet the ore processing just has no tangible room for upgrading. sure  I could always build more Crushers, but a Crusher is just a Crusher, nothing more. With Power, I start at LV knowing its crappy but I know that eventually I reach HV eventually, set it as a goal i strive to achieve. The crushers just don't give the same feel, its just the same thing over and over, a repetitive grind rather than a engaging mechanic.

Immersive Engineering all ready has two tiers of machinery, yet these two tiers seem quite divergent from one another, why can we not have blending of the two? If we had upgrades to the Crusher and other tier 1 machines, we could approach Tier 2 by the time we reached mid/endgame. It would provide some of the vertical progression many of us seek. These upgrades need not be just speed, but add extra functionality, such as secondary outputs or multiple items at a time. We could build huge, expensively elaborate machines to eat our ore and feel that we are better off than that dinky stock crusher our friends have in their base.

**Comment by VermillionX** [comment]
Well that's more than *just* a speed upgrade item like this thread was about.
I recommend you make a dedicated upgrade suggestion with ideas on how to make a unique, engaging and challenging means of upgrading machines.

**Comment by BluSunrize** [comment]
Alright, this discussion has gone on long enough, so to save yourselves the trouble of theorizing: I will not add the option to add speedupgrades to the crusher. Nor do I plan to add an upgrade system for multiblocks in general.
