### ISSUE TITLE
Diesel Generator producing unexpected amounts of power

### ISSUE THREAD

**Issue by MuteTiefling** [BluSunrize/ImmersiveEngineering#5128]
### Description of the issue:
BioDiesel fuel values don't appear to be working as expected.

Diesel gen config: 
```
#The Flux per tick that the Diesel Generator will output. The burn time of the fuel determines the total output
#Range: > 0
dieselGen_output = 16384
```

Base burn rate for biodiesel is 250. I'm assuming this is ticks. 
The expected output of these settings from one bucket is 4,096,000 FE. 
Actual output from one bucket is 2,048,000 FE.

When overriding the burn time with the new data packs, I still get the same output. Burn time of 1220 should result in about 20M FE. I still get 2.04M FE, however.

Further, it appears to be generating infinite energy off of other fuels added via data pack. 

```
{
    "type": "immersiveengineering:generator_fuel",
    "fluidTag": "forge:kerosene",
    "burnTime": 1342
}
```

Sample data pack above. It accepts kerosene, but I'd expect an output of about 22M FE from a bucket. Instead I've gotten about 300M FE while writing this up and it shows no sign of stopping. 

### Crashlog:
No crash

### Versions & Modlist
IE: ImmersiveEngineering-1.16.5-5.0.6-141.jar
Forge: 36.2.20
Pneumaticcraft: pneumaticcraft-repressurized-1.16.5-2.14.6-277

Minimal instance. Needed some extra fuels to test.

**Comment by MuteTiefling** [comment]
Quick update. Came back after leaving it running over night and had 11 billion FE stored and it's still running from that one bucket :D

**Comment by malte0811** [comment]
The second part (your datapack-added kersone producing infinite energy) is unfortunately kind of expected: The diesel generator works by consuming `floor(1000 / burnTime)` mB of fuel per tick, which is 0 if you specify a burntime greater than 1000.

The first part is also working fine on the latest 1.16.5 commit, but that includes a fix for the generator. I haven't tested on the CF build, but make sure that the output can actually accept 16k FE/t; otherwise the remainder will be lost. With default IE configs there isn't a way to accept that much energy in 3 block faces (max with default cconfigs is 4k per face, so 12k on 3 faces).
