### ISSUE TITLE
[1.16.5] Addin/removing veins from excevator

### ISSUE THREAD

**Issue by drago87** [BluSunrize/ImmersiveEngineering#5145]
Is it possible in minecraft 1.16.5 to add/remove veins from the exavetor with crafttweaker or kubejs or some outher way? 
And if so can you pint me in the right direction?

**Comment by BluSunrize** [comment]
Our veins are done like vanilla recipes, so you can use a datapack to add, replace or disable them.

If you know how vanilla datapacks work, doing compat for IE is very easy, you just match our folder structure `data/immersiveengineering/recipes/mineral` and you can throw replacement files there.

The original files can be viewed here:
https://github.com/BluSunrize/ImmersiveEngineering/tree/1.16.5/src/generated/resources/data/immersiveengineering/recipes/mineral

**Comment by drago87** [comment]
Never used datapacks before and cant seem to get it to work. I'm using multimc
I hava made a file named diamond.json in
`.minecraft/saves/[save name]/data/immersiveengineering/recipes/mineral/diamond.json`
I have also tried it in the `[save name]/datapacks`
And the content of the json file is
`{
  "type": "immersiveengineering:mineral_mix",
  "ores": [
    {
      "chance": 0.6,
      "output": {
        "item": "minecraft:gravel"
      }
    },
    {
      "chance": 0.4,
      "output": {
        "item": "minecraft:diamond_ore"
      }
    }
  ],
  "dimensions": [
    "minecraft:overworld"
  ],
  "weight": 8,
  "fail_chance": 0.2,
  "sample_background": "minecraft:netherrack"
}`
atleast i cant find it in the ingame manual or if i run the `/ie mineral list`

**Comment by BluSunrize** [comment]
Yeah of course that isn't gonna work, because that's not the correct file path at all. Datapacks go into `saves/(world)/datapacks`, are a subfolder or zip file there, which *must* contain a `pack.mcmeta` file and then a `data` subfolder which is where your filepath should continue.

But it's not our job to teach you how a vanilla datapack works. Minecraft has a wiki for that:

https://minecraft.fandom.com/wiki/Data_pack
