### ISSUE TITLE
[0.6.0-pre] Can't craft Sheet Metal Block

### ISSUE THREAD

**Issue by mmermerkaya** [BluSunrize/ImmersiveEngineering#515]
The crafting recipe for sheet metal block produces 4 iron grits instead.

It works as expected if I set "Disable Hammer Crushing" to true.

**Comment by VermillionX** [comment]
Might be better if the recipe was changed to require the Engineer's Workbench and Blueprints instead of using the Normal crafting table. It would prevent conflicts in and out of IE.
I wish more recipes were made via the Engineer's Workbench. It seems a bit odd to craft some of the more technical components by hand. Though that hasn't stopped other mods.
