### ISSUE TITLE
1.18.1 - Can't see crafting Complex Machines in The Manual

### ISSUE THREAD

**Issue by Whekainl** [BluSunrize/ImmersiveEngineering#5161]
Due to the lack of recipes for complex cars on the Internet for version 1.18.1 - I cannot craft the things I need. I play on the Russian version of the mod.
Version 1.18.1
I tried to change the graphics settings, as well as disable mods
[Debug](https://pastebin.com/pqs7TsYZ)
[Latest](https://pastebin.com/E5C5NhBr)
![2022-01-02_21 38 26](https://user-images.githubusercontent.com/72886938/147883765-e01a4721-6ca3-408e-9ab4-c5e4ee0d78b9.png)
![2022-01-02_21 39 46](https://user-images.githubusercontent.com/72886938/147883767-fd4fa570-3a1f-4961-89f6-2298cefa9e6f.png)
![image](https://user-images.githubusercontent.com/72886938/147883757-9d7dec66-e0b5-4e91-96df-b140cca821cb.png)

**Comment by FynnWaelsing** [comment]
I am having this same bug as well, and I have narrowed down a pair of mods that cause the crafting of complex machines to not work in the Engineering Manual:

Starlight (version: starlight-1.0.1+forge.36a1c6c)
Radium (version: radium-0.7.7g)

I have left bug reports on the Githubs for these two mods already. Since these two are just one of many Forge ports of jellysquid's mods, I imagine that the others may cause this same issue. Just wanted to update this so y'all are aware.
