### ISSUE TITLE
[1.18.1] Assembler can craft Bucket of Redstone Acid without bucket

### ISSUE THREAD

**Issue by HeadlessClient** [BluSunrize/ImmersiveEngineering#5183]
The assembler will craft Bucket of Redstone Acid even when no bucket of water, or bucket is in its inventory.

Causes bucket duping
![2022-01-14_17 55 19](https://user-images.githubusercontent.com/97768634/149599666-bf036a1e-f129-4e19-849d-df6923d1257b.png)
![2022-01-14_17 55 25](https://user-images.githubusercontent.com/97768634/149599668-dd331cb8-1ed3-4034-bb6d-213833bf293b.png)

**Comment by BluSunrize** [comment]
@malte0811 I need your feedback here.

How do we handle a recipe where the output has a container item and an input does as well? Is there a reliable way for us to figure that out?
Alternatively, do we add some option that prevents handling of special ingredients for assembler recipes?

**Comment by malte0811** [comment]
We can't really detect if a recipe is going to do this (since MC doesn't natively support it), but I think it's relatively safe to disable "direct" fluid support for recipe classes overriding `getRemainingItems`. That will take a little bit of reflection hackery, but I don't think there's any other way to fix this.

**Comment by BluSunrize** [comment]
Can I assign you to this to make that happen?

**Comment by BluSunrize** [comment]
I would not class it as high-prio

**Comment by BluSunrize** [comment]
Fixed by #5404
