### ISSUE TITLE
1.16.5 Dupe using create. 

### ISSUE THREAD

**Issue by BazZziliuS** [BluSunrize/ImmersiveEngineering#5203]
Dupe using create. When you break the disconnected blocks, several pieces fall

https://imgur.com/cQK148N

List of items that can be multiplied
<item:immersiveengineering:blastfurnace_preheater>
<item:immersiveengineering:turret_gun>
<item:immersiveengineering:cloche>
<item:immersiveengineering:sample_drill>
<item:immersiveengineering:turret_chem>
<item:immersiveengineering:fluid_pump>

Full list of mods
https://pastebin.com/NW0zWPMe

Forge - 36.2.23
ImmersiveEngineering-1.16.5-5.0.7-143

**Comment by BluSunrize** [comment]
uuhh.

Hey @malte0811, aren't all our multiblocks marked as immovable by pistons? Is Create maybe ignoring that very important limitation?

**Comment by malte0811** [comment]
I'm looking into it, it looks like they're using [their own tag](https://github.com/Creators-of-Create/Create/blob/dfe2f41b59d91bd9bbf11fb6bca7b260dc1c47fe/src/main/resources/data/create/tags/blocks/non_movable.json) instead of the ones that I thought were used universally at this point ([these](https://github.com/BluSunrize/ImmersiveEngineering/tree/a7e9124380d4170956283ca10c9d1ead9cce2726/src/generated/resources/data/forge/tags/tile_entity_types)).

CC @simibubi: Is there any reason for that? I'd rather not add a separate tag for every mod that can move BEs.

**Comment by BluSunrize** [comment]
This is on Create to fix, tbh. There are well established tags to prevent blocks from moving and if Create doesn't respect those, that's on their end.
