### ISSUE TITLE
[1.16.5] Minor Power Tool hiccups

### ISSUE THREAD

**Issue by DragonAce765** [BluSunrize/ImmersiveEngineering#5212]
These may not be bugs and if they are not I apologize for wasting your time.

Firstly, the mining drill works without the pressure tank when submerged in lava.

Second, the Buzzsaw doesn't recognize vanilla Nether trees, most likely since they have wart blocks instead of leaves, which brings me to my third point: The Buzzsaw won't chop down trees that have no leaves covering the top surface of the wood. This one is the one I'm least certain is a bug because it's probably implemented that way to avoid accidentally tearing down your build.

**Comment by BluSunrize** [comment]
1. That's because mining is only slowed down in water, not in lava. If you use a pickaxe, its speed while submerged in lava is the same.

3. Yes, the buzzsaw only detects something as a tree if it ends in a leaf. This *does* work diagonally (to a degree) in order to work for Acacia trees for instance.
We use tags to identify leaves - any leaves, even modded ones, should be in the `minecraft:leaves` tag. The wart blocks that act as "leaves" for nether trees (warped wart and nether wart) do not have a tag, so we would have to specifically hardcode stuff to make the buzzsaw work on them. And then that wouldn't extend to any mod that adds new kinds of giant fungi. So yeah, that's why it's not a thing.

**Comment by DragonAce765** [comment]
I actually didn't know that about pickaxes, thanks! Also good to know there's no good way to add compatibility for the nether trees, which stinks, but is understandable.
