### ISSUE TITLE
Inventory Sorter with Engineer's Toolbox Voids Items

### ISSUE THREAD

**Issue by HenryMaxler** [BluSunrize/ImmersiveEngineering#5235]
### Description of the issue:
Using middle click when the toolbox is full of bottom row items voids all the tools (using Inventory Sorter mod)

<img width="374" alt="image" src="https://user-images.githubusercontent.com/75149748/157931715-34a71be7-4d68-4513-9a60-6837d752fbb4.png">
<img width="358" alt="image" src="https://user-images.githubusercontent.com/75149748/157931808-b9a42b5c-dff9-447e-ae09-ccd0232af076.png">

### Versions & Modlist
IE: 1.16.5-5.0.7-143
Forge: 36.2.30
Inventory Sorter: 1.16.1-18.1.0

**Comment by malte0811** [comment]
Blocked by cpw/inventorysorter#119. AFAICT InvSorter believes that it should be able to freely swap around stacks since all slots are using the same `Slot` implementation, but that is simply not true in true in this case and IMO a bug in InventorySorter (though probably not easily fixable). The easiest solution would have been to mark these slot implementations as invalid for sorting using IMC, but that's broken as described in the linked issue.

**Comment by BluSunrize** [comment]
Closing this because support for 1.16.5 has ended
