### ISSUE TITLE
Enhancement: Create Default Tag to add to INVALID_RECYCLING_OUTPUTS

### ISSUE THREAD

**Issue by SkySom** [BluSunrize/ImmersiveEngineering#5285]
The Recycling API currently has the ability to use Predicates to invalidated a Recipe for output, but adding a simple Tag should make it easier for Users to remove Recycling recipes with Datapacks.

**Comment by BluSunrize** [comment]
Right so, having just researched this, there is a misunderstand / poor labeling here.

`INVALID_RECYCLING_OUTPUTS` is a list of predicates that prevents recycling from *propagating* through an item. So that something like a hammer being used to craft a plate isn't being lumped in with the outputs. Or else a copper plate would recycle into 1 copper ingot and 2 iron ingots.

We do not currently have a feature of "these items are invalid as recyling inputs", but this issue seems like a good opportunity to create such a thing.

**Comment by BluSunrize** [comment]
This is my first pitch at it. Three new tags to allow users to interact with recycling.

We'll have to see how it plays out.

**Comment by BluSunrize** [comment]
This has been in for a while now, so I'll close this.
