### ISSUE TITLE
Empty Array Crash

### ISSUE THREAD

**Issue by Moobien** [BluSunrize/ImmersiveEngineering#5290]
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.12] Capacitor Interaction Crash"

### Description of the issue:
Describe what happens, how it affects your game/gameplay and provide screenshots where possible.
as of a few days ago I have been unable to join any SP worlds I have made while I have IE installed/enabled.  Game loads fine but I CTD on world load. 

Side note. When this crash happens and I have Pretty Beaches, Cooking for Blockheads, Inventory Essentials and Balm installed as well as IE they crash too, but games load fine with those mods enabled and IE disabled.

### Crashlog:
If your Minecraft instance has crashed, a file will have been generated in the folder `crash-reports` of your minecraft folder. To understand what has happened, we need to know the content of that file. But please don't just put it directly in your report (that makes it hard to read), upload it to a site like [pastebin](http://pastebin.com) or [gist](http://gist.github.com) and put a link in the actuall bug report.

https://gist.github.com/Moobien/d24577633b02b1e7e03f3a882154ed9a

### Versions & Modlist
IE and Forge versions are mandatory. *Note that saying "latest" is **not** valid. Always give the proper version number*
Other mods should be listed (with their versions) in a [pastebin](http://pastebin.com) or [gist](http://gist.github.com) upload. The easiest way to get these lists is a crashlog, you may force one with F3+C.
If your game crashed (see above) you may omit the modlist, but IE and Forge version would still be nice.

Also, please try testing an issue in a minimal instance, with just IE, Forge and maybe JEI. That makes elminating compat issues easier.

IE: 1.18.2-8.0.1-147
Forge: 40.1.0 and up

### Lastly (you may delete this from the report itself)
Please, for the love of all that is voxelbased, **read the contribution guidelines. They are linked to the right in the message box.**
When reporting issues, these are crucial, and the team withholds the right to close an issue for the plain stupidity of not reading and adhering to them.

Thank you for reporting issues, without people reporting them, they wouldn't get fixed. You're helping contribute to this mod and that is much appreciated <3

**Comment by Lucent-Spire** [comment]
Did some more looking, because I'm coming up on this error too. 
If Cooking for Blockheads is removed, the crash shifts to something relating to quark oddity's magnet blocks; if that feature is disabled it becomes a more specific "invalid player data" error that happens whenever a new world is created or an existing one is loaded into. (see crashlog) 

https://pastebin.com/Un47Mfeu

However I can't seem to isolate which mod is also causing this, even comparing our mod lists. If it's just IE and forge, it doesn't seem to happen, and despite running through the mods 1by1 I can't find a specific cause. Apologies!

EDIT: this is less helpful than I'd like, but it didn't seem to happen on forge 40.1.15. Possibly related to the step height attribute change?

EDIT EDIT: Same mod list works fine on .15. Looks like it's related to the step height change?

**Comment by malte0811** [comment]
This is a bug in JAOPCA, see TheLMiffy1111/JAOPCA#229.

**Comment by Moobien** [comment]
Thank you for working out the culprit!

**Comment by AmmoniumX** [comment]
Hi, not sure why this was closed since the root issue is still there, when there's an empty item tag or just a malformed recipe with an empty output, IE's Arc Furnace recipe checker will cause the world to crash. While yes, you could pin the blame on whatever mod has the malformed recipe or tag, this is still not ideal, _especially_ when you are dealing with a large modpack where the crash only shows the final cause of the crash being IE. I think IE just needs to add a failsafe on their recipe handler to make sure that either the item or the tag they are looking for is not empty.
Crash log: https://pastebin.com/KNrXAnDY
