### ISSUE TITLE
[1.18.2] Crusher Working Inconsistently

### ISSUE THREAD

**Issue by joycert** [BluSunrize/ImmersiveEngineering#5322]
When I feed ore into the crusher it does not drop 2 powders for each ore, it randomly drops 1 or 2. Overall average seems to be about 1.3 powder per ore. This makes my gameplay sad. The animation, sound, power consumption work as normal.

IE version 1.18.2, Forge version 1.18.4, 40.1.0
No other mods.

I could not find the contribution guidelines, I hope this conforms to them. Thank you for all the work you do on the mod, it's super cool!

**Comment by TeamSpen210** [comment]
This is intentional behaviour. After 1.17 added Raw Ore drops (which can be increased via the Fortune enchantment), it was decided to change the mechanics to fit. Crushing Raw Ore gives 1.3 ingots on average, while Crushing Silk Touch-ed full ore blocks gives 2 ingots, or you can use the Arc Furnace to directly get the same. Alternatively you can use Fortune III to get up to 4 Raw Ore per block, but that's incompatible with the Mining Drill.

**Comment by BluSunrize** [comment]
Yeah what Spen said. This is intentional gameplay design, and you can literally see that the secondary output has a chance if you look at the recipe in JEI.

**Comment by SergioInToronto** [comment]
The description says, "Crushing an ore is an effective way of increasing their yield, for each ore creates two dusts which you can then smelt." I think we need to update the description.

Where did 1.3 come from? Seems low given the complexity of building the crusher.
