### ISSUE TITLE
[Suggestion] Toolbox Tool Additions

### ISSUE THREAD

**Issue by voidsong-dragonfly** [BluSunrize/ImmersiveEngineering#5359]
### Description of the feature:
The toolbox has _some_ things as tools, but it is missing quite a number of things I would consider tools:
![image](https://user-images.githubusercontent.com/40431605/179374772-1d3a169e-e648-434c-9921-ed767fb1b49f.png)

#### The Two Big Tags:
`forge:tools/wrench` - Gets Most:tm: modded wrenches, including PNC's, AE2's, and Supplementaries' 
`forge:buckets/empty` - Gets buckets, and hopefully other (well-made) ones. For Some Reason, not Ceramics or Wooden Bucket

#### The Vanilla Items
- [x] Spyglass
- [x] Clock
- [x] Compass
- [ ] Bundle
- [x] Fishing Rod
- [x] Flint And Steel
- [ ] Carrot On A Stick & Warped Fungus On A Stick (?)
- [ ] Nametags (?)

#### The Immersive Engineering Items
- [x] Engineer's Manual
- [ ] Jerrycan

### Versions & Modlist
  Forge: 40.1.54
  [✔️] ImmersiveEngineering-1.18.2-8.0.2-149

**Comment by Random832** [comment]
Might be worthwhile to just do forge:tools instead of only wrench. I've also made another suggestion to use tool actions [which would catch various modded tools, but not any of these]

**Comment by BluSunrize** [comment]
I opted to not add:

- The bundle, because I want to avoid container items stacking inside eachother
- The jerrycan, because I feel it's too "big" for a toolbox (just, like, flavor wise)
- <item> on a stick, because... I dunno, felt out of place
- Nametags for the same reason

`forge:buckets/empty` meanwhile is not actually a tag added by Forge. So unless some other mod populates it, this won't ever do anything.
