### ISSUE TITLE
freezing for a couple seconds after pressing shift over an item in an invenotry

### ISSUE THREAD

**Issue by EnderMelody** [BluSunrize/ImmersiveEngineering#5375]
### Minecraft Version

1.18

### Immersive Engineering Version

8.0.2-149

### Expected Behavior

not to freeze

### Actual Behavior

freezing and getting this error in the logs
[message.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/9175029/message.txt)

### Steps to reproduce

1. hold shift when hovering on item in inventory
2. freeze for a couple seconds
3. continuing to hold shift doesn't do anything unless you toggle it again or move over a different item, empty slots do not do anything

### Debug Crash Log

[crash-2022-07-23_23.07.28-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/9175038/crash-2022-07-23_23.07.28-client.txt)

**Comment by BluSunrize** [comment]
Please report this to PrimalMagick =)

The message we throw there is:
```IRecipe#getRemainingItems was called with an inventory that does not match the recipe according to IRecipe#matches. This is probably a bug in some mod in the following stacktrace, if in doubt report it to Immersive Engineering```

From what  I can tell, they are querying all recipes and then giving them a fake crafting inventory that uses the length of incredients as a width and then uses 1 for the height. Thus, our recipes can't find their fluid containers in there.
They do not distinguish between shaped and shapeless recipes, and I believe that to be the cause of the issue. Please communicate this to them.

Also, they do this every time you hold shift over an item, going through basically the entire list of crafting recipes. That's likely the reason for the freeze, because you have a modlist of 350 mods. That's gonna be a **lot** of recipes to go through.

**Comment by malte0811** [comment]
Even better, the inventory it passes only contains empty stacks. I haven't traced out why that's the case, but our `getIngredients` returns a sensible list of ingredients that shouldn't result in empty items.

**Comment by EnderMelody** [comment]
alright, i will put an issue on their tracker, thanks for the help
