### ISSUE TITLE
No such class com.blamejared.crafttweaker.api.event.type.CTCommandRegisterEvent

### ISSUE THREAD

**Issue by Hxrlio** [BluSunrize/ImmersiveEngineering#5407]
### Minecraft Version

1.18

### Immersive Engineering Version

2-8.1.0-150

### How did it happen?

Possible cause of someone else's crash on attempting to join world.

As shown below in excerpt from a dedicated server file, an error is caused by your mod failing to find a class in Craft Tweaker.

Upon investigating both mod's github pages, I have discovered that the issue is from
[CrafttweakerEventHandlers.java](https://github.com/BluSunrize/ImmersiveEngineering/blob/1.18.2/src/main/java/blusunrize/immersiveengineering/common/util/compat/crafttweaker/CrafttweakerEventHandlers.java)
line 13,
import com.blamejared.crafttweaker.api.event.type.CTCommandRegisterEvent;

but as you can see from
[the relevant folder in the forge files](https://github.com/CraftTweaker/CraftTweaker/tree/1.18/Forge/src/main/java/com/blamejared/crafttweaker/api/event/type)
and
[the lack of a /event folder in the common files](https://github.com/CraftTweaker/CraftTweaker/tree/1.18/Common/src/main/java/com/blamejared/crafttweaker/api)
no such class exists.

As for how this situation occurred, I have absolutely no idea. I don't know how long this has been the case, and assume you will be more easily able to figure out the whys and hows if you so wish to.

### Crash Log

https://gist.github.com/Hxrlio/da475723aa0059d6d764b4dea58e7d9f

**Comment by BluSunrize** [comment]
It occured because CraftTweaker decided to break their API...
They removed the event, and they did not increment major versions or anything. No deprecation, no legacy support.

https://github.com/CraftTweaker/CraftTweaker/commit/2211bbf0869d1eba53b307d54c9ce74b1b105c86#diff-ccd6cc220873c566c63e6af9a71c94b13b586bafcd87dba40a2d19a084d77ac0

Hey @TheSilkMiner why'd you do something like that? =P

**Comment by jaredlll08** [comment]
@BluSunrize That commit was included in this pull request https://github.com/CraftTweaker/CraftTweaker/pull/1444 which didn't increase the major version, however, the first time that code hit the `1.18` branch (to be pushed to Jenkins / maven / CF) was in this commit: 
https://github.com/CraftTweaker/CraftTweaker/commit/5457583fb4431abf238284462a0417161bed2e7c

Which did increase the major version number
https://github.com/CraftTweaker/CraftTweaker/commit/5457583fb4431abf238284462a0417161bed2e7c#diff-3d103fc7c312a3e136f88e81cef592424b8af2464c468116545c4d22d6edcf19R2

That commit was also the commit that updated us to 1.18.2, which due to changes made in the base game by Mojang, meant we can't be compatible with 1.18.1 builds anyway (mainly the tag changes).
