### ISSUE TITLE
Immersive Engineering 1.19 Server Crash

### ISSUE THREAD

**Issue by waddon1** [BluSunrize/ImmersiveEngineering#5426]
### Minecraft Version

1.19

### Immersive Engineering Version

1.19.2-9.0.0-153

### How did it happen?

When starting server it crashes

### Crash Log

https://pastebin.com/wkj8RDHd

**Comment by malte0811** [comment]
Please upload a full server log (`logs/debug.log`). It may be too large for pastebin, https://gist.github.com has a higher limit. Since more mods than just IE are crashing (scroll down a bit), I'm pretty sure something's crashing earlier in the loading process and Forge doesn't properly stop loading.

**Comment by waddon1** [comment]
I found out that the issue is actually with Primal Magick I'll close this and report the issue there.
