### ISSUE TITLE
[minor] Multi-block render issue

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#546]
When any formed multi-block that IE adds is broken, the particles produced are rendered in an unexpected manor, see below
![image](https://cloud.githubusercontent.com/assets/3110986/10861468/ba1cb700-7f3d-11e5-93a9-3941fba38d26.png)
![image](https://cloud.githubusercontent.com/assets/3110986/10861474/deabd75e-7f3d-11e5-854f-4fe20461084f.png)

IE build 2d98f88

**Comment by BluSunrize** [comment]
Doesn't happen in my environment .-.
Must be another mod messing with it or something

**Comment by cobra** [comment]
Tested with my environment: some particles look a bit funny when looking at a screenshot, but it's definitely the correct multiblock texture and nothing I see as a bug. Is this another modpack-too-large-error caused by funny stuff happening with packets having smaller fields than needed? Some other mod's bug?
Exhibit A:
![](https://cloud.githubusercontent.com/assets/163331/10864811/a1be2376-7ff9-11e5-8b48-5071f17a11de.png)

**Comment by BluSunrize** [comment]
Well that they look funny like that is because the multiblock texture (a 256x image) is stitched into the blocksheet and used as a single icon. That doesn't explain what happened in the pictures above though.

**Comment by theunkn0wn1** [comment]
I am not running a kitchen-sink pack, though I do have a large amount of mods mounted. (FTB infinity latest with magical mods removed). 

I attempted to reproduce this in my bare-minimum MC instance (IE, NEI, and their dependencies) but was unable to reproduce this glitch.

Weird... it must be a inter-mod incompatibility. IDK which mod is doing it though, and I do not have time today to dissect my pack to find the cause. :/

**Comment by BluSunrize** [comment]
Well then...closed ^^
