### ISSUE TITLE
[Suggestion] JEI integration for all shader items

### ISSUE THREAD

**Issue by Toastr125** [BluSunrize/ImmersiveEngineering#5460]
### Explain your idea

Currently, while all of the shader grab bags show in JEI, only one of the actual shaders does. Would it be possible to make it show all shaders? It would be nice to be able to see all of them in survival mode to check their colors (like, so that if someone else mentions one by name you can tell which they're talking about), check their rarities (to know which grab bags to go for if you want that shader), and generally have a complete list of them (such as if you want to collect all of them).

**Comment by BluSunrize** [comment]
No, they are intentionally not shown because that would take up a lot of space in JEI.

A full list of shaders is visible in the manual: Go to "General -> Shaders", on the second page, click "check here".
That gives you a list of all shaders. It tells you their rarity, and if you have previously acquired them, it gives you additional info and a button to "buy" more of them with silver grit.
