### ISSUE TITLE
[Crash] Immersive Engineering comes up in a crash report when it wasnt even being used...

### ISSUE THREAD

**Issue by Mowmaster** [BluSunrize/ImmersiveEngineering#5462]
### Minecraft Version

1.19

### Immersive Engineering Version

ImmersiveEngineering-1.19.2-9.0.0-153.jar

### How did it happen?

This was a NPE crash from a pedestals chopper (fakeplayer) where the weakreference<fakeplayer> player.get() returned null.
Clearly an issue by pedestals, but very curious as to why IE comes up in the log when it wasnt being used at all.

Just something to look into. Nothing major.

### Crash Log

https://pastebin.com/KX38DH5S

**Comment by malte0811** [comment]
This is expected. We use the `HarvestCheck` event to detect when a player tries to use a drill underwater without the relevant upgrade (I don't know whether there's a better way by now). The first step is to check if the player is using a drill, and if not just return without doing anything. In this case that check crashes, since we have to get the held item from the player.
