### ISSUE TITLE
[1.19.2] Crash when loading and creating world

### ISSUE THREAD

**Issue by ffuentesm** [BluSunrize/ImmersiveEngineering#5473]
### Minecraft Version

1.19

### Immersive Engineering Version

ImmersiveEngineering-1.19.2-9.0.0-153

### How did it happen?

![image](https://user-images.githubusercontent.com/44974827/197409287-3dd6b0e0-56f1-4f69-8cc9-1bfa1e80ff95.png)

When loading a new world I get this error 
NullPointerException: Cannot invoke "com.google.gson.JsonArray.size()" because "array" is null

it might have been some incompatibilities with Create or one of the add-ons, but I don't think is that. 
Create 0.5.0.f
Create Crafts & Additions 1.19.2-20221023a
Create Jetpack 2.1.0
Create Stuff & Additions 2.0.1

### Crash Log

https://crashy.net/sMwZdCv3gEPUxo8BJaqO

**Comment by BluSunrize** [comment]
Are you running any datapacks?

And can you reproduce this issue without the Create addons?

**Comment by ffuentesm** [comment]
Apparently, the new Craft&Addition release for 1.19.2 is causing the problem.
The game runs with C&A if IE is disabled, and vice versa.

**Comment by BluSunrize** [comment]
The issue is likely the same as it was in 1.18
We made this change: https://github.com/BluSunrize/ImmersiveEngineering/commit/3de851eb1d32d27da5bc61382826a2b507e324e6

And then released a hotfix. We did not release that hotfix for 1.19, because C&A wasn't released for that yet.

Please inform the C&A team. While this issue will get resolved from IE side with the next 1.19 release, they should absolutely add spoils to their veins. Also, this shows that they did not test their release against IE, which is a little disheartening :/

**Comment by BluSunrize** [comment]
Issue resolved on C&A's side
