### ISSUE TITLE
Floodlight LoS

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#550]
Issue: The floodlight's projected light entities do not check if LoS is maintained after being set at an angle, the projected light sources can be placed behinds wall relative to the projector after it is set up and powered.

Steps to reproduce:
[1] Setup and power the floodlanp
[2] Construct wall between the projected light sources and the floodlamp itself.

Here is a set of pictures in action:

No power:
![image](https://cloud.githubusercontent.com/assets/3110986/10866714/a1e9af40-7ffa-11e5-9e31-677658e7aae9.png)
Power without obstruction:
![image](https://cloud.githubusercontent.com/assets/3110986/10866717/e1ac3030-7ffa-11e5-95f3-4971e88e16b1.png)
Power with obstructions placed
![image](https://cloud.githubusercontent.com/assets/3110986/10866718/f8109a82-7ffa-11e5-92e7-e02369e4a2a8.png)

IE build cf77da7

**Comment by BluSunrize** [comment]
Yeah because like wires, that'd require raytracing every tick, which is a nono. The Floodlight updates its lights every 512 ticks, it will fix itself then.
And what's even worse than raytracing is lighting recalc, which happens on every light placed, so updating them per tick is the worst possible thing to do. I run on a pretty good PC and I went down to 4 FPS when I was testing this =P

summary:
Known issue, fixing it is not very feasible, wontfix
