### ISSUE TITLE
Multiblock building tutorials only show formed multiblock in guidebook

### ISSUE THREAD

**Issue by CipherUnknown** [BluSunrize/ImmersiveEngineering#5504]
### Minecraft Version

1.18

### Immersive Engineering Version

8.3.0-155

### Expected Behavior

Guidebook showcasing the tutorial on building the multiblocks. The up and down arrows also dont work as they have no effect.

### Actual Behavior

The book only displays the structures completely built, rather than the layer-by-layer tutorial on the block placement required.
![image](https://user-images.githubusercontent.com/108961957/208331275-94f3a72e-3e56-4e18-b944-69c3412eb216.png)
![image](https://user-images.githubusercontent.com/108961957/208331670-8f9c52fe-ee5f-4aa0-8ce0-f449495fc8e2.png)
![image](https://user-images.githubusercontent.com/108961957/208331694-3e00c7af-5391-469c-99e3-399869dd681b.png)

### Steps to reproduce

1. Open book
2. Open page of any multiblock
3. Structure will showcase completely formed, rather than the layers of the un-assembled blocks

### Debug Crash Log

https://pastebin.com/9LZLtcnb

**Comment by malte0811** [comment]
The manual pages should start by showing the structure, but can be switched to the "formed" view by clicking on the square between the arrows. Does the structure show up if you click on that? If not it's probably some mod interaction. Is the pack you are using available anywhere?

**Comment by CipherUnknown** [comment]
No, clicking the square toggles what I would assume to be the formed structure and the block placement, but clicking it just toggles between the formed structure and a complete blank.
Its a pack of my own.
![image](https://user-images.githubusercontent.com/108961957/208579086-2f01626b-f2ea-4763-8b50-b495fa534084.png)
![image](https://user-images.githubusercontent.com/108961957/208579109-6f95bb11-d2ce-4284-8db2-ac30a4ea8fbf.png)

**Comment by Landaz2** [comment]
I have the same behaviour as @CipherUnknown in a self-made collection of mods that include several performance and visual improvements (including shaders). It worked before, but after an update of both forge (to 40.1.92) and several mods, it broke. After turning off several combinations of these mods that might interfere with the visuals, the culprit seems to be Radium Reforged (radium-0.7.10). Once turned off, the step by step guide is working again. I was even able to turn on Oculus (1.4.3) with shaders, Rubidium (0.5.4) and Starlight (Forge, 1.0.2) back on without this issue.
This is with VBO turned off due to conflicts with the shaders.
