### ISSUE TITLE
Error loading mods 2 errors have occoured loading

### ISSUE THREAD

**Issue by Sammythybunnie67** [BluSunrize/ImmersiveEngineering#5509]
### Minecraft Version

1.18

### Immersive Engineering Version

8.3.0-155 curseforge 1.18.2

### How did it happen?

This happened during load
[message (1).txt](https://github.com/BluSunrize/ImmersiveEngineering/files/10296568/message.1.txt)
![20221223_174717](https://user-images.githubusercontent.com/96631619/209382710-89ab66d9-9eb9-4214-971f-601e65c4d25a.jpg)

### Crash Log

https://github.com/BluSunrize/ImmersiveEngineering/files/10296568/message.1.txt

**Comment by mindforger** [comment]
>Crash report saved to C:\Users\Samantha Slade\curseforge\minecraft\Instances\Create Modpack\crash-reports\crash-2022-12-23_17.34.25-fml.txt

Please add the actual crash report it is more readable

**Comment by TishinaVC** [comment]
same here
 https://pastebin.com/xvv8AeiM

**Comment by malte0811** [comment]
We need to move the POI for the machinist to some block from IE. Currently we use the vanilla anvil, which breaks in this case since [another mod](https://www.curseforge.com/minecraft/mc-mods/mo-villager/) also uses the anvil as a POI (each block state can only be used in one POI). Since that's mostly a gameplay decision I'll leave this issue to @BluSunrize.

**Comment by BluSunrize** [comment]
Damnit. We did it first =P

I'll have a think about this.

**Comment by BluSunrize** [comment]
Oh this is fixed now, btw.
I forgot to close it.
