### ISSUE TITLE
[Suggestion] Better Revolver Loading

### ISSUE THREAD

**Issue by Shibva** [BluSunrize/ImmersiveEngineering#5575]
### Explain your idea

Very basic; Just add the ability to fill a revolver and its quickloader via shift-clicking

makes loading it quicker and more convenient; Obviously a QoL thing

**Comment by Shibva** [comment]
To clarify: I mean for loading cartridges into their slots

**Comment by TeamSpen210** [comment]
It's intentional behaviour to prevent loading the revolver via shift-click - that makes it take time to load, making the capacity upgrade and quickloaders have a use with distinct behaviours. It also gives a bit of a downside to the revolver compared to bows and the railgun. It's up to you to decide which tradeoffs are better.

**Comment by BluSunrize** [comment]
Yep, what Spen said!
