### ISSUE TITLE
Aluminium is called "Aluminum" in the tags, messing up compat

### ISSUE THREAD

**Issue by Vapaman** [BluSunrize/ImmersiveEngineering#5606]
### Minecraft Version

1.19

### Immersive Engineering Version

1.19.2-9.2.0-162

### Expected Behavior

Immersive Engineerings aluminium would be interchangeable with other mods for example, IE2C.

### Actual Behavior

Aluminium is tagged as "aluminum", breaking compat
![kuva](https://user-images.githubusercontent.com/77460466/224140516-38bf2bbb-a8e4-48eb-a628-6190ff35a733.png)

### Steps to reproduce

Look at the F3+H information

### Debug Crash Log

https://pastebin.com/35cFPv19

**Comment by BluSunrize** [comment]
Uh. No, that is correct.

"Aluminum" is the American spelling. Forge uses American spelling internally, and so its tags are to be American as well.
All tech mods have agreed to this years ago. Tinkers, Mekanism, Thermal - they all use "Aluminum".

The reason that the item is *named* as Aluminium is simply because I prefer the English spelling (because it matches the German way of spelling it as well). But that's only in its translated name.
Internally and in tags, the American spelling is the correct and widely accepted way to do it.
