### ISSUE TITLE
HV Accumulator not charging

### ISSUE THREAD

**Issue by Destroyanad** [BluSunrize/ImmersiveEngineering#5643]
### Minecraft Version

1.19.2

### Immersive Engineering Version

1.19.2-9.2.0-162

### Expected Behavior

When connected to my power grid, it should be charging.

### Actual Behavior

It does not charge when connected to my power grid. Input is going into the input port, and output is coming from the output port.

### Steps to reproduce

Place accumulators.
Connect to power grid.
It charges, however after a seemingly random amount of time, it stop even though it is supplied with power.

### Debug Crash Log

no crash

**Comment by mindforger** [comment]
>Debug Crash Log
no crash

then force one please and maybe add more details on how to "Connect to power grid." 
(a picture says more than thousand words)

**Comment by Destroyanad** [comment]
I dont know how to force it to crash. HV connectors on the input and output, HV wires going from generators into the input, and HV wires coming from the output into machines. The accumulators are not charging,

I can not take images rn bc my friends server is down.

**Comment by mindforger** [comment]
>I litteraly told you how i connected it

HV connectors and wires and in which direction you connected it ... that is esssential more info than "connect to grid" :P 

you can hold F3 + C until the game forcibly crashes, then take the content of the crashlog and copy it to pastebin and send the link here (but that info should have been in the issue template when you created the report)

point for questioning is, there have been many reports before, that used relays instead of connectors and similar "simple" errors hence saying "connect it" is too generic
and the crashreport contains not only your game-, forge- and IE version, but also the whole list of other mods so one could actually possibly reproduce your issue

**Comment by BluSunrize** [comment]
The issue template gives you specific instructions for how to produce a crashlog.
![grafik](https://user-images.githubusercontent.com/4106382/230410763-50e975af-04f5-4c46-b076-d4e661746827.png)

Also, get us pictures of your setup, or there is zero way for us to help you.

**Comment by Destroyanad** [comment]
https://pastebin.pl/view/93a80396

![image](https://user-images.githubusercontent.com/115004118/230481425-d98f7417-dbe7-4ee5-a9ee-f0b56a83365d.png)
![image](https://user-images.githubusercontent.com/115004118/230481438-44115275-52a4-4ecc-a1d4-7c426aa8a9cc.png)

Input is receiving power through 2 thermoelectric generators. I know its generating power because the input damages me when I touch the wires.

**Comment by BluSunrize** [comment]
Well for one, I took a holiday, and I don't do dev work in that time.

Having now looked into this again, I find myself unable to reproduce this issue. Unless you can produce a testcase in a creative world or such there is nothing I can do here...
