### ISSUE TITLE
Compatability crash with IC2 classic

### ISSUE THREAD

**Issue by noel0719** [BluSunrize/ImmersiveEngineering#5690]
### Minecraft Version

1.19.2

### Immersive Engineering Version

ImmersiveEngineering-1.19.2-9.2.2-165.jar

### How did it happen?

When crafting IE concrete with IC2 classic cell's game crashes instantly
i have recreated this in single and multiplayer.

### Crash Log

https://pastebin.com/r3ERatRn

**Comment by malte0811** [comment]
This is essentially https://github.com/MinecraftForge/MinecraftForge/issues/6651: If a stack becomes empty by decreasing its size (such as when crafting from the last set of ingredients), it retains its capabilities. IMO that is severly broken behavior in Forge, but as Lex declared it intended behavior we have to live with it. We can guard against this in IE by checking for empty stacks before checking capabilities, but I would also consider this a bug in IC2-classic (if we accept Forge's behavior as a non-bug).

**Comment by Speiger** [comment]
@malte0811 I wouldn't call this a IC2C bug. Lexes argument about resurecting itemstack is just dumb right out of the gate.
NonNull/Immutable ItemStacks were introduced to fight a ton of Duplication bugs that were happening with the old system.
(Immutable in the sense that you can not change the item inside of a stack)

Anyways since its a crash that you can easily run into on accident I will implement also a patch that tests the item instance.
Since that is a free check.
