### ISSUE TITLE
Engineers workbench crashes game when inserting blueprint

### ISSUE THREAD

**Issue by 256noname256** [BluSunrize/ImmersiveEngineering#5704]
### Minecraft Version

1.18.2

### Immersive Engineering Version

8.4.0-161

### Minecraft Version
 1.18.2
 
 ### Immersive Engineering Version
 8.4.0-161
 
 ### How did it happen?
 ### Description
 There is already a similar case on issues, but there is a reason in the optifine, and there are no graphic mods here .

 ### Steps to reproduce
 1. Create workbench
 2. Place workbench
 3. Insert blueprint, engineers
 4. [Potentially shift click blueprint into workbench]
 5. Game should crash
 

### Crash Log

https://pastebin.com/H1T3VgPz

**Comment by BluSunrize** [comment]
Do you have `enableVBO` set to true in your Immersive Engienering client config?

**Comment by TwinMinds** [comment]
I have this same problem.  I saw that this was supposedly fixed in ImmersiveEngineering-1.19.2-9.2.1-164 version, but the issue exists in the older ImmersiveEngineering-1.18.2-8.4.0-161 version which is the latest available for 1.18.2.

I have enableVBO set to False to fix the missing excavator bucket issue related to Rubidium/Oculus shaders.

**Comment by 256noname256** [comment]
YEAAAA It s working but i set it on and it works

**Comment by TwinMinds** [comment]
A shame you closed this issue.  I'm hoping the 1.19.2 fix can be backported to 1.18.2 so I can leave enableVBO set to false to resolve other rendering issues.
