### ISSUE TITLE
Recipes from Theurgy are not visible when IE and NotEnoughRecipeBooks are installed. 

### ISSUE THREAD

**Issue by MuteTiefling** [BluSunrize/ImmersiveEngineering#5708]
### Minecraft Version

1.19.2

### Immersive Engineering Version

1.19.2-9.2.2-165

### Expected Behavior

Recipes for Theurgy should show despite the inclusion of IE and NERB

Already reported to Theurgy and NotEnoughRecipeBook devs. Reporting to you as well in case you can offer any insight on what might be happening.

https://github.com/klikli-dev/theurgy/issues/117

### Actual Behavior

The recipes for Theurgy don't show if IE and NERB are both active. If either or both are disabled, the recipes for Theurgy show without issue. 

### Steps to reproduce

- Search the rods in JEI
- Check recipe
- No recipe shows

Minimal mods to reproduce: 
- ImmersiveEngineering-1.19.2-9.2.2-165.jar
- jei-1.19.2-forge-11.6.0.1015.jar
- modonomicon-1.19.2-1.30.2.jar
- nerb-1.19.2-0.2.jar
- theurgy-1.19.2-1.3.3.jar

### Debug Crash Log

https://gist.github.com/MuteTiefling/15b5cd2cd2d598afcd7e186c2bfde731

**Comment by malte0811** [comment]
This is a very silly problem… I have not worked out the full details, but I'm pretty sure this is the rough cause:

Theurgy uses the [`initCapabilities`](https://github.com/klikli-dev/theurgy/blob/3d5dd71dfe5295bf8660aae2da741b81de1d7281/src/main/java/com/klikli_dev/theurgy/item/DivinationRodItem.java#L346-L348) method on their divination rod item to also modify/initialize the item stack NBT. This is only relevant for `SETTING_ALLOW_ATTUNING` since all other values are set in the recipes. IIRC this used to be mostly safe since capabilities were constructed on item stack construction, but Forge switched to lazily initializing them instead. So now the item stack changes the first time its capabilities are queried. Without IE that is "roughly never" for stacks in recipes and the JEI ingredient list. IE [queries a capability when tooltips are generated](https://github.com/BluSunrize/ImmersiveEngineering/blob/7d49b2aa24b5759931db0220ecffec447dc854b9/src/main/java/blusunrize/immersiveengineering/client/ClientEventHandler.java#L199-L207), in particular when search trees for the creative menu, JEI's ingredient list **and the vanilla recipe book** are computed. With IE and working recipe books, this means that both the items in the ingredient list and those in recipes have their NBT initialized. With IE and non-working recipe book (i.e. with NERB), only those in the ingredient list are initialized. This is a problem since JEI determines which recipes correspond to an ingredient using subtype interpreters. [The interpreter used for divining rods](https://github.com/klikli-dev/theurgy/blob/3d5dd71dfe5295bf8660aae2da741b81de1d7281/src/main/java/com/klikli_dev/theurgy/integration/jei/DivinationRodSubtypeInterpreter.java) considers the initialized item (`settingAllowAttuning=true`) and non-initialized (`settingAllowAttuning=false`) items to be distinct, so recipe lookup breaks.

Overall I would say that this is on Theurgy to fix.

**Comment by klikli-dev** [comment]
Thanks for researching! I'll look into how to mitigate that! 

EDIT: Thanks again, fixed as per https://github.com/klikli-dev/theurgy/issues/117#issuecomment-1575096748
