### ISSUE TITLE
[1.19.2] Permanent Floating Bullets

### ISSUE THREAD

**Issue by Cell-Technology** [BluSunrize/ImmersiveEngineering#5720]
### Minecraft Version

1.19.2

### Immersive Engineering Version

9.2.2-165

### Expected Behavior

Firing the revolver to not produce any permanent entities.

### Actual Behavior

Every bullet that doesn't hit anything eventually stalls in the air and stays stuck there permanently, they have to be manually removed.

### Steps to reproduce

1. Fire the Revolver in the air.
2. Follow the bullet and wait.
3. Floating bullet.

### Debug Crash Log

https://pastebin.com/0BFAeUea

**Comment by jojo2357** [comment]
Can be fixed by making [this line](https://github.com/BluSunrize/ImmersiveEngineering/blob/1.19.2/src/main/java/blusunrize/immersiveengineering/common/entities/IEProjectileEntity.java#L204) increment ticksinground, which will cause it to despawn, i believe. Alternatively, the bullet could be given extra "gravity" when in water to help get it out of such an abnormal location.

**Comment by BluSunrize** [comment]
Fixed by
https://github.com/BluSunrize/ImmersiveEngineering/commit/607222dae00c8c9fc3a7e50d75d4274aa1e01e48
