### ISSUE TITLE
[1.20.1] Support Forge 47.1.3 until Neoforge can be used

### ISSUE THREAD

**Issue by JaisDK** [BluSunrize/ImmersiveEngineering#5755]
### Minecraft Version

1.20.1

### Immersive Engineering Version

10.0.0-169

### Expected Behavior

Most packs are using 47.1.3 because Curseforge app does not support Neforge yet. If you want to the mod to be put into packs you should roll back to that version.

### Actual Behavior

Also your issue template needs updating.

![image](https://github.com/BluSunrize/ImmersiveEngineering/assets/15868585/12362a13-dbbd-4b9f-ae2e-e4453e0f1a64)

### Steps to reproduce

..

### Debug Crash Log

.

**Comment by ffuentesm** [comment]
Same, if I recall in 1.20.1, both Neoforge support forge 47.1.3 (The last stable version of Forge), and from what I am seeing, IE requires version 47.1.54

**Comment by Jerome226** [comment]
Please change the mods toml to support 47.1.3, it works if you change it.

**Comment by VirtualGaming1** [comment]
would be nice if you put Forge as support when using curseforge app I have to manualy add it

**Comment by SentinelX101** [comment]
2nd this, it would be great for this mod to be marked as forge compatible for version 1.20.1 on Curseforge, it doesn't appear possible to install it at all without that in the CurseForge launcher.

Please upload a Forge compatible version, it would be great to use this amazing mod and many of us are still stuck on Forge 1.20.1 as many mods have no updated past that yet

**Comment by BluSunrize** [comment]
But we're not Forge compatible. We built on NeoForge.

We've literally seen issues arise from people using Forge instead of Neo and so I can and will not label our mod Forge compatible if there is a chance that it may break.

Go complain to CurseForge. It's **their** fault that they don't have support for NeoForge on 1.20.1, and they **refuse** to fix that. It's not _our_ job to give you a workaround.
