### ISSUE TITLE
1.20.1 multi-unit "assembly line" system is not assembled

### ISSUE THREAD

**Issue by BloodInAs** [BluSunrize/ImmersiveEngineering#5774]
### Minecraft Version

1.20.1

### Immersive Engineering Version

ImmersiveEngineering-1.20.1-10.0.0-169

### Expected Behavior

multi-unit "assembly line" system is  assembled

### Actual Behavior

multi-unit "assembly line" system is not assembled

### Steps to reproduce

assemble a conveyor

### Debug Crash Log

-

**Comment by BluSunrize** [comment]
Can you provide a detailed description of your error and some pictures please?

**Comment by BloodInAs** [comment]
![image](https://github.com/BluSunrize/ImmersiveEngineering/assets/146227359/0d1f7726-7b9e-4ac8-9ea0-1d9e86f90cb5)

**Comment by BloodInAs** [comment]
I poke it with an engineering hammer everywhere I can, it won’t go

**Comment by BloodInAs** [comment]
![image](https://github.com/BluSunrize/ImmersiveEngineering/assets/146227359/d400e103-2c44-467d-a2e3-0a253a375a63)

**Comment by BluSunrize** [comment]
The conveyor in the back middle is oriented wrong, it needs to be facing forward.
The conveyors form a line, from the back corner to the middle right. This should be displayed as such in the engineers manual.

**Comment by BloodInAs** [comment]
https://youtu.be/JR7YMZwWQww

**Comment by BluSunrize** [comment]
Once again, the direction of the conveyors matters. You demonstrated it yourself on the bottling machine. As soon as all conveyors were correctly oriented, you can form it.

You have not placed the conveyors on the automated workbench correctly, and thus you can't form it.

Please refer to the manual for the correct direction of the conveyors.

**Comment by BloodInAs** [comment]
direction has no effect. on a filling machine, no matter how you set it up, it comes together.

**Comment by satonagrad1234** [comment]
No, the problem is not with the conveyor belt, I tried to arrange them like in a book and in a different way, the structure still does not activate.
When you click on the block that is highlighted in red in the book, the structure simply does not assemble for an unknown reason.

I also downloaded this version of the mod, started creating it alone, and it also failed to create an automatic workbench there.

![image](https://github.com/Gravity-Craft/Supports/assets/112409236/72ab1553-849e-4201-a56e-c72ff95f1667)
