### ISSUE TITLE
Powered lanterns not stopping mob spawn.

### ISSUE THREAD

**Issue by Drawde2** [BluSunrize/ImmersiveEngineering#5787]
### Minecraft Version

1.20.1

### Immersive Engineering Version

10.0.0-169

### Expected Behavior

Powered lanterns are supposed to stop mob spawns within 32 squares.

### Actual Behavior

I have a walled off area that I've used before in other versions, with 16 powered lanterns powered inside.  But I still had mobs inside the walls spawning.

### Steps to reproduce

I built an area walled and fenced off, set up some powered lanterns every 16 squares on posts, and powered them up.  They were all lit up.  Mobs spawned within the walls.

I turned the difficulty to peaceful to get rid of the mobs, then back to normal.  Mobs spawned inside the wall.  Repeated several times.

### Debug Crash Log

no crash

**Comment by mindforger** [comment]
any other mods present?! you can create a debug crashlog by holding ctrl+c until the timer runs out

**Comment by BluSunrize** [comment]
Can you please provide:
1) pictures of the setup
2) a debug crash
3) Elaborate on which mobs you had spawning there? Was it vanilla ones like zombies, or some added by other mods?

**Comment by Drawde2** [comment]
1.  I don't know how to post pictures, plus it's been removed.  Basically, I had a 5x5 chunk area walled off, with fences outside the wall at the top of it to prevent spiders.  I used a 4x4 grid of posts with a powered lantern on top of each, in the corners of the chunks.  With a single thermoelectric generator with two blue ice and two uranium blocks on the sides.  All connected with LV covered wire, and all the lanterns were lit up.  The same layout I've used before in other Minecraft versions.  I made certain that I saw the lanterns lit and nothing blinking, just in case the blue ice didn't work.
2.  
[crash-2023-10-26_04.02.58-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/13176508/crash-2023-10-26_04.02.58-client.txt)

3.  Vanilla mobs.  Spiders, skeletons, zombies, and creepers.

I started tearing it down, then decided to check it again before getting rid of them all.  I had 11 lanterns still up at that point, all lit up.  I had mobs spawning between the posts.

It's possible that it's a mod interaction since it's a homemade modpack, but I have no idea which mod could do that.

**Comment by Vectrobe** [comment]
I'm also seeing this but with a much shorter list of mods, although curiously only in areas exposed to sunlight and snow, at least so far, have not seen any spawns inside a pair of dark isolated rooms.
have not yet checked if this is isolated to IE alone

**Comment by scytail** [comment]
I'm also having this issue. 

Minecraft 1.20.1
forge 47.2.1

**Full mod list:**
![image](https://github.com/BluSunrize/ImmersiveEngineering/assets/9435256/bab0b0c3-dcf2-4800-a1c8-d0392b4be761)

**Pictures of the recreation:**
![image](https://github.com/BluSunrize/ImmersiveEngineering/assets/9435256/89d1d987-0694-4768-bf15-55eea2685280)
Note that the lantern is powered (and with a reliable source of energy from a windmill), and that the creeper spawned on the block pictured. 

I went over to that block and measured, and even if you count going up and over rather than a straight-line radius, the distance is about 15 blocks (was running from zombies so it might be a little farther, but certainly not 32 blocks):
![image](https://github.com/BluSunrize/ImmersiveEngineering/assets/9435256/cf390611-9bed-42d4-8115-c2ea1955d00d)

I don't have any special configurations that would change mob behavior, and my gameplay is fairly vanilla (so I could focus on Immersive Engineering!)
