### ISSUE TITLE
[1.20.1] Startup crash with Iguana Tweaks Reborn

### ISSUE THREAD

**Issue by Mike-U5** [BluSunrize/ImmersiveEngineering#5848]
### Minecraft Version

1.20.1

### Immersive Engineering Version

10.0.0-169

### How did it happen?

**Versions**:
* Minecraft:  20.1
* NeoForge: 47.1.84 
* IguanaTweaks Reborn: 3.0.4
* InsaneLib: 1.12.1]
* ImmersiveEngineering 10.0.0-169

**What Happens**:  
The game crashes when I boot the game after changing any config option in IguanaTweaks. Only happens when ImmersiveEngineering is installed. 

**Crashlog**:
https://gist.github.com/Mike-U5/6190e0e05381d8bd37d4d081e449efe1

**Iguana Tweaks Reborn Config**:  
https://gist.github.com/Mike-U5/df3263960f79ec242f89015612f0e122

**Mod used**:
IguanaTweaks Reborn + InsaneLib + MaxHealthFix + ImmersiveEngineering

### Crash Log

https://gist.github.com/Mike-U5/6190e0e05381d8bd37d4d081e449efe1

**Comment by JessAlias** [comment]
Hi all, I'm getting similar error, or at least what looks like it. I went through the IguanaTweaks Reborn config file, manually testing every config setting.

It SEEMS like the error only occurs if any of the 'data pack' settings are changed with IguanaTweaks Reborn's config file. You can change other stuff, but if a datapack with IguanaTweaks Reborn is disabled, the game explodes when trying to load any world.

I noticed that the crashlog mentions arc furnace recycling. I looked in the ImmersiveEngineering config file, and it mentions something about how the recycling functionality was changed to use datapacks rather than the config file. Wondering if this is related? I'm no minecraft modder, just a doofus who knows how to read config files and crash logs...
