### ISSUE TITLE
Import ImmersiveEngineering dependency crashes : java.lang.NoSuchFieldError: f_118259_

### ISSUE THREAD

**Issue by remarxk** [BluSunrize/ImmersiveEngineering#5877]
### Minecraft Version

1.20.1

### Immersive Engineering Version

1.20.1-10.0.0-169.48

### How did it happen?

Information in the process of loading mod games crash, message is java.lang.NoSuchFieldError: f_118259_
![image](https://github.com/BluSunrize/ImmersiveEngineering/assets/86111678/0e60edcc-690c-4aab-b8b3-61dd9cd792bb)

### Crash Log

https://pastebin.com/tYiBRf2B

**Comment by malte0811** [comment]
You seem to be trying to use IE as a dependency in mod development. In this case you need to wrap the gradle dependency in `fg.deobf` to handle the (de)obfuscation, like [here](https://github.com/BluSunrize/ImmersiveEngineering/blob/e1e8df79c574553f3f52ef40eb3214c1bbee3e37/build.gradle#L211).

Additionally you should add [this](https://github.com/BluSunrize/ImmersiveEngineering/blob/e1e8df79c574553f3f52ef40eb3214c1bbee3e37/build.gradle#L9) line to your build script if it is not already there; otherwise you will get Mixin-related crashes with IE.

Both of these points will become irelevant in 1.20.4 since NeoForge got rid of runtime obfuscation.
