### ISSUE TITLE
Change recipe balance in Fermenter & Squezeer

### ISSUE THREAD

**Issue by alexeik** [BluSunrize/ImmersiveEngineering#5915]
How can i change ratio of input(vegetable or fruits) and ouput (mB) for 1 mB?
i want to set 64 items for 1 mB or smth

**Comment by TeamSpen210** [comment]
All the recipes are defined in the datapack in the mod JAR. You can just create a vanilla datapack, copy out the [original JSONs](https://github.com/BluSunrize/ImmersiveEngineering/blob/1.20.1/src/generated/resources/data/immersiveengineering/recipes/fermenter/apple.json) from the JAR (open it as a zip), then modify them. That said I'm not sure you could do a recipe that extreme, since it'd require it to track fractional millibuckets, or consume multiple items at a time.

Currently, one apple makes 80mb for instance, and the refinery uses 8mb of ethanol + 8mb of plant oil for 16mb of diesel. Combining those, currently you'd need 6.25 apples for a bucket, compared to your recipe which would require 32,000 apples. That seems a bit absurd.

**Comment by alexeik** [comment]
good.
now i know formula. 
and will correct my ratio :)

**Comment by alexeik** [comment]
do i need to keep this folder structure?
![image](https://github.com/BluSunrize/ImmersiveEngineering/assets/318732/7d140201-ab36-4a90-8610-aae313671c5d)

**Comment by alexeik** [comment]
i asked because there is no info about datapack overriding for mods

**Comment by mindforger** [comment]
you have to keep the forlder structure, not sure if you actually need to keep the files you did not touch though

**Comment by alexeik** [comment]
> Currently, one apple makes 80mb for instance, and the refinery uses 8mb of ethanol + 8mb of plant oil for 16mb of diesel.

how can i change this ratio?
i want to move inflation from items needed to refinery formula 
like this:
80mb+80mb=16mb of diesel

you know:) as you said 32 000 items is too much number for recipe and fractions way too.

**Comment by BluSunrize** [comment]
All our recipes are done with JSON - exactly like vanilla.
They can be overridden in the exact same way as any vanilla recipe.
The Minecraft wiki has an excellent guide on making data packs here:
https://minecraft.wiki/w/Data_pack

If you follow that guide and learn how to do vanilla recipe stuff *first*, then doing it for Immersive Engineering recipes becomes self-explanatory.

**Comment by alexeik** [comment]
@BluSunrize i know.
but it was a mistake to change recipe.
when your world is full of apples :) u can not adapt  fermenter and squezer through recipes. thank to @TeamSpen210 
it would be much easier to adapt through refinery recipes.

oh! refinery recipes are in datapack :) nice!

**Comment by alexeik** [comment]
thanks guys
it works.

**Comment by alexeik** [comment]
[test.datapack.zip](https://github.com/BluSunrize/ImmersiveEngineering/files/15012203/test.datapack.zip)
land it here for anyone )
