### ISSUE TITLE
Repository doesn't build

### ISSUE THREAD

**Issue by Baughn** [BluSunrize/ImmersiveEngineering#593]
If I clone the repository, then run ./gradlew build, I get a large number of errors. Some are encoding-based, some appear to be missing code. There may be libraries missing; if so, and if you can't include them, it'd be good to mention this in README.md.

You'll get more contributors if the repository always builds. Here's a pre-commit hook you can use to make sure that's the case: https://github.com/Dolu1990/ElectricalAge/blob/1.7.10-MNA/pre-commit.sh

**Comment by Baughn** [comment]
And the complete list of errors, for fun: http://sprunge.us/bONd

**Comment by mindforger** [comment]
this is intended!

**Comment by Baughn** [comment]
Having the repository not build is intended?

...

Okay then. I suppose I won't contribute. Thanks for the catenary code, though.

**Comment by cobra** [comment]
Well-known, @BluSunrize doesn't like maven, many dependencies don't even have a maven repo, so they would need to be included in the git repo.

Be aware that there is no license, so any code you're taking without consent would be a breach of copyright.

**Comment by Baughn** [comment]
Yes. The usual solution to that is to document it: Put a list in README.md of all the libraries used, so people know what to download and stick in lib.

I've found that most mod developers are happy to allow exceptions if you ask, though in my own case I don't generally bother to integrate with mods that aren't open-source in the first place.

That said, there would be build errors even if I had all the libs. Most of the errors in that paste are *not* missing dependencies.

**Comment by cobra** [comment]
I'm doing regular gradle builds with a customised build.gradle and that works.

Those unmappable chars look really strange, how the heck did that happen? Do the files containing them look okay in an editor? How did you clone the repo?

**Comment by BluSunrize** [comment]
Yes, in fact most of that log is dependencies. The reason for it? If you can figure out the dependencies on your own, you're also qualified enough to give me decent bug reports and code assistance. Malte, mind, cobra and unknown are great examples, they all figured out the libs on their own, and thanks to them, most 0.6 bugs where fixed before they ever saw a release.

I just don't want to have to deal with hundreds of people going "I built off of your git and it broke", because, no shit, it's a development version, of course it breaks.

So yes, I don't Maven, aided in that decision by the fact that at least one of my libs has no maven.

**Comment by Baughn** [comment]
@cobra 

$ git clone https://github.com/BluSunrize/ImmersiveEngineering.git
$ cd ImmersiveEngineering
$ ./gradlew build

<Errors>

**Comment by BluSunrize** [comment]
Ah, but I never say that. I don't advertise the custom-build of my code, because I'm afraid of the giant amount of version mismatches and released rebuilds that's going to cause. A fellow dev of mine had multiple problems of that kind, where people were reporting bugs that only existed because they were playing with a forked built that they had no control over. I'd hate for the same thing to happen to IE.

Also, what's "Eln"? ^^

**Comment by Baughn** [comment]
Electrical Age, aka. http://electrical-age.net/
