### ISSUE TITLE
Curseforge not showing Immersive Engineering mod when searching for MC 1.20.1 version?

### ISSUE THREAD

**Issue by TheOrionsun** [BluSunrize/ImmersiveEngineering#5931]
### Explain your idea

Not sure if this is just my issue, but Curseforge not showing Immersive Engineering mod when searching for MC 1.20.1 mod versions.

**Comment by BluSunrize** [comment]
It's right here:

https://www.curseforge.com/minecraft/mc-mods/immersive-engineering/files/all?page=1&pageSize=20&version=1.20.1

**Comment by frizzle101101** [comment]
I was just about to open an issue for this too. The problem is the file is only under the neo forge mod loader but apparently the mod file is compatible with both neo forge and normal Forge, curseforge does not seem to recognize milti modloader compatibility, I don't think at least, maybe just add another copy of the file on curseforge under the forge mod loader would be the best solution

**Comment by BluSunrize** [comment]
No, it isn't, because we don't officially _support_ Forge.

We build and release under NeoForge, not tagging our File as "Forge" was a deliberate choice, because we can not guarantee that it will keep working. 
We are NeoForge only from here on, that won't change.
