### ISSUE TITLE
Treated Wood Planks Recipes

### ISSUE THREAD

**Issue by AriaElidove** [BluSunrize/ImmersiveEngineering#5997]
### Explain your idea

Allow Treated Wood Planks and cosmetic variants be usable as regular planks for misc recipes, not including ones which are treated variants (ie Slabs, Sticks). For example, a 2x2 should make a crafting bench with Oak Planks, but don't with Treated Wood Planks.

**Comment by BluSunrize** [comment]
We can't easily do that.

We can't tag them as `minecraft:planks` because then we have a recipe conflict between sticks and treated sticks, as well as chests and crates.

So instead we'd have to add *specific* recipes for:
- crafting table
- cartography table
- fletching table
- smithing table
- grindstone
- loom
- note block
- jukebox
- beehive
- bookshelf

And that's *just* vanilla blocks we'd have to satisfy. Treated planks can not be used to replace normal planks. But you can always use a sawmill and make some Fiberboard to maximize your plank output ^^
