### ISSUE TITLE
[Suggestion] Some form of automatically farming hemp seeds and other crops.

### ISSUE THREAD

**Issue by MrGreenTea** [BluSunrize/ImmersiveEngineering#602]
I think it would be a nice addition to this mod to be able to somehow farm crops automatically. Maybe even add compatibility with Steve's Carts' Farmer Module?
I don't have a concrete idea how it should work, so maybe take this issue as a place to discuss it.
Maybe it could be a multi-block greenhouse? Maybe someone else has a better idea.

**Comment by BluSunrize** [comment]
Farmign is planned but without concrete ideas as of yet. For one, Immersive Integration had plans for farms a few weeks ago, secondly, Hemp is already farmable in many ways. Forestry has compat for it, EIO does too, afaik, I added support for Hydraulicraft and you can always do a purely vanilla farm using pistons, the same way you'd farm sugarcane

**Comment by 2bithacker** [comment]
One note related to this, I tried setting up a hemp farm using Botania Mana Spreaders with Bore Lenses. This works for farming things like sugar cane that grow 2 block high. However with Industrial Hemp, the mana bursts pass through the top section without breaking it. I would have expected the behavior to match that of sugar cane. Not sure if this is an IE issue or a Botania issue though.

**Comment by BluSunrize** [comment]
Vazkii makes manabursts pass through instances of BlockBush. She probably has very good reason for that.
My hemp extends BlockBush, because I didn't want to copy the whole plant code over. Sugarcane doesn't, it extends normal blocks and does all the plantable stuff again. I couldn't be bothered to do so so instead went with bush, which btw., is the unspoken consensus for adding any sort of crop in Minecraft. A lot of other mods do this too.
I'll see what I can come up with though.

**Comment by p75369** [comment]
I thought I'd add my two cents to this as I was thinking about it the other day.

The main draw of IE is the immersion, something which is sorely lacking from 90% of farms, except the ones which use drones/robots/golems/villagers. There still isn't a farm that has a proper industrial aesthetic to it. So this would be a valuable addition to the IE repertoir.

So, my suggestion on how it could work: Combine harverster. Although a installed machine rather than a vehicle.

Say a 7wide x2 x2 multiblock with two lengths of rails running perpendicular and part of the 1st and 7th bottom blocks of the multiblock. This would create a 5 x (rail length) plot of farmland. On a redstone pulse, the harvester moves along the rails harvesting the crops, ejecting produce out of one end, before returning "home" and waiting for another signal. Place it and ground level for vanilla crops, or raise it a block to only trim the top of hemp.

Then, a similar multiblock at the other end of the rails that works as a planter.

**Comment by Joshwoo69** [comment]
giving my support for the combine harvester. +1

**Comment by mindforger** [comment]
plus adding an optional machine that can be placed on the other side of the rails...

the **planter**, using the same rails and the same animation just different textures to plant seeds if present in inventory :)

**Comment by MrGreenTea** [comment]
Would it use the standard rails? 
Something that would be very important for me, would be the ability to use seeds from other mods. Most automation for planting I have used couldn't do that.

**Comment by mindforger** [comment]
standard rails would make no sense, i was thinking more about "rails" in the sense of horizontal guides for the axis of the mill/roller rather than train rails

planting by default uses a virtual rightclick, i have no idea which type of farmer you used so far, but almost all use a virtual rightclick and if the plant itself is coded in a normal sane way, it should accept this methode of planting! Else it is either designed to not be able to be automated or just programmed very stupid

**Comment by Joshwoo69** [comment]
Well I think hunger overhaul or spice of life uses right click.. this harvests the plant and plants it back.... vanilla users use left click.

**Comment by elkillo** [comment]
+1 to this idea (sorry if necro)
