### ISSUE TITLE
[Suggestion] Optimize texture loading in the atlas

### ISSUE THREAD

**Issue by Lolothepro** [BluSunrize/ImmersiveEngineering#6064]
### Explain your idea

![minecraft_textures_atlas_blocks png_0](https://github.com/user-attachments/assets/6f12f4fd-3c56-418a-95a0-66323f0fbd36)

![2024-09-28_15 44 36](https://github.com/user-attachments/assets/7c4a9a21-3e96-433d-b2df-eb915841abda)

Currently, with Immersive Engineering, a lot of empty space is created in the atlas.
Many textures occupy a large space in the atlas, even though they are small.
like
![2024-09-28_15 44 56](https://github.com/user-attachments/assets/ad5b8018-f206-4d65-b0f5-84e9f170b672)
![2024-09-28_15 46 35](https://github.com/user-attachments/assets/f3d089de-a552-4759-ad57-b3db30d773e3)
![2024-09-28_15 46 41](https://github.com/user-attachments/assets/d554e800-eab7-4d61-b055-6faaf948b33f)
![2024-09-28_15 46 43](https://github.com/user-attachments/assets/70bc72c7-d2fb-442e-b7d6-f79d2118feb0)

I wonder if it's possible to make these textures allocate less space in the atlas?

**Comment by voidsong-dragonfly** [comment]
You can't make the shader textures smaller because they have a set blueprint only some parts of them apply to for any given shader. You can see shaders there with much larger or smaller percentages filled due to that.

However, you're also testing with only IE and Minecraft, which misrepresents the actual space IE would take up in a larger pack, as there would be many more blocks and items from other mods.


On top of all of that, atlas size is not really an issue unless there's so much texture space (there won't be) the graphics card can't load it fully into the card and errors out, which I have only seen _once_ and it was on a potato.
