### ISSUE TITLE
Aluminium scaffolding 

### ISSUE THREAD

**Issue by dominx** [BluSunrize/ImmersiveEngineering#607]
IE is another mod that adds aluminium and then doesn't use much of it. It would be nice to have at least an aesthetic use: aluminium scaffolding, fences, etc.

**Comment by BluSunrize** [comment]
I never really took it into consideration, but I'd recommend approaching Damien (@Damien_hazard on twitter), since he'd have to do the art for all of that =P

**Comment by dominx** [comment]
I don't think that requires much of new artwork, just recoloring of existing textures. In version I'm on (0.5.1) its 4 different blocks. Fifteen minute job I'd guess. I've never used twitter so singing up seems excessive just for that.

I've loooked at IE stuff in NEI and tought that aluminium could be also used for an 'advanced windmill'. Just a thought.

**Comment by victicdin** [comment]
Write out explicitly what you'd expect, I have his twitter on file atm. If you give enough information I can discuss it with him. What blocks would need recolours?

**Comment by dominx** [comment]
It's Steel Fence, Steel Scaffolding, Structural Arm, Steel Wall Mount and perhaps Structural Cable Connector. There are possibly some new blocks I don't know, as I'm still on 3 months old Infinity at the moment.

**Comment by BluSunrize** [comment]
Not the wallmount, neither the structural connector. Those will remain steel only.

**Comment by victicdin** [comment]
@dominx Just a note: Damien is on a road trip to Oslo(elsewhere in Norway, left pretty much 2 hours ago) atm and could even head to Sweden, so whenever he's settled again is when I'll ask about it. I hope we can agree that the timing is a bit off.

@BluSunrize Can you think of any other restrictions off the top of your head? I'm currently battling with compatibility troubles from API changes (and CoFH generation creation is at the top of my list atm) for my pack so I'm not in a position to check on blocks for a few days. Frankly, I'm not as familiar with systems past LV->MV as I would like to be, mainly due to the now fixed wire bugs.

**Comment by cobra** [comment]
from IRC: Mr. Hazard says he'll do the aluminium stuff.

**Comment by BluSunrize** [comment]
I added it, Haz might update the textures some time.
