### ISSUE TITLE
Bottling machine issue?

### ISSUE THREAD

**Issue by kienerxyzzy** [BluSunrize/ImmersiveEngineering#6075]
### Minecraft Version

1.20.1

### Immersive Engineering Version

10.1.0-171

### Expected Behavior

Look below
(This could potentially a bug with your JEI display)

### Actual Behavior

![Screenshot 2024-10-15 191731](https://github.com/user-attachments/assets/423338e7-dbca-448d-ba81-eecd4d9e2810)
![Screenshot 2024-10-15 192052](https://github.com/user-attachments/assets/058f6be2-489e-43b5-bbbb-7751c471c3f6)

### Steps to reproduce

I looked in JEI

### Debug Crash Log

none

**Comment by BluSunrize** [comment]
That's a JEI bug, it works perfectly fine in world.

**Comment by KnightMiner** [comment]
I just had this reported to me at SlimeKnights/TinkersConstruct#5298. Yes, its a JEI bug, but its a bug with your JEI integration, so its still a bug with Immersive Engineering that should be fixed.

The problem is your logic scanning the fluid registry to generate recipes just makes a [seemingly random assignment](https://github.com/BluSunrize/ImmersiveEngineering/blob/be78896be8b6be40a9313a889f28396fddf23366/src/main/java/blusunrize/immersiveengineering/common/util/compat/jei/JEIHelper.java#L241-L249) from from fluid one of its fluid tags for the recipe; you could just create a `FluidTagInput` with a list of fluid IDs to display the single fluid the recipe is meant to input.
