### ISSUE TITLE
CurseForge Availability

### ISSUE THREAD

**Issue by Explode007** [BluSunrize/ImmersiveEngineering#6119]
### Minecraft Version

1.20.1

### Immersive Engineering Version

ImmersiveEngineering-1.20.1-10.1.0-171

### Expected Behavior

So basically on curseforge you cannot download immersive engineering when you are using a forge modloader because its not tagged as such (even though it runs perfectly fine) making it impossible to download via handlers or upload packs (because the download isn't resolved to curse). All im requesting is to add the Forge tag to immersive so curse stops preventing the download

### Actual Behavior

a

### Steps to reproduce

a

### Debug Crash Log

ad

**Comment by BluSunrize** [comment]
Yeah because we only release on NeoForge

**Comment by Explode007** [comment]
So it's not just a curseforge thing? It's determined by the compiled mod?

**Comment by BluSunrize** [comment]
We can not guarantee that it works on Forge, because we built it against Neo.
It *might* work, but we have already seen a few bugs that only show up with Forge and not with Neo.

As such we don't want to make a blanket statement for compatability, and we won't.

I would honestly just recommend moving to 1.20.4 and onwards anyway.
