### ISSUE TITLE
Adding mystical agriculture seed recipies to cloche - Minecraft 1.21.1

### ISSUE THREAD

**Issue by Presyon** [BluSunrize/ImmersiveEngineering#6120]
### Explain your idea

Hello I wasn't sure where to put this so its here. As the title says I'm trying to add mystical agriculture seeds to the cloche through a datapack. What I have so far is attached, I need help getting it to work.

[ClocheSeeds.zip](https://github.com/user-attachments/files/17899590/ClocheSeeds.zip)

**Comment by BluSunrize** [comment]
1. Your datapack isn't correctly formatted, specifically you are missing a **namespace**. Please refer to Minecraft's very own wiki for how to do that:
https://minecraft.wiki/w/Data_pack#Folder_structure
2. We have plenty examples of what a Cloche recipe should look like, you should try to actually copy it properly:
https://github.com/BluSunrize/ImmersiveEngineering/blob/1.20.4/src/generated/resources/data/immersiveengineering/recipes/cloche/azure_bluet.json
Notably, you got the rendertype wrong, presumably because you copied it from some old version somewhere. You should refer to our *up to date* code for how to do it, not some outdated stuff.
3. I don't like downloading zip files. Next time, make it a proper github repository
4. This issue tracker is not for debugging datapacks. Let's handle this on discord next time.
