### ISSUE TITLE
IE particles to not respect light

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#637]
It seems the particle effects emited by the crusher and the Excavator do not change their appearance with light levels, in the shadows of a thunderstorm they display bright as day.

![image](https://cloud.githubusercontent.com/assets/3110986/11107935/302ecf20-8897-11e5-8679-fdd3e172a2ae.png)

**Comment by mindforger** [comment]
can you try repeating this issue with only IE installed? there are some roaming lighting issues between botania, enderIO and carpenters blocks (carpenters are leaking GL states currently)

**Comment by cobra** [comment]
I already noticed that and tried to find a fix, but didn't succeed. These are the same particles the crusher is using, so that one is glowing the same way. Totally intended code-wise, there's no bug or mod interaction, they just don't calculate their brightness value and disable lighting in the renderer.
