### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by Potsukin** [BluSunrize/ImmersiveEngineering#685]
This crash happens  frequently

http://pastebin.com/E6TVNbdA

**Comment by BluSunrize** [comment]
DON'T POST UNSPOILERED CRASHLOGS.
Jeez, use pastebin or something >_<

Also, line 96 of your crash, in a compiled instance, apparently is 
"indirectConnections.get(node).addAll(fluidHandlers);"

I have no idea how that null crashes.
@cobra, @malte0811, any ideas?

**Comment by Potsukin** [comment]
>DON'T POST UNSPOILERED CRASHLOGS.
Jeez, use pastebin or something >_<

Sorry I am going to use pastebin next time.

>Also, line 96 of your crash, in a compiled instance, apparently is
"indirectConnections.get(node).addAll(fluidHandlers);"

This crash happens at random, not everytime. I do not change any IE blocks about a 3 days though.

**Comment by BluSunrize** [comment]
Also, you're using Lightloader. Pretty well known for breaking things. I'd recommend not using it.

**Comment by Potsukin** [comment]
I know that install Lightloader to forge profile may have a problem. Instead of this , put Lightloader.jar to forge's mods folder  should not have a problem I guess. I use Lightloader for  WorldEdit CUI only.

**Comment by BluSunrize** [comment]
Just use it without LightLoader, honestly. There is so little point to having it.

**Comment by malte0811** [comment]
This is not LiteLoader, though it may be amplified by it. I managed to reproduce it in my dev environment, though it is very rare (2 or 3 crashes in half an hour of testing). I have a potential fix though, I think it's race conditions between server and client thread.
I uploaded a test build with proper side checks [here](https://www.dropbox.com/s/uc26uj0sgaz53ed/ImmersiveEngineering-0.6.2_m1.jar?dl=0) (this is the 0.6.2 version, so no new content or anything). @Potsukin, it would be nice if you would try to use that version instead of the official one (If you want to see the source code, it's [here](https://github.com/malte0811/ImmersiveEngineering/tree/0.6.2_PipeNPE)). It should not cause any problems, but I added a debug printout, if that spams your log, please tell me. If you experience this crash with my version, please tell me as well.
Also, it is possible to edit posts. Please edit your post to be a link to the crashlog on pastebin or something instead of this wall of text.

**Comment by BluSunrize** [comment]
huh, alright. Guess that really is on our side then ^^

**Comment by Potsukin** [comment]
@malte0811 Moved a crash log to pastebin. I am going to try a test build, thanks.

**Comment by malte0811** [comment]
Did you have any problems or spammed logs with my test build? If not, i will PR a mergeable version of the changes I made.

**Comment by Potsukin** [comment]
@malte0811  No crash at all with test build. Really stable.
