### ISSUE TITLE
Item Router Crash when it doesn't have valid routes

### ISSUE THREAD

**Issue by Alaberti** [BluSunrize/ImmersiveEngineering#686]
http://pastebin.com/pCaArgEH

100% just trying to see what happens when you put item routers next to each other with stuff coming into one of them but no routes specified for any items. Result: bad day.

**Comment by BluSunrize** [comment]
I don't quite know how to replicate this. Could you provide pictures of the setup and the router configurations?

**Comment by Alaberti** [comment]
I have one router (input) receiving items from an ender conduit, one adjacent (south) with a hopper underneath (output) dropping items onto a conveyor belt. That worked fine. When I added item routers to the east and west of the input router, that's when the crash happened. 

None of the routers had any configuration at all. I had figured I could set them up and see how items went through them, ie, if there were no instructions would they attempted to leave via the nearest neighbor. Looks like they got caught in a loop trying to decide which way to exit the input router.

**Comment by BluSunrize** [comment]
Ah, I understand the issue. It's a cyclic loop of routers. Yeah that's a problem :/

**Comment by Alaberti** [comment]
I uh...whoops? ^_^;;

**Comment by BluSunrize** [comment]
Not your fault, I'm just thinking about how to prevent that now... x3

**Comment by Alaberti** [comment]
Is there a way to have it check what side its been through so it doesn't go that way next pass, with the end result either being it finds a way out or it stays (or is ejected into the world or goes back if possible_) from the router?

**Comment by BluSunrize** [comment]
There is no going back. The issue ensues during the check for avaiable outputs. I need to check there, otherwise, pipe mods like Thermal Dynamics or EIO would try to force insert, and there is no way of blocking that past the initial check.

This routing goes through a vanilla method, which does not allow me to parse any additional info, so a list of visited locations is not easy to implement. I'm sure I'll find a solution, but it may take a bit.
