### ISSUE TITLE
Inconsistent book back button

### ISSUE THREAD

**Issue by UnwrittenFun** [BluSunrize/ImmersiveEngineering#69]
I've noticed inconsistent behaviour when pressing the back button in the top left of the book.

For instance when on the page Industrial Hemp it takes me back to Overview and Resources category, however when on the Ores page for example, it take me back to the starting page (titled Engineer's Manual).

The behaviour of that button is different depending on each page seemingly randomly.

**Comment by BluSunrize** [comment]
yeah, @joshiejack reported that ages ago, and I never figured out how to fix it .~.

**Comment by UnwrittenFun** [comment]
hrmm

**Comment by mindforger** [comment]
just from a short peek,
and not beeing able to find the actual manual description file because of beeing blind,
isn't the "class ItemDisplay extends ManualPages" handling buttons only implicit and thus probably missing the proper return path and defaulting to the beginning? ... i will look a bit deeper when i get back from work :P
