### ISSUE TITLE
Info request

### ISSUE THREAD

**Issue by bookerthegeek** [BluSunrize/ImmersiveEngineering#696]
Fromhttps://github.com/BluSunrize/ImmersiveEngineering/issues/680

May we have the defaults for each of the veins in regards to the excavator scripts.

Also, will your book update with the new information if we remove or modify or add veins? If not, I'll request that from the mod tweaker guys/gals.

**Comment by bookerthegeek** [comment]
Darn phone...

https://github.com/BluSunrize/ImmersiveEngineering/issues/680

**Comment by BluSunrize** [comment]
All the necessary info is found here:
https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/IEContent.java#L510-L527

The book will update. And talking to the Mine-/Modtweaker peeps would do nothing, because IE's MT integration is done internally and written by me, not them =P

**Comment by bookerthegeek** [comment]
Thank you much! And wow on the quick response. Love the mod and look forward to seeing what comes next.
