### ISSUE TITLE
[feature request] Redstone breaker redstone relay

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#709]
The redstone breaker as it stands is great, I appreciate that it was added, though might I suggest an possible improvement?

 Can we get the device to relay redstone signal? Some builds do not grant room or is cost-inhibitive to wire redstone to each breaker in a series, yet if the Breaker relayed the signal it received builds can be more compact/eye candy.
![image](https://cloud.githubusercontent.com/assets/3110986/11432715/f9e147d0-9468-11e5-82f4-f86801b37e67.png)

**Comment by mindforger** [comment]
i support this, let the breaker itself act as a redstone signal relay when there is another relay beside it

regular redsonte relaying can lead to signal loops :P

**Comment by BluSunrize** [comment]
I'm working on it, but vanilla redstone is a pain in the butt. x3

**Comment by mindforger** [comment]
that's what i meant :P 
propagate the redstone state to neighbour relays (something like IRSPropagateable) when hit by wrench could possibly be easier to implement and would be less bug prone or worse ... exploitable

**Comment by BluSunrize** [comment]
Naaah, fuck that. I'm not adding specific interfaces like that. If I can't get it to work with vanilla methods, I'll just scrap the idea. Not worth the hassle.

**Comment by BluSunrize** [comment]
![img](http://puu.sh/lAnEJ/84b0198b1e.jpg)
![img](http://puu.sh/lAnFc/165939dd06.jpg)

It works!

**Comment by mindforger** [comment]
now layout 2 or more relays w/o redstone in between over a chunk boundary and check for ghostloading while having a fast clock feeding in the relays

**Comment by BluSunrize** [comment]
If you attach a fast clock to a breaker switch, you are an idiot and deserve to have your instance crash on you for forcing excessive wire pathfinding.

**Comment by mindforger** [comment]
no cables attached :D i was suggesting to make an exploit test

**Comment by BluSunrize** [comment]
Tried it, signal doesn't get stuck.

**Comment by theunkn0wn1** [comment]
Built against 17f3470, and found a bug/exploit.

![image](https://cloud.githubusercontent.com/assets/3110986/11449398/53a268ac-9528-11e5-85a3-b3a388cedd13.png)

If two Redstone breakers are set side-by-side, as to share a RS input, said input becomes 'stuck' until the breaker gets a block update. In the above, I removed a lever that provided the RS input and the signal remains. The inverse applies with the below:
![image](https://cloud.githubusercontent.com/assets/3110986/11449406/99a20d62-9528-11e5-99f1-4250e888994b.png)

**Comment by mindforger** [comment]
yeah, that's kind of what i expected :(
redstone is bitchy .. and the moment you throw in blockupdates, it becomes even more ugly!
with those blocksupdates you could build (ghost)chunkloaders

**Comment by mindforger** [comment]
that's kind of why i suggested to make an interface for that purpose :)

**Comment by cobra** [comment]
…and it's gone again. Turns out redstone is really ugly and will break in all possible ways, especially when using modded redstone conductors - including signal loops and missing updates. Vanilla redstone dust would also show a connection to the breakers, but not power them when running either a line parallel to them or connecting to a redstone dust corner.

You can still achieve the desired effect of switching many adjacent breakers by running redstone in a "E" pattern (vanilla limitation) or by using repeaters. Of course, any modded redstone conductor will also do its job, but might need some manual interaction to make it connect to the breaker - there's no generic API for marking a block as redstone signal receiver.
![](https://cloud.githubusercontent.com/assets/163331/11596299/95ba407a-9ab4-11e5-86ec-3d7b923df2d4.png)
