### ISSUE TITLE
Potential Crusher recipe loss?

### ISSUE THREAD

**Issue by 1skandar** [BluSunrize/ImmersiveEngineering#767]
Ok, maybe I am crazy, but I swear you used to be able to throw logs into the crusher and have it spit out sawdust. Was this removed?

**Comment by James-T-Oudvoure** [comment]
Sawdust? Immersive Engineering never added sawdust.

**Comment by 1skandar** [comment]
No, but it used to do Thermal Expansion sawdust. And sometime between 0.6.0 and 0.6.4 it stopped.

**Comment by BluSunrize** [comment]
You can thank ThermalExpansion for not registering it's OreDictionary entries in preInit.
I added a new safety check to avoid flooding the OreDict with empty lists. That check makes it so that recipes are only added when the entry in the OreDict exists. I add the wood recipe before TE registers its dustWood.
So yeah, blame Team CoFH, because for fucks sake, do your registry in preInit, not init, you numbnuts.
I'll move it to my compat module to fix it.
