### ISSUE TITLE
Colorful Armor and Immersive Engineering world stall on "Starting recipe profiler for Arc Recycling, using 4 Threads"  issue Temp Fix.

### ISSUE THREAD

**Issue by CcytherR** [BluSunrize/ImmersiveEngineering#797]
Current as of this post, when the latest Colorful armor and Immersive Engineering are used together the world creation stalls at "Starting recipe profiler for Arc Recycling, using 4 Threads" and remains stuck on Building Terrain Phase.

Somewhat of a temp fix: After further testing with these 2 mods ive found you can change this line B:"Enable metadata Recipes(disable if laggy in craftguide)"=true in colorful armor's config change this to false and though it still loads slow the world will load mostly as normal after about 20-30 seconds after "Starting recipe profiler for Arc Recycling, using 4 Threads" is printed out in the console

See http://pastebin.com/svwGs6BG information reported in the console regarding the issue.

**Comment by cobra** [comment]
Too many recipes, plain and simple. The recycling calculation has to check each and every recipe and its ingredients. The author of colorful Armor has apparently seen as similar problem as well. Using that many recipes instead of a more elegant way (custom crafting handler, using a dedicated mechanic other than vanilla crafting) is bad style imho.

**Comment by BluSunrize** [comment]
Agreed. Having looked at the mod, it's not very well written on the recipe side. Recipes are incredibly repetitive and could be easily condensed into a custom IRecipe. Instead, the dev is flooding the recipe list with massive amounts of clutter. No wonder that IE takes its sweet ass time to iterate through that.
Aka: "Not my fault"
