### ISSUE TITLE
Railgun issues

### ISSUE THREAD

**Issue by Alaberti** [BluSunrize/ImmersiveEngineering#834]
Hello, and happy new year!

I was playing with the railgun (I love this thing, all do compliments to you and your artist) on 0.6.5.1, and I noticed a few things:
- Magnification doesn't change at all whether its at 1.6 or 10x
- Graphite Electrodes don't trigger as ammo, nor do any of the railcraft rails.

Everything else seems to work just fine though.

**Comment by malte0811** [comment]
Regarding the second problem: @cobra and I knew about that, we talked about it on irc shortly after the railgun was added. It is caused by the id map changing between loading and actually playing in the world. To reproduce it, add some early-loading mod(e.g. bloodmagic), create a world and restart mc without said mod (same procedure as used for the oredict nuke=oreTin bug). The bug should now happen in that world. Using item id's in ComparableItemStack is not a good idea since those change during world load, i'd try storing the item obiect and replacing the item id with the hash value of that item

**Comment by theunkn0wn1** [comment]
As for the first issue, can you please elaborate?

**Comment by Alaberti** [comment]
Below you'll see what I see; despite changing the magnification levels, there is no discernible change in zoom levels.
![2016-01-01_21 41 31](https://cloud.githubusercontent.com/assets/10929796/12072091/7b7f5f24-b0d0-11e5-8049-1f49d1bbe14d.png)
![2016-01-01_21 41 27](https://cloud.githubusercontent.com/assets/10929796/12072092/7b7fdd96-b0d0-11e5-944d-ee16ce633909.png)
![2016-01-01_21 41 29](https://cloud.githubusercontent.com/assets/10929796/12072090/7b7d81d6-b0d0-11e5-8315-6ce148843d5b.png)

**Comment by theunkn0wn1** [comment]
That's new, I have not been able to reproduce that :confused: 
Works well in my testing environment. Perhaps an inter-mod conflict is occuring?
I was testing the Rail Gun yesterday against build  e7ad9eacec25f52b4168cc2adac4c8554c36f8f6

**Comment by Alaberti** [comment]
Same, I just grabbed it from curseforge like I normally do and tossed it in the pack.

**Comment by theunkn0wn1** [comment]
![image](https://cloud.githubusercontent.com/assets/3110986/12072394/381a2e74-b091-11e5-9ed1-4c3f9c53028d.png)

![image](https://cloud.githubusercontent.com/assets/3110986/12072397/4e087d8a-b091-11e5-95a8-ccc4f468a024.png)

Built IE myself against the above build, inserted the resulting .JAR into my FTB Infinity testing instance. The result is the two images above. What pack are you using?

**Comment by Alaberti** [comment]
A pack I built myself. Here is the modlist: http://pastebin.com/5ygXm0kB
The download: (it may not be working atm though): http://www.technicpack.net/modpack/automataprogressio.746126

**Comment by XFactHD** [comment]
In my self-built mod pack this works perfectly. Can you reproduce this without Fastcraft?

**Comment by theunkn0wn1** [comment]
Works fine with fastCraft, my main test instance (modified FTB Infinity) includes that mod. Was unable to reproduce with that mod.

**Comment by XFactHD** [comment]
Than the only thing that is left is to take the modpack apart and test.

**Comment by BluSunrize** [comment]
Some other mod is hooking into the FOV event and resetting it to 1. Try without Modular Powersuits to see if the bug persists.
the ComparableItemStacks still are a bit shit, yeah. I'll need to dig into them more. Problem is that I know little of hashing ^^"

Also, just in order to take all the credit. I totally modelled and textured that Railgun myself >_>

**Comment by Alaberti** [comment]
Confirmed, removing Numina, Modular Powersuits' coremod removes the magnification problem. Checking further, it can be fixed by changing its config option "B:"Ignore speed boosts for field of view"=false" so that's a plus. 

Thank you everyone for your insights in solving this problem! And @BluSunrize full credit is fully earned I'd say.

**Comment by BluSunrize** [comment]
MachineMuse is actually the author of that Event. She PRed it to Forge and I'm happy she did. I'm glad she added a config to disable her force-reset.

**Comment by malte0811** [comment]
I can look into the comparable item stacks tomorrow once i'm home. One thing i would like to warn you about is storing the item object and checking the registry for the ID to calculate the hash value. Hash values are not meant to change during runtime, which would then happen on world change.

**Comment by BluSunrize** [comment]
Other suggestions for building the hash for an item?

**Comment by malte0811** [comment]
Replace the id with the hash of the item object, that might work. Can't test that right now, i don't think i have a forge source with me.

**Comment by BluSunrize** [comment]
Item's don't override hashCode, will that still work? :/

**Comment by malte0811** [comment]
The default implementation of hashCode is pretty good, it usually uses a java-intern memory address. I would be more worried about  modders overriding hashCode, that would probably be less safe. Generally it can happen that 2 objects that aren't equal have the same hash, which would result in problems, but since there are 2^32 possible hashes, i'd say it is too improbable to worry about it.

**Comment by PrincessRTFM** [comment]
You could use `System.identityHashCode(Object object)` to get the hash code that would be returned by a non-overridden `hashCode()` method. Documentation for [Java 6](http://docs.oracle.com/javase/6/docs/api/java/lang/System.html#identityHashCode(java.lang.Object)), [Java 7](http://docs.oracle.com/javase/7/docs/api/java/lang/System.html#identityHashCode(java.lang.Object)), and [Java 8](http://docs.oracle.com/javase/8/docs/api/java/lang/System.html#identityHashCode-java.lang.Object-).

Keep in mind, of course, that uniqueness is NOT guaranteed. There's probably a better way to do it, but I'm not sure how you're making the checks.
