### ISSUE TITLE
[Suggestion] more drill head metal

### ISSUE THREAD

**Issue by karakufire** [BluSunrize/ImmersiveEngineering#883]
When multi-mod environment, I guess probably not interisting drill head only from both of iron or steel.
There are charming metal in the environment, bronze and enderium (when installed thermal foundation) for example.

**Comment by BluSunrize** [comment]
Core IE will never add that, because I hate the idea of using CoFH metals for tools. Enderium is a dimensional transcendent material used for tesseracts, it doesn't belong on a power drill.
Neither does Signalum, Lumium or Invar.
There is a project in the works that aims to combine Metallurgy and IE, but I cannot say more on the subject, because it's not my project.

**Comment by karakufire** [comment]
I understand.

**Comment by karakufire** [comment]
but I said not only CoFH metals. tungsten steel(Gregtech), reinforced obsidian(Mekanism) and manyullyn(Tinker's Construct) are suitable for drill head I guess.

**Comment by BluSunrize** [comment]
Mayullyn is not suitable anymore at all, since 1.8 has changed it. In TCon 1.8 it's designed for attack damage, not mining.
Tungsten Steel is far too specific, since only one mod adds it.
Obsidian is a brittle crystal.

**Comment by karakufire** [comment]
I see your thought. thanks
