### ISSUE TITLE
Metal Press not inserting into inventories

### ISSUE THREAD

**Issue by XFactHD** [BluSunrize/ImmersiveEngineering#884]
If I place an inventory (chest, me interface) on the output of the metal press, the products don't get inserted into the inventory, they are thrown onto the ground.

**Comment by malte0811** [comment]
did you actually try using a chest? it is a bit bugged (it inserts into the side opposite of the side it should insert into), but that shouldn't do anything to chests since they should behave the same from every side.
For ME interfaces, try putting them on the side of the wire opposite to the one you usually would attach it to (so if you would usually attach it to the south side of the wire, try the north side)

**Comment by XFactHD** [comment]
That works but looks a bit funny.

**Comment by BluSunrize** [comment]
Wonder how that happened though. I tried with conveyors, and those are direction specific...

**Comment by malte0811** [comment]
Well, the conveyor throwing stuff on itself and the press throwing stuff on the conveyor isn't much of a difference really, I assume you saw the press spitting out items and thought it was the conveyors.

**Comment by cobra** [comment]
Mixing up output sides seems to become some sort of running gag, err bug. :P
That also explains why items were jumping around like crazy when having just one conveyor at the output of the press.
