### ISSUE TITLE
Capacitor OC support

### ISSUE THREAD

**Issue by XFactHD** [BluSunrize/ImmersiveEngineering#906]
I know that the development for 1.7.10 is more or less finished but it would be awesome if you could add OC support to the capacitors to be able to read the energy level and to set the sides to input, output or off.

**Comment by malte0811** [comment]
We (@cobra and I) activly decided to not implement that, but that was when OC support didn't use adapters. We thought that it would be a bit silly to plug a lan wire into a pretty huge high voltage capacitor.
Since OC compat now uses adapters, it wouldn't be a problem for "physics" part of me to implement that, but I would still like to have an oppinion from @BluSunrize or @cobra.
