### ISSUE TITLE
[Dupe Bug] Duplication bug with Terrafirmacraft

### ISSUE THREAD

**Issue by dexman545** [BluSunrize/ImmersiveEngineering#924]
Using double ingots in a plate press will produce a double sheet, which then can be melted down for 4 ingots, duplicating the amount of metal that was originally in existence.

**Comment by BluSunrize** [comment]
Does TFC require two ingots to make a sheet?

**Comment by dexman545** [comment]
Yes, TFC requires two ingots to make a single sheet, 2 sheets are welded together to make a double sheet. The single sheet is not a large issue, as IE makes its own versions of those sheets, which cannot be melted down, thus avoiding the dupe bug. Double sheets, however, are TFC, and can be melted for 4 ingots

**Comment by BluSunrize** [comment]
Well not my fault then. Blame TFC for oredicting it like it dos and using a different recipe. I have NO intentional compatibility for TFC, the only reason this recipe gets registered is because TFC registers it's ingots as "ingotDouble" and the plates as "plateDouble", which is why my OreDict crawler makes a recipe between them.
Solutions to this problem would be TFC not oredicting their plates as "plateDouble" when they technically quire 4 ingots, or you using Minetweaker to change the recipe. But I will/can not fix this, for the sake of compatibility with every other mod that isn't TFC.
