### ISSUE TITLE
Crash error on  mod loading. 

### ISSUE THREAD

**Issue by hentaiwizard** [BluSunrize/ImmersiveEngineering#930]
I keep getting this crash on startup. What could it be?
[crash-2016-01-30_15.42.35-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/111054/crash-2016-01-30_15.42.35-client.txt)

**Comment by theunkn0wn1** [comment]
I see you are running IE 0.6.2
Please update to the latest version and see if the problem persists

**Comment by hentaiwizard** [comment]
Well I first tried the newest version and it gave me the same exact error. so I tried an older version. 
I will attach the newest version error report as soon as I'm back at my computer. 
Is it like a block conflict error?

**Comment by theunkn0wn1** [comment]
Preliminary analysis of your original Crashlog indicates something other than a Block ID issue. It suggests an inter-mod conflict is occurring. Is it possible for us to get a copy of the full client log?

**Comment by malte0811** [comment]
Try removing Optifine. It apparently caused a similiar crash with Ars Magica at some point.

**Comment by hentaiwizard** [comment]
Here is the entire log when I tried loading the latest version of it.

**Comment by hentaiwizard** [comment]
For some reason it won't let me paste the txt file of the log. I will try to find a way.

**Comment by hentaiwizard** [comment]
Here is the full log. After using the newest mod version. Also optifine isn't the issue. I still get the crash when removing optifine. 


[fml-client-latest-1.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/111661/fml-client-latest-1.txt)

**Comment by theunkn0wn1** [comment]
Im not exactly sure the root cause of this though I suspect a different mod (other than IE itself) is adding a crop/flower IE is not expecting. Can you please attempt to identify exactly what combination of mods with IE is inducing this crash?

Also: GitHub allows you to edit posts you have made, just sayin' :seedling:

**Comment by hentaiwizard** [comment]
Yeah I'll try to figure it out. I'll go through all my mods to see which one starts causing the issue. 

Lol sorry, I'm new to all this minecraft forum and reporting problems and stuff thing.

**Comment by cobra** [comment]
You are running PML, which is apparently modifying minecraft outside of forge. Try removing that and any related mods (the seasons mod) and see if this happens again.

**Comment by BluSunrize** [comment]
Yeah from the looks of it, this exception is thrown because of bytecode modification or something. I've seen similar issues when writing ASM code. It's loading an IIcon onto the stack despite the method not requiring one? I have seriously no idea what the heck is going on there but I'm very sure it's not IE's fault. IE does not contain any bytecode modifications so I don't think I'm to blame here. Nor do I have any idea how to fix it on my side.

**Comment by hentaiwizard** [comment]
Yep! That's the issue. PML and the seasons mod is incompatible. I will message the creator of that mod. Thank you for letting me know cobra! And also thank you everyone else.
