### ISSUE TITLE
[Suggestion] Config to limit cables to only transport RF or EU

### ISSUE THREAD

**Issue by abculatter2** [BluSunrize/ImmersiveEngineering#945]
I looked through the config and couldn't see anything in there about this. Personally, I like having RF and EU be separate systems, representing different forms of power and therefore useful for different things.
As a tangent of this, this would likely also require changing the energy consumed by machines to be whatever was chosen in the config.

**Comment by BluSunrize** [comment]
There's a config to disable IC2 compat. Actually search the config next time maybe?

**Comment by abculatter2** [comment]
I don't want to limit it to only RF, though, I want to limit it to EU.

**Comment by BluSunrize** [comment]
Well you're shit outta luck then mate, because IE is an RF mod with EU compat, not the other way round. :D
The internal mathematics of IE are RF based and that's how they'll stay. EU compat is just tacked on.

**Comment by PrincessRTFM** [comment]
I don't know how the mod works internally, but would it be possible to simply have a flag that gets checked every time RF _specifically_ is moved into a wire network or machine? If so, it could probably also be checked to force EU output instead of RF from wire connectors. That might make it possible to keep the internals RF based, while only using EU externally. Just a thought, I understand that it may not be possible (or easy enough to bother with).

**Comment by BluSunrize** [comment]
Okay lemme rephrase: I have no INTENTION of doing that. IE is an RF mod and that's how it should be.

**Comment by PrincessRTFM** [comment]
Fair enough. I'm just overly curious.
