### ISSUE TITLE
Minetweaker Arc Furnace Requires Additive

### ISSUE THREAD

**Issue by abculatter2** [BluSunrize/ImmersiveEngineering#946]
The italicized part of the recipe format, although it's apparently supposed to be optional, does not appear to be so:
addRecipe(output, input, slag, time, energyPerTick, ***additives**)

Trying to run a recipe without an additive causes the following error in chat:
Error executing Scripts.zs: null

**Comment by mindforger** [comment]
looks like 
`		Object[] adds = new Object[additives.length];`
`		for(int i=0; i<additives.length; i++)`
`			adds[i] = MTHelper.toObject(additives[i]);`
is missing a nullcheck ?!

**Comment by BluSunrize** [comment]
hrrm yeah, might need a null. I always figured it'd just give you an empty array if nothing was defined, but oh well.

**Comment by mindforger** [comment]
the problem is, you used an simple ("native" ... this makes me feel strange to say in java) array which requires a number as input for the size
what you assume only is valid when using  lists or such sort of array-like objects and they perform the null check for you in their constructors then or they don't and fail the same way XD
