### ISSUE TITLE
[Suggestion] Concrete post

### ISSUE THREAD

**Issue by karakufire** [BluSunrize/ImmersiveEngineering#947]
Posts made from (reinforced)concrete are popular in Japan.
And increase uses of concretes.
thank you

**Comment by BluSunrize** [comment]
Not bad of an idea actually. May look into that for 1.8

**Comment by InuYasha86000** [comment]
if I may add on to this idea, extendable posts, I currently find the posts right now seem too short to me, especially if you put either lights or insulators under the hanging arms, my modpack contains flans mod so that might be why they look too short to me, but both concrete and wooden posts could look good together especially if they are extendable, wooden for urban areas, cement for long distance wires from dams and such.

**Comment by BluSunrize** [comment]
You're looking for the extendable wooden posts from Immersive Integration ;D

**Comment by InuYasha86000** [comment]
I did try use those but I couldn't get them to extend at all, was at it for 2 hours. there's not much documentation on how to use and connect a lot of the items from Integration.

**Comment by laz2727** [comment]
Rightclick them with IE wooden fences.

**Comment by BluSunrize** [comment]
There's a book on it. They also have their own github to report that to. >_>

**Comment by bookerthegeek** [comment]
Fully understand the extension of the top ofive the post. I was more hoping for a base for the pole that matches your pole made out of concrete.
