### ISSUE TITLE
Villager does not properly check for metadata on items

### ISSUE THREAD

**Issue by Azutte** [BluSunrize/ImmersiveEngineering#960]
Running ImmersiveEngineering-0.7.0.jar, running [these](http://www.curse.com/modpacks/minecraft/241433-engevona) additional mods. Allows such exploits as "trading treated sticks for emeralds, instead of steel machine casings" and "trading copper wire for emeralds, instead of the steel wire"(HV?).

**Comment by PrincessRTFM** [comment]
Is it still a problem in 0.7.1.2?

**Comment by malte0811** [comment]
Very likely, the code concerning villagers was not changed.

**Comment by malte0811** [comment]
Confirmed to be present in the latest version (0.7.1.2 and 5258381df85bfc23987151b483b1d355229816b6)
@BluSunrize Unless we make IE's villager a separate entity, this is impossible to fix AFAIK (without changing vanilla code). The standard `MerchantRecipe` implementation does not care about metadata or NBT, and nothing but the standard implementation will be loaded from NBT. The only other "fix" I can think of is removing any trades that use items with metadata, but I am not sure whether there would be any trades for emeralds left if we do that.

**Comment by BluSunrize** [comment]
Well that's just fucking brilliant, ain't it? .-.
I'll look into this later tonight.

**Comment by malte0811** [comment]
I can do that, I just wanted to be sure that you are ok with a new villager entity.

**Comment by BluSunrize** [comment]
I really don't want a new Villager Entity. That seems like it's overdoing it. Once again, I'll look into the code later.

**Comment by malte0811** [comment]
Just want to throw this in here, this is a vanilla bug that was fixed for version 1.8.1:
https://bugs.mojang.com/browse/MC-349

**Comment by malte0811** [comment]
Since this is a problem with any villager, both modded and vanilla, I have made a coremod that fixes this. The source code is available [here](https://github.com/malte0811/VillagerMetaFix), the mod file itself can be downloaded from [curse](http://minecraft.curseforge.com/projects/villagermetafix). It even works if you install it on the server, but not on the client.
By the way, ASM is hard to debug, but very nice if it works.

**Comment by BluSunrize** [comment]
Yaaaaaaaay!
That's actually pretty cool. Nice work @malte0811! :D

**Comment by malte0811** [comment]
Thanks!

**Comment by baconofspam** [comment]
I used this in Infinity 2.3.5 to trade RFTools Dimlets in a loop. One villager required a rare dimlet and gave 3 emeralds, another required one emerald and gave a common dimlet. Since the meta data was never checked, this resulted in a loop that netted 2 emeralds each time. 

Can confirm it's not an IE exclusive error.

**Comment by malte0811** [comment]
@BluSunrize I think this can be closed now.

**Comment by BluSunrize** [comment]
Roger that.
Anything left to do @malte0811? Otherwise I wanna build tomorrow.

**Comment by malte0811** [comment]
I have one more unpushed fix, for a bug I reported on IRC in June. I'll push it as soon as possible, I don't know why I didn't push it yesterday.
