### ISSUE TITLE
Redox/Flow Batterys to fill the Gap

### ISSUE THREAD

**Issue by mindforger** [BluSunrize/ImmersiveEngineering#967]
I personally still see a power gap between 500RF/t and 4kRF/t

and i had an idea to somewhat fill the gap that can either work as an large capacitor or as an chemical generator if you want to see it like that
.. and i don't want to deep into https://github.com/BluSunrize/ImmersiveEngineering/issues/964#issuecomment-185755763 again :P

the idea is somewhat freaky but very immerse and it is something you can only do with steam atm. 

medium power (512RF/t) capacitors with moderate buffer size (1m at max) that, when charged over 50% and when supplied with certain chemicals starts converting the chemicals make them storing energy in liquid form
https://en.wikipedia.org/wiki/Flow_battery

it would be awesome if i can manage to pump around my energy as liquid

plus 2 recipes in the refinery! one for the "oxydized" liquid at medium cost and one incuding the "oxydized" liquid plus some other liquid to "reduce" it chemically instead of electrical by providing power to the redox battery

would be working as when your diesel gen is outputting the oil again and you need to remix it with ethanol :)

**Comment by BluSunrize** [comment]
Where exactly is that Gap? MV is 1024, not 512. Voltages rise by 4x multiplication.
I personally am not to fond of using liquids for energy transfer, I'll say that right there, because once again, IE has a transfer system already. And like the often requested block-based wires for indoors, a second transfer system feels inappropriate to me.

Redox power storage is an appealing principal but seems a little too scientifically advanced for IE, but maybe that's just me.

**Comment by mindforger** [comment]
>Redox power storage is an appealing principal but seems a little too scientifically advanced for IE, but maybe that's just me.
that's all what i was thinking of but you are right i was referring the missing 1k not 512RF/t there slipped a power of 2 from my mind

and i again want to say my goal was storing power in an "alternative" form like reduced battery ooze that can be oxidized in the cap to produce power and reduced again by sustaining an RF level above 50% capacity
