### ISSUE TITLE
MineTweaker and the Blast Furance

### ISSUE THREAD

**Issue by SneakyDevil** [BluSunrize/ImmersiveEngineering#980]
Using most recent version of IE, editing the blast furnace to use TFC Wrought iron instead of the minecraft ingot. Atm, Blast furnace takes the ingot and fuel(but they visually disappear from GUI), the game crashes(and I get that crash log) then when I load back in the steel ingot is in the output slot. What is going on?

Crash-log: http://puu.sh/npdsW/eb6e504f15.txt
Script: http://puu.sh/npdvK/b35b4bdcdf.zs

Edit: its not just with Minetweaker(I disabled everything there) Now it just does not show recipe progress of fuel status

**Comment by malte0811** [comment]
Th crash was reported before and has been fixed for the next version. For now you can add some cheap item like cobblestone as slag, that should prevent the crash.
The items are not being rendered because you have installed optifine. It is not supported by IE since we don't know what exactly it does to Minecraft and are therefore unable to fix the bugs caused by it.

**Comment by SneakyDevil** [comment]
Yeah, I figured the visual bug came from Optifine. 

Thanks for the quick fix, Love this mod.
