### ISSUE TITLE
Conveyor Belt feeding issue

### ISSUE THREAD

**Issue by ShaneCourtrille** [BluSunrize/ImmersiveEngineering#993]
The following setup where _ is a single conveyor at ground level and then / is a conveyor going upwards will rarely feed into the metal press properly.  Most of the time (95%) the ingots will just stack in the world instead of being rendered on the presses conveyor.

_ / PPP

**Comment by BluSunrize** [comment]
Pictures of the setup.

**Comment by malte0811** [comment]
I think I have seen this bug before, when I had a hopper feeding into a single conveyor belt feeding into the press. It is probably caused by the items "hopping" onto the press, where they are completely ignored. A possible fix would be (assuming that this is really the cause) to make the press take in item entities that touch the input conveyor of the press.

**Comment by BluSunrize** [comment]
It does in 1.8, I just cba to backport it x3

**Comment by ShaneCourtrille** [comment]
The hopping describes what I see visually so yeah that makes sense.  If
fixed in 1.8 then yeah I wouldn't bother fixing this one either so feel
free to close.
