### ISSUE TITLE
Buckets/bottles have no container item

### ISSUE THREAD

**Issue by headprogrammingczar** [BluSunrize/ImmersiveEngineering#997]
Get an itemFluidContainers bucket, then use it on a tank block, and the bucket disappears.

I suspect you'll need to construct separate ItemIEBases for bottles and buckets so that they return their appropriate empty item.

**Comment by BluSunrize** [comment]
No, they actually very much do have a container item, as show clearly here:
https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/IEContent.java#L269-L286

What tank where you using them on, what IE version and what other mods?

**Comment by headprogrammingczar** [comment]
I was using the ticon seared tank.

**Comment by malte0811** [comment]
Fixed.
This is one of these silly causes for a bug: TCon is calling `Item.hasContainerItem()` instead of `Item.hasContainerItem(ItemStack)`. The first method (which is actually marked as deprecated) isn't overridden by IE's fluid containers and just checks some internal `containerItem` variable that isn't set for those containers, so fixing the bug just meant overriding the first method.
